### ISSUE TITLE
Рефакторинг plugin.py

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#100]
Сейчас плагин импортирует 5 форматов файлов. Для этого реализовано 4 класса-оператора. В этих классах много дублирующейся логики (выбор файлов, выдача ошибок типа "No files selected" и т.п.).

Нужно сделать так, чтобы при добавлении новых операторов не приходилось дублировать большую часть кода существующих.

Есть пара идей (но надо проверять, получится ли):
1. Наверное, для некоторых форматов, было бы достаточно просто экспортировать функции экспорта и импорта из модуля (который и отвечает за этот формат), а операторы импорта/экспорта уже герерировать автоматом. В этом случае, можно было бы расшарить общую логику и даже сделать пакетный импорт, когда выбрано несколько файлов.
2. Просто разнести операторы импорта/экспорта по разным модулям, т.е. у каждого формата будет свой каталог, в котором будут модули отвечающие за свойства их отображение, за логику импорта/экспорта и за операторы импорта/экспорта.

**Comment by PavelBlend** [comment]
Мне кажется, что проще сделать как сейчас сделано в details плагине.
Код будет более читаемым и простым.
Так как всё, что относится к определённому формату, находится в одном месте.
То есть создать пакеты модулей (details, object, ogf, skls...) и внутри этих пакетов (папок) будут модули:
`__init__`, `operators`, `format_`, `export`, `import_`, `read`, `write`, `ui` и т. д.
То есть получится вариант 2.

**Comment by igelbox** [comment]
Согласен. Details выглядит норм.

Ещё, на плохо бы, как-то поиграться с Git-ом, чтобы он почуял (чтоб потом по истории было проще искать), что логика перенеслась в другие модели, а не просто удалилась и создалась новая. Думаю, это получится для fmt\_\*\*\_imp.py fmt\_\*\*\_exp.py файлов, если их перенести/переименовать, но не менять содержимое (ну или не сильно менять).
