### ISSUE TITLE
Настройки по типу объекта

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#101]
На данный момент, с точки зрения плагина, существуют 3 вида объектов (импортированные из / экспортируемые в): object, anm, dm.
Для object-объектов есть своя панелька с настройками, которая активна по-умолчанию.
Для dm-объектов тоже есть своя панелька с настройками, которая тоже активна по-умолчанию.
Если так пойдёт и дальше, то мы рискуем захламить интерфейс вкладки свойств объекта своими панельками.

Предложение: должна быть всего одна панель с переключателем типа объекта (anm, dm, object) и, в зависимости от типа объекта, мы будем показывать только те свойства, которые применимы к выбранному типу.

Доп. польза от такого подхода: мы можем использовать выбранный тип объекта для определения формата файла при экспорте проекта (см. #93).

Пока не понятно: скорее всего нужен не переключатель, а отдельные чекбоксы, т.к., думается, что один и тот же объект blender-а может экспортироваться как в object, так и в anm.

**Comment by PavelBlend** [comment]
Переместил всё параметры в одну панель:
f32fdc4fbb6eb61c9a0abebe8362ff647c887214
