### ISSUE TITLE
ошибочный экспорт источников света

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#102]
На данный момент плагин экспортирует источники света в object, которые естественно не откроются в SDK. И не только источники света, а и другие, отличные от меша, объекты. Это мешает при batch экспорте. Так как обычно batch экспорт делается так: нажимаем A и делаем экспорт. А сейчас, если так сделать, будут экспортироваться ненужные объекты типа лампы и т.д. Приходится перед экспортом снимать выделения с ненужных объектов, или хранить их на неактивном слое, или после экспорта искать ненужные object файлы и удалять их.

Нужно чтобы плагин делал фильтрацию по типу объекта, и экспортировал только меши.

**Comment by igelbox** [comment]
> А сейчас, если так сделать, будут

Т.е. ты хочешь сказать, что раньше плагин не экспортировал лампы? Я думаю, что он всегда так делал (ну, по крайней мере, начиная с v0.0.4).
Но всегда можно было (и есть) снять галочку "XRay - object root" во вкладке свойств объекта.

> и экспортировал только меши

Я планировал экспортировать всевозможные типы объектов (см. #101). Например, чтобы можно было для создания анимации аномалии анимировать лампу, и выгружать её в anm.

Я думаю что надо как-то переделать галочку "XRay - object root" так, чтобы она была по умолчанию выключена.

**Comment by PavelBlend** [comment]
> Т.е. ты хочешь сказать, что раньше плагин не экспортировал лампы?

Нет. Похоже тоже экспортировал.
Я только сейчас это заметил.

> переделать галочку "XRay - object root" так, чтобы она была по умолчанию выключена

Может пусть будет включена по умолчанию. А только при экспорте в object, ogf, dm фильтровать отличные от меша объекты. А при экспорте в anm не фильтровать.
