### ISSUE TITLE
баг импорта весов вершин

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#109]
Этот object файл имеет развесовку вершин в blender, отличную от Actor Editor:
![blender-xray_weight_bug](https://cloud.githubusercontent.com/assets/7983249/21074182/a3b120d0-bf03-11e6-9672-1ea7b1ba04f6.png)

Скачать object файл:
https://yadi.sk/d/r0-baUkG32tea8

**Comment by igelbox** [comment]
Странно, похоже что blender не учитывает маленькие веса (< ~0.0001). Придётся при импорте их немного увеличивать.
