### ISSUE TITLE
неправильный импорт групп сглаживания

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#112]
Плагин не правильно импортирует MAX группы сглаживания.
Объект objects/props/objects/dekor/vedro_01.object из SDK 0.4 имеет несглаженные полигоны, рёбра которого при импорте в блендер не помечаются как Sharp.
![bug_sg_max_type_blend_ae](https://cloud.githubusercontent.com/assets/7983249/21078989/8a5a4bca-bf94-11e6-8c95-af2dbb4eb17a.png)

**Comment by igelbox** [comment]
Детальное описание, см. коментарии в #57.
