### ISSUE TITLE
ValueError при импорте object файла

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#113]
Файл lex\mp_military_1.object из слива исходников от GSC импортируется с ошибкой ValueError.
Скачать файл:
https://yadi.sk/d/3Kb_cV4h32zLc2

**Comment by igelbox** [comment]
А это точно нормальный/официальный файл? Или может он был получен каким-то кривым конвертером? А то в нём есть полигоны у которых 2-е вершины из 3-х ссылаются на одну и ту же точку.
Можно, конечно, сделать плагин устойчивым к таким мешам, но уж очень неприятный код получается.

**Comment by PavelBlend** [comment]
> это точно нормальный/официальный файл? Или может он был получен каким-то кривым 
конвертером?

Официальный, из слива исходников от GSC

> А то в нём есть полигоны у которых 2-е вершины из 3-х ссылаются на одну и ту же точку.

Файл был создан в 2004 году. Может в те времена экспортёр у GSC работал с ошибками?
Но Actor Editor его открывает. Только в лог пишет предупреждение: `Optimize: Invalid face found. Removed.`

Может в исходниках посмотреть, как Actor Editor обрабатывает случаи с такими полигонами? И сделать так же.

>  уж очень неприятный код получается

а что именно неприятного в коде будет? Скорость импорта упадёт? Если да, то можно сделать опцию при импорте, которая будет указывать на метод импорта: обычный импорт и импорт, устойчивый на ошибки. Второй будет медленнее, но его нужно будет использовать только тогда, когда обычный метод не справляется.
