### ISSUE TITLE
окно с предупреждениями

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#119]
Сейчас, при возникновении каких либо ошибок при импорте, плагин записывает предупреждения в сплывающее окошко. Иногда ошибок бывает очень много (битые полигоны, например), и окно превращается в длинный список, который долго пролистывать.

Пример:
Импортировать файл lex\mp_military_1.object (#113) с помощью плагина из ветки issues/113-empty-polygons (a42bb08d6fd4a084c6ac1ca9b3e9837e35a523ff)

Нужно чтобы плагин выводил суммарную информацию. Например: "Тип Ошибки: Количество ошибок этого типа"

И ещё можно сделать опцию "Подробный лог ошибок при импорте". Это пригодится, если всё таки понадобится узнать какие именно ошибки были. Например, узнать какие кости были переименованы и как они были переименованы. Или узнать координаты вершин или индексы битых полигонов.

**Comment by igelbox** [comment]
Думаю, вместо "Подробный лог ошибок при импорте", можно всегда писать подробный лог в новый лист в TextEditor, например `bpy.data.texts.new('Import bla-bla.log')` и очищать user-ов у этого лога, чтобы он не сохранялся в blend-файл.
