### ISSUE TITLE
компактное меню импорта/экспорта

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#121]
Сейчас меню импорта `*.object` находится в `File > Import > X-Ray object (.object)`
И другие импорты находятся там же.
Возможно ли сделать вложенное меню?
Чтобы меню импорта выглядело так:
`File > Import > X-Ray >`
`object`
`animation`
`skeletal animation`
`detail model`

И меню экспорта выглядело так:
`File > Export > X-Ray >`
`object`
`animation`
`skeletal animation`
`detail model`
`game object`

И сделать в настройках плагина опцию `компактное меню импорта/экспорта` (с вложенным меню) и `стандартное меню импорта/экспорта` (такое, как сейчас).

И сделать в настройках  возможность отключения меню импортов/экспортов.
Это нужно для того, чтобы меню не было загружено большим количеством пунктов. Например, пользователь моделирует уровни и ничего другого. Он знает точно, что импортом/экспортом skl, skls, dm, details он пользоваться не будет. Ему нужен только object.

**Comment by igelbox** [comment]
Я тоже думал про это. Но думаю, что будет удобнее пользоваться кнопкой экспорта проекта (см. #93) и настроить нужные типы объектов для экспорта (см. #101). Т.е. вообще не придётся лазить в меню, а можно будет после правок нажимать шоткат и все нужные (настроенные) объекты экспортируются.

**Comment by PavelBlend** [comment]
А меню тогда может удалить? Или сделать возможность его отключать.
