### ISSUE TITLE
Вопрос по внедрению импорта/экспорта новых форматов

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#126]
Я хочу добавить в плагин поддержку других форматов (err, ogf, level и т. д.)
Стоит ли их добавлять? Или сделать новый плагин (чтобы не оказалось так, что в blender-xray будет слишком много импортёров/экспортёров)?
Если стоит, то какие именно?
В планах:
cform, hom, som, err, bones, ogf, level, wallmarks, prj, geom, geomx, omf.

**Comment by igelbox** [comment]
Я против добавления импортёров для таких форматов, как `ogf` и `omf`, т.к. их можно легко (используя сторонний конвертер) превратить в `object` и `skl` соотвественно (которые плагин умеет импортировать). А если конвертер - вдруг глючит, то давай его исправлять, т.к. это поможет и другим людям, которые не используют blender. Если конвертер исправить не возможно - что ж, давай обсуждать это отдельно. А пока, импорт `ogf` и `omf` - выглядит, как пустая трата времени и усложнение кода и поддержки плагина.
А вообще, я думаю, что добавлять форматы в плагин нужно только если у тебя, или у других пользователей плагина, есть необходимость (нельзя обойтись другими средствами) в их импорте/экспорте. Давай, каждый импортёр/экспортёр каждого формата заводить как отдельную ишью, в которой можно будет написать, почему мы делаем или не делаем этот импорт/экспорт (с указанием сторонних утилит и альтернативных путей решения проблемы). Только заводи не все сразу, а по мере возникновения необходимости.

**Comment by PavelBlend** [comment]
> Я против добавления импортёров для таких форматов, как ogf и omf

я хотел их добавить, чтобы импортировать модели из билдов.
И в формате ogf хранятся визуалы в уровнях.
Импорт уровня предпочтительнее, чем его конвертация. Так как при конвертировании теряется информация о цвете вершин и UV для карт освещения. Я хотел сделать экспорт в level с сохранением карт освещения. Так например можно редактировать уровни из билдов. Не делая перекомпиляцию. Редактировать косметически (убрать косяк и т.д.)

И импорт level пригодится для портирования уровней в другие движки (у меня была идея портировать на bge уровни из билдов)

**Comment by PavelBlend** [comment]
> А если конвертер - вдруг глючит, то давай его исправлять

конвертер неправильно конвертирует ogf модели из билдов. И некоторые уровни отказывается декомпилировать.

> А вообще, я думаю, что добавлять форматы в плагин нужно только если у тебя, или у других пользователей плагина, есть необходимость

Я думаю если реализовать импорт ogf, то желающие им пользоваться найдутся. Сейчас необходимости нет, так как есть object. У меня один человек на форуме спрашивал про импорт ogf:
http://www.gameru.net/forum/index.php?s=&showtopic=65003&view=findpost&p=1589215

**Comment by igelbox** [comment]
> конвертер неправильно конвертирует ogf модели из билдов
> при конвертировании теряется информация о цвете вершин и UV для карт освещения

Думаю, самый свежий конвертер где-то тут: https://bitbucket.org/stalker/xray_re-tools/downloads
Если и в нём не работает, то попробуй заслать ишью в их репозиторий. Если не сработает, тогда будем думать, как быть. Может получится самим исправить и пулл-реквест им заслать. Иначе, всё-таки придётся в плагин впиливать.

> Так например можно редактировать уровни из билдов. Не делая перекомпиляцию.

Примерно так и появился нынешний сырой экспорт `ogf`, т.к. Actor Editor из SDK вносит косяки при экспорте модели в ogf.
Я боюсь, что мы намучаемся с вычислением tangent-ов и LOD для мешей при экспорте в `ogf`.

**Comment by PavelBlend** [comment]
Я написал в репозиторий конвертера по поводу ogf:
https://bitbucket.org/stalker/xray_re-tools/issues/26/ogf-object

Но ответа нет. И этот репозиторий редко обновляется. За 5 лет было добавлено 16 коммитов.
Я думаю придётся делать в блендере импорт (если конечно не слишком трудозатратно это будет).
Всё равно импортёр ogf пригодится для импорта/экспорта level/level.geom
Я создам новый issues, в котором будут обсуждения проблем по внедрению импорта/экспорта ogf.
