### ISSUE TITLE
Экспорт .цифр в пути текстуры

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#127]
Сейчас плагин экспортирует путь к текстуре как есть (без проверок на корректность).
Если при экспорте в `object` включить опцию `Texture Name From Image Paths`, то плагин в качестве пути к dds файлу будет использовать имя текстуры.

В блендеровской сцене не может быть текстур с одинаковыми именами. Если будут одинаковые текстуры в сцене, то их имена будут иметь вид:
texture_name, texture_name.001, texture_name.002, ..., texture_name.00№
В конце некоторые имена содержат точку и цифры.

Чтобы правильно экспортировать меш с такими текстурами, нужно перед экспортом сделать так, чтобы меш не использовал повторяющихся текстур. Иначе путь сохранится не правильно (с цифрами в конце).

Нужно придумать, как решить эту проблему.
Есть такие предложения:
При импорте выводить предупреждение, если имя созданной текстуры не совпадает с именем, которое указано в `object` файле.
При экспорте с опцией `Texture Name From Image Paths` выводить предупреждения, если имя текстуры в конце имеет цифры.

Второй вариант:
Создать свойство Texture в панели XRay, которое будет использоваться при импорте/экспорте.
Но есть одна проблема: `не понятно что с ним делать, если пользователь выбрал другую картинку для текстуры`.
Но такая же ситуация в первом варианте: имя текстуры тоже не изменяется при указании нового изображения. Зато во втором варианте нет конфликтов имён.

**Comment by igelbox** [comment]
Я бы вообще убрал опцию экспорта `Texture Name From Image Paths`. И заложился бы на то, что текстуры всегда берутся из каталога "gamedata/textures" либо "rawdata/testures" и имена текстур (из *textures.ltx*) соотвествуют их относительным путям в gamedata. Т.е. при экспорте брал бы имя файла текстуры и брал бы их него подстроку после каталога "xxxdata/textures" и до расширения файла. Например: "S:/NS/gamedata/textures/wpn/wpn_aksu.dds" => "wpn\wpn_aksu".
Такой подход будет работать даже у тех пользователей,  у которых нет распакованных архивов игры. И им не надо точно знать, что в blend-файле имена текстур были даны правильно.

**Comment by PavelBlend** [comment]
> и брал бы их него подстроку после каталога "xxxdata/textures" и до расширения файла. 

В некоторых билдах папка с ресурсами называется просто data, а не gamedata/rawdata. Это билды 1114, 1154. А в билдах 749, 756, 788 папка textures называется maps. Не знаю, стоит ли из-за этих билдов делать какие-то ухищрения. И не понятно, как будет себя вести плагин, если текстуры будут находится на диске T ("T:\wpn\wpn_aksu.dds")

> Т.е. при экспорте брал бы имя файла текстуры

То есть из bpy.data.images[*].filepath?

> И им не надо точно знать, что в blend-файле имена текстур были даны правильно.

А при импорте как будет производится сравнение текстур? Имя будет игнорироваться?

**Comment by igelbox** [comment]
> если текстуры будут находится на диске T

Блин. Точно. Забыл.
Я так понимаю, что в этом случае в настройках плагина в "Textures Folder" будет задан путь "T:\"?
А что, если сохранять настройку "Textures Folder" и в blend-файле, обновляя её перед каждым его сохранением. Тогда на любом компе, открыв такой blend-файл, плагин сможет определить какой был "Textures Folder" и сможет вычислить имя текстуры (для object-файла) относительно этого сохранённого пути.

> То есть из bpy.data.images[*].filepath?

Да.

> А при импорте как будет производится сравнение текстур? Имя будет игнорироваться?

По имени файла. Имя уже сейчас игнорируется в некоторых случаях))

**Comment by PavelBlend** [comment]
> Я так понимаю, что в этом случае в настройках плагина в "Textures Folder" будет задан путь "T:"?

Да. Будет указан `T:\`

> А что, если сохранять настройку "Textures Folder" и в blend-файле, обновляя её перед каждым его сохранением. Тогда на любом компе, открыв такой blend-файл, плагин сможет определить какой был "Textures Folder" и сможет вычислить имя текстуры (для object-файла) относительно этого сохранённого пути.

Это будет свойство сцены? То есть `Texture Folder` будет в настройках плагина и в параметрах сцены?

**Comment by igelbox** [comment]
> Это будет свойство сцены? То есть

Да. Да, только в "параметрах сцены" он будет невидимым(ненастраиваемым) свойством, которое перед каждым сохранением синхронизируется из настроек плагина. Надеюсь, такое можно сделать через через `bpy.app.handlers.save_pre`.

**Comment by igelbox** [comment]
Сейчас перечитал всё ещё раз и... передумал.
У нас же в игре не может быть двух разных текстур с одним именем. Так откуда же они могут взяться в blend-файле? И, я надеюсь, что все модели в одном blend-файле относятся к одному SDK (к одной игре/моду).
Вообщем, я думаю надо просто warning писать. Только вот тут возможны варианты (что делать в случае конфликта):
1. Привязывать материал к текстуре с суффиксом .00№
 ++ Видно актуальные текстуры
 -- Проблемы с экспортом
2. Использовать существующую текстуру (и может быть создавать новый image с суффиксом, чтоб легко было переключить, если пользователь захочет)
 -- Видно оригинальные текстуры (может выглядеть очень странно)
 ++ Экспорт в норме

Мне больше нравится 2й вариант. А вам?

**Comment by PavelBlend** [comment]
По-моему данная issue была заведена ещё тогда, когда плагин создавал кучу дублирующихся текстур, вместо использования уже имеющихся в blend файле. Сейчас в blend файле не могут быть одинаковых текстур, так как при импорте идёт проверка на наличие текстуры.

Но дублирующиеся текстуры могут возникнуть, если пользователь сам их создаст вручную.

Если всё таки в сцене есть такие текстуры, то решение такое: вручную изменить их на уже имеющиеся.

Думаю в плагине можно ничего не изменять. И закрыть данную issue.

**Comment by PavelBlend** [comment]
Всё таки есть проблемы с цифрами.

Сейчас делал объекты для уровня в разных blend файлах. Потом все объекты объединил в один blend файл и получилось много дублирующихся текстур с цифрами в конце.

Может сделать фильтр при экспорте, который отсекает цифры из имени текстуры?

**Comment by igelbox** [comment]
Так а после объединения текстура с суффиксом и без - это одна и те же тестура? Если да, то давай на этапе импорта их объединять, если нет - то как так вышло?

**Comment by PavelBlend** [comment]
> Так а после объединения текстура с суффиксом и без - это одна и те же тестура?

да. Они ссылаются на одно и тоже изображение.

> как так вышло?

я моделировал два здания в разных blend файлах. И в этих blend файлах есть текстуры с одинаковыми именами.

Потом я решил эти два здания объединить в один blend файл, чтобы между ними смоделировать бетон. Это я сделал с помощью меню File > Append. В итоге в конечной сцене появились дублирующиеся текстуры.

**Comment by igelbox** [comment]
> Это я сделал с помощью меню File > Append. В итоге в конечной сцене появились дублирующиеся текстуры.

Супер. Давай тогда сделаем тулу, или найдём уже готовую, которая объединяет одинаковые тестуры. Я почти уверен, что не только у нас такая проблема => кто-то уже её как-то решил.

Т.е. после append-а надо будет ткнуть кнопку и текстуры исправятся. Я думаю, это лучше, чем поддерживать экспорт текстур с испорченными именами.

**Comment by PavelBlend** [comment]
А если сами будем делать эту тулу, то она будет частью blender-xray? Или надо будет отдельно устанавливать? Если частью, то можно было бы в T панель её поместить.

А вообще, решение данной проблемы - это использовать галочку "Texture names from images paths"
Но это решение сработает только тогда, когда у пользователя есть папка gamedata\textures, и текстуры ссылаются на правильные пути к изображениям.

**Comment by igelbox** [comment]
Поискал готовые инструменты.. и.. не нашёл. Печаль. Похоже придётся самим писать. Можно делать учитывать все свойства (сложно), а можно только те, которые мы экспортируем в SDK (гораздо проще).

Я ~не~ думаю, что  "Texture names from images paths" - это закрывание глаз на проблему, т.е. у тебя получается blend-файл, заполненный дубликатами текстур, коорые могут иметь какие-то разные настройки (я пока не знаю, что там можно разное натроить, но всё же), а ты экспортирешь, и они все к одной текстуре привязываются.

**Comment by PavelBlend** [comment]
В блендер версии 2.8x отсутствует интернал рендер, из-за этого нет возможности указать текстуру для материала. Вместо текстур в Cycles/EEVEE используются ноды изображений. И эти ноды изображений не имеют конфликтов имён (то есть можно легко избежать имен нодов, у которых есть цифры в конце). Эти ноды имеют пространство имён в пределах одного материала (а не в пределах всего blend файла, как в случае с текстурами из 2.79). Думаю эту issue можно закрыть, так как рекомендуется не использовать блендер 2.79. А в 2.8x нет таких проблем с именами.
