### ISSUE TITLE
Вопрос о проблемах в object анимациях, skl, skls

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#129]
Какие на данный момент есть проблемы с анимациями при импорте/экспорте skl, skls и object анимаций?

Как плагин работает с различными типами интерполяций? И почему в блендере невозможно нормально представить X-Ray анимации?

**Comment by igelbox** [comment]
На данный момент существует 2 проблемы с импортом/экспортом анимаций:
1. Не соответствие алгоритмов вычисления координат дочерних костей между:
   - Blender - `Rc = Rp * Ec * Tc`
   - XRay SDK - `Rc = Rp * Tc`

   где (матрицы):
   - `Rc` - результирующее положение дочерней кости
   - `Rp` - уже рассчитанное положение родительской кости
   - `Ec` - смещение положения дочерней кости относительно родительской, заданное в EditMode
   - `Tc` - трансформации, заданные кривыми анимации.

   Т.е. в Blеnder в расчёт положения костей вмешивается положение костей, заданное в EditMode. И беда в том, что хотя анимацию перемещения ещё можно без потери качества адаптировать к Blender-овскому алгоритму расчёта, то с анимациями вращения - так не получится.

   Я вижу 2-а варианта решения этой проблемы:
   - архи-сложный: допилить blender (добавить настройку), чтобы он мог рассчитывать анимации дочерних костей пропуская `Ec`, но я не знаю, как убедить разработчиков blender-а принять такой патч.
   - не удобный: при импорте выставлять все кости в одно положение (чтоб все их вращения были равны 0). Но тогда, в процессе анимирования, легко случайно крутануть кость и тогда мы снова не сможем экспортировать ключевые кадры один к одному (придётся делать так, как делается сейчас).

2. Различие алгоритмов `BEZIER`-интерполяции между Blender и SDK. Так, например, в Blender невозможно (вытягиванием bezier-ручек) сделать так, чтобы в середине кривой был острый пик, а SDK так может.
Ума не приложу, как тут можно импортировать/экспортировать без изменения кривых.

3. Отсутствие в Blender необходимых алгоритмов интерполяции кривых анимации, например: `HERMITE` и `TCB`.
Я думаю, что эту проблему можно решить заменяя (без потери качества) эти типы интерполяции на Blender-овский `BEZIER`. Но тут нужен какой-то хитрый алгоритм.

Все перечисленные проблемы влияют на импорт/экспорт анимаций в `skl`, `skls` и `object` форматах.
Проблемы 2 и 3 влияют на импорт/экспорт `anm` формата.

**Comment by PavelBlend** [comment]
> И беда в том, что хотя анимацию перемещения ещё можно без потери качества адаптировать к Blender-овскому алгоритму расчёта, то с анимациями вращения - так не получится.

А как на данный момент плагин импортирует анимации? Алгоритмы расчёта разные, но анимации не отличаются от того, как они выглядят в СДК. Я различий не заметил.

> Т.е. в Blеnder в расчёт положения костей вмешивается положение костей, заданное в EditMode.

А как в max, maya, lightwave просчитывается положение дочерних костей?

> архи-сложный:
 допилить blender (добавить настройку), чтобы он мог рассчитывать анимации дочерних костей пропуская Ec, но я не знаю, как убедить разработчиков blender-а принять такой патч.

Я думаю этот вариант не подойдёт. Если конечно других способов не найдётся.

**Comment by igelbox** [comment]
> А как на данный момент плагин импортирует анимации?

Плагин создаёт множество ключевых кадров для анимации (в каждом Blender-овий кадр становится ключевым). Поэтому, анимации в Blender-е выглядят правильно. Но если их растянуть, чтоб происходила интерполяция между ключевыми кадрами - то возможны проблемы (пример привести не могу, но я видел их у себя на компьютере).
Точно такой же алгоритм работает при экспорте, т.е. плагин экспортирует много-много ключевых кадров (с типом `STEP`) всегда, вне зависимости от количества и типа ключевых кадров созданных в Blender-е.

> А как в max, maya, lightwave просчитывается положение дочерних костей?

Х/з. я с ними не разбирался. Я только в LightWave смотрел, как ведут себя кривые анимации и понял, что в Blender-е так сделать будет очень сложно (см. про "острый пик" в п2).

**Comment by PavelBlend** [comment]
А при экспорте в omf интерполяция сохраняется? Или всё преобразуется в STEP? Просто конвертер бардака при конвертации omf в skls выдаёт только STEP. Это сам конвертер преобразует или все omf имеют такой тип интерполяции?

Если omf не поддерживает ничего, кроме STEP, то думаю плагин не стоит переделывать. Если конечно не найдутся проблемы. Но интерполяция нужна для anm.

**Comment by igelbox** [comment]
> А при экспорте в omf интерполяция сохраняется? Или всё преобразуется в STEP?

Ты про XRay SDK? Я пока не знаю, как он работает. Знаю только, что анимация в omf файлах хранится в каком-то странном формате (там не указывается тип интерполяции => движок использует какой-то один тип интерполяции для всех скелетных анимаций).

> Это сам конвертер преобразует или все omf имеют такой тип интерполяции?

Сам конвертер (см. https://bitbucket.org/stalker/xray_re-tools/src/fb79439b25090af27e6a033173a519fa60de2e14/xray_re-tools/source/xray_re/xr_envelope.cxx?at=default&fileviewer=file-view-default#xr_envelope.cxx-143). Но м.б. и движок тоже интерпретирует кадры из `omf` как `STEP` (надо долго ковыряться в исходниках).

> Если omf не поддерживает ничего, кроме STEP, то думаю плагин не стоит переделывать.

Думаю, стоит добавить WARNING, если при импорте мы встречаем не поддерживаемый тип интерполяции (на манер, как сейчас сделано для `anm`). И ждать, может у кого он вылетит.

**Comment by PavelBlend** [comment]
> Плагин создаёт множество ключевых кадров для анимации (в каждом Blender-овий кадр становится ключевым). Поэтому, анимации в Blender-е выглядят правильно.

То есть все типы X-Ray'евских интерполяций (TCB, HERMITE, BEZIER_1D, LINEAR, BEZIER_2D) преобразуются в STEP? Если да, то как плагин делает преобразование? Ведь в TCB есть дополнительные свойства (натяжение, скос/склонение, непрерывность). Они не учитываются?

И ещё: я импортировал анимацию бинокля. И кривые анимаций имеют всего 4 ключевых кадра (а вся анимация длится 200 кадров). Это значит, что плагин не все типы кривых преобразует в STEP?

**Comment by igelbox** [comment]
> То есть все типы X-Ray'евских интерполяций (TCB, HERMITE, BEZIER_1D, LINEAR, BEZIER_2D) преобразуются в STEP?

Для skl - все типы, а для anm - все, кроме LINEAR и STEP (которые должны превращаться в LINEAR и CONSTANT в Blender-е). Только вот не в STEP преобразуются, а в Blender-овский BEZIER. Да и преобразованием-то это назвать сложно (см. далее).

> Если да, то как плагин делает преобразование? Ведь в TCB есть дополнительные свойства (натяжение, скос/склонение, непрерывность). Они не учитываются?

Не учитывается ничего, кроме времени и значения в точке (т.е. все доп.свойства TCB - не учитываются).

> И ещё: я импортировал анимацию бинокля. И кривые анимаций имеют всего 4 ключевых кадра (а вся анимация длится 200 кадров).

Из всех (в твоём случае 4-х) кадров плагин возьмет уникальные времена, по каждой кости в отдельности (т.е. если для какой-то кости было меньше ключей, то он возьмет меньше временных точек), и для каждого уникального времени он поставит ключевые точки на все кривые этой кости. Но это будет не STEP, а blender-овский BEZIER (но, опять же, без каких-либо хитрых манипуляций с "ручками" у кривой, т.е. "ручки" выставит сам blender, как ему нравится).

**Comment by igelbox** [comment]
> Но если их растянуть, чтоб происходила интерполяция между ключевыми кадрами - то возможны проблемы (пример привести не могу, но я видел их у себя на компьютере)

Получилось воспроизвести:
- открываем object-файл из [linear-vs-stepped.zip](https://github.com/igelbox/blender-xray/files/801251/linear-vs-stepped.zip) в ActorEditor
- выставляем скорость анимации 0.2
- и смотрим/сравниваем Motions-ы 'linear' (все кадры - LINEAR) и 'stepped' (все кадры - STEP)

На этой скорости будет видно "дрожание" для 'stepped' и артефакты для 'linear'.
