### ISSUE TITLE
Возможность создать камеру, такую же как в игре

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#138]
Было бы удобно проверять только что настроенные анимации оружия не выходя из bledner-а.
Для этого нужна например кнопка, по которой на сцену будет добавляться камера на высоте глаз игрока и с таким же углом обзова, как в игре.
Кнопку можно поместить в `T`ools панель, рядом с `XRay Materials`, а саму вкладку переименовать в `X-Ray Engine Tools`.

**Comment by PavelBlend** [comment]
Камера должна находиться вроде бы в позиции 0, 0, 0. Направлена в положительную сторону оси Y. И иметь угол обзора не совсем понятный: 37.8 градусов. FOV оружия отличается от FOV уровня.

**Comment by PavelBlend** [comment]
37,8 градусов - это угол обзора, если разрешение камеры 1024x768.
51.5 градусов - это угол обзора, если разрешение камеры 1280x720.
В общем угол обзора зависит от соотношения сторон экрана.
Нужно в исходниках посмотреть, по каким законам меняется FOV.

**Comment by PavelBlend** [comment]
Данный запрос связан с этим #371 
Путём экспериментов было выяснено, что для ТЧ камера и FOV для hud моделей являются такими:
FOV (в градусах в блендере): 30,5
Sensor Fit (в блендере): Vertical
Разрешение: любое
Позиция: 0, 0, 0
Вращение: 90, 0, 0

FOV для уровня отличается.

**Comment by PavelBlend** [comment]
Теперь камеру можно добавить в окне Properties, вкладка Object, панель X-Ray Engine: Object, свиток Utils, кнопка Add X-Ray Camera.
