### ISSUE TITLE
ретаргетинг костей

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#141]
Нет ли у вас возможности реализовать в аддоне  ретаргетинг костей как в видео https://youtu.be/EYWGk4lIyX4?t=1m42s

**Comment by igelbox** [comment]
Видео посмотрел, но так и не понял что требуется сделать. Опишите подробнее: что у вас есть на входе (какой скелет, что за анимации, и т.п.) и что вы хотите получить на выходе? Может примеры файлов сможете прикрепить. А я подумаю, как это реализовать.

**Comment by PavelBlend** [comment]
Ретаргеринг костей делается с помощью других аддонов. Blender-Xray - это импортёр/экспортёр 3д моделей и анимаций движка xray, то есть сталкера. И для каких костей нужно сделать ретаргеринг? Для тех, которые были импортированы из object файла? Это врядли получится сделать. Так как скелеты специфичны, но я не пробовал.

**Comment by s30-zip** [comment]
Суть: есть .bvh файл с анимацией (их полно в интернете), нужно перенести анимацию на скелет x-ray. Через mocap tools пробовал, но толком не получается, перекручивает скелет.В приведённом видео на https://www.youtube.com/watch?v=EYWGk4lIyX4&feature=youtu.be&t=4m19s рассказывается суть реализации.Как я понял из видео, там не важно какой скелет, выбранные параллельные кости просто синхронизируются в пространстве.К примеру .bhv файл https://yadi.sk/d/gPHPmobP3Liigu . Думаю такая опция переноса была бы полезна при создании кат-сцен так, как bvh файлов полно, а создавать  анимиации не каждый умеет.

**Comment by igelbox** [comment]
[Я тут немного поигрался.](https://youtu.be/fkoQIWxdMk4)
А с "mocap tools" - тоже не получилось. Х/з, может ещё один плагин замутить?))

**Comment by s30-zip** [comment]
Вроде отлично получилось."...ещё один плагин...", я так понял  опция ретаргетинга не вписывается в рамки Blender-Xray?Может есть возможность реализовать аддон с дополнительными возможностями . типа  Blender-Xray-tools?

**Comment by Xottab-DUTY** [comment]
Если судить по названию, то Blender-XRay не ограничивает рамки проекта импортом/экспортом.Можно и реализовать ретаргетинг в рамках этого проекта. =)

**Comment by s30-zip** [comment]
Возможно ли, что что-либо подобное добавится в ближайшем обновлении?

**Comment by igelbox** [comment]
Всё возможно. Только вот вотпрос, как скоро это обновление выйдет..
Я думал, что с переносом анимаций всё проще получится, но пока никак не получается.
Можно, конечно, попробовать реализовать более простой подход: подогнать сталкеровский скелет под тот, что в BVH (в моём видео именно так и сделано), но тогда нужно будет экспортировать отдельные object/ogf и skls/omf файлы которые будут использоваться только для кат-сцены (т.е. те меш-ы, что уже лежат в игре - не подойдут для нового скелета).
Было бы не плохо, если бы кто-то скинул мне ссылку на простой урок, как делать кат-сцены с анимированными персонажами (чтоб я понимал, что требуется в итоге).

**Comment by igelbox** [comment]
Кажется получилось [см. ещё одно видео для привлечения внимания :)](https://youtu.be/0OAwBPt2Ejc).
Если срочно нужно, то до выходных постараюсь выложить долгую и скучную инструкцию, как сделать такое с помощью python-скрипта прямо в blender-е.
Если нужно не срочно, то буду думать, как этот скрипт в плагин впилить.

**Comment by s30-zip** [comment]
Ух... Интересно было бы потестить, но не к спеху.

**Comment by igelbox** [comment]
Выложил нулевую версию плагина для переноса анимаций: [blender-retarget](https://github.com/igelbox/blender-retarget).
Небольшая инструкция по его использованию есть в [README.md](https://github.com/igelbox/blender-retarget/blob/master/README.md). Было бы круто, если бы кто-то сделал видеоурок по работе с ним.

Жду замечания и предложения по этому новому аддону.

**Comment by s30-zip** [comment]
Попробовал аддон, впечатления положительные https://youtu.be/I1oU6vku2h0 , всё так и представлял. Есть ньюансы, скелет bvh должен быть в такой же позе как наш, после ретаргетинга можно подгружать прочие будут работать нормально, но если например изначально назначать на лежачую позу bvh, то толком не работает

**Comment by igelbox** [comment]
> скелет bvh должен быть в такой же позе как наш
> но если например изначально назначать на лежачую позу bvh, то толком не работает

@s30-zip Добро пожаловать в https://github.com/igelbox/blender-retarget/issues :)
Заводи там ишью, описывай проблему или улучшение - посмотрим, что можно сделать.
