### ISSUE TITLE
Не экспортировать пустые Bone Parts, т.е. Bone Groups в которых нет экспортируемых костей

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#142]
Есть предложение сделать опцию XRay для каждой Bone Group в блендере, чтобы экспортировались в object файл только те, у которых включена эта галочка.

Для чего это нужно:
при создании собственного рига иногда приходиться создавать свои группы костей, чтобы окрасить кости в разные цвета для удобства и наглядности при анимации. Но эти созданные группы костей не должны попадать в object файл, а должны использоваться только внутри блендера.

Если сейчас экспортировать скелет с более чем 4-мя группами костей, то СДК выдаст ошибку при открытии object. И группы костей в СДК называются Bone Parts и они должны содержать строго определённые имена (у персонажей).

**Comment by igelbox** [comment]
> и они должны содержать строго определённые имена

А мы всегда в blender-е сможем дать им эти имена?

**Comment by PavelBlend** [comment]
> А мы всегда в blender-е сможем дать им эти имена?

имя группы костей - это и есть имя Bone Parts в СДК.

**Comment by igelbox** [comment]
Это-то да. Но я имею ввиду, что мы не можем поместить одну и туже кость в 2 и более группы (что немного меня печалит). Т.е. это значит, что мы не можем поместить экспортируемую кость ещё и в какую-то другую группу. А из этого можно сделать вывод, что надо экспортировать только те группы в которых есть хотя бы одна экспортируемая кость. Так подойдёт?

**Comment by PavelBlend** [comment]
Думаю да. Только те группы, в которых назначены кости с галочкой XRay.
