### ISSUE TITLE
Возможность редактировать центр массы костей

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#148]
Реализовать возможность редактировать в блендере центр массы кости. Сейчас можно только менять числовые поля, но это не удобно, так как визуально не видно центра массы. Сделать так, чтобы в 3д окне отображался центр массы и чтобы его можно было редактировать в том же окне, а не только менять числовые поля.
В сдк это выглядит так:
![center_of_mass](https://user-images.githubusercontent.com/7983249/34638208-ee1cc904-f2d7-11e7-81f7-f40c2f28d77d.png)

**Comment by s30-zip** [comment]
... кнопку центрации(среднего значения) якоря(центр масс) относительно формы
