### ISSUE TITLE
Возможность импорта ровного скелета

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#149]
Цитата с YouTube:
> При привязке сгибающихся суставов иногда не удобно ибо не видно в каком именно месте сочленяются две кости, ориентир лишь custom shape, или дефолтное отображение, поэтому иногда не не так как надо привязываются вертексы.

Идеи для реализации:
- Опция при импорте object-файла.
- Кнопка "Выровнять кости" в свойствах арматуры.
- Режим, в котором кости "выравниваются" только в blender-е, т.е. при экспорте object/skls будут совместимы с оригинальными анимациями/скелетом.
- Кнопка "Применить текущее положение костей, как оригинал", после активации которой, все последующие экспорты будут использовать новый скелет, не совместимый с оригинальным.
- Не забыть про редактирование форм костей.
- Подумать над сохранением настроек IK Limits.

**Comment by igelbox** [comment]
@PavelBlend, @s30-zip, напишите, пожалуйста, какие проблемы с существующим (v0.3.1) скелетом могут/должны решиться с помошью нового "ровного" скелелета.

**Comment by PavelBlend** [comment]
Честно говоря, меня всё устраивало в старой версии плагина. Я на ютубе спросил, возможно ли такое реализовать, чтобы знать точный ответ и не ввести в заблуждение того, кто изначально спросил. Я не думал, что ты начнёшь реализовывать эту идею. И я ещё не до конца понял, как будут сохраняться анимации, если ориентация костей импортируется совсем не так, как в файле прописано.

**Comment by s30-zip** [comment]
"ровный" скелет просто добавляет удобства при привязке, заметил, что точнее происходит автопривязка (меньше ручной доработки). Возможно (как компромисс) с "ровными" оставить фейковые кости , но чтоб они были совсем крохотными (незаметными), чтоб IK был.Но если для этого нужно много чего городить возможно тогда это спорная идея.

**Comment by igelbox** [comment]
@PavelBlend 
> Честно говоря, меня всё устраивало в старой версии плагина

Я просто замечил, что ты в уроке (сейчас я его уже не смог найти, наверное на твоём старом канале остался) по анимации оружия (HUD) первым делом кости разворачивал, вот я и подумал, что "ровный" скелет тоже может тебе пригодиться.

> как будут сохраняться анимации, если ориентация костей импортируется совсем не так, как в файле прописано.

Да, как придумаем, так и будут. Я тут, после blender-retarget, вроде бы прокачался с матричной математикой. Теперь, перенос анимация с одного скелета на другой на лету - не такая уж и большая проблема.

**Comment by igelbox** [comment]
@s30-zip 
> Возможно (как компромисс) с "ровными" оставить фейковые кости , но чтоб они были совсем крохотными (незаметными), чтоб IK был.

С фейковыми костями легче проблему решить. Я там отдельный PR открыл с вариантом решения, см #150.

> заметил, что точнее происходит автопривязка (меньше ручной доработки)

Тогда, если оставлять только это требование, то можно сделать 2 кнопки в свойствах арматуры: "Выровнять кости" и "Отменить выравнивание костей". Результат работы этих кнопок никак не будет влиять на импорт/экспорт (т.е. будет существовать только в blender-е).
Или, можно сделать ещё проще, можно сделать свою кнопку автопривязки, которая будет выравнивать кости, авто-привязывать и отменять выравнивание (всё за 1 действие). Только мне надо знать точно: что это за "автопривязка" такая (т.е. как она в blender-е запускается и сколько её видов существует)?

**Comment by PavelBlend** [comment]
@igelbox
> Я просто замечил, что ты в уроке (сейчас я его уже не смог найти, наверное на твоём старом канале остался) по анимации оружия (HUD) первым делом кости разворачивал

Я ещё менял Roll у всех костей. Если бы не Roll, то я бы наверное не выравнивал бы кости. Но из-за изменения Roll'а анимации будут не такие, как нужно.

Для ЗП я не выравнивал кости, так как в ЗП важно сохранить изначальный скелет рук.

**Comment by igelbox** [comment]
@PavelBlend 
> Я ещё менял Roll у всех костей.

Зачем?

> Но из-за изменения Roll'а анимации будут не такие, как нужно.

Не факт. Я ж говорю, теперь будет не так сложно сделать преобразование анимаций на-лету.

> так как в ЗП важно сохранить изначальный скелет рук

Это из-за того, что в ЗП анимации хранятся отдельными файлами (а не вместе с mesh-ем, как в ТЧ)?
Можно попробовать сделать, чтобы руки при экспорте анимации использовались оригинальные, а остальные кости оружия - изменённые. Например, как вариант, сделать флаг у каждой кости, оригинальное положение или актуальное использовать при экспорте.

**Comment by PavelBlend** [comment]
@igelbox 
> Зачем?

Я когда анимирую, то включаю локальные оси костей (а не глобальные) и перемещаю за стрелки локальных осей (либо G+X+X или R+Z+Z). Если Roll не изменить, то локальные оси будут смотреть куда попало, а не в сторону изгиба:
![bone_roll_test](https://user-images.githubusercontent.com/7983249/34648295-a1699ad4-f3a8-11e7-9a89-c0ef092619c6.png)

**Comment by s30-zip** [comment]
Я обычно привязываю так: подгоняю в pose mode под мешь кости, применяю позу как позу покоя, в object mode выделяю мешь потом скелет Ctrl+P->"скелетная деформация"->"с автоматическими весами" и после этого правлю вручную в редакторе весов (weight paint) не корректную привязку.Кроме пункта "с автоматическими весами" там есть ещё "с пустыми группами" и "с весами обёртки" - последним не пользуюсь по не знанию.

**Comment by igelbox** [comment]
@s30-zip, ок, теперь я нашёл, разобрался.
> подгоняю в pose mode под мешь кости, применяю позу как позу покоя

Так после этого выгруженный object-файл будет не совместим с существующими skls-файлами, а выгружаемые skls-ы с существующими скелетами.
Или ты так делаешь только для моделей, у которых анимации хранятся внутри object-файла (у моделей оружия так бывает)?

---
@PavelBlend, интересный case. Я посмотрел пару моделек (модель персонажа и худ оружия), если их импортировать в v0.3.1, то там кости вроде норм располагаются (ну, только если оси перепутаны, но если R+Y+Y нажимать, то норм крутятся). Скинь, пожалуйста, ссылку на файл, при импорте которого кости получались вывернутыми (чтоб пришлось их руками править).
А #147 получается ломает эту "встроенную" возможность, т.к. после импорта с Pretty Bones кости получаются вывернутыми, как будто Roll у них рандомный стал.
У меня теперь идея появилась, не делать точное выстраивание костей в цепочку, а делать некое приближение к идеалу, с помощью поворотов, кратных 90 градусам. При таком подходе можно будет и IK и совместимость анимаций сохранить. Буду экспериментировать.

**Comment by s30-zip** [comment]
Я пока работаю только с привязкой моделей персонажей под ЗП.

**Comment by PavelBlend** [comment]
@igelbox 
> Я посмотрел пару моделек (модель персонажа и худ оружия), если их импортировать в v0.3.1, то там кости вроде норм располагаются (ну, только если оси перепутаны, но если R+Y+Y нажимать, то норм крутятся). Скинь, пожалуйста, ссылку на файл, при импорте которого кости получались вывернутыми (чтоб пришлось их руками править).

Я хотел добавить новое оружие в ТЧ. Решил взять меш рук из ЗП (так как в ЗП руки более качественно смоделены): 
[wpn_hand_01.zip](https://github.com/igelbox/blender-xray/files/1612593/wpn_hand_01.zip)

Импортировал его и увидел, что кости пальцев торчат куда попало и Roll у них рандомный. Решил выровнять скелет и изменить Roll, чтобы пальцы гнулись в правильном направлении.

> Я просто замечил, что ты в уроке (сейчас я его уже не смог найти, наверное на твоём старом канале остался) по анимации оружия (HUD) первым делом кости разворачивал, вот я и подумал, что "ровный" скелет тоже может тебе пригодиться.

Если Roll будет корректным, то может и пригодиться. Если не корректным, то тоже пригодиться (меньше работы по выравниванию надо будет сделать в ручную). Но если Roll не будет корректным, то я его изменю, а анимации испортятся. Этот способ подойдёт для HUD моделей оружия для ТЧ с абсолютно новыми анимациями.

**Comment by PavelBlend** [comment]
Создание ровного скелета реализовано с помощью оператора `Create Connected Bones`. Подробнее здесь:
https://github.com/PavelBlend/blender-xray/releases/tag/v2.8.0 (есть ссылка на видео в ютубе)
#602
