### ISSUE TITLE
Редактирование формы костей в Pose Position

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#152]
Сейчас координаты helper-а расчитываются относительно Rest Position:
![image](https://user-images.githubusercontent.com/5264687/34696916-a858d3b6-f4e1-11e7-9ad1-b225de4cbb1e.png)
Это выглядит немного неожиданно для пользователя.

Возможные проблемы:
- Если начали редактировать при одном положении кости, а применяем изменения уже при другом положении.

**Comment by PavelBlend** [comment]
Может сделать так, чтобы плагин переключал отображение скелета на Reset Position при нажатии на кнопку Edit Shape? А потом обратно, на Pose Position, при нажатии на Apply Shape. Или этот способ костыльный?

**Comment by igelbox** [comment]
> Может сделать так, чтобы плагин переключал отображение скелета на Reset Position при нажатии на кнопку Edit Shape?

Я думаю, возможность поренуть кость в Pose Mode, чтобы, например, лучше рассмотреть шейп, может быть очень полезной. А в Rest Position, кости, вроде бы, не двигаются.
Да и положение скелета в Rest Position может сильно отличаться, из-за чего это будет выглядеть как дёрганье модели, при нажатии кнопки редактирования шейпа.

**Comment by s30-zip** [comment]
В объектном режиме выбираем скелет, вкл. отображение шейпов, в структуре проекта выбираем нужную косточку - работает редакция формы и перемещение якоря (центр масс), если так не задумано, то может быть фишкой.

**Comment by PavelBlend** [comment]
> Я думаю, возможность поренуть кость в Pose Mode, чтобы, например, лучше рассмотреть шейп, может быть очень полезной.

Кстати, в старых билдах в OGF файлах нет Bind Position. Из-за чего при конвертации в object конвертер бардака Bind позу выставляет для всех костей в нулевые координаты. В итоге редактировать шейпы таких моделей в Reset Position будет невозможно (все кости находятся в одной точке). И редактирование костей в Pose Position будет полезна в таких случаях.

**Comment by igelbox** [comment]
@s30-zip
> в структуре проекта выбираем нужную косточку - работает редакция формы и перемещение якоря

Не понятно, по какому действию происходит переход от выбора кости к редактированию формы. Вообще без кнопки запуска редактирования что ли?

@PavelBlend про старые билды - не знал, спасибо.

**Comment by s30-zip** [comment]
С кнопкой.Просто я думал, что оно не должно было в объектном режиме работать.
