### ISSUE TITLE
Ускорить импорт анимаций

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#154]
Возможно ли ускорить и оптимизировать импорт анимаций? Их, как правило, много. Особенно в stalker_animations.omf Ждать приходится долговато.

**Comment by igelbox** [comment]
Да, ускорить возможно. У меня на ноутбуке, после некоторых оптимизаций аддона, импорт этого файла занимает примерно 11 минут, а Blender при этом съедает больше 2.5ГБ оперативки. После сохранения, получаю blend-файл в 1.3ГБ. Что приводит к мысли, что тут не только в скорости проблема.
А точно все анимации из skls-файла нужны? Может сделать возможность импорта отдельных анимаций (например, по имени) или групп анимаций (например, по маске со звёздочками) из skls-файла?

**Comment by igelbox** [comment]
Ещё, как идея для отдельной ишью, можно попробовать реализовать фичу, которая будет спрашивать пользователя (например, каждые 10 секунд), хочет ли он продолжить процесс импорта.

**Comment by PavelBlend** [comment]
> Ещё, как идея для отдельной ишью, можно попробовать реализовать фичу, которая будет спрашивать пользователя (например, каждые 10 секунд), хочет ли он продолжить процесс импорта.

Я думаю пойдёт и так, как сейчас плагин работает. А то добавятся ещё новые опции при импорте.

**Comment by PavelBlend** [comment]
> Может сделать возможность импорта отдельных анимаций (например, по имени) или групп анимаций (например, по маске со звёздочками) из skls-файла?

Я думаю это будет полезная фича. Вот только как это сделать? При импорте будет высвечиваться список анимаций, среди которых можно выбрать нужные?

**Comment by igelbox** [comment]
> А то добавятся ещё новые опции при импорте.

А разве это проблема? Обычно, для всех опций есть дефолтные значения в панели свойств аддона.
И как без этой фичи остановить/прервать blender в процессе имполрта/экспорта?

---
> Вот только как это сделать? При импорте будет высвечиваться список анимаций, среди которых можно выбрать нужные?

Можно и так попробовать, правда это потребует предварительного анализа импортируемого файла, что будет немного подтормаживать процесс.
А ещё, как вариант, можно просто добавить тестовое поле ввода и импортировать только те анимации, имена которых совпадают с маской, введённой в это поле.
