### ISSUE TITLE
Invalid Faces

### ISSUE THREAD

**Issue by akaSpy** [PavelBlend/blender-xray#158]
Добрый день!

Есть проблема в виде ошибки "Invalid Faces". Но не могу понять, где узкое место. Компилятор мне указывает ошибки на эти места https://yadi.sk/i/uvtHlbGF3RZk2w, но в Blender проблемы не вижу (как только не пробовал проверять).

Может ли при экспорте, что-то ломаться?

**Comment by s30-zip** [comment]
двойных вершин там нет?

**Comment by akaSpy** [comment]
@s30-zip нет, я делал remove doubles с разным порогом.

**Comment by PavelBlend** [comment]
@akaSpy Может полигоны слишком маленькие? Если да, то компилятор уровней объединяет их и в итоге в процессе компиляции могут появиться битые полигоны.
Или ещё может из-за неправильной юви карты могут быть битые полигоны.
И желательно было бы выложить blend файл с данным мешем, чтобы не гадать.

**Comment by akaSpy** [comment]
@PavelBlend Прилагаю .blend-файл https://yadi.sk/d/Q_qOiD9b3RaVME

Развертка здесь временная, но для тестирования подходит. Полигоны, вроде, не супер маленькие.

**Comment by PavelBlend** [comment]
@akaSpy у меня получилось скомпилировать уровень с этим объектом. Нет никаких битых полигонов. В объекте ничего не менял. Только добавил текстуру, так как её не было.

**Comment by akaSpy** [comment]
@PavelBlend хм, очень странно. Тогда у меня есть несколько вопросов:
1. Компилировали случаем не в обход invalid faces? В этом случае и у меня компилируется, но ломает модель в игре — автоматически объединяет проблемные полигоны.
2. Какими компиляторами пользуетесь? Можете дать на них ссылку?
3. Может ли быть моя локальная проблема из-за того, что я масштабировал модель в Level Editor?

**Comment by PavelBlend** [comment]
> Может ли быть моя локальная проблема из-за того, что я масштабировал модель в Level Editor?

попробуй не менять масштаб и скомпилировать. Может из-за маленького масштаба полигоны стали слишком маленькими.

> Компилировали случаем не в обход invalid faces?

без обхода компилировал.

> Какими компиляторами пользуетесь? Можете дать на них ссылку?

[https://www.gameru.net/forum/index.php?s=e8d941f042acecd401f361a68e8ac7de&showtopic=59990](https://www.gameru.net/forum/index.php?s=e8d941f042acecd401f361a68e8ac7de&showtopic=59990)

**Comment by akaSpy** [comment]
> попробуй не менять масштаб и скомпилировать. Может из-за маленького масштаба полигоны стали слишком маленькими.

Похоже, действительно дело было в масштабе. В реальном размере скомпилировалось. Очень странный механизм в сталкере.

@PavelBlend, большое спасибо за помощь!

Извините, получается, что не в тему написал.
