### ISSUE TITLE
Выводить предупреждения при экспорте вместо ошибки

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#161]
Если экспортировать объект в object без UV или без материала, то будет ошибка. Нужно сделать вывод предупреждения вместо ошибки.

**Comment by igelbox** [comment]
> Нужно сделать вывод предупреждения вместо ошибки.

Т.е. выводить WARNING, но всё-таки экспортировать объект?

И материал нужен, чтобы выгружать чанк `SFACE = 0x1009`, без него (или с пустым чанком) SDK ругается при открытии экспортированного объекта:
```
---------------------------
Fatal Error
---------------------------
Expression    : assertion failed
Function      : CDB::MODEL::build
File          : D:\prog_repository\sources\trunk\xrCDB\xrCDB.cpp
Line          : 86
Description   : (Vcnt>=4)&&(Tcnt>=2)
stack trace:
---------------------------
```

Можно попробовать автоматом назначать какой-нибудь SFACE для всех полигонов, например назвать его "default".
Или, жду пример object-файла без материала, который нормально окрывается в SDK.

**Comment by PavelBlend** [comment]
Нет. Экспортировать не нужно такие объекты. Просто сейчас появляется окно со стеком вызовов и типом ошибки и для обычного пользователя не будет понятно из-за чего ошибка. А если будет WARNING с читаемым текстом, то пользователю будет понятно, что надо сделать для правильного экспорта.
