### ISSUE TITLE
Некорректная работа Normal Map, ошибки сглаживания.

### ISSUE THREAD

**Issue by akaSpy** [PavelBlend/blender-xray#166]
Приветствую, коллеги по цеху!

Снова я к вам за помощью, так как косвенно это относится к плагину экспорта и вы в целом больше в теме внутренних особенностей.

В общем, проблема такая. Карту нормалей запёк в Substance Painter. В Substance всё выглядит отлично, в Marmoset тоже. Но в игре (Зов Припяти) имеет такие же ошибки сглаживания (3ds Max с Xoliul Shader):
![2018-01-30_20-56-53](https://user-images.githubusercontent.com/5264687/35772103-bcebf912-0949-11e8-833b-346e76d9366c.png)

Не могу разобраться в чём дело, как только не пробовал запекать. Подскажите, пожалуйста, какие есть варианты? Такое ощущение, что, что-то не то с нормалями.

P.S. Модель сделана в Blender и экспортирована через текущий плагин.

**Comment by igelbox** [comment]
Здравствуй, @akaSpy 
По скриншоту сложно сказать в чём проблема.
Было бы полезно посмотреть на blend-файл, object-файл и получившуюся карту нормалей, чтобы хоть как-то понять в чём может быть проблема.
А экспорт же был сделан с использованием `Format Version: CS/CoP`?

**Comment by akaSpy** [comment]
@igelbox, спасибо, что откликнулся. И извини, что ответил не сразу, был пока не у дел. Я сегодня проведу ещё пару тестов и постараюсь предоставить детальную информацию.

**Comment by akaSpy** [comment]
@igelbox 

Пока не могу нормально провести тесты, так как ломается модель.
Сделал тестовую модель, но не могу понять, что с ней происходит в Actor Editor:
![2018-02-03_19-09-27-](https://user-images.githubusercontent.com/5264687/35772153-1a45591e-094a-11e8-9795-81721211bce0.png)

Похоже на проблему с группами сглаживания, судя по возросшему vertex count. В игре (Зов Припяти) аналогично плохо всё:
![2018-02-03_19-14-55](https://user-images.githubusercontent.com/5264687/35772157-2261d8d4-094a-11e8-929e-a59212ecd4d2.jpg)

Это как-то решается?

P. S. Сам экспорт модели проходит нормально, при импорте обратно в Блендер модель выглядит корректно.

**Comment by akaSpy** [comment]
@igelbox 

Blend-файл [GameTest.zip](https://github.com/igelbox/blender-xray/files/1692247/GameTest.zip)

**Comment by igelbox** [comment]
Думаю проблема в не правильной `Format Version:`. У меня, при выставленной `Format Version: CS/CoP` - нормально в CoP SDK открывает:
![image](https://user-images.githubusercontent.com/5264687/35772172-6aed3a30-094a-11e8-9985-6590758d2226.png)

**Comment by akaSpy** [comment]
@igelbox 
Действительно, спасибо! Как же я не догадался попробовать, ведь при импорте та же проблема была. В общем, у меня по какой-то причине эти кнопки перепутаны. Я когда импортировал модель Winchester 1300 из игры, то при выставленном CS/CoP ломались группы, а при SoC норм. При экспорте видимо та же ситуация. Версия плагина 0.4.0 Видимо есть какой-то баг, либо, что-то я неправильно установил.

**Comment by akaSpy** [comment]
@igelbox 
По поводу основной проблемы. Подскажи, пожалуйста, передаётся ли tangent space из Blender? Подобные проблемы сглаживания указывают, как раз на то, что не соответствуют tangent space Blender'a и Stalker'a. И как их синхронизировать не могу понять. Кучу разных способов перепробовал, но ошибки сглаживания как были, [так и есть](https://s16vla.storage.yandex.net/rdisk/084c0972990c86efdf11747a73a48e0925dbc0b6bf71c5b27dc270c186d41be9/5a76e8ce/9fNnVlekWsBdp-T9LKrm1XJ2ak_yicPJiBEHaOLc64DByjVYj92dhioYVkR26M2hxxJxCGh-kXL82JCi3tziAw==?uid=0&filename=2018-02-04_10-04-07.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=2397275&hid=0207b6e8692e2a410f91ef8575954b31&media_type=image&tknv=v2&etag=a9969c69ec805ba7991925a80264bb5f&rtoken=BgKXmoHV8RCs&force_default=no&ycrid=na-246289c1dd3c8161149e896c8179dfef-downloader15h&ts=56460e9d14f80&s=a4d6410789be1dd78d08f3f109568e437209dfc05602aa9d07138f417923be83&pb=U2FsdGVkX18QpEZixcYkdjc2AmXCm95J7HzpLGYxVPLMXWdsrdJX4pSSykZ_R3rspXw3ybpDB6Y9B-bl0QD_ieQ6apbyr49EcCMCIQG5Li0=).

**Comment by igelbox** [comment]
> Я когда импортировал модель Winchester 1300 из игры, то при выставленном CS/CoP ломались группы, а при SoC норм. При экспорте видимо та же ситуация. Версия плагина 0.4.0 Видимо есть какой-то баг

Какая версия игры? Какой конкретно файл импортировался? Чем был сконвертирован из ogf в object?

> Подскажи, пожалуйста, передаётся ли tangent space из Blender?

на сколько я знаю, формат object не предоставляет возможности передачи tangent map, т.е. SDK его каждый раз рассчитывает при экспорте в ogf.
Если всё таки есть примеры где он передаётся, напиши - мы реализуем в аддоне.

**Comment by akaSpy** [comment]
> Какая версия игры? Какой конкретно файл импортировался? Чем был сконвертирован из ogf в object?

1. Версия игры — 1.6.02 (Steam-лицензия)
2. Импортировал файл — wpn_winchester1300_hud.object [(скачать)](https://github.com/igelbox/blender-xray/files/1692662/wpn_winchester1300_hud.zip). Это не оригинальный из игры, а мой, но он также нормально импортируется только при выборе SoC.
3. Конвертер не помню от куда скачал, датируется 24-06-2015, конвертируется через converter.exe с помощью .bat-файла.

**Comment by igelbox** [comment]
У меня, при открытии этого файла в CoP SDK, он загружается так же плохо, как и в Blender. Получается - это проблема с `converter.exe` (что он всегда конвертирует в SoC-овские группы сглаживания).
@PavelBlend, может ты знаешь, каким конвертером правильно преобразовывать модели ЗП.
Но, вообще, думаю можно смело импортировать сконверченные модели с `Format Version: SoC`, а сохранять для SDK с `Format Version: CS/CoP`.

**Comment by akaSpy** [comment]
> Но, вообще, думаю можно смело импортировать сконверченные модели с Format Version: SoC, а сохранять для SDK с Format Version: CS/CoP.

В том то и дело, что если сохраняешь с Format Version: CS/CoP, то бьются группы сглаживания, а если в SoC, то всё ок :) Магия! Может у меня, что-то локально не так.

Может при импорте куда-то фиксируется в blend-файл? Тот файл, который я выше скидывал, удалось сохранить как CS/CoP, но без битых групп?

**Comment by igelbox** [comment]
> Может при импорте куда-то фиксируется в blend-файл?

Навряд ли. Такого в аддоне не было.

> Тот файл, который я выше скидывал, удалось сохранить как CS/CoP, но без битых групп?

Да. Импортировал в Blender как `SoC` и сразу же экспортировал как `CS/CoP`. Потом открыл получившийся object-файл в SDK и там со сглаживанием всё хорошо.
Версии ПО:
SDK - 0.7
blender-xray - 0.5.0

**Comment by PavelBlend** [comment]
Конвертер бардака всегда сохраняет группы сглаживания в формате SoC, независимо откуда был взят ogf  файл (из ТЧ или из ЧН/ЗП).

@akaSpy я скачал твой файл wpn_winchester1300_hud.object, импортировал в blender, потом экспортировал в object в формате CS/CoP, потом сохранил в ogf с помощью SDK 0.7. В итоге в игре модель выглядит так же как в blender:
![sg_cop_test](https://user-images.githubusercontent.com/7983249/35776943-a2006134-09b6-11e8-8d78-92d880f95593.png)

Чтобы не было таких чёрных затенений на модели, нужно править группы сглаживания, так как сейчас они не совсем правильно настроены. Вот я исправил:
![fix_sg](https://user-images.githubusercontent.com/7983249/35777026-ba1fc538-09b7-11e8-8ea7-c73cdfd9ca63.jpg)

И вот blend сцена с исправленным сглаживанием:
[fix_sg.zip](https://github.com/igelbox/blender-xray/files/1692738/fix_sg.zip)

**Comment by akaSpy** [comment]
> Да. Импортировал в Blender как SoC и сразу же экспортировал как CS/CoP. Потом открыл получившийся object-файл в SDK 0.7 и там со сглаживанием всё хорошо.
>@akaSpy я скачал твой файл wpn_winchester1300_hud.object, импортировал в blender, потом экспортировал в object в формате CS/CoP, потом сохранил в ogf с помощью SDK 0.7. В итоге в игре модель выглядит так же как в blender:

Попробую поставить свежую версию плагина, очень странно.

> Чтобы не было таких чёрных затенений на модели, нужно править группы сглаживания, так как сейчас они не совсем правильно настроены. Вот я исправил.

@PavelBlend 
Дело не в группах сглаживания, они сделаны такими специально для тестирования карты нормалей. В игре карта нормалей по какой-то причине не компенсирует подобное сглаживание, хотя должно. Я предполагаю это из-за не соответствия tangent space. Но как синхронизировать не могу найти решение. Толи вектора из Blender имеют не то направление, то ли ещё чего. Пока нет мыслей.

**Comment by akaSpy** [comment]
Вот здесь хорошо показана проблема, при смене tangent basis (аналогичная моей): https://youtu.be/m-6Yu-nTbUU?t=2m31s

**Comment by PavelBlend** [comment]
@akaSpy можешь показать как выглядит карта нормалей?

**Comment by akaSpy** [comment]
@PavelBlend да, я в течении получаса подготовлю модель и карту нормалей, и скину сюда.

**Comment by akaSpy** [comment]
@igelbox, @PavelBlend 

[Каталог с файлами](https://yadi.sk/d/Lqw2e7OZ3S5ZKN)

in-game — скомпилированная модель для игры
raw — исходники

**Comment by PavelBlend** [comment]
@akaSpy я менял группы сглаживания и косяков стало меньше. Может в сталкере карта нормалей не компенсирует сглаживание, а дополняет его. Сквозь карту нормалей проглядываются затенения от групп сглаживания. В оригинальных моделях ЗП на острых углах нет сглаживания. Может так нужно делать и со своими моделями?

**Comment by akaSpy** [comment]
@igelbox, @PavelBlend 
Ребята, спасибо за помощь! Возьму время ещё на пару тестов.

**Comment by s30-zip** [comment]
Так же не забывайте удалять двойные вершины и выворачивать нормали наружу.

**Comment by akaSpy** [comment]
@igelbox 
Хочу уточнить, а при экспорте необходимо накидывать модификатор Edge Split, чтобы сохранить группы сглаживания?

Только недавно обратил внимание, что появляется ошибка (про неё я уже прочитал): 
Maya-SG incompatible: sharp edge adjacents has same smoothing group
Так вот Edge Split фиксит её.

И вообще как сохранить группы сглаживания?

**Comment by akaSpy** [comment]
@PavelBlend 
Подскажи, а как ты экспортишь группы сглаживания? У меня почему-то бьются в AE и в игре соответственно ломается нормалка.

В редакторах:
![2018-02-07_20-47-11](https://user-images.githubusercontent.com/5639749/35932231-33a80680-0c48-11e8-9fba-9f2c025f57e7.png)

В игре:
![2018-02-07_20-51-33](https://user-images.githubusercontent.com/5639749/35932475-beca2540-0c48-11e8-8c4b-85a9fd3c7ce0.png)



Edited: похоже опять проблема с форматом. Не знаю почему, но у меня экспортируется только в SoC нормально.

**Comment by PavelBlend** [comment]
@akaSpy просто нажимаю File>Export>XRay Object и ставлю тип формата (SoC или CS/CoP) и всё.
И никаких модификаторов Edge Split не нужно ставить.

А при экспорте этой модели есть предупреждения Maya-SG incompatible? Может острое ребро преобразовалось в сглаженное. Хотя если это ЗП, то не должно быть такого предупреждения. Только для ТЧ есть определённые ограничения в этом плане.

**Comment by akaSpy** [comment]
@PavelBlend 
Понятно, спасибо!

В SoC формате группы сохраняет. Но склеивает вершины и из-за этого бьет группы :(((( Флаг HQ Geometry не помогает. Существуют какие-то лекарства? 

![2018-02-07_21-06-02](https://user-images.githubusercontent.com/5639749/35933137-c45d462a-0c4a-11e8-93c5-516184b9b3e3.png)

**Comment by igelbox** [comment]
@akaSpy 
> Хочу уточнить, а при экспорте необходимо накидывать модификатор Edge Split, чтобы сохранить группы сглаживания?
И вообще как сохранить группы сглаживания?

Обычно и без него работает. Но, думаю, он может помогать в сложных случаях (разделяя треугольники, дублируя рёбра), когда текущий меш не представим в формате SoC/Maya. Тут, кстати, есть ишью по этому поводу (если уж очень нужен SoC формат) - #57, но у меня пока мощи не хватает, сделать нормальный алгоритм расчёта.
А в CoP-формате - нет таких ограничений, любые группы сглаживания должны поддерживаться аддоном, безо всяких дополнительных модификаторов.

**Comment by akaSpy** [comment]
@igelbox 
Спасибо за ответ! Я честно говоря так и не понял, почему у меня нормально не экспортируется в CoP-формате. Плагин поставил свежий. Может ещё СДК на всякий случай переустановить, странно это всё.

**Comment by igelbox** [comment]
Попробовал открыть модель из _Test/raw/sdk/editors/rawdata/meshes/dynamics/weapons/wpn_winchester1300/_ из ранее приложенного "Каталог с файлами" в SDK 0.7 - сглаживание сломано, в SDK - 0.4 - склаживание - норм.

Попробовал экспортировать модель из Test/raw/GameTest.blend используя формат CS/CoP - в SDK 0.7 - сглаживание норм, в SDK - 0.4 - склаживание сломано.

Может всё-таки версия SDK - не правильная. У меня, кстати, были похожие проблемы при использовании SDK 0.4: при компиляции OGF ломались нормали и в игре это выглядело как на половине с "original":
![akim](https://user-images.githubusercontent.com/5264687/35941784-8262dd38-0c64-11e8-82a6-9bc8017876dd.jpg)
Из-за этого в аддоне и появилась сырая поддержка экспорта в ogf (см. половину с "my (fixed)").
Сейчас, я тестирую в (откуда я их взял - уже не помню):
- xray-cop-sdk-setup.exe (версия 0.7) - 467937392 байт - MD5=b4dbf14d8a0731daa80ef9b9ea973f49
- xray-sdk-setup-v0.4.exe - 328910736 байт - MD5=4b79e90bc978493d0e1e3b3e88dca3bf

Вообщем, попробуй тоже экспортировать с CS/CoP и открыть в SDK для ЗП. Если не получается, то пиши, какой SDK используешь (не думаю, что сюда надо ссылку на пиратские ресурсы постить, может просто описание, как его найти на просторах интернета).

**Comment by akaSpy** [comment]
@igelbox 
Ты прав. Я установил чистый официальный SDK 0.7. Что-то было внутри SDK, что ломало весь процесс, либо какие-то файлы от 0.4 версии. С экспортом CS/CoP сглаживание заработало как надо. Правда не сразу. Модификатор Edge Split ломает группы в модели, по крайней мере в промежуточном использовании в *.fbx для запекания карты нормали, развёртки. И меня это сильно путало. Когда отказался от него, всё пошло как надо. **Большое тебе спасибо!** Наконец-то мои мучения закончились :)

Пока единственной проблемой осталось склеивание вершин, с HQ Geometry, в редакторе вроде по лучше выглядит, чем в игре. То есть как будто в игре игнорируется этот флаг. Ну хоть группы не ломает, уже хорошо. Но тут как вариант ещё есть оптимизировать модельку.

Накинул тестовую текстурку:
![2018-02-08_12-17-14](https://user-images.githubusercontent.com/5639749/35965119-edb057e4-0cca-11e8-9a03-9c51751cb301.png)

**Comment by s30-zip** [comment]
Есть ещё какой-то фикс "форсирование групп сглаживания" для SDK 0.7 https://www.gameru.net/forum/index.php?showtopic=46774

**Comment by igelbox** [comment]
Похоже на то, что вопрос решён. Если что, можно будет переоткрыть эту ишью.
