### ISSUE TITLE
Редактирование details: автоматизированная pack-овка текстур

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#168]
Судя по [видео](https://youtu.be/qlmiTV7BRD0), сейчас после редактирования, надо каждый раз ручками проходить и паковать текстуры.

Было бы лучше, если бы аддон автоматом паковал те текстуры, которые он понимает, как карты травы. Ну или сделать в Tool Shelf-е кнопку, упаковать карты травы в текстуры (чтоб один раз кликать, прямо из окна 3D View, не залезая в окно текстур).

**Comment by PavelBlend** [comment]
> сейчас после редактирования, надо каждый раз ручками проходить и паковать текстуры.

нужно это делать не после редактирования, а перед сохранением blend файла. Делать экспорт можно и без паковки. Но если нужно сохранить изменённые изображения в blend файл, то да, надо паковать.

> Ну или сделать в Tool Shelf-е кнопку, упаковать карты травы в текстуры

может тогда лучше в окне Properties, рядом с параметрами level.details пустышки (XRay - details панель)?

**Comment by igelbox** [comment]
> может тогда лучше в окне Properties, рядом с параметрами level.details пустышки

Да, так тоже подойдёт. Только, надо посмотреть, что удобнее в Tool Shelf лазить или в окно свойств.

**Comment by PavelBlend** [comment]
> Только, надо посмотреть, что удобнее в Tool Shelf лазить или в окно свойств.

в T панель быстрее залезть, но не факт, так как там куча вкладок и не всегда будет открыта нужная вкладка. А в окне свойств более логично. Всё будет находиться там где нужно, а не раскидано по всему интерфейсу безупрорядочено.
