### ISSUE TITLE
Баг в xray_io.Reader.gets()

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#179]
Если в цикле while True вызывать xray_io.Reader.gets(), то цикл будет работать бесконечно, даже если offs > len(data). По идее должна быть ошибка, так как байтов в data ограниченное количество, а не бесконечно.

**Comment by igelbox** [comment]
> в цикле while True вызывать xray_io.Reader.gets()

Можно конечно поправить, чтоб ошибка вылетала, но это будет ещё одно ветвление в таком часто-используемом коде, а Python и так не очень шустрый.
Но вообще, твой пример - спорный, ты же не будешь читать в бесконечном цикле, а потом ловить исключение. Давай лучше, может быть, метод добавим, который будет проверять, что ещё остались данные (не весь поток считан).

**Comment by PavelBlend** [comment]
Я когда разбирался с форматом level, запустил цикл While, который был бесконечным. А сейчас импортёр level работает без цикла While. Я просто подумал, что это ошибка, но если это так и было задумано, то пусть всё остаётся как есть. Нужды в новом методе нету.

**Comment by igelbox** [comment]
> но если это так и было задумано

Ну, просто так получилось)

> то пусть всё остаётся как есть

:+1:
