### ISSUE TITLE
Форматы level, level.geom, level.geomx

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#180]
Как устроен формат level.geom, а именно чанк 0x9 (вершинные буферы)?
И являются ли идентичными файлы level.geom и level.geomx? И для чего нужен level.geomx?

**Comment by PavelBlend** [comment]
Всё таки удалось понять, как устроен чанк 0x9. Но вопрос один остался: для чего нужен level.geomx

П.С.: я написал тестовый импорт level и level.geom. Но возможно ли будет сделать экспорт? Какие проблемы могут возникнуть при написании экспорта?

Я пока вижу следующие проблемы:
- нужно генерировать SWI DATA (упрощённые версии меша)
- нужно сохранить группы сглаживания. В уровнях сглаживание реализуется за счёт нормалей вершин. Но в этом я не уверен.
- нужно генерировать тангенсы и бинормали (кстати для чего они нужны и что из себя представляют?)

В общем придётся чуть ли не компилятор писать.

**Comment by igelbox** [comment]
Пока, могу сказать только про:
> SWI DATA

Там, по моему, всё сложно. Я из-за этой сложности так OGF-экспорт и не доделал.

> сглаживание реализуется за счёт нормалей вершин

Ну, тут всё должно быть гораздо проще - надо просто меш разбить по острым рёбрам (т.е. вместо одного острого ребра нужно сделать 2, у каждого из которых будет только по одному треугольнику), в bledner-е навреное, уже даже какой-нибудь готовый оператор для этого есть.

> нужно генерировать тангенсы и бинормали (кстати для чего они нужны и что из себя представляют?)

Эти штуки нужны, чтобы правильно рендерить с картами рельефа.
Еле нашёл [более-менее понятный пример](https://www.blender.org/forum/viewtopic.php?t=13400).
Ну, и вот [тут](http://www.opengl-tutorial.org/ru/intermediate-tutorials/tutorial-13-normal-mapping/) тоже, вроде бы, что-то нормальное написано.
Но, на самом деле, я думаю, что нужны только 2 вектора, например: нормаль и тангенс, т.к. третий вектор легко получается из двух предыдущих.

А зачем нам экспорт для level-формата? Может всё-таки пусть лучше SDK сам компилирует, а мы будем редактировать какие-нибудь исходные файлы, а не скомпилированные.

**Comment by PavelBlend** [comment]
> Там, по моему, всё сложно. Я из-за этой сложности так OGF-экспорт и не доделал.

а возможно сделать аналогично, как в компиляторе xrLC?

> А зачем нам экспорт для level-формата?

я хотел сделать из блендера своего рода конвертер. Например, для конвертирования уровней между разными билдами. А импорт может пригодиться для создания анимаций anm, чтобы анимировать камеру между деревьями, не влетая в них.

**Comment by igelbox** [comment]
> а возможно сделать аналогично, как в компиляторе xrLC?

Да всё можно сделать, но какой ценой. Я б не рискнул начинать.

> я хотел сделать из блендера своего рода конвертер. Например, для конвертирования уровней между разными билдами. 

Так а разве конвертер bardak-а не умеет уровни декомпилировать, чтоб получить какой-то аналог исходников от уровня, чтоб не нужно было возиться со скомпилированными файлами?

**Comment by PavelBlend** [comment]
> Так а разве конвертер bardak-а не умеет уровни декомпилировать, чтоб получить какой-то аналог исходников от уровня, чтоб не нужно было возиться со скомпилированными файлами?

В этом и проблема, что конвертер может только декомпилировать. И что делать после декомпиляции уровня? Заново его компилировать? Я хотел из блендера сделать конвертер. Чтобы была не только декомпиляция, но и возможность сохранения в игровой формат без необходимости тратить много часов на повторную компиляцию. И чтобы была возможность сохранить уровень в формат любого билда, а не только в формат финальной игры.

Но это трудно реализуемо, поэтому я закрою данную issue.
