### ISSUE TITLE
How to use this to export .ogf?

### ISSUE THREAD

**Issue by kdrnic** [PavelBlend/blender-xray#181]
I have tried importing both with https://github.com/igelbox/blender-ogf and with the .smd Blender plugin (after converting with ogf2smd), then editing and re-exporting to .ogf. However, it fails to export with either python errrors or "too many object roots found". Model I was trying to edit is wpn_knife_hud.ogf from STALKER SoC. I see there is an issue to create a tutorial for the wiki, but in the meantime could you explain quickly how to export it? This is very interesting project BTW.

**Comment by s30-zip** [comment]
Try to delete all elements not related to the model (lamp, camera ...) before exporting. But it's better to skip the model through the SDK.

**Comment by igelbox** [comment]
>  have tried importing both with https://github.com/igelbox/blender-ogf and

I do think the correct way to edit STALKER models is:
- convert the original OGF file to OBJECT one using the Bardak's converter
- import the OBJECT file using this (blender-xray) addon (*not* the blender-ogf one)
- export to the OBJECT file format (yeah, there is an experimental support for OGF that mustn't be used in a kind of production builds)
- compile the new OBJECT file into an OGF one using the official XRay SDK (for the desired version of STALKER).

> I see there is an issue to create a tutorial for the wiki

Yeah. However, I don't believe we'll add this wiki in a near future.
I think the best way to learn this addon is looking for tutorials on YouTube (e.g. https://youtu.be/xZ12xVqXZzE).

> This is very interesting project BTW.

Thanks, I'm glad to hear that.
BTW, you could help this project e.g. via filing issues (proposals and bugs) and create tutorials and lessons :)

**Comment by igelbox** [comment]
Well, if there's nothing else, I close the issue.
