### ISSUE TITLE
Некоторые баги импорта/экспорта

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#182]
1.Некоторые модели не правильно проигрывают анимацию https://yadi.sk/d/13-TDNXH3TDWUr
2.При изменении форм коллизий в блендер они багуют  в игре, при косании все отлетает https://yadi.sk/d/XpRsfwfy3TDWUy (пример настройки в блендер и СДК 0.7).

**Comment by igelbox** [comment]
@s30-zip ссылки не открываются.

**Comment by s30-zip** [comment]
А, я думал через кнопку "add a link" нужно добавлять, а там просто ссылку можно вставлять, поправил.

**Comment by igelbox** [comment]
@s30-zip 
По bug_rotate.blend - нужен object-файл, иначе импорт не проверить. И ещё очень бы желательно понять откуда такой object-файл взялся, например, из какого ofg-файла был сконвертирован и чем был сконвертирован.

Про wall.zip - я не очень силён ни в SDK, ни в модостроении => мне нужна простая инструкция, как воспроизвести эту багу с отлетанием, чтоб я смог её починить.

**Comment by s30-zip** [comment]
Попробуйте сконвертить meshes\dynamics\el_tehnika\disel_generator.ogf или krisagenerator.ogf  из архивов игры или СДК, импортировать в блендер и вкл. анимацию. Пробовал несколько конвертеров bardak-а rev10192 и ещё какой-то, но результат тот же.
Заспавните в ЗП wall и wall_sdk и постреляйте по ним или просто попробуйте пройти сквозь стену.
wall- разрушаемый объект. Файл "wall.ogf"-стена с формами коллизии сгенерироваными и смасштабированными в блендер https://youtu.be/1DVlrBHFxpc , а "wall-sdk.ogf" - сделано в сдк https://youtu.be/wvxMk6nHedM

**Comment by igelbox** [comment]
Да, с `krisagenerator.ogf` получилось воспроизвести. Там, после конвертера получаются скачки вращения по одной из осей +3.14, -3.14, +3.14 из-за этого у аддона крышу сносит. Буду чинить.

А по поводу разрушаемой стены - попробуй поднастроить формы в Bledner с зазорами, чтобы они точно не пересекались. Всё равно в игре разлетается или помогло?

**Comment by s30-zip** [comment]
Пробовал, не помогает. Можно даже проще, поменять в блендер какому-нибудь предмету форму (например канистре), и в игре при попытке походить по ней она отлетает (или вы :)) в не предсказуемом направлении, почему-то ей придаётся не слабый импульс, причем что бы поправить это нужно в сдк заново генерировать формы, ибо простым масштабированием не правится.

**Comment by redpython** [comment]
@s30-zip 
> Пробовал несколько конвертеров bardak-а rev10192 и ещё какой-то, но результат тот же.

Не могу предположить. имеет ли это отношение к описанной проблеме, но на всякий случай конвертер с исправленным сохранением лимитов: https://yadi.sk/d/nivUmGybuCXSC

**Comment by s30-zip** [comment]
Уточнение: баг с физикой проявляется только после редактирования формы "куб", у "сферы" и "цилиндра"  замечено не было.

**Comment by s30-zip** [comment]
> конвертер с исправленным сохранением лимитов

к сожалению новая версия дел не меняет

**Comment by igelbox** [comment]
Я выяснил в чём проблема с "куб"-ической формой костей - я не правильно проинтерпретировал использование полноценной матрицы 3х3 в object-файлах. Оказывается, движок её как-то по-особенному использует. Скоро, думаю, залить фикс, после которого режим редактирования формы кости будет генерить нормальную матрицу.
А пока, @s30-zip проверь, пожалуйста, следующий скрипт, исправляющий форму костей, испорченную редактированием. Этот скрипт можно будет и после фикса использовать, чтоб починить сразу все кости, не редактируя их по-отдельности:
```python
import bpy
from mathutils import Matrix, Vector

def v2ms(vec):
    mat = Matrix.Identity(3)
    for i, val in enumerate(vec):
        mat[i][i] = val
    return mat


for arm in bpy.data.armatures:
    for bone in arm.bones:
        shape = bone.xray.shape
        if tuple(shape.box_hsz) != (1, 1, 1):
            continue

        # construct a matrix
        rot = shape.box_rot
        mat = Matrix((rot[0:3], rot[3:6], rot[6:9])).transposed()
        mat *= v2ms(shape.box_hsz)

        # de-construct the matrix
        scale = mat.to_scale()
        if scale.x < 0:
            scale *= -1
        mrt = (mat * v2ms(scale).inverted()).transposed()
        for i in range(3):
            shape.box_rot[i * 3:i * 3 + 3] = mrt[i].to_tuple()
        shape.box_hsz = scale.to_tuple()

        print('%s / %s' % (arm.name, bone.name))
```

А насчёт бага "Некоторые модели не правильно проигрывают анимацию" - навряд ли я смогу его быстро поправить, так что если он ещё актуален, то заведи его, пожалуйста, как отдельный баг. А этот мы закроем как баг формы костей.

**Comment by s30-zip** [comment]
> насчёт бага "Некоторые модели не правильно проигрывают  анимацию"

Пока не пользуюсь этими моделями, но есть прикол импортирую модель СДК 0.7 из rawdata например krisagenerator.object , работает нормально, а сконверченная СДК 0.7 из gamedata - нет. Видимо конвертер влияет на правильность отыгрывания анимации.

**Comment by igelbox** [comment]
@s30-zip баг с импортом `krisagenerator.object` был исправлен в #217. Спасибо @PavelBlend!
