### ISSUE TITLE
Передача репозитория в другую организацию

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#183]
В последнее время у меня чертовски мало ресурсов на поддержание этого проекта.
И похоже, что из драйвера этого проекта, я становлюсь его блокером, т.к. @PavelBlend открывает пулл-реквесты, а мне некогда их ревьюить и некогда выкладывать релизные версии аддона.

Поэтому, чтобы не блочить разработку аддона, есть идея отдать его под контроль какой-нибудь другой организации (в терминах GitHub-а), где найдутся люди, которые смогут ревьюить код и следить за качеством аддона. Ну и где я тоже бы смог время от времени принимать участие.

План действий:
- [ ] Определиться с организацией и договориться с её участниками о поддержке.
- [ ] Почистить репозиторий от временных/экспериментальных веток.
- [ ] Передать репозиторий и склонировать его сюда, как форк.
- [ ] Установить README.md с текстом, где искать оригинальный репозиторий (для ишью и пулл-реквестов).

**Comment by igelbox** [comment]
Предлагайте, пожалуйста, в какие организации можно отдать этот проект.
Я пока думаю с https://github.com/OpenXRay попробовать договориться, но может где-то есть более крупная и известная организация, у которой больше человеческих ресурсов на поддержку.

**Comment by PavelBlend** [comment]
Я не знаю ни одной организации.

Мне кажется, что в блендере среди модостроителей никто не заинтересован до такой степени, чтобы продолжить писать плагин. У меня у самого желание писать плагин то пропадает, то появляется.

И мне кажется, что плагин достиг своей финальной версии. Разве что не хватает выбора экспортируемых анимаций. А остальное - это всего лишь улучшения, которые необязательны.

> Поэтому, чтобы не блочить разработку аддона, есть идея отдать его под контроль какой-нибудь другой организации (в терминах GitHub-а)

А это как? Другая организация сможет удалять и добавлять ветки/issues/pulls? Или подразумевается простой форк?

**Comment by Xottab-DUTY** [comment]
> А это как? Другая организация сможет удалять и добавлять ветки/issues/pulls? Или подразумевается простой форк?

Да, сможет.

> Я пока думаю с https://github.com/OpenXRay попробовать договориться, но может где-то есть более крупная и известная организация, у которой больше человеческих ресурсов на поддержку.

@nitrocaster, можешь что-то сказать?

Также, помимо нас мне известен xrOxygen. @ForserX, приди =)

Хотя, лично я сомневаюсь насчёт передачи репозитория кому-либо, вместо этого можно просто выдать доступ к репозиторию товарищу @PavelBlend

**Comment by ForserX** [comment]
Можно к нам.

**Comment by Xottab-DUTY** [comment]
Для качественной поддержки (а не просто на плаву) необходимо знать Питон и иметь опыт работы с Блендером (а ещё, желательно, пользоваться им). Надеюсь, кроме @igelbox и @PavelBlend, найдётся ещё один такой человек, а лучше больше. =)

**Comment by redpython** [comment]
Учитывая тот факт, что активных программистов среди сталкироманов мало; занимающихся решением актуальных проблем, а не _чем-то непонятным_, считанные единицы; а уж блендерщиков так вообще лишь двое - обсуждение выглядит по меньшей мере странным.

В настоящее время единственный профит, которого вы сможете достичь, передавая свой репозиторий налево - это получить красивый урл для него и какой-то бонус к посещаемости.

**Comment by igelbox** [comment]
> а уж блендерщиков так вообще лишь двое

Я думаю, что больше, судя по количеству набранных звёздочек.

> это получить красивый урл для него и какой-то бонус к посещаемости

@redpython, не пали контору, это и был мой тайный план)

> вместо этого можно просто выдать доступ к репозиторию товарищу @PavelBlend

@Xottab-DUTY, я считаю, что для качественного кода нужно минимум 2 человека - разработчик и код-ревьюер. Получается, просто передача этой репы другому человеку, проблему не решит, т.к. всё-равно нужен будет один разработчик для ревью. Вот я и подумал, что ещё одного человека будет проще найти, если этот репозиторий будет располагаться по какому-то красивому урлу (в какой-нибудь популярной и тематической организации).

**Comment by redpython** [comment]
@igelbox раз уж на то пошло, могу предложить запустить зеркало этого репо на битбакете https://bitbucket.org/stalker/
Некоторые проекты так и делают - кто просто для удобства пользователей, кто по той же причине, что толкнула к созданию этого ижью. В любом случае, посещаемость увеличится.

Что касается звёздочек - я тоже ставил, хотя даже не использую блендер. Это форма респекта разработчикам, но не индикатор количества кодеров, потенциально готовых участвовать в проекте :)

**Comment by ForserX** [comment]
https://github.com/xrOxygen/blender-xray 

Вот вам красивый url. По фану добавил.

**Comment by igelbox** [comment]
Эх, меня прям калит, когда открытый/свободный код становится не совсем свободным.
Вообщем, после долгих терзаний, репозиторий был передан к @PavelBlend :tada: 
Всем спасибо за участие.
@ForserX удали (ну или форкни репозиторий Павла), пожалуйста, https://github.com/xrOxygen/blender-xray. А то он как параллельная реальность какая-то))
