### ISSUE TITLE
Сломаны тесты test_preferences.py

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#184]
Если запустить тесты, то появляется 4 ошибки в скрипте test_preferences.py
```======================================================================
FAIL: test_auto_values_from_some_file (tests.cases.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\unittest\mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "D:\git\blender-xray\tests\cases\test_preferences.py", line 39, in test_auto_values_from_some_file
    self.assertEqual(prefs.gamedata_folder, '')
AssertionError: '\\gd' != ''
- \gd
+


======================================================================
FAIL: test_auto_values_if_no_paths (tests.cases.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\unittest\mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "D:\git\blender-xray\tests\cases\test_preferences.py", line 53, in test_auto_values_if_no_paths
    self.assertEqual(prefs.gamedata_folder, '')
AssertionError: '\\gd' != ''
- \gd
+


======================================================================
FAIL: test_auto_values_if_textures_is_root (tests.cases.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\unittest\mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "D:\git\blender-xray\tests\cases\test_preferences.py", line 82, in test_auto_values_if_textures_is_root
    self.assertEqual(prefs.gamedata_folder, '')
AssertionError: '\\gd' != ''
- \gd
+


======================================================================
FAIL: test_auto_values_no_reassign (tests.cases.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\unittest\mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "D:\git\blender-xray\tests\cases\test_preferences.py", line 67, in test_auto_values_no_reassign
    self.assertEqual(prefs.gamemtl_file, '')
AssertionError: '\\gdf\\gamemtl.xr' != ''
- \gdf\gamemtl.xr
+
```

Это связано с тем, что папка gd или gdf должна существовать. Иначе аддон автоматом установит значения в пустую строку для остальных путей. Т. е. если нету папки gd то аддон работает некорректно.

**Comment by igelbox** [comment]
Не, не должна существовать, т.к. там логика проверки существования файла мокается через `from unittest.mock import patch`.
Странно как-то, такое чувство, что тесты у тебя подцепили какие-то существующие настроки blender-а. А ты как тесты запускаешь, так же как написано в `.travis.yml` ?

**Comment by PavelBlend** [comment]
Я запускаю командой, как в tests\README.md:
```blender --factory-startup -noaudio -b --python tests/runner.py --save-html-report```

И перед запуском у переименовываю каталог ```C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\```, чтобы настройки были по умолчанию. И плагин я храню в ```C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons```

**Comment by PavelBlend** [comment]
> Не, не должна существовать

у меня почему-то не так. Я запускаю блендер, захожу в настройки плагина и вижу, что все поля пустые. Потом в поле `Gamedata folder` я вставляю путь к существующей `gamedata` папке и все остальные поля заполняются правильно. Но если удалить папку `gamedata\textures`, то все поля проставятся правильно, кроме `Textures folder` (она будет пустой строкой).

В общем если нету папки, то автоматом плагин установит её в пустую строку.

**Comment by PavelBlend** [comment]
Сейчас начал разбираться ещё раз в этой проблеме. По-моему тесты не правильные. 

> такое чувство, что тесты у тебя подцепили какие-то существующие настроки blender-а

да, подцепили настройки, только не блендера, а от предыдущего теста.

То есть сначала выполняется тест [test_auto_values_default.](https://github.com/PavelBlend/blender-xray/blob/b761249bb5b80a965b3ce786b1f32fc3230650b6/tests/cases/test_preferences.py#L12) Он ничего плохого не делает.

Потом выполняется тест [test_auto_values_from_gamedata](https://github.com/PavelBlend/blender-xray/blob/b761249bb5b80a965b3ce786b1f32fc3230650b6/tests/cases/test_preferences.py#L20), который заполняет поля своими значениями, а именно `\\gd`.

Далее выполняется тест [test_auto_values_from_some_file](https://github.com/PavelBlend/blender-xray/blob/b761249bb5b80a965b3ce786b1f32fc3230650b6/tests/cases/test_preferences.py#L36), который подцепляет настройки из предыдущего теста, а именно `gamedata_folder` = `\\gd`

Из-за чего возникает ошибка, которую я указал в первом [комментарии](https://github.com/PavelBlend/blender-xray/issues/184#issue-332663866)

Вот она:
```FAIL: test_auto_values_from_some_file (tests.cases.test_preferences.TestPreferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79b\2.79\python\lib\unittest\mock.py", line 1159, in patched
    return func(*args, **keywargs)
  File "D:\git\blender-xray\tests\cases\test_preferences.py", line 39, in test_auto_values_from_some_file
    self.assertEqual(prefs.gamedata_folder, '')
AssertionError: '\\gd' != ''
- \gd
+
```

Решение проблемы: обнулять все настройки плагина, перед выполнением каждого теста.

@igelbox а у тебя тесты из последнего коммита без ошибок работают?

**Comment by igelbox** [comment]
Проверил на последнем коммите 7db3374 - полёт нормальный:
> Ran 72 tests in 9.627s

**Comment by PavelBlend** [comment]
Почему-то у меня эти тесты 00fb477ab59185cd1c5b00855a19e8d4934d790b отказывались работать. Я их изменил. Теперь работают без ошибок. Я делал тесты для dm, details, err. Мне нужно было срочно временно исправить эту проблему. Не знаю, правильно я решил её или нет f41c561e1d5e15ff4d225cb75a7ef0d8c23db95f

**Comment by igelbox** [comment]
Я думаю, что такое решение допустимо. Лучше бы, конечно, разобраться, почему `--factory-startup` не работает. Но это долго, и может быть неоправданно. Единственное чего я бы там поправил, это вместо многократного повторения вызовов функции очистки - перенести её вызов в метод https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp.
