### ISSUE TITLE
Нельзя редактировать userdat'у

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#185]
Сейчас в плагине невозможно изменить userdata у вновь созданных объектов, так как она всегда серая (неактивная). При нажатии на кнопку вставить, ничего не происходит.

**Comment by igelbox** [comment]
Ошибка появилась в коммите 5b309c668e58c872e0a90427bd8619886e7bb905. Там вместо блокировки кнопки стала блокироваться вся панель.
