### ISSUE TITLE
Загружать текстуры шейдеров

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#192]
Сделать загрузку шейдерных текстур, которые выступают в виде детальной текстуры.
Придумать, как это реализовать. В виде кнопки или в виде галочки при импорте.
Если в виде кнопки, то куда её поместить: в окно материалов или в T панель во вкладку XRay.
Так же сделать кнопку для удаления данных детальных текстур.
И возможно придётся изменить экспорт, так как при экспорте путь к текстуре берётся из активного текстурного слота.
Возможно придётся научить плагин определять прозрачность шейдера, самосвечение и прочие визуальные параметры, которые указываются в XRay SDK.

**Comment by s30-zip** [comment]
"+" к детальной текстуре получается другая развертка применяется.
Я думаю в Т-панели две кнопки лучше, одна генерирует "деталку" с надстройками, другая - чистит.
 И может быть делать кнопку экспорта не активной с предупреждением о необходимости очистки "деталки" при включённой опции?

**Comment by PavelBlend** [comment]
> "+" к детальной текстуре получается другая развертка применяется.

помоему второй юви не нужно. А нужно изменить параметр Size у текстуры.

> И может быть делать кнопку экспорта не активной с предупреждением о необходимости очистки "деталки" при включённой опции?

нужно сделать, чтобы плагин автоматом вычислял где базовая текстура, а где детальная. Без необходимости включать/выключать опции.

**Comment by PavelBlend** [comment]
Я думаю эту функцию мы реализовывать пока не будем, так как есть проблема:
все детальные текстуры terrain'а хранятся в xr файлах (и это легко реализовать), а что делать для других текстур (здания, камни, деревья...)? Для других текстур придётся писать парсер thm и ltx, так как все деталки хранятся в thm (ЗП) и в файле textures.ltx (ТЧ). А это будет тяжело сделать. И если этого не делать, а сделать только чтение деталок из xr файлов, то ради одних террейнов так заморачиваться... Легче вручную самому накинуть вторую текстуру для террейна. Там всего 3-4 материала настроить, это не муторно. 

То есть усложнять плагин ради террейнов мы не будем. Такие материалы легко настроить самому.
