### ISSUE TITLE
Проблемы с импортом "Error list"

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#193]
Не получается импортировать ошибки геометрии, пример .err https://drive.google.com/open?id=1OgLzE1QfvQH6TBiEUpFabRj7z0cKWm4J При импорте ни чего не происходит, думал  загрузить модели и импортировать .err, чтоб показало, но ни чего, даже сообщений нет.

**Comment by PavelBlend** [comment]
А ты каким компилятором пользуешься? SoC, CS или CoP?

**Comment by s30-zip** [comment]
SoC

**Comment by PavelBlend** [comment]
Дело в том, что в твоём err файле неизвестные чанки: 0xA, 0xB и 0xC. А должны быть 0x1, 0x2 и 0x3. Может у тебя компилятор правленный и не оригинальный? Если да, то можешь дать ссылку, где можно его скачать?

**Comment by s30-zip** [comment]
Сборкой не я занимаюсь, я лишь правлю ошибки геометрии, как только скинут, выложу тут.

**Comment by PavelBlend** [comment]
Можешь ссылку на сдк не скидывать. Я только что понял в чём проблема. Твой err файл получен путём экспорта из сдк. При экспорте из сдк получается другой формат err. Всего получается два формата err. Один сохраняется с помощью xrLC, а второй получается после экспорта из сдк.

**Comment by PavelBlend** [comment]
Всё, исправил. Теперь err должен нормально импортироваться. Можешь качать аддон из ветки develop (последний коммит) и проверять. Если всё работает, то я закрою данную issue.

**Comment by s30-zip** [comment]
Вроде работает, ещё неколько вопросов: на некоторых моделях есть группы вершин с названием .xr-bad!, это тоже ошибки геометрии?Как они получаются (эти группы)? И можно ли сделать что бы ерор импортировались в таком виде?То есть импортируешь модель и ерор лист и получаешь .xr-bad!?

**Comment by PavelBlend** [comment]
> на некоторых моделях есть группы вершин с названием .xr-bad!, это тоже ошибки геометрии?

для СДК это не является ошибкой, для блендера - является. Точнее не для блендера, а для модуля bmesh, который используется в блендере.

> Как они получаются (эти группы)?

Если в object файле есть одинаковые полигоны, то создаётся данная группа, в которую назначаются эти дублирующиеся полигоны. Дублирующиеся - это значит, что они построены на одних и тех же вершинах.

> И можно ли сделать что бы ерор импортировались в таком виде?То есть импортируешь модель и ерор лист и получаешь .xr-bad!?

а для чего это может пригодиться?

**Comment by s30-zip** [comment]
А, я думал это и есть инвалид фэйсы, просто получаются другим путём, я просто глянул на один такой он был похож на растянутый полигон...Тогда всё, думаю можно закрыть ишью.
