### ISSUE TITLE
Проверка на пустые материалы

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#194]
Можно ли сделать проверку на пустые материалы? Иногда бывает на карте нужно удалить какую-либо сетку которая может использовать несколько единичных материалов, в итоге матерал есть, сетки нет и сдк на это ругается, но при куче материалов и большом редактировании сетки нужно потом каждый раз проверять какой материал выскочит с ошибкой в сдк ибо списка нет.Было бы удобно сделать проверку с удалением или выводом в текст эдиторе пустых материалов.

**Comment by PavelBlend** [comment]
Есть стандартный аддон `Materials Utils Specials`. Если его включить, то при нажатии на `Shift+Q` в объектном режиме, выскочит меню, в котором можно выбрать `Clean Slots > Clean Material Slots`. Этот оператор удаляет все неиспользуемые материалы у выделенных объектов.

Решение проблемы такое: перед экспортом воспользоваться данным аддоном и удалить всё неиспользуемые материалы.

Мне не хочется добавлять в аддон эту возможность, так как экспорт может замедлиться. Вот только на сколько замедлиться? Если не сильно, то можно добавлять проверку. Я попозже это проверю.

**Comment by igelbox** [comment]
> Мне не хочется добавлять в аддон эту возможность, так как экспорт может замедлиться

:+1: Если уже есть готовое решения, то я бы тоже не стал "переизобретать велосипед".

Я бы лучше проверку и Warning во время экспорта добавил, что бы заранее знать, что SDK при импорте скорее всего ругаться будет. И увидев это сообщение, пользователь может запустить свой любимый аддон для очистки материалов.

**Comment by s30-zip** [comment]
Не знал про этот аддон, спасибо за подсказку.

**Comment by PavelBlend** [comment]
> Если уже есть готовое решения, то я бы тоже не стал "переизобретать велосипед".

можно было бы и реализовать это в аддоне, так как неудобно каждый раз после редактирования пользоваться аддоном для очистки материалов. Для меня главное чтобы скорость экспорта не значительно замедлилась.

**Comment by PavelBlend** [comment]
@s30-zip я сделал удаление пустых материалов при экспорте. Можешь проверять. У меня вроде всё работает. Код находится в ветке `issue/194/materials_clean`.

**Comment by s30-zip** [comment]
Да, работает, спасибо!

**Comment by PavelBlend** [comment]
Смержил в ветку develop.
