### ISSUE TITLE
Проблемы с группами сглаживания

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#195]
При открытии обжэкт файла в СДК 0.4 сыплются такие ошибки 
Invalid smooth group found (Maya type). Object: 'levels\l03_zavodrostok\l03_zavodrostok_part0752'. Vertex: [206.65, -0.64, 117.51] 
Invalid smooth group found (Maya type). Object: 'levels\l03_zavodrostok\l03_zavodrostok_part0752'. Vertex: [206.65, -0.64, 117.51] 
и т.д.  Файл: https://drive.google.com/file/d/1_6jgomcLRqPDhwMTOWvFBy8Hz2txUT8m/view
При экспорте в Blender стоит SoC сглаживание.

**Comment by PavelBlend** [comment]
Сейчас скомпилировал уровень с объектом, который имеет `Invalid smooth group`. Компиляция прошла успешно. Это видимо не ошибка, а предупреждение. В исходниках движка пытался выяснить, из-за чего это предупреждение появляется, но так и не понял. @igelbox а что ты скажешь по этому поводу? Чем это может быть вызвано?

**Comment by s30-zip** [comment]
В общем: заметил что ошибки в большинстве по одним и тем же координатам, удалил двойные вершины в блендер, теперь вроде нормально открывается. Я читал на форуме , что это ни чего страшного , что всё компилится нормально, но человек который собирает сборку пишет что  "на практике это не так ,у меня вот в доме, периметр делал ещё, с таким сглаживанием линии в доме появились, исправили - исчезло" по этому я и обратился

**Comment by igelbox** [comment]
Думаю, похоже на двойные вершины, т.к. если на двойной вершине построен треугольник, то его площадь и нормаль будет 0, а поиск по исходникам (правда, это исходники 1.6, а исходников SoC я так быстро не нашёл, но в SoC этот код не был закомментирован ещё) [показал](https://github.com/OpenXRay/xray-16/blob/2aad79ae658503f7e08ba84ba82448bf99cc03c9/src/editors/ECore/Editor/EditMesh.cpp#L180), что да, эта ошибка из-за того, что длина вектора нормали какого-то треугольника < EPS_S, т.е. равна 0 скорее всего.

**Comment by PavelBlend** [comment]
Я экспортировал стандартный объект Suzanne, и в СДК появилось данное предупреждение. Потом импортировал в блендер полученный object и на носу Сюзанны есть два дублирующихся полигона (xr-bad). Но их площадь не равна нулю. СДК как раз ругается на вершину из данных полигонов.

**Comment by igelbox** [comment]
Попробовал пример с Suzanne:
* Там, у оригинальной мартышке, на носу 2 четырёхугольника.
* А SDK понимает только треугольники.
* Поэтому в аддоне есть вызов преобразующий все N-гоны в треугольники.
* Из-за этого преобразования в mesh-е появилось 2 треугольника, использующие одни и те же вершины, у которых противоположенные нормали
* SDK, при [вычислении нормали у вертекса](https://github.com/OpenXRay/xray-16/blob/2aad79ae658503f7e08ba84ba82448bf99cc03c9/src/editors/ECore/Editor/EditMesh.cpp#L288), сложил нормали обоих треугольников и получил 0

Самый прикол в том, что получается, что bmesh всё-таки иногда поддерживает наличие нескольких полигонов на одних и тех же вершинах, раз уж он сам такую геометию на-триангулировал) Но, это скорее баг Blender-а.

**Comment by igelbox** [comment]
Реализовал алгоритм, убирающий сглаживание с рёбер, треугольники которых имеют противоположенные нормали. И протестировал производительность:
* agroprom_cuts.object (928042 рёбер, 590775 треугольников) => 70 сек весь экспорт, из них 1 сек - этот алгоритм.
* mp_atp_buildings.object (154550 рёбер, 98373 треугольников) => 6 сек весь экспорт, из них 0.16 сек - этот алгоритм.

Итого, замедление экспорта составит ~2-3%.
И я бы включил этот алгоритм по-умолчанию. И сделал бы возможность выключать его в Expert-Mode. Что думаете?

**Comment by PavelBlend** [comment]
> И сделал бы возможность выключать его в Expert-Mode.

можно этого не делать. Так как скорость не значительно упала. И не хочется усложнять интерфейс плагина.

**Comment by igelbox** [comment]
@s30-zip а попробуй почистить геометрию с помощью [Degenerate Dissolve](https://docs.blender.org/manual/en/dev/modeling/meshes/editing/cleanup.html#degenerate-dissolve) например. Помогает?

_правильный ответ - помогает :smile: 
(я проверил на твоём object-файле - ошибок нет)_

**Comment by s30-zip** [comment]
Да, вы правы, честно говоря никогда не попадалась эта вкладка (clear) обычно горячие клавиши и T/N панелей для работы достаточно было. В принципе похоже это подходящее "лекарство", наверно можно закрывать ишью, хотя... есть ли смысл сделать проверку на такие ошибки в виде кнопки валидности геометрии при которой перед экспортом можно проверить на invalid faces и smooth groups?

**Comment by igelbox** [comment]
> есть ли смысл сделать проверку на такие ошибки в виде кнопки валидности геометрии при которой перед экспортом можно проверить на invalid faces и smooth groups?

С одной стороны - кажется полезной фичей, т.к. можно заюзать актуальные лимиты из исходников SDK.
А с другой стороны - почему бы просто, после экспорта, не загрузить полученный объект в реальный SDK и узнать все проблемы со 100% гарантией?

**Comment by PavelBlend** [comment]
> почему бы просто, после экспорта, не загрузить полученный объект в реальный SDK и узнать все проблемы со 100% гарантией?

потому, что объектов может быть очень много. Например, после декомпиляции билдовских уровней. Можно конечно в blender'е все объекты объединить по логическим группам и сделать десяток (вместо сотен) объектов, но это дополнительная работа. Да ещё проблема в том, что если так объединить объекты, то в LevelEditor'е нужно будет перенастраивать сектора и порталы.

**Comment by igelbox** [comment]
Ну, тогда сделаем утилитную возможность выгрузки всех или только выделенных объектов в единый object-файл. Т.е. для проверки геометрии надо будет:
1. выделить нужные объекты
2. запустить этот специальный режим экспорта
3. загрузить один object-файл в ActorEditor (например) и он уже скажет, где геометрия не хороша.

**Comment by PavelBlend** [comment]
Мне кажется, что лучше не делать специальный режим экспорта, так как это усложнит плагин. Лучше сделать кнопку в T панели, с помощью которой можно удалить полигоны с нулевой площадью у всех выделенных объектов. И реализовать это с помощью инструмента Degenerate Dissolve. Так будет более интуитивно и понятно, чем новый режим экспорта.

**Comment by igelbox** [comment]
Я тут вижу следующие недостатки:
* Решаем только одну проблему "полигоны с нулевой площадью". И то не совсем решим, т.к. у Blender и у SDK могут быть разное понимание, что такое полигон с нулевой площадью, например SDK может считать нулевой площадь меньшую какого-то маленького числа.
* Не диагностируем проблему с острым ребром на носу у Suzanne.
* Приучаем пользователей Bledner к нашей самодельной кнопке, вместо втроенной стандартной возможности (рядом с которой живут другие интересные действия).

Про усложнение плагина из-за добавления ещё одного режима экспорта - согласен. Я думал, там надо будет просто ещё одну галочку сделать в существующем экспорте, но пока не получается. А с нашей стороны, там уже есть эта логика по экспорту много-мешевых геометрий, надо только её правильно вызвать, ну и тестами закрыть и забыть.

**Comment by igelbox** [comment]
О, только что осознал:
> потому, что объектов может быть очень много. Например, после декомпиляции билдовских уровней. Можно конечно в blender'е все объекты объединить по логическим группам и сделать десяток (вместо сотен) объектов, но это дополнительная работа.

Так, это что получается, в итоге человек экспортирует все эти сотни объектов из Blender в SDK один за одним? Если да, то это жесть какая-то и надо бы эту боль как-то автоматизировать. Если нет, то получается что не все объекты и проверять-то надо.

Да и вообще, как так может пролучиться, что мы экспортим из Blender много объектов и потом не загружаем их в SDK? Зачем мы их тогда экспортировали-то? Я так понимаю, что любой экспортированный объект так или иначе в SDK загружается, т.е. разработчик мода уже и так вынужден это делать => проверка ошибок самим SDK для него бесплатная.

**Comment by PavelBlend** [comment]
Я думал так:

- Декомпилим уровень и получаем сотни object'ов

- Открываем этот уровень в LevelEditor и видим кучу ошибок Invalid Smoothing Group у многих объектов (пока я такого не встречал правда)

- Импортируем в блендер все объекты уровня, выделяем их и нажимаем одну кнопку "Check Geometry"

- Делаем экспорт

И эти действия проделать легче, чем по логу из СДК искать проблемные object'ы и каждый проверять вручную с помощью Degenerate Dissolve.

И на кнопку "Check Geometry" можно навесить поиск Invalid Faces и Invalid UVs (это разновидность инвалидных полигонов).

**Comment by s30-zip** [comment]
Всё таки оно жалуется на не связанные вершины в одной точке, были ещё такие предупреждения и там явно две части меша трубы(вообще их было пять) были краями приставлены, я для поиска пользовался 3д курсором-выставлял координаты xyz из сообщения, только в блендер нужно выставить значения на xzy и находил таким образом расположение, но затратно по времени.

**Comment by PavelBlend** [comment]
Закрываю данную issue, так как решение этой проблемы обсуждается здесь: https://github.com/PavelBlend/blender-xray/issues/202
