### ISSUE TITLE
Декомпрессия чанков

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#198]
Научить модуль [xray_io](https://github.com/PavelBlend/blender-xray/blob/develop/io_scene_xray/xray_io.py) работать со сжатыми (по алгоритму Хаффмана) чанками.
Пример алгоритма можно посмотреть здесь:
[lzhuf](https://github.com/abramcumner/xray_re-tools/blob/master/garbage/lzhuf/lzhuf.c)
или здесь:
[xr_lzhuf](https://github.com/abramcumner/xray_re-tools/blob/master/sources/xray_re/xr_lzhuf.cxx)
Решить как это реализовать: на питоне или на более быстром языке?

**Comment by igelbox** [comment]
Мне, однажды, такое тоже понадобилось, но для распаковки sav-файлов.
А зачем это надо аддону?

**Comment by PavelBlend** [comment]
Некоторые билдовские файлы имеют компрессию. Я делаю импорт уровней из билдов. Вот в этом репозитории: [stalker_tools](https://github.com/PavelBlend/blender_stalker_tools_addon)
Дело в том, что данный аддон устанавливается поверх blender-xray. Это я сделал из-за того, что не хотел изобретать велосипед в виде модуля xray_io, параметров материалов в окне properties и прочее.

**Comment by PavelBlend** [comment]
@igelbox, а допустимо скомпилировать код отсюда: [lzhuf](https://github.com/abramcumner/xray_re-tools/blob/master/garbage/lzhuf/lzhuf.c) в exe и потом запускать этот экзешник с параметрами из xray_io? Или этот способ костыльный?

**Comment by igelbox** [comment]
> в exe и потом запускать этот экзешник с параметрами из xray_io?

Я, как пользователь Linux буду на тебя в обиде за это)

Я тут вижу два варианта:
- переписать тот можуль на python (найти готовый у меня пока не получилось), хорошая новость в том, что нам нужна только распаковка.
- подключить поддержку Cython для этого плагина (нужно будет релизить для 2-х платформ: Windows + Linux)

**Comment by PavelBlend** [comment]
По-моему первый вариант лучше. Так как для тестирования новых возможностей пользователю не обязательно ждать релиза. Не нужна компиляция, а можно сразу пользоваться аддоном.


> * подключить поддержку Cython для этого плагина

это нужно будет на Cython'е писать декомпрессор? Или можно уже готовый Си файл скомпилировать в pyd?

**Comment by igelbox** [comment]
> Не нужна компиляция, а можно сразу пользоваться аддоном.

Да. Вот и мне тоже не хочется таких возможностей лишаться.

> Или можно уже готовый Си файл скомпилировать в pyd?

Думаю, можно будет прям готовый взять.

**Comment by igelbox** [comment]
Давай я попробую переписать с C на pure python?
Если ОК, то назначь эту таску на меня.

Я только х/з, что с лицензией делать, т.к. их оригинальный код под лицензией с "Permission granted for non-commercial use.", а у нас тут BSD, которая более свободная.

**Comment by PavelBlend** [comment]
> назначь эту таску на меня.

а как это сделать?

**Comment by igelbox** [comment]
> а как это сделать?

"Assignees" блок справа вверху.

**Comment by PavelBlend** [comment]
У меня есть ещё просьба: если когда будешь переписывать с Си на питон, то можешь названия переменным давать такие, чтобы их можно было бы перевести в гугл переводчике? Например, имя переменной format_ более предпочтительнее чем fmt. Так как я хотел бы тоже разобраться в алгоритме Хаффмана, и в случае чего править код. Просто когда я читаю код, где переменные имеют непонятные названия, теряю суть. Всё становиться не очевидным.

**Comment by PavelBlend** [comment]
> Я только х/з, что с лицензией делать

а что сделал с лицензией Bardak, когда писал конвертер? Какая у конвертера лицензия?

**Comment by igelbox** [comment]
> Какая у конвертера лицензия?

Я не знаю и в исходниках ничего найти не удаётся. Я думаю, ему пофиг было на лицензии в то время.

> то можешь названия переменным давать такие, чтобы их можно было бы перевести в гугл переводчике

Я постараюсь оставить названия близкими к оригиналу (т.е. такими же непонятными), т.к. я сам х/з, что каждая переменная значит. Если ты в процессе разберёшься что к чему, то сможешь переименовать их.

Вообщем, pure-python код почти готов (удалось им распаковать 400кб поток, созданный оригинальным сишным кодом).

@PavelBlend помоги, пожалуйста, найти пример файла (одного из форматов, поддерживаемых этим аддоном), чтоб я смог тест написать.

**Comment by PavelBlend** [comment]
> @PavelBlend помоги, пожалуйста, найти пример файла (одного из форматов, поддерживаемых этим аддоном)

по-моему только билдовские уровни имеют сжатие. В object, dm, details, anm, ogf сжатия нету.

> Вообщем, pure-python код почти готов (удалось им распаковать 400кб поток, созданный оригинальным сишным кодом).

а по скорости питоновский код сильно уступает сишному?

**Comment by igelbox** [comment]
Жаль, придётся искуственно какой-то файл сжимать.

По скорости - не замерял, но уверен, что будет драматически медленнее. Т.к. это побитовый парсинг двоичных данных.

**Comment by PavelBlend** [comment]
Проверил. Всё работает.
