### ISSUE TITLE
add wiki

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#2]
- installation
- configuration
- basic usage
- nice screenshots & renders!

**Comment by PavelBlend** [comment]
Надо бы написать полную документацию к плагину. А то у меня есть такое ощущение, что пользователи не используют половины возможностей, так как просто о них не знают. И в текстовом виде удобнее читать, чем смотреть 30 минутное видео.

**Comment by PavelBlend** [comment]
Большая часть документации уже написана: https://github.com/PavelBlend/blender-xray/wiki
