### ISSUE TITLE
Перенести панель XRay Mesh

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#206]
Перенести панель XRay Engine: Mesh из вкладки object во вкладку Data. Так как логичнее параметры меша хранить именно там, а не у объекта. Просто получается, что во вкладке object имеется сразу две панели XRay.

**Comment by s30-zip** [comment]
Чего-то не понял, какие две панели?

**Comment by PavelBlend** [comment]
Нужно включить режим Expert Mode в настройках и тогда во вкладке object будет две панели: одна для свойств объекта, другая для свойств меша.

**Comment by s30-zip** [comment]
А когда кости нажимаешь "data" вроде неактивна, а там нужно выставить тип динамики например.

**Comment by PavelBlend** [comment]
@igelbox , а как ты считаешь, стоит переносить? Или эта панель специально помещена во вкладку object?

**Comment by igelbox** [comment]
@PavelBlend 
Я уже и не помню, т.к. это было 4 года назад cd173a36732bc03c2801bdf6ba6acd384e0eb81e.
Думаю, что просто хотелось всё сгруппироваь в одном месте, чтоб не бегать по разным частям интерфейса Blender-а в попытках настроить все свойства.
Но, с другой стороны, эти свойства уже давно хранятся/привязываются к Mesh, а не к Object, т.е. если в Blender создать 2 объекта с одинаковым Mesh, то эта панелька будет вестисебя странно - отображать/редактировать одно и то же для обоих объектов.

@s30-zip 
> а там нужно выставить тип динамики например

У кости в PoseMode панелька появляется. Или что ты имеешь ввиду под "выставить тип динамики"?

**Comment by PavelBlend** [comment]
> эта панелька будет вестисебя странно - отображать/редактировать одно и то же для обоих объектов

то есть желательно панель переместить во вкладку Data?

**Comment by s30-zip** [comment]
@igelbox
Та то меня переклинило думал, что большую панель перенести надо, а так то да подходит такое.

> желательно панель переместить во вкладку Data
