### ISSUE TITLE
Удалить Expert Mode

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#209]
Есть предложение: отказаться от Expert Mod'а. Сделать так, чтобы все панели по-умолчанию были видимыми. На мой взгляд, эксперт мод только вводит в заблуждение пользователя. Возможно потому, что эта опция нигде не описана. Она усложняет интерфейс плагина. И, без документации, мало кому понятно, для чего она предназначена.

Вместо эксперт мода, можно добавить подробное описание для флагов меша. Или выводить предупреждение, если пользователь пытается отключить флаг Visible.

**Comment by igelbox** [comment]
> И, без документации, мало кому понятно

Так поэтому и скрыто было, что я не понимаю, зачем эти флаги нужны. Но, вдруг кто-то понимает, и он сможет их изменить через наш аддон.

Поэтому я считаю, что expert mode - хорошее место для прятанья каких-то сырых фишек. Я бы туда ещё недоделанный OGF export спрятал. Можно переименовать этот флаг в Experimental Features. А делать ненужные штуки видимыми - тоже плохо, т.к. захламляет UI.

**Comment by PavelBlend** [comment]
> я не понимаю, зачем эти флаги нужны

вроде бы влаг Visible включает видимость меша в СДК. Флаг SGMask - указывает формат сглаживания (Max/Maya). А Locked - я не знаю.

**Comment by PavelBlend** [comment]
Закрываю этот вопрос. Создам новый, про Experimental Features флаг. Так как данная issue про удаление эксперт мода.
