### ISSUE TITLE
Не правильная трансформация цилиндрических шейпов

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#216]
Если выбрать цилиндрический шейп кости и нажать Edit Shape, то поворот цилиндра будет отличаться от оригинального поворота.

**Comment by PavelBlend** [comment]
Исправил: f14e9401c9c3d4944f6a86ee9bdec2a5febf56d5
Но не знаю, насколько это правильное решение.

**Comment by igelbox** [comment]
Нашёл, что это я сломал в #200.

Можно заменить на `mat *= MATRIX_BONE_INVERTED`, что тоже странно выглядит, но уже хотя бы с костями связано, а не просто матрица.

**Comment by igelbox** [comment]
Добавил тесты: 536f97095641d7027dbb676fe1a5822238127daf
Они должны упасть, но будут работать когда ты cherrypick-нешь этот коммит к себе в ветку.

**Comment by PavelBlend** [comment]
Может мне удалить ветку issue/216/fix-cylinder-bone-shape и создать её заново, чтобы исправить мою матрицу на MATRIX_BONE_INVERTED?

**Comment by igelbox** [comment]
Думаю, ветку удалять нет неоходимости. Просто исправь в твоей ветке, закоммить и запушь.
Ветки в гите же просто указатели на вершины графа коммитов. Поэтому, можно (но не желательно) творить бардак и переписывать историю локально, а потом force-push-ить её в репозиторий.
