### ISSUE TITLE
TypeError: Python number not a bool (0/1)

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#221]
Как воспроизвести:
- Добавить Armature
- Переключиться на вкладку свойств кости
- Нажать кнопку-флаг "No Physics"

Кнопка не нажимается, в консоли ошибки типа `TypeError: Python number not a bool (0/1)`.

Версия Blender: 2.79
Версия аддона: f1d3085de354b00fec946aae254727735c4780df

**Comment by PavelBlend** [comment]
У меня не получается воспроизвести ошибку. Всё правильно работает почему-то.

**Comment by igelbox** [comment]
Хм. На официальной сборке от марта 2018 у меня тоже всё норм.
А у меня установлена какая-то несуществующая 2.79.6 от января 2019.
Попробовал скачать бету 2.80 сижу вот теперь офигеваю от нового интерфейса. Аддон-то там и не работает почему-то.
Ну, раз в официальной сборке всё норм, то значит проблемы пока нет, может в 2.80 выстрелит, а может и нет.

**Comment by PavelBlend** [comment]
> 2.79.6

это дневная сборка наверное. Её можно скачать отсюда:
https://builder.blender.org/download/

И она отличается от этой версии:
https://www.blender.org/download/

То есть разработчики блендера разрабатывают две версии одновременно: 2.80 и 2.79.X (которая новее 2.79b)
