### ISSUE TITLE
Импорт level, level.geom и level.geomx

### ISSUE THREAD

**Issue by IgeNiaI** [PavelBlend/blender-xray#226]
Здравствуйте.
Меня интересует ситуация с импортом геометрии уровня.
Здесь https://github.com/PavelBlend/blender-xray/issues/180 вы говорили, что написали тестовый импорт .geom, но, как я понял, в релиз он не попал.

Я переношу карту Затон в UE4, поэтому меня интересует только импорт и дальнейший экспорт в .fbx . Я импортировал карту через 3ds max и столкнулся с двумя проблемами.

Первая: часть Mesh отсутствует.
![nocars](https://user-images.githubusercontent.com/9607628/55840185-92098f00-5af8-11e9-85cb-281d8d720540.png)
Это мост Преображенского и здесь должна быть разбитая военная колонна, но её нет и ящики просто висят в воздухе. Наверняка отсутствует что-то ещё, но я пока не находил. Я не знаю, эта проблема в плагине импорта или же колонны нет в файле level.geom. Если второе, то где она? Подозреваю, что в файле level или level.geomx. Может, вы знаете?

Вторая проблема:
![looseparts](https://user-images.githubusercontent.com/9607628/55840353-2bd13c00-5af9-11e9-93dd-a047f869d5ce.png)
Я здесь выделил одну Mesh, но, как видите, она состоит из нескольких, находящихся в разных концах карты. Опять же, не знаю, проблема в плагине импорта, формате .fbx или же в самом сталкере оно так устроено.

Ну и мелкая проблема: все Mesh имеют фактический центр в координате 0-0-0, а не в центре своей геометрии. Это видно по стрелкам на втором скриншоте.

В любом случае, прошу реализовать импорт геометрии уровней в вашем плагине, очень уж плагин и Blender хороши.

**Comment by PavelBlend** [comment]
> вы говорили, что написали тестовый импорт .geom, но, как я понял, в релиз он не попал.

да, я написал импорт, но в отдельном репозитории:
https://github.com/PavelBlend/blender_stalker_tools_addon

> Я не знаю, эта проблема в плагине импорта или же колонны нет в файле level.geom.

колона скорее всего есть в level.geom, но не в виде статической геометрии, а в виде MultipleUsage. Проще говоря колона - это лод объект (как деревья).

> она состоит из нескольких, находящихся в разных концах карты.

Это компилятор уровней xrLC так разбивает геометрию. И с этим ничего не поделаешь. Так устроено в сталкере.

> все Mesh имеют фактический центр в координате 0-0-0

вся статическая геометрия имеет координаты 0, 0, 0. Только лоды имеют разные координаты.

> Меня интересует ситуация с импортом геометрии уровня.

насчёт внедрения импорта level.geom я пока не уверен. Так как это может занять много времени и сил. Тот импорт, который я написал, является сырым и практически не тестировался. Просто мы сосредоточены на редактировании исходных файлов: object, skls.

@igelbox а ты относишься к внедрению плагина level.geom? Всё так же против?

**Comment by IgeNiaI** [comment]
> колона скорее всего есть в level.geom, но не в виде статической геометрии, а в виде MultipleUsage. Проще говоря колона - это лод объект (как деревья).

То есть, остальная геометрия не имеет LOD вообще? Как же они тогда это оптимизировали в игре? Просто обрезают на расстоянии и прикрывают туманом, как я?
Если всё же возьмётесь за импорт level.geom, то прошу сперва реализовать импорт MultipleUsage и, если возможно, с сохранением их позиций на карте.

> Это компилятор уровней xrLC так разбивает геометрию. И с этим ничего не поделаешь. Так устроено в сталкере.

А что если ковертировать из исходников? Хотя, там наверняка формат гораздо более сложный.

**Comment by igelbox** [comment]
Да, я всё так же (как и в #126) против добавления фич, если без этого можно обойтись.
Попробовал сейчас импортировать Затон, как: `converter -level zaton -with_lods`
В итоге получил жирный cuts.object файл (который еле-еле грузится в Blender) и с полсотни lodsXX.object файлов. Проблема в том, что все LOD-ы импортируются в центр карты.
@PavelBlend а что если вместо полноценного импорта geom файлов, мы будем импортировать только положения LOD-ов и расставлять эти LOD-ы, которые мы заранее импортировали из сконвертированного уровня? Думаю, такая задача гораздо легче и быстрее решится, чем полноценный импорт.

**Comment by PavelBlend** [comment]
@igelbox у меня пока нет идей, как это можно реализовать. Как определить, что привязано к определённой позиции? По имени и номеру object файла?

**Comment by IgeNiaI** [comment]
@igelbox @PavelBlend а как вы изучаете исходники? Может, смогу помочь.

**Comment by PavelBlend** [comment]
> а как вы изучаете исходники?

исходники движка xray? Для этого нужно знать язык си++. Но я сам его не знаю. Чаще всего пользуюсь поиском по файлам в notepad++, чтобы найти интересующую вещь (например, ввожу в поиск идентификатор чанка).

**Comment by IgeNiaI** [comment]
Нет, не движка, а файлов что ваш плагин читает. Как мне увидеть формат того же level.geom?

**Comment by PavelBlend** [comment]
> Как мне увидеть формат того же level.geom?

нужно смотреть в исходниках движка. Или в исходниках конвертера от Бардака.

**Comment by IgeNiaI** [comment]
Чтож, попробую помочь

**Comment by PavelBlend** [comment]
@IgeNiaI попробуй импортировать уровень с помощью моего плагина:
https://github.com/PavelBlend/blender_stalker_tools_addon
Он вроде должен из ЗП уровни импортировать. Если что-то будет не получаться, то пиши.

**Comment by IgeNiaI** [comment]
@PavelBlend попробую, но часов через 9.
Я вот что подумал. Ведь чтоб открыть уровень в SDK, нужно распаковать его конвертером от бардака. А он все лоды кидает как отдельные меши в отдельную папку, но в редакторе уровней они на своих местах. Наверняка в распакованном формате где-то есть отдельный файл со всеми координатами, возможно даже текстовый.

**Comment by PavelBlend** [comment]
Да, есть такой файл. Называется scene_object.part Лежит в папке с декомпилированным уровнем в rawdata\levels

**Comment by IgeNiaI** [comment]
Вот только все координаты там на нуле. Редактор же берёт где-то информацию.

**Comment by IgeNiaI** [comment]
А вот кстати и нет. Прокрутите к середине списка, там координаты есть.
Объекты zaton_part координат не имеют, а у zaton_lod они есть.

**Comment by IgeNiaI** [comment]
@PavelBlend что ж ты не сказал что уже сделал? :) Я то подумал что ещё мучаешься.
В блендере открылось вроде бы нормально, сейчас попробую экспортировать в UE

**Comment by IgeNiaI** [comment]
Импортируется в блендер прекрасно, правда в UE я пока не перевёл. Там нужно пару оптимизаций провести, но это я уже сам сделаю. Если хотите, поделюсь потом скриптом.
Пока что больше вопросов нет, благодарю.

**Comment by IgeNiaI** [comment]
Правда, есть один недостаток. Нормальная и упрощённая модели для всех мешей импортируются как два разных объекта. Но это проблема при дальнейшем экспорте в UE, а как в остальных случаях, не знаю.

**Comment by PavelBlend** [comment]
Чтобы удалить упрощённую геометрию, запусти этот скрипт:
```
import bpy


bpy.ops.object.select_all(action='DESELECT')
for obj in bpy.data.objects:
    if obj.name.startswith('FASTPATH'):
        obj.select = True
```
И все упрощённые модели будут выделены.

**Comment by IgeNiaI** [comment]
Я собираюсь их использовать, поэтому ситуация сложнее. Пока что всё работает хорошо, дальше уже целиком моя морока. Так что можно закрывать issue.

**Comment by IgeNiaI** [comment]
Сделайте, пожалуйста, чтоб названия секторов брались из поля "name" в файле sector.part. Просто у карт есть дефолтный сектор, который содержит около 80% всех объектов и мой скрипт по оптимизации должен его обрабовать по-другому. Просто нужно чтоб этот сектор всегда имел одинаковое имя, которое в файле sector.part всегда равно "Sector_DEFAULT"

**Comment by PavelBlend** [comment]
@IgeNiaI давай, если будут ещё вопросы по плагину stalker_tools, то пиши их сюда:
https://github.com/PavelBlend/blender_stalker_tools_addon/issues
Так как этот репозиторий относится только к blender-xray плагину.
Для данного вопроса я создал issue здесь:
https://github.com/PavelBlend/blender_stalker_tools_addon/issues/9
