### ISSUE TITLE
Exported level.details file won't work

### ISSUE THREAD

**Issue by Szabi123** [PavelBlend/blender-xray#230]
Dear Pavel!

Please, be so kind to help me solving an issue, becouse at the moment I think I can hope for help only from you.

I'm creating a new mod for STALKER - LOST ALPHA v1.40007. My mod aims to replace all grass and plant textures with my own 4K ones. I also would like to offer 3 presets for grass height: default, medium and high.

Using your Blender X-Ray plugin I import the level.details file, and I try to change grass height either by upscaling the min and max values, or manualy increasing the mesh sizes in edit mode, like you see in this short video: https://streamable.com/ebkcn

When everything is done, I export the file without any issues, I start the game, but at "synchronizing game resources" loading freezes (and log file doesn't tell me any usefull details).

I must admit, that I'm not an expert of Blender, but this method works fine for Call of Chernobyl level.detail files, but for some reason doesn't work with the LA file.

I uploaded this level.details file in which I would like to increase grass height here, so you can take a look at it: https://drive.google.com/open?id=1BMFRiGwbwloe5nXNODH9pTnihovxSSLP

If you know, what do I do wrong, please tell me, what and how to do to make it work (treat me like a newbie, becouse like I said, I'm not an expert in Blender).

I'm so much looking forward to seeing your reply, becouse untill now nobody could help me.

Thank you very much in advance, my greetings!

**Comment by PavelBlend** [comment]
I can not reproduce the problem. Everything works. I downloaded your level.details file imported into blender zoomed meshes and exported:
![details_test](https://user-images.githubusercontent.com/7983249/58752850-7d28f680-84be-11e9-8286-36ec453837e1.jpg)
Try not to change anything. Import level.details and then export immediately.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you so much for looking into this, I really appreciate! This means, there is hope for me and I do something wrong.

Before I would start to bomb you with lots of annoying questions, may I ask: is there any chance you could perhaps upload a quick video for me, like the one I linked above, where I could see all your settings and also what you do with this level.details file in Blender step by step?

Perhaps it would be a much faster way for me to solve the problem and to learn. Is it possible? 

If not, I will try my best to describe what I'm confused about and hopefuly finally I will recognize the cause of the issue according to your lead.

With many thanks and regards: Szabi

**Comment by PavelBlend** [comment]
Recorded video:
https://youtu.be/JGEtbwufC9Y

Try updating the blender-xray addon. Download it from here (green button "Clone or download"> "Download ZIP"):
https://github.com/PavelBlend/blender-xray/tree/a51fe2da55a38b5c6aa34483b50b56ceab817001

This is the last commit. Copy the io_scene_xray folder to blender add-ons.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you so much for your video, I really appreciate!

Now I followed your instructions step by step. But still no luck, my game freezes at "synchronizing game resources" stage.. :((

I uploaded a video about me creating the level.details file, you can watch it here: https://www.youtube.com/watch?v=VBcxSi35uos&feature=youtu.be

I also uploaded the level.details file I created, if you want to examine: https://drive.google.com/open?id=1ouYcG0VLXyKnspA45Zw0r4ISHFPsxos8

Please, be so kind to help me find the source of the problem, becouse I can not think about anything particular at the moment, but you have a much greater experience.

By the way, at the end of the video of course I didn't hit the "launch game from selected save" button, becouse the only thing you could see is freezing of load screen.

Thank you very much in advance!

**Comment by PavelBlend** [comment]
> https://www.youtube.com/watch?v=VBcxSi35uos&feature=youtu.be

This video is not available.
And you updated the plugin?

**Comment by PavelBlend** [comment]
I added your level.details to Lost Alpha and got the error:
```
FATAL ERROR
 
[error]Expression    : fatal error
[error]Function      : CBlender_default::Compile
[error]File          : BlenderDefault.cpp
[error]Line          : 63
[error]Description   : <no expression>
[error]Arguments     : Not enought textures for shader, base tex: build_details
```
This means that meshes have the wrong shaders installed.
I don’t know how you did it, but for some reason, when importing level.details, all meshes have the default shader installed:
![01](https://user-images.githubusercontent.com/7983249/58761134-5532a500-8549-11e9-8b67-42d694b2a86f.jpg)

Set EShader value to `details\blend`. And try to export to the game.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you really much, that was it! I wouldn't have noticed this without your help. Now the game loads fine. However, it froze again, but I think it was becouse I was in demo record mode flying around the map too fast, and my build_details texture files are 4K resolution, so perhaps the engine didn't like this.

If you don't mind, please let me ask about some further things in really short:

1. When importing LA level_details file into Blender, is there any importance, if I choose Build 1096-1230 or Build 1233-1558?
2. However, I have set the place of my installed LA gamedata folder when I installed your Blender X-Ray  plugin, when I set viewport shading to "texture" in Blender, I don't see the textures applied on the meshes from build_details file, I only see purple coloring. Where and what should I set in Blender in order to see my textures on the meshes? It looks like this now:

![kép](https://user-images.githubusercontent.com/20930116/58763827-7783ed00-8560-11e9-9af7-8206953f5d9e.png)

3. If I want ALL the plants and grasses to be like 30% or 50% etc. taller than default size, is there a method, I could set this in one step, instead of having to manually set each values one by one?

Thank you so much!

**Comment by PavelBlend** [comment]
1 - for LA, this parameter has no effect. This parameter is needed for builds 1096-1558.

2 - The build_details texture should be in the same folder as level.details

3 - Yes, there is such a way. Need to select the necessary objects. Then click on the Min / Max Scale parameter with Alt clamped. And then enter the desired value.

**Comment by Szabi123** [comment]
Dear Pavel!

According to question no.2, my build_details texture is in the same folder as level.details:

![kép](https://user-images.githubusercontent.com/20930116/58764334-2bd44200-8566-11e9-9449-744b5ccce44a.png)

Perhaps there is any additional setting in Blender that I missed?

Thanks!

**Comment by PavelBlend** [comment]
And what is your version of the add-on blender-xray? This error was in older versions. Version 0.6.0 fixed this bug.

**Comment by Szabi123** [comment]
It's version 0.6.0

![kép](https://user-images.githubusercontent.com/20930116/58765189-66db7300-8570-11e9-9079-d7eea91682cd.png)

**Comment by PavelBlend** [comment]
> Perhaps there is any additional setting in Blender that I missed?

For loading textures from level.details no settings are needed.

And again I can not reproduce this error.

**Comment by Szabi123** [comment]
Dear Pavel!

Sorry, it was my bad! I didn't notice, that Blender wanted to load "build_details 001" file, so I switched to "build_details" in material, and everything is fine.

However now I discovered some errors in my work. As you see in the images below, some of my textures have other additional parts from the other textures. Is this, becouse I inserted my own textures to the place of the old ones in a too big area inside build_details? How could I avoid this to happen?

Thank you!

![kép](https://user-images.githubusercontent.com/20930116/58765802-1ddaed00-8577-11e9-9dfb-19b937f794f5.png)

![kép](https://user-images.githubusercontent.com/20930116/58765812-259a9180-8577-11e9-9c71-7d35c59bbf90.png)

![kép](https://user-images.githubusercontent.com/20930116/58765819-2c290900-8577-11e9-97a9-3a854f40f223.png)

**Comment by PavelBlend** [comment]
You can edit the texture (make less the area where there is a plant). Or you can change the UV sweep so that the polygons do not cover unnecessary textures.

**Comment by Szabi123** [comment]
Perhaps it is a good way, to insert my textures into the place of the old ones in a smaller area inside build_details, becouse if they seem to be not big enough, I can increase their size with the meshes using your method...?

Thank you very much for all your support and help, I greatly appreciate! If I further would come to any issue, I will let you know.

**Comment by PavelBlend** [comment]
You can also store one kind of grass in one *.dds file, instead of using one texture atlas for all plants. But for this you need to scale the UV sweep.

**Comment by Szabi123** [comment]
Sorry, but what does "scaling the UV sweep" mean exactly? Do you have maybe any tutorial video, where you show this, so I could understand the concept? (My apologies, like I said, I just recently started to study Blender). Untill now I haven't seen any attempts among STALKER mods to store the grass textures in individual dds files, but if that is possible somehow (and especially if this method could increase visual quality), I'm really interested to learn, how can this be done!

**Comment by PavelBlend** [comment]
Recorded video:
https://youtu.be/o83XQHxSjC4

Only I did this for Shadow Of Chernobyl, but for Lost Alpha the principle is the same.
![1](https://user-images.githubusercontent.com/7983249/58788925-96808e80-85f5-11e9-98ae-c0ddea6710c1.jpg)

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you so much for your help, this is great!

Do you perhaps have experiences with these separate dds textures? I have about 60-70 new plant textures ready. I wonder, if I use them as individual dds textures and not in the build_details atlas, will it make a serious hit on the engine (especially, that my textures are 4K resolution).

Thank you!

**Comment by PavelBlend** [comment]
I have no such experience. I did not check the performance.

**Comment by Szabi123** [comment]
Dear Pavel!

I created a *dds plant texture and placed it inside installed LA gamedata\levels\la02_garbage folder, where level.details and build_details files take place:

![kép](https://user-images.githubusercontent.com/20930116/58816830-98187980-862a-11e9-8c92-f1cba90b86b5.png)

I made everything as in your tutorial video: in Blender I picked a mesh, created new material, added my new texture on it, named it the right way, created the UV properly, choosed the right ESHader and exported the file. But my game freezes while loading at "synchronizing game resources". I tried to export the file without "Texture names from image paths" checked, and also with checking this option, but no luck either ways.

Could you give me some advise, what can be wrong? Thank you!

**Comment by PavelBlend** [comment]
What is written in the log file (Losta Alpha\appdata\logs\xray_username.log)?

**Comment by Szabi123** [comment]
I've already checked it, but doesn't tell me much. You can read it here:
https://drive.google.com/open?id=14KGOSGg-uDhtvNdCWJp86EPXaWttz8h4

You can see the exported level.details file here: https://drive.google.com/open?id=1-WpbDhLSU44QTzCLNIXQSwjLn9yVOmCt

I used a 2048x4096 resolution *dds format plant image, that was placed in my installed LA game, inside gamedata\levels\la02_garbage folder, by the name of VIRAG_1_DDS.dds

**Comment by PavelBlend** [comment]
Rename the texture to blender. Give her the name `VIRAG_1_DDS`.
![01](https://user-images.githubusercontent.com/7983249/58820106-64dde680-863a-11e9-853c-fed5efe52b2d.jpg)
The texture `VIRAG_1_DDS.dds` can be placed in the `gamedata\levels\la02_garbage\VIRAG_1_DDS.dds` folder or it can be placed in `gamedata\textures\VIRAG_1_DDS.dds`. If you put the textures in the above paths, then the texture name in blender should be `VIRAG_1_DDS`.

But there is a second way:

You can put the texture in `gamedata\levels\la02_garbage\det\VIRAG_1_DDS.dds` or place it in `gamedata\textures\det\VIRAG_1_DDS.dds`
In this case, the name of the texture in the blender should be `det\VIRAG_1_DDS`

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you so much for your efforts! I learned more in two days thanks to you, than previously by myself in one month.

I will let you know, if I bump into any issues.

By the way: 4K textures stored and loaded separately make an impressive look, but I think - especially if I use more of these - this method could impact FPS so hard, that I probably have to stick with build_details atlas.

**Comment by Szabi123** [comment]
Dear Pavel!

Please be so kind to help me in the following question.

In most of build_details files there are these two parts:

![kép](https://user-images.githubusercontent.com/20930116/59048830-fc377980-8886-11e9-9156-243c40e60550.png)

Could you tell me, what are these used for? 

If I want to create a new build_details atlas for my own textures, do I have to implement these two parts? If yes, how and where to implement them?

Thank you!

**Comment by PavelBlend** [comment]
These textures are used by stones, nails, bolts and nuts:
![01](https://user-images.githubusercontent.com/7983249/59103621-06658080-8938-11e9-9dca-aeac6aee91c6.jpg)
