### ISSUE TITLE
Кости меняют свои трансформации после экспорта

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#233]
Если импортировать данный object файл (это модель худа рук из ЗП, полученная при конвертации конвертером от Бардака):
[wpn_hand_01.zip](https://github.com/PavelBlend/blender-xray/files/3245047/wpn_hand_01.zip)

а потом экспортировать его, то кости сохраняться с небольшим смещением (видно на правой руке). Чтобы это проверить, нужно импортировать результат экспорта обратно в блендер и будет видно следующее:
![cop_hud_export_bug](https://user-images.githubusercontent.com/7983249/58765501-782a7c80-857c-11e9-98d8-44218757fda7.gif)
(это я переключаюсь между первым и вторым слоем. На первом слое лежит оригинальная модель, а на втором - результат экспорта)

**Comment by PavelBlend** [comment]
Проверил старые версии плагина, и этот баг есть даже в версии 0.0.7
И левая рука почему-то не меняется, а правая изменяется. И при многократном реэкспорте кости смещаются всё дальше и дальше.

**Comment by igelbox** [comment]
Похоже, проблема в том, что импортируем как `edit_bones`, а экспортируем как `bones`. И поэтому, приходится использовать разные матрицы => разные мат-преобразования применять.

Но я попробовал переписать код экспорта на использование `edit_bones` (думаю, что импорт было бы сложнее переписать, т.к. там всё в процессе и скелет ещё не полный в каждый момент). Вообщем, похоже оно устаканилось. Попробую дополировать и открыть PR.
