### ISSUE TITLE
Неправильный экспорт анимаций для костей с выключенным флагом Inherit Rotation

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#234]
Если выключить галочку Inherit Rotation у кости, проанимировать её и экспортировать в СДК, то анимация будет не такой как в блендере. Вот сцена:
[inherit_rotation_test.zip](https://github.com/PavelBlend/blender-xray/files/3249649/inherit_rotation_test.zip)

на последнем слое у арматуры лежат деформирующие кости. И у них выключена эта галочка (кости пальцев, например).

**Comment by PavelBlend** [comment]
Вот пример попроще:
[inherit_rotation_test1.zip](https://github.com/PavelBlend/blender-xray/files/3250802/inherit_rotation_test1.zip)

**Comment by PavelBlend** [comment]
Я посмотрел код экспорта анимаций и даже не знаю как эту ошибку исправить. @igelbox а у тебя есть идеи? Я пока думаю, что нужно в этой строчке что-то изменить, но что именно - не знаю:
https://github.com/PavelBlend/blender-xray/blob/a51fe2da55a38b5c6aa34483b50b56ceab817001/io_scene_xray/xray_motions.py#L273

**Comment by PavelBlend** [comment]
Выяснил, что во всём виновата функция `Object.convert_space`. Если на её вход подать разные `pbone.matrix` (одна матрица кости с флагом `use_inherit_rotation`, а вторая матрица без этого флага), то она может вернуть одинаковые значения. То есть эта функция не учитывает флаги `use_inherit_rotation` и `use_inherit_scale`.

**Comment by igelbox** [comment]
Хм, а я думаю, что проблема в том, что анимации всех костей экспортируются относительно их какого-то parent-а (см. вызовы `find_bone_exportable_parent`). Т.е. получается, что blender анимирует в системе координат bone.matrix_local (т.е. Rest Position кости), а мы экспортируем анимацию в системе координат (т.е. Rest Position **parent**-кости), т.к. SDK интерпретирует анимацию - как абсолютное смещение относительно положения parent, а не локальное смещение относительно Rest Position самой кости.
И такое чувство, что, раз уж SDK не всегда применяет анимации так, как будто бы они inherit, то нужно как-то инвертировать rotate преобразование от parent-кости.

_Чёт тяжко у меня соображается (давно адом матриц Blender-а не оперировал), но можно попробовать просто алгеброй:_
Т.е. если финальное положение кости по мнению SDK - это перемножение матриц костей `FM = PM * M`, где `FM` - финальное положение, `PM` - для parent-кости, а `M` - для дочерней, ну и сами эти матрицы - результат переменожения 2х операций перемещения и вращения - `M = M_tran * M_rot` (если оно будет в другом порядке `M = M_rot * M_tran` - то хз, как это лечить).
То в развёрнуом варианте получим: `FM = PM_tran * PM_rot * M`. Получается, мы можем аннулировать вращающую матрицу parent-а, путём домножения матрицы child-а на матрицу, обратную `PM_rot`. Т.е. мы при экспорте делаем `M' = PM_rot.inverted() * M` во время экспорта и в SDK получится `FM = PM_tran * PM_rot * PM_rot.inverted() * M`, тогда `FM = PM_rot * PM_rot.inverted()` сократится и останется только `PM_tran * M`.

И надо бы ещё понять, это проблема чисто анимаций. Или там ещё Rest Position не правильно экспортируется, т.е. моделька в SDK без применённой анимации выглядит так же правильно, как в Blender в Rest Position? Если нет, то надо сначала чинить Rest Position, а уже потом браться на анимации.

**Comment by PavelBlend** [comment]
Написал тест. Матрица одинакова в обоих случаях (с флагом inherit_rotation и без него):
```py
import math

import bpy


arm = bpy.data.armatures.new('test')
obj = bpy.data.objects.new('test', arm)
bpy.context.scene.objects.link(obj)
bpy.context.scene.objects.active = obj
bpy.ops.object.mode_set(mode='EDIT')
bone_parent = arm.edit_bones.new('bone_parent')
bone_parent.head = (0, 0, 0)
bone_parent.tail = (0, 0, 2)
bone_child = arm.edit_bones.new('bone_child')
bone_child.head = (0, 0, 2)
bone_child.tail = (2, 0, 2)
bone_child.parent = bone_parent
bone_child.use_inherit_rotation = False
bpy.ops.object.mode_set(mode='POSE')
pose_parent_bone = obj.pose.bones[bone_parent.name]
pose_parent_bone.rotation_mode = 'XYZ'
pose_parent_bone.rotation_euler = (0, 0, math.pi / 4)
pose_child_bone = obj.pose.bones[bone_child.name]

bpy.context.scene.update()
mat_1 = obj.convert_space(pose_child_bone, pose_child_bone.matrix, 'POSE', 'LOCAL')

bone_child.use_inherit_rotation = True

bpy.context.scene.update()
mat_2 = obj.convert_space(pose_child_bone, pose_child_bone.matrix, 'POSE', 'LOCAL')

print(mat_1)
print(mat_2)
print(mat_1 == mat_2)
bpy.ops.object.mode_set(mode='OBJECT')
```

Наверное придётся писать свой аналог функции convert_space, которая будет учитывать эти флаги.

**Comment by igelbox** [comment]
> Наверное придётся писать свой аналог функции convert_space, которая будет учитывать эти флаги.

Что-то не верится, что это поможет. Она же у нас высчитывает локальную анимацию кости относительно её Rest Pose. SDK же не умеет выключать inherit rotation? Несли не умеет, то придётся инвертировать вклад анимации parent-кости в каждом кадре. А это выглядит как-то жестоко/сложно.

**Comment by PavelBlend** [comment]
Ну тогда не знаю, что делать. Я обошел данный баг добавлением дубликатов костей и назначив нужные констрейнты и изменив родительские связи.

**Comment by igelbox** [comment]
Хотя. У нас же в `def _export_motion_data(pkw, action, bones_animations, armature):` уже финальные матрицы. Если туда прокинуть ещё и Rest Pose костей, то можно вращение взять из Rest-поз, а остальное из финальных матриц. Но, тогда не понятно в каком случае считать, что rotation не меняется (вдруг оно каким-то констрейнтом управляется).

Другой вариан - не использовать local-положения вообще и расчитывать всё через какие-то более глобальные матрицы, которые реагируюи и на inherit_* и на констрейнты. Хз, насколько это сложно/просто передедать будет.
