### ISSUE TITLE
Где можно скачать стабильный СДК 0.4

### ISSUE THREAD

**Issue by Krone0** [PavelBlend/blender-xray#235]
Можете подсказать, где можно скачать стабильную версию xray-sdk (ActorEditor)? win 10 64x.
(желательно 0.4)

**Comment by PavelBlend** [comment]
Я пользуюсь сборкой от YURSHAT. Скачать можно здесь:
https://www.gameru.net/forum/index.php?showtopic=59990
она достаточно стабильная

**Comment by Krone0** [comment]
Спасибо! А как сделать, чтобы из папки .gamedata, файлы конвертировались в .object (в папку rawdata)

**Comment by PavelBlend** [comment]
Я когда-то писал скрипт на питоне:
https://github.com/PavelBlend/stalker_batch_converter
Правда там идёт конвертация не из gamedata в rawdata, а из папки input в output.

**Comment by Krone0** [comment]
А что за проблема, когда воспроизводишь анимацию в ActorEditor, а анимация не работает. Но при этом, шкала анимации движется (этот же файл анимации, прекрасно воспроизводится в блендере, а в АЕ почему-то нет). Так и должно быть?

**Comment by PavelBlend** [comment]
Нужно включить галочку Real Time в меню Options (слева внизу).

**Comment by Krone0** [comment]
Большое спасибо за помощь! Я вот-вот только знакомлюсь с  мододелом, по-этому многих основ не знаю. Вы не против, если я изредко буду задавать не сложные вопросы здесь?

**Comment by Krone0** [comment]
А ваш скрипт совместим с CoP? Я просто попытался конвертировать модельку оружия с анимацией (из мода) ogf>object, и у меня выдало ошибку+краш. С SoC всё отлично. Или просто я скачал багнутую версию конвертера? (От бардака)
![1](https://user-images.githubusercontent.com/51322214/58908373-d3e63880-8729-11e9-91e6-751b202d69b0.png)

**Comment by PavelBlend** [comment]
> Вы не против, если я изредко буду задавать не сложные вопросы здесь?

если вопросы по плагину к блендеру, то да. А если по сдк, то лучше мне на почту:
stalkermodkytia@yandex.ru
Так как данный репозиторий создан именно для плагина blender-xray.

> А ваш скрипт совместим с CoP?

да.

> Или просто я скачал багнутую версию конвертера?

попробуй скачать отсюда:
https://github.com/abramcumner/xray_re-tools/releases/tag/0.1.7

**Comment by Krone0** [comment]
Учту всё на счёт вопросов! Да, этот конвертер начал работать. Всё-таки проблема была видимо в устаревшей версии скачанного мною конвертера. В очередной раз вас благодарю!
