### ISSUE TITLE
Добавить индикацию работы (курсор мышки)

### ISSUE THREAD

**Issue by vika-sonne** [PavelBlend/blender-xray#240]
После начала импорта Blender на десяток секунд выглядит зависшим и не понятно, пошёл импорт или просто я промахнулась мимо кнопки :)
Если не трудно, добавьте, пожалуйста, перед началом импорта/экспорта **context.window.cursor_set('WAIT')**. Главное, не пропустить по завершению **context.window.cursor_set('DEFAULT')**.  ;)

**Comment by PavelBlend** [comment]
Сделал.

Я посмотрел твои репозитории и увидел xray-skls-file-browser. У тебя нет желания внедрить этот просмотрщик в плагин blender-xray? Чтобы его не нужно было отдельно устанавливать.

**Comment by vika-sonne** [comment]
Оперативно :)

Добавить xray-skls-file-browser можно.

Вопрос в эргономике его использования. Мне был нужен только импорт анимаций в блендер. А как встроить просмотрщик в среду редактирования X-Ray - вопрос для меня открытый. К примеру, xray-skls-file-browser не импортирует XRayActionProperties.
Но мне интересно приложить руки... если не боишься :) я программирую в блендер полгода.

**Comment by PavelBlend** [comment]
> Но мне интересно приложить руки

ну тогда делай форк, потом изменения в пулл реквесте скинешь

> если не боишься :) я программирую в блендер полгода.

если что-то будет не подходить, то это всегда можно будет исправить. Я бы и сам сделал, но как-то копипастить твой код/идею не правильно. А если ты реализуешь функцию, то в авторстве плагина себя напишешь. И автором своего кода будет ты.

Я проверял твой аддон и он работает только на дневной сборке блендера. Нужно чтобы и в стабильной версии (2,79b) тоже работал. И можно добавить кнопку "Импортировать активную (или всё) анимацию в сцену". Ну или я сам потом это сделаю.
