### ISSUE TITLE
Копировать настройки анимаций

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#243]
При создании новых анимаций приходится вручную настраивать параметры XRay. Нужно сделать возможность копирования этих параметров из других файлов (object, skl, skls).

**Comment by igelbox** [comment]
А что если:
- импортировать какую-то одну анимацию из skls (сейчас же есть аддон позволяет выбирать анимации при импорте)
- в Dope SHeet > Action Editor на панели свойств нажать копировать _(добавим кнопку)_
- выбрать нужную анимацию и нажать вставить _(добавим кнопку)_
- удалить ненужную импортированную анимацию

?

**Comment by PavelBlend** [comment]
Можно и так. Даже лучше будет. Так как при первом варианте нет возможности просмотреть, что будет добавлено из настроек.

**Comment by igelbox** [comment]
Посмотрел реализацию - на первый взгляд, если б их не в файл, а в буфер в текстовом виде копировать, то можно было б в блокнот вставлять несколько, сохранять на будущее, делиться и/или хз ещё сколько разных применений текстовому представлению можно придумать :smile: 

Я, в другом аддоне, в configparser формате их в буфере держу - https://github.com/igelbox/blender-retarget/blob/master/animation_retarget/core.py

**Comment by PavelBlend** [comment]
@igelbox я пока код не смотрел, но вопрос: будет ли работать копирование из одного blend файла в другой? И чтобы было кроссплатформено.

**Comment by igelbox** [comment]
Да, будет так же кроссплатформенно, как сейчас. Т.к. что сейчас, что с configparser - оно преобразуется с какой-то промежуточный формат, который этот аддон будет стараться поддерживать в будущем.
Думаю, что configparser-формат на разных платформах только символами перевода строки отличается, но, верю, он будет их сам обрабатывать. Да и человеко-читаемо оно, типа фомат INI-файла получается.

**Comment by PavelBlend** [comment]
Я посмотрел и здесь идёт копирование в буфер?:
https://github.com/igelbox/blender-retarget/blob/master/animation_retarget/ops.py#L15
Там у объекта WindowManager есть свойство clipboard. Это свойство разве не будет отличаться от файла к файлу? Я просто думал (даже протестировал), что это свойство работает только в пределах blend файла, а не за пределами других файлов.

UPD: видимо плохо протестировал. Оказывается это свойство одинаково для всех файлов.

**Comment by igelbox** [comment]
Странно, я сейчас открыл 2 Blender-а. В одном запустил в Python Console `bpy.context.window_manager.clipboard = 'some-text'`, в другом `bpy.context.window_manager.clipboard` и оно выдало 'some-text', ну и после этого я могу Ctrl+V в блокнот и вижу 'some-text'.
Т.е. у меня, на Linux оно рил через общий/системный буфер обменя проходит, а не через данные blend-файла и/или сцены.

**Comment by PavelBlend** [comment]
Я потом переделаю на текстовый формат с использованием этого буфера.
