### ISSUE TITLE
Неправильный экспорт материалов в ogf

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#257]
Если объект состоит из нескольких материалов, то при экспорте в ogf сохранится только один материал.
![ogf_material_bug](https://user-images.githubusercontent.com/7983249/60108273-04d9ec00-9771-11e9-8d99-6368db0cdef0.jpg)

**Comment by igelbox** [comment]
Так экспорт в OGF - дико экспериментальная штука. Может не надо, тратить на неё какие-либо усилия.

**Comment by PavelBlend** [comment]
Тогда я закрою данную issue.
