### ISSUE TITLE
Не импортируются skls анимации

### ISSUE THREAD

**Issue by IgeNiaI** [PavelBlend/blender-xray#260]
Blender 2.79b, плагин 8.0.0

Сконвертировал **wpn_hand_01.ogf** и **wpn_hand_ak74_hud_animation.omf** через конвертер бардака в **.object** и **.skls** соотвественно.
Импортировал модель, всё нормально. Пытаюсь импортировать анимацию и ничего не происходит. Никаких ошибок не выводит. При этом Skls File Browser работает нормально.

Пробовал то же самое с **stalker_hero_1.ogf** и **stalker_animation.omf** и тоже не импортирует, но теперь уже выводит ошибку:

> Digest:
>  [4x] Markers are not supported yet
> 
> Full log:
> +-import-motion()
> |  Markers are not supported yet: {'name': 'Left foot\r'}
> |  Markers are not supported yet: {'name': 'Right foot\r'}
> |
> +-import-motion()
> |  Markers are not supported yet: {'name': 'Left foot\r'}
> |  Markers are not supported yet: {'name': 'Right foot\r'}

**Comment by igelbox** [comment]
> плагин 8.0.0

Каково оно там в будущем? У нас сейчас ещё только 0.8.0 ))

> Markers are not supported yet

Это warning, т.е.всё-равно должен импортить нормально.

**Comment by PavelBlend** [comment]
@IgeNiaI а можешь скинуть эти object и skls файлы? У меня всё импортируется. Я проверил на оригинальных моделях ЗП.

**Comment by IgeNiaI** [comment]
Скорей всего я что-то не так делаю, но не могу понять что

[hands_anim.zip](https://github.com/PavelBlend/blender-xray/files/3346881/hands_anim.zip)

**Comment by PavelBlend** [comment]
Я установил 0.8.0 и твои файлы в ней нормально импортировались. А в окне Dope Sheet в режиме Action Editor нет анимаций в списке? Может они импортировались, но ты их не присвоил к скелету, поэтому модель статична.
![01](https://user-images.githubusercontent.com/7983249/60458567-a36dbd80-9c47-11e9-916c-d86c371de00e.jpg)
Либо можно в окне Properties во вкладке Object в панеле XRay включить параметр Motions > Play Active Motion и клацнуть на любой анимации из списка ниже.

**Comment by IgeNiaI** [comment]
> А в окне Dope Sheet в режиме Action Editor нет анимаций в списке?

Потому и жалуюсь, что их там нет. А как их присвоить к скелету?

**Comment by PavelBlend** [comment]
> А как их присвоить к скелету?

нужно сделать скелет активным и в Dope Sheet выбрать из списка анимацию.

> Потому и жалуюсь, что их там нет.

значит это ошибка. Мне нужно её воспроизвести. Если я этого не сделаю, то не смогу её исправить. Поэтому мне нужно больше информации: какая версия блендера? Стабильная 2.79b или дневная сборка 2.79b? Какая ОС? Какая последовательность действий была при импорте? Не были сняты галочки с анимаций в списке Filter Motions при импорте?

**Comment by IgeNiaI** [comment]
Стабильная 2.79b, Windows 7 Pro SP1
Действовал в том же порядке, что на скриншотах. После импорта анимаций картинка идентична третьему скриншоту.

![1](https://user-images.githubusercontent.com/9607628/60460174-08f28780-9c11-11e9-9212-d85e020ee6c5.png)
![2](https://user-images.githubusercontent.com/9607628/60460175-08f28780-9c11-11e9-94c2-8bf869a4f991.png)
![3](https://user-images.githubusercontent.com/9607628/60460176-098b1e00-9c11-11e9-8385-ee1cb0f62907.png)
![4](https://user-images.githubusercontent.com/9607628/60460177-098b1e00-9c11-11e9-92a4-ee787eb2adb9.png)

**Comment by PavelBlend** [comment]
Странно. А попробуй скачать последний коммит с ветки develop:
https://github.com/PavelBlend/blender-xray/tree/7a19914104c4da419bfe8eb6cc4e90ce795288a4
Кнопкой clone or download, распакуй скачанный архив и помести папку io_scene_xray в аддоны блендера (C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\). Может поможет. Я просто всё равно не могу воспроизвести эту ошибку.

**Comment by PavelBlend** [comment]
И, кстати, просто совет, не относящийся к ошибке:
при импорте object файлов, которые были получены путём конвертации из ogf конвертером Бардака, нужно всегда устанавливать тип формата SoC, вместо CoP. Даже если ogf были взяты из ЗП. Просто конвертер Бардака не поддерживает сохранение групп сглаживания в формате CoP.

**Comment by IgeNiaI** [comment]
> А попробуй скачать последний коммит с ветки develop

Не помогает.

При импорте модели появляются предупреждения, но они вряд ли причастны

> Digest:
 [9x] Weight VMap has values that are close to zero

> Full log:
+-file(path='E:\\SMPStuff\\converter_18oct2017\\wpn_hand_01.object')
| +-mesh(name='wpn_hand_01Shape')
| |  Weight VMap has values that are close to zero: {'vmap': 'l_upperarm'}
| |  Weight VMap has values that are close to zero: {'vmap': 'l_forearm'}
| |  Weight VMap has values that are close to zero: {'vmap': 'l_hand'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger11'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger12'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger2'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger21'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger22'}
| |  Weight VMap has values that are close to zero: {'vmap': 'bip01_l_finger31'}

**Comment by PavelBlend** [comment]
Хммм... А у объекта есть в списке анимаций что-нибудь? Я имею в виду в окне Properties > Вкладка Object > Панель XRay Engine: Object > Свиток Motions.
И я записал видео:
https://youtu.be/f56hoCIZ3gQ
Может чем-то поможет. Как видно у меня твои skls без проблем импортировались.

**Comment by igelbox** [comment]
Я тоже попробовал (на Blender 2.79):
- оно конечно да `После импорт анимаций картинка идентична третьему скриншоту.`, но если ткнуть на список Action-ов, то там всё есть и если выбираю - у меня работает.
- `Weight VMap has values that are close to zero` не должны влиять.

**Comment by IgeNiaI** [comment]
Я тупой. Не додумался посмотреть в Browse Actions to be linked. Всё на месте, спасибо.

**Comment by PavelBlend** [comment]
Тогда я закрываю issue.

**Comment by igelbox** [comment]
Я уж чуть было видос не записал, чтоб показать, что всё ОК.

@PavelBlend, ты опять меня опередил))
Я думаю, может добавить какие-нибудь info-логи и записывать их в Text-блоки (куда предупреждения сейчас пишутся), типа:
```
Blender: 2.79b bla-bla
Version: 0.8.0

Imported successfully: 20 motions.
```

**Comment by PavelBlend** [comment]
Можно ещё в Info добавить время импорта/экспорта. Или не надо? И наверное лучше создать отдельную issue, и в ней обсудить?

**Comment by igelbox** [comment]
Можно и время. Этот блок всё-равно не сохраняется, т.к. у него users=0.
Да, если норм - то давай отдельную ишью.
