### ISSUE TITLE
Выводить информацию в Info после импорта/экспорта

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#263]
После импорта/экспорта выводить в окно Info в заголовок дополнительную информацию. И записывать её в лог файл.

Например, сколько объектов/анимаций было импортировано/экспортировано, время импорта/экспорта. Можно ещё добавить дату и время запуска импорта/экспорта в лог.

И не создавать новый лог файл при каждом импорте/экспорте, а добавлять в уже существующий. Так как однажды не обращал внимание на эти логи, а потом открыл сцену и в текстовом редакторе увидел больше 10 лог файлов. Долго их удалять. Можно во время удаления случайно удалить свои текстовые файлы.

Список того, что печатать в лог файл:
- [x] потраченное время на импорт всех файлов
- [x] потраченное время на экспорт всех файлов
- [x] потраченное время на импорт отдельного файла
- [x] потраченное время на экспорт отдельного файла
- [x] потраченное время на импорт анимаций из отдельного файла (только для `object` и `ogf` форматов)
- [x] потраченное время на экспорт анимаций в отдельный файл (только для `object` и `ogf` форматов)
- [x] дата выполнения импорта
- [x] дата выполнения экспорта
- [x] количество импортированных файлов
- [x] количество экспортированных файлов
- количество созданных блоков данных во время импорта:
  - [x] объектов
  - [x] мешей
  - [x] материалов
  - [x] изображений
  - [x] текстур (для `blender` `2.7x`)
  - [x] анимаций
  - [x] арматур

**Comment by igelbox** [comment]
> Так как однажды не обращал внимание на эти логи, а потом открыл сцену и в текстовом редакторе увидел больше 10 лог файлов.

Я был уверен, что они не сохранялись, т.к. у них users=0 (я думал, это общая практика Blender-а). Но, похоже, для `texts` это не работает((

**Comment by PavelBlend** [comment]
> И не создавать новый лог файл при каждом импорте/экспорте, а добавлять в уже существующий

Хотя будет трудно в одном логе искать предупреждения от последнего импорта/экспорта. Можно сделать так: создавать один лог общий (xray_log.txt), а второй лог - для последнего действия: xray_import.object, xray_import.anm, xray_export.object, xray_export.anm и т. д... После каждого нового действия удалять xray_import.object и помещать его содержимое в конец xray_log.txt, потом создать новый xray_import.object и в него поместить лог от последнего действия.

**Comment by PavelBlend** [comment]
Теперь аддон будет создавать два текстовых файла со статистикой:
`xray_stats` - статистика последнего импорта/экспорта
`xray_stats_history` - история статистики для всех импортов/экспортов

![01](https://github.com/PavelBlend/blender-xray/assets/7983249/f9fc8182-4086-4ddf-b6e0-e5fbdd21712b)
