### ISSUE TITLE
Bones set in blender make the Actor Editor crash

### ISSUE THREAD

**Issue by PanzerKadaver** [PavelBlend/blender-xray#265]
From whatever reason and whatever methods (set bones from scratch or replace mesh in an already set of bones), it look like bones export is broken and try to load a .object in Actor Editor lead to a crash.

The following error is written in the Actor Editor log :

`Object 'c:\users\toxic\pictures\tarkov dump\helmet_zsh\helm_zsh.object' successfully loaded. Loading time - 0.08(s).
 
FATAL ERROR
 
[error]Expression    : assertion failed
[error]Function      : x:\stalker_addon\sources\trunk\xrcore\FixedVector.h
[error]File          : x:\stalker_addon\sources\trunk\xrcore\FixedVector.h
[error]Line          : 38
[error]Description   : id<count`

Importing .object without bones into Actor Editor is done without problem.

**Comment by igelbox** [comment]
@PanzerKadaver would you mind attach the object file to help us to repro this issue?

**Comment by PanzerKadaver** [comment]
> @PanzerKadaver would you mind attach the object file to help us to repro this issue?

Sure. Here you go. I've also joined my .blend files.

[helmet_zsh.zip](https://github.com/PavelBlend/blender-xray/files/3351134/helmet_zsh.zip)

**Comment by PavelBlend** [comment]
The helmet object has no vertex groups.

@igelbox у меня даже не получилось экспортировать из блендера этот объект. Видимо ошибка в коде. Создал issue #267

И надо сделать предупреждение, что "объект не имеет групп вершин" в случае, если у объекта есть скелет. Я создал отдельную issue #266 , так как это не относиться к предупреждениям, а скорее всего связана с отсутствием групп вершин или с отсутствием весов.

**Comment by PanzerKadaver** [comment]
> The helmet object has no vertex groups.

It's an error that I can fix by myself in blender or it's inherent to your plug-in ?

**Comment by PavelBlend** [comment]
@PanzerKadaver 
![01](https://user-images.githubusercontent.com/7983249/60615936-f9be3600-9dd8-11e9-8648-11a5ad0f8ec0.jpg)
![02](https://user-images.githubusercontent.com/7983249/60615941-fd51bd00-9dd8-11e9-9a77-ffcd95f05ba7.jpg)
The name of the vertex group must match the name of the bone to which it is attached.
Here is a lesson on this topic:
https://youtu.be/Tl4qTgwQwYw

**Comment by PavelBlend** [comment]
Did my advice help you? If not, let me know. For now, I will close this issue to clear the bug tracker.
