### ISSUE TITLE
Когда релиз на Blender 2.8?

### ISSUE THREAD

**Issue by ghost** [PavelBlend/blender-xray#270]
Когда примерно аддон выйдет на новую версию блендера 2.8?

**Comment by PavelBlend** [comment]
Мы уже портировали аддон на 2.80. Осталось дождаться релиза. Релиз будет наверное после того, как мы исправим некоторые баги. Например, #266 #258 #256

**Comment by ghost** [comment]
Отлично, спасибо!

**Comment by igelbox** [comment]
@dmsass можно, на свой страх и риск, установить аддон прямо из develop ветки, не дожидаясь релиза.
Заодно, поможешь нам с тестированием текущего состояния под 2.80 :+1:

**Comment by PavelBlend** [comment]
Зарелизил: https://github.com/PavelBlend/blender-xray/releases/tag/v0.9.0
