### ISSUE TITLE
Is build_details file necessary to exist in level folder?

### ISSUE THREAD

**Issue by Szabi123** [PavelBlend/blender-xray#280]
Dear Pavel!

Please, be so kind to give me advice in the following matter.

The first stage of my mod is ready: I have created all plant textures I will use.

Now comes the second step: to create the new plant models in Blender, use my textures on them and exchange the existing vanilla models in level.details with my own models.

My problem is the following. I will have to create vegetation for 20 different levels. I want to use two build_details files for each level. Now to create those enormous amount of texture atlases for each level is an incredible work and would last for ever.

My idea is the following. I would create six texture atlases as build_details files including all my textures, and I would place all six atlases into a \det folder. Then I would create all my plant models and UV-texture them from these six atlases. This way there wouldn't be any build_details file in the level folder (where level.details file is), becouse level.details file would use my texture atlases from the \det folder.

Do you think this method could work? Or is there any better solution?

Thank you!

**Comment by PavelBlend** [comment]
Yes, this method will work. You will need to place your textures in the `gamedata\textures\det` folder. Or to any folder in the `gamedata\textures` directory. And it will be necessary for new 3D models to create textures that will refer to dds files in the `gamedata\textures\det` folder. Thus, all levels will use shared dds files from the `gamedata\textures\det` folder.

The presence of a build_details.dds file is optional.

**Comment by Szabi123** [comment]
Thank you! I will let you know about how I make progress!

**Comment by Szabi123** [comment]
Dear Pavel!

Please help me to figure out an issue.

So in case of some models - like mushrooms etc. - it would be important for me to be able to place only a very few (2-3), or even ONLY ONE of a model to a map. My problem is, that no matter how hard I try to set alpha or other options in your Blender plugin, I'm unable to do that, even with the lowest alpha settings I get way too much of a model to one place.

I've looked into Lost Alpha - escape map, and I see, that in some cases there are plants, of which there is only one model, like this fern for example:


![kép](https://user-images.githubusercontent.com/20930116/65600907-5a58ab80-dfa1-11e9-8e2e-5a7188118311.png)

There are also some cases, where you see only 2-3 models of a plant, like this yellow flower here:

![kép](https://user-images.githubusercontent.com/20930116/65601028-98ee6600-dfa1-11e9-911a-e1dfa704ce27.png)

Would you please take a look into this matter and help me to find out how could I place only 2-3 or even only one plant model to a part of a map? You could help me really a lot with this! 

Wait for your reply, thank you!

**Comment by PavelBlend** [comment]
The format level.details can store 16 gradations of density.
0 - this means that the mesh to the level will not be added.
1 - is the minimum density.
15 - this means maximum density.
You most likely need the lowest possible value that can be set.
But in a blender there is no way to specify colors in an integer format.
Instead, float color values are used.
And the importer and exporter do the conversion between them.


To set the density to 1, do the following:

- remove the alpha channel from one pixel (make it equal to 0.0). Use an Erease Alpha brush with a Strength value of 1.0

- add an alpha value of about 0.25 to the alpha channel of one pixel. Use the Add Alpha brush with a Strength value of 0.25.

Here is the result of these actions:
![01](https://user-images.githubusercontent.com/7983249/65714969-dab40500-e0a4-11e9-8f25-7572054da8dd.jpg)

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you! Seems to work fine!

![kép](https://user-images.githubusercontent.com/20930116/65766141-6d4ab780-e12a-11e9-8f78-0d2f60231688.png)

I'll let you know about further results.

Cheers!

**Comment by Szabi123** [comment]
Dear Pavel!

Please let mo point out a strange thing. As you saw on my previous image I was able to add only one plant following your instructions. However, both you and me placed the plant to a place (asphalt or plane ground), where there are no plants originaly in the game.

But. I tried to do the same thing in a place, where plants already exist. And in those places I am unable to add only one model, even if I erase alpha from all four details meshes png files. The image you see below was made the following way:
- I erased alpha with maximum strength (1.0) from all four details meshes png
- I added 0.25 alpha in "details meshes png 0" into seven separate pixels.
- I added color in "MIX" mode with maximum strength (1.0) into all the mentioned seven pixels in "details meshes png 0" 
Here is the result:
![kép](https://user-images.githubusercontent.com/20930116/65783544-4c955880-e150-11e9-92a0-4b6f7fe309d8.png)
So you clearly see the seven pixels filled, but there are not only one plants, but many in each pixel.

Could you please help to find out the cause for this?

Thank you!

**Comment by PavelBlend** [comment]
Try to make all the items in a different order.
That is, like this:

1:
> I added color in "MIX" mode with maximum strength (1.0) into all the mentioned seven pixels in "details meshes png 0"

2:
> I erased alpha with maximum strength (1.0) from all four details meshes png

3:
> I added 0.25 alpha in "details meshes png 0" into seven separate pixels.

**Comment by Szabi123** [comment]
Dear Pavel!

I tried your method, I did everyrthing exactly as you wrote, but untill now, unfortunately, no luck. I get this using your method (15 pixels filled with plant):

![kép](https://user-images.githubusercontent.com/20930116/65907005-cd0fbf80-e3c3-11e9-9e2e-f2de97623b5c.png)

Besides, please let me ask another thing as well. There is a plant model, I want to increase the height. But no matter, what value I set, I can not make the plant any bigger. As you see, I set an enormous 8-9 value, but no change. Can you recommend something to solve this problem? Here is a screenshot:

![kép](https://user-images.githubusercontent.com/20930116/65907110-fe888b00-e3c3-11e9-9d42-2c6b60e64d6c.png)

Thank you!

**Comment by PavelBlend** [comment]
I can’t reproduce the problem with the scale of grass patterns. I entered a scale value of 8 and got this:
![ss_pavel_09-30-19_22-43-26_(test_details)](https://user-images.githubusercontent.com/7983249/65910693-e587d600-e3d3-11e9-8af1-79281fbdb29d.jpg)

**Comment by PavelBlend** [comment]
Checked the density of grass seeding.
The minimum density looks like this:
![ss_pavel_09-30-19_23-02-32_(test_details)](https://user-images.githubusercontent.com/7983249/65912399-ccccef80-e3d6-11e9-903e-8f6b71910a61.jpg)
The density was written to the file at a value of 1 (minimum value).
In the graphics settings, grass density is set to maximum.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you for the instructions!

Please, let me ask another question. I would like to add ivy models to walls of buildings. Since I'm not familiar with SDK Level Editor, is there any way I could do that using Blender X-Ray plugin?

**Comment by Szabi123** [comment]
Dear Pavel!

Please help me, I have an issue and can not find out what is happening.

So. I paint on one of the detal meshes png files with the color of a model. I export level.details file and run the game. I see, that my model is there on the map, so everything is OK. I close the game and go back to Blender. I continue work, this time I paint with another color to add a new model. I export level.details file again and run the game. But I see, that however my new plant is there, the previous one completely disappeared from all places of the map... What can be the cause of this??

**Comment by PavelBlend** [comment]
Have you clicked the Pack Details Images button?
![01](https://user-images.githubusercontent.com/7983249/66218840-aeb30800-e6d2-11e9-8dd0-db7c50815b6c.jpg)
This button saves all changes to images.

**Comment by Szabi123** [comment]
Hi!

No, untill now, I didn't know such button even exists... But I will try it, and tell you about the results.

Thank you!

**Comment by Szabi123** [comment]
Hi!

No, untill now, I didn't know such button even exists... But I will try it, and tell you about the results.

Thank you!

**Comment by Szabi123** [comment]
Dear Pavel!

I have checked, but I don't have this button. I use Blender 2.79 and X-Ray plugin 0.7.0

**Comment by Szabi123** [comment]
Here is an image

![kép](https://user-images.githubusercontent.com/20930116/66244007-dd4ad600-e706-11e9-88a1-56a2b38a7960.png)

**Comment by Szabi123** [comment]
OK, I tried 0.9.0, that has this feature.

**Comment by Szabi123** [comment]
Dear Pavel!

Would you please tell me, what is the most effective way to extract multiple coordinates from the game? I would like to add a script with falling leaves to trees and to do that, I would need to extract the coordinates of some trees from the game somehow.

By the way, Lost Alpha has got a tool that opens with F2, it shows actual coordinates, and there is also a little box called "to Log", but no matter I check this box, nothing happens, I don't find a log file with coordinates anywhere in my folders.

But perhaps you know a better and faster way to do this.

Thanks!

**Comment by PavelBlend** [comment]
I do not know how to find out the coordinates.
The only thing that comes to my mind is that you can import a level with trees using the stalker_tools addon:
https://github.com/PavelBlend/blender_stalker_tools_addon
And in the blender, calculate the desired coordinates.
But this method is not good in that everything will slow down in a blender. There will be low productivity.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you!

Is there a way to delete color from details meshes png? If I erase alpha, I only erase density, but the original color still remains there if I add alpha back.

**Comment by PavelBlend** [comment]
You can remove color in Photoshop/Gimp using the magic wand tool. Save the image in tga format and open it in a raster editor.

**Comment by Szabi123** [comment]
Dear Pavel!

So you say there is no way to delete a color from the png image inside Blender's texture editor?

**Comment by PavelBlend** [comment]
To remove all the pixels in one color at once, you need Photoshop/Gimp.
And a note:
To remove a plant from the slot, you need to paint over a portion of the details meshes image in black color.

**Comment by Szabi123** [comment]
This is a really usefull detail! So basically black color works as an "eraser tool"?

**Comment by PavelBlend** [comment]
Yes, black is an eraser. That is black color - this means that the mesh of vegetation will be absent.

**Comment by Szabi123** [comment]
Dear Pavel!

I know we have discussed about this several times, but please, let me get back a little bit to number of plants.

So I use your method:

- I paint on details meshes png 0 with "mix" set to 1.0
- I erase alpha from all four details meshes png 
- I add alpha with the value of 0.25 on details meshes png 0

In the following image you see the result (grass density is turned to maximum in game menu). I painted on 15 pixels, but I only get 9 pixels filled, and non of them are individual plants, but mostly 3 pieces per pixel.

![kép](https://user-images.githubusercontent.com/20930116/66725121-4977b900-ee2e-11e9-81e6-3b5a7b6ea1a6.png)

But how is this possible? If I erase alpha from all png images and I add the exact same amount of alpha? I can not understand. However, I was thinking, if you look at the leaves on the road, they are always individual leaves. So perhaps somehow possible to add only one plant?

I would mostly need this for mushrooms, becouse if there are 2-3 mushrooms in the same spot, they collide into each other and it looks ugly.

Furthermore, somebody advised me to use spawn scripts to add mushrooms to the levels. Do you have any experience how to do that?

Thank you!

**Comment by PavelBlend** [comment]
Drawing details meshes in a blender is pretty problematic.
It is easier to do this in a raster editor (Photoshop/Gimp ...).
And you got fewer embedded pixels in the game, because the details plugin is arranged in a certain way. Namely:

The colors in the details meshes image indicate the 3D model number. And this image has a resolution 2 times less than the seeding density of 3D models.
That is, you need to draw on the RGB channels with a brush in the size of two pixels. Since if you paint with a brush the size of one pixel, then you can get the following:
![01](https://user-images.githubusercontent.com/7983249/66855483-fc115e00-ef8b-11e9-8309-3da993a9b1fb.png)

But the alpha channel of the image details meshes has a resolution twice that of the RGB channels. That is, if you have a level and this level has a size of 100x100 meters, then this level will have 50x50 slots (each slot is 2x2 meters) for planting.

And this means that the resolution of the RGB channels details meshes of images will be 50x50 pixels. And the resolution of the alpha channel details meshes (this alpha channel indicates seeding density) will be 100x100 pixels.

The details meshes image contains two images with different resolutions. In RGB channels, the first image, and in the alpha channel, the second image (twice as much in resolution).

If you open the images in a raster editor, then you can enable the display of the grid in 2x2 pixels for the landmark.

Regarding the number of models in one slot:
you have a screenshot in the same place are several models of mushrooms. Can you give a link to download this level.details file so that I can find out the reason for this arrangement of models?

**Comment by Szabi123** [comment]
Dear Pavel!

Just to clarify: if I understand you right, you basicaly say, that it is possible to add only one plant to a location, if I export one level details meshes png file to Photoshop and I paint on it there? Is that what you are saying?

If that is the case, would it be possible, that you would make me a little tutorial video, how to do this? I would be utterly grateful! Today I was trying this thing in Blender all the day, but no luck. In theory I understand what you wrote, but I have no clue how to start.

Thank you!

**Comment by PavelBlend** [comment]
You can draw in a blender, but in Photoshop it is more convenient to do this.
Here is a video where I place several models of mushrooms on a map using only a blender.
https://youtu.be/JG9G75xukZg

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you for the video, I appreciate!

So I did exactly what you do in the video. In most cases I get 1 piece of mushroom, sometimes 2-3 in one pixel. What is not good, that sometimes I get two pieces of mushroom very close to each other and it looks ugly:

![kép](https://user-images.githubusercontent.com/20930116/66872198-aea1ea80-efa5-11e9-9336-b4d0cfc570dc.png)

What is the reason for this? Is there any method to avoid this kind of duplication? Or if I  can not avoid this kind of duplication in Blender, is it possible in Photoshop?

Thank you!

**Comment by PavelBlend** [comment]
Can you give a link to download level.details with these mushrooms? I do not yet fully understand why this is happening.

**Comment by Szabi123** [comment]
Dear Pavel!

Unfortunately I deleted that file, but if I can recreate this, I will save and send to you.

Please, let me get back to a previous question. So, did I understand it correctly, you say, that editing details meshes png file in Photoshop could make it sure, that I never have these kinds of duplications and I can always add only one plant to a location for sure? I would be very much interested about this method, if it's true.

Thank you!

**Comment by PavelBlend** [comment]
In a blender, you can do everything as in Photoshop. But in Photoshop, many things are more convenient to do. As for the duplicates: I don’t yet know why they appear and I’m not sure that they can be avoided with the help of Photoshop.

**Comment by Szabi123** [comment]
Dear Pavel!

Please let me ask the following.

On sloping surfaces parts of my leaves are missing, becouse the leaf is in collision with the surface, like this:

![kép](https://user-images.githubusercontent.com/20930116/67180843-18bdf380-f3db-11e9-8a82-59464b9cabb5.png)

My model looks like this:

![kép](https://user-images.githubusercontent.com/20930116/67180903-460aa180-f3db-11e9-8d62-0df1ad417893.png)

Can you give me some advise, how to fix this issue?

Thanks!

**Comment by PavelBlend** [comment]
This cannot be fixed.
This is how the X-Ray engine works.
All 3d models of leaves and grass always look up, regardless of the slope of the surface.
The only thing that can be done is to raise up the vertices of 3d leaf models.

**Comment by Szabi123** [comment]
Dear Pavel!

Previously you recommended me to make editing faster deleting fastpath objects using the following script:

"bpy.ops.object.select_all(action='DESELECT')
for obj in bpy.data.objects:
    if obj.name.startswith('FASTPATH'):
        obj.select = True"

I write this script into script editor, hit enter, then I go back to the map, I hit X - delete, but nothing happens. Can you tell me, what I do wrong?

Thanks!

**Comment by PavelBlend** [comment]
To run the script, press Alt + P, but not Enter.

**Comment by PavelBlend** [comment]
Do you want to import a level file into blender and speed up blender?
If so, here is the instruction:
- install the stalker_tools addon from the last commit https://github.com/PavelBlend/blender_stalker_tools_addon
- activate it.
- import level file
- the importer will create many fastpath object. Fastpath are objects that are stored in level files.
- To remove all fastpath objects and speed up blender, open outliner, turn on group mode and select the FASTPATH group.
![fastpath_select](https://user-images.githubusercontent.com/7983249/68083014-e8437400-fe34-11e9-9b3a-94974b738725.jpg)
- You can also delete the CFORM group.
- after these steps, you can combine all the objects into one using the keys Ctrl + J.
- After these steps, the blender will work faster.

**Comment by Szabi123** [comment]
Dear Pavel!

I open console using shift+F4 and I paste the code. It looks like this:

![kép](https://user-images.githubusercontent.com/20930116/68082433-ebcb0100-fe1c-11e9-8e6a-162ad6a352c6.png)

Now either I press Alt+P or I press autocomplete button, nothing happens. If I go back to 3D view nothing is selected, if I press x - delete selected objects nothing happens. What do I do wrong?

**Comment by Szabi123** [comment]
Dear Pavel!

Last time you asked me to send you a level.details file, where I had two models on the same spot. That file I unfortunatelly deleted, so I made a new experiment. I got to some interesting conclusions that I would like to show to you.

I have created some test mushrooms on LA Antennas level. I used the method you told me:
1. As a start I erased alpha with 1.0 value from all four details meshes png images.
2. I added mix color with 1.0 stregth.
3. I erased alpha with 1.0 strength.
4. I added alpha with 0.25 strength.

In all the operations above alpha was checked in the box: 
![kép](https://user-images.githubusercontent.com/20930116/68093899-152a7200-fe9b-11e9-8900-3d452b44f120.png)

The result I got in the game was this:
![kép](https://user-images.githubusercontent.com/20930116/68093903-283d4200-fe9b-11e9-92de-e7f1b08f3e4f.png)

As you see, in most cases I don't get only one model. In two pixels I don't get model at all, in other pixels I get up to 7 models in one pixel like this:
![kép](https://user-images.githubusercontent.com/20930116/68093925-5e7ac180-fe9b-11e9-8c6a-19d797542a40.png)

In some case, I also get 3 models on the same spot, very close to each others:
![kép](https://user-images.githubusercontent.com/20930116/68093961-b285a600-fe9b-11e9-80d0-ebf598611ccc.png)

In the next round I do exactly the same routine (erase alpha with 1.0 value from all four details meshes png images; add mix color with 1.0 stregth; erase alpha with 1.0 strength; add alpha with 0.25 strength), but this time I left the alpha box unchecked:
![kép](https://user-images.githubusercontent.com/20930116/68093980-f5e01480-fe9b-11e9-896a-7872497c3ebc.png)

Pixels looked like this in Blender:
![kép](https://user-images.githubusercontent.com/20930116/68094224-99cabf80-fe9e-11e9-8b18-ded53009859e.png)

And the result I got in the game was the following:
![kép](https://user-images.githubusercontent.com/20930116/68093994-05f7f400-fe9c-11e9-80d6-9436e0179f34.png)

As you can see, this time there are fewer models, but I don't get only one model\pixel even with this method, so the situation is not really different compared to the previous one.

What is also interesting, that the models have different sizes on the map as you can see, however I set the min and max values both equaly to 2.0:
![kép](https://user-images.githubusercontent.com/20930116/68094008-47889f00-fe9c-11e9-9dfe-abd08b38b053.png)

Now I still try to understand the cause of these results and I would still very much need the ability to be able to get only one model to one spot. I know, you told me, that the color map is half the resolution of the alpha map in the details meshes png image. However, I can not understand, how can this happen, due to the fact, that as a first action I erased alpha from all four details meshes png images, but perhaps different resolution can be the reason.

You also told me, it would be better to do this in Photoshop. Most important question is: **is it possible to add only one model, if I use Photoshop to edit details meshes png files instead of Blender's texture paint option?** 

If this is possible with Photoshop, please, be so kind to show me how can I do that? What is needed to be done in Photoshop, to get that result? I would be really thankfull for your help again!

If you need a look into them, you can find my level details files here: https://drive.google.com/open?id=1P7bLPKnb1lDpjcoxK9RMfM9DwtJ9lQJ5

Thank you so much!

**Comment by Szabi123** [comment]
One note to my previous comment. The reason, why placing only one model to one spot would be so important for me, is that this way I would be able to place for example mushrooms in various kinds and sizes at once, without any long and hard work of editing, and most importantly, I would be able to avoid, that the models would be in physical collision (like you see on my prveious images), plus this I could do in Blender, and I wouldn't have to fidget with SDK Level Editor and such things. I could use even more complex models like this:

![kép](https://user-images.githubusercontent.com/20930116/68094500-6d647280-fea1-11e9-9d11-d583528cd1fb.png)

**Comment by PavelBlend** [comment]
I looked at your level.details file.
Mushroom meshes have a minimum density (value 1).
I do not know why in one place there are several mushrooms at once.
This is probably how the grass position generator works in the XRay engine.
You can try to arrange the mushrooms at a further distance from each other. But maybe this will not help.

If you use photoshop, the result will be the same.

**Comment by Szabi123** [comment]
Dear Pavel!

I try to follow your instructions and delete fastpath objects from the level. I select outliner:

![kép](https://user-images.githubusercontent.com/20930116/68544750-d2025e80-03c6-11ea-8f91-aed70f023698.png)

But when I switch to "groups" the field turns blank:

![kép](https://user-images.githubusercontent.com/20930116/68544772-f5c5a480-03c6-11ea-9a3c-20f8fe3fe7ff.png)

What do I do wrong?

**Comment by PavelBlend** [comment]
Update the addon. Download the latest commit.

**Comment by Szabi123** [comment]
Thank you!

**Comment by Szabi123** [comment]
Hello Pavel!

As formerly you suggested, I downloaded and installed the latest stalker tools addon. It works OK, but there is a problem. With former versions it took me only about 2-3 minutes to import a level. 

But with this new version it takes about 15-20 minutes (!) to import a level. This is a huge difference and a very long time. What is the reason for this?

**Comment by PavelBlend** [comment]
I do not yet know why imports slowed. When I find the reason, I will say this.

**Comment by Szabi123** [comment]
Did you also experience that importing level is very slow with the latest version of stalker tool?

**Comment by PavelBlend** [comment]
Yes, I also checked, importing became slower. When I wrote the code, I tested at small levels, so I did not notice the slowdown.

**Comment by Szabi123** [comment]
Last time I tried to import Darkscape from LA, which is not the biggest level. But after 20 minutes it was still not imported, so I shut Blender down.

**Comment by Szabi123** [comment]
Dear Pavel!

I imported a level file into Blender. I had the idea, to add an ivy model to the wall and export the level using x-ray Blender plugin. I get error message. I'm not even sure if this is possible.

Is it possible in your opinion, to delete an object - for example a tree -, or add an object to the level and then export the altered level using Blender plugin and use it in the game?

![kép](https://user-images.githubusercontent.com/20930116/71481952-65211780-2800-11ea-8e42-2596726c8695.png)

**Comment by PavelBlend** [comment]
And what is the error text?

It is possible to delete an object and add a new object. But provided that the shaders are specified correctly and the 3D model is correctly added to the sector. To do this right, look at the imported levels. The level has empty objects that act as sectors. A hierarchy of visual objects is attached to these objects. You must correctly specify the place in the hierarchy for the new object.

**Comment by Szabi123** [comment]
Dear Pavel!

I'm so excited about what you wrote! My aim would be, to delete some trees on first place, that I don't like, and secondly to add my ivy models in some places. The problem is, that I don't really understand the sector hierarchy, and I'm also not an expert in Blender yet.

Previously you tought me a lot through tutorial video you made. Is there any chance, that you could make a video, where you show, that you import a level into Blender, you add an object and then you export a level? This way I could learn the process of this.

I would be so much gratefull to you, if you could do that for me!

Thank you so much!

Cheers!

**Comment by PavelBlend** [comment]
I forgot to warn you. If you import a level into blender and then export, you will lose some information in your exported level.
This information is as follows:

- smoothing 3D models at the boundaries of visual objects
- geometry simplification data (SWIS, slide window items)

I do not know how to solve this problem. Therefore, I added the ability to import and export to level as is. And at the moment I do not plan to develop this plugin, as I am busy with other things.

I myself have already managed to forget how the level plugin works.
But I looked at already imported models and figured out how to do it.
Some models require vertex lighting, some require a lighting map.
If you have questions, you can do the same by analogy with the imported level models.

And I noticed that editing levels with blender is a time consuming process.
If you want to make a lot of changes, it is better to make level compilation using xrLC.exe.
Initially, the level plugin was designed to convert levels between different builds of the game.
But I did not finish the support of all the builds, but settled only on the final version of the game.

Here's a video. I made some mistakes and the plugin threw errors, but I fixed them and did re-export.

https://youtu.be/g3-MAoQLFao

So there is no need to repeat all the actions from the video 100%

Result:
https://youtu.be/_W6IEDKcQVA

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you so much for your kind support!

I will follow your instructions, however, what you mentioned, that graphics quality can be reduced if I export level file from Blender, this can be a problem. But I will have to test this.

Other thing is, that if I import a tree for example, I will either ways have to create new AI map and spawn, becouse Blender will not create these for me.

**Comment by Szabi123** [comment]
Dear Pavel!

Last time, when you showed me, how to place an object into a level using X-Ray Blender plugin, you told me, that the final result in visuals will be worse, than if I used level editor of SDK.

Can you tell me, in what regards will be the visuals worse, if I use your method in Blender shown in your video?

If I plan to place only ivy to the walls, will be the visuals worse only regarding the ivys that I imported, or all other viseuals of the map will be worse as well?

Thank you!
