### ISSUE TITLE
Поддержка импорта/экспорта уровней

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#281]
#### Описание идеи:
Предлагаю в этой issue обсудить внедрение формата level. Обсудить все плюсы и минусы, и возможно ли это сделать на должном уровне. В отдельном репозитории я веду разработку импорта этого формата:
https://github.com/PavelBlend/blender_stalker_tools_addon
Но во первых, это не удобно, так как импортёр использует некоторые вещи из аддона blender-xray.
Во вторых, его нужно переписать заново, так как код трудно поддерживать в таком состоянии.

У меня есть идея: нужно изменить код аддона так, чтобы он стал объектно ориентированным. Нужно создать классы форматов. Для примера есть такой класс для dm формата:

```python
import os

from io_scene_xray import xray_io


class Format:
    def _read_file(self):
        with open(self._file_path, 'rb') as file:
            data = file.read()
        self._packed_reader = xray_io.PackedReader(data)


class DetailModelScale:
    def __init__(self):
        self.minimum = 1.0
        self.maximum = 1.0


class DetailModelMesh:
    VERTICES_COUNT_LIMIT = 0x10000

    def __init__(self):
        self.vertices_count = 0
        self.triangles_count = 0
        self.vertices = []
        self.uvs = []
        self.triangles = []


class DetailModel(Format):
    def __init__(self, file_path):
        self._file_path = file_path
        self._read_file()
        self._read_name()
        self._read_data()

    def _read_name(self):
        self.name = os.path.splitext(os.path.basename(self._file_path))[0]

    def _read_data(self):
        self._read_shader()
        self._read_flags()
        self._read_scale()
        self._read_geometry()

    def _read_shader(self):
        self.shader = self._packed_reader.gets()
        self.texture = self._packed_reader.gets()

    def _read_flags(self):
        self.flags = self._packed_reader.getf('<I')[0]

    def _read_scale(self):
        self.scale = DetailModelScale()
        self.scale.minimum = self._packed_reader.getf('<f')[0]
        self.scale.maximum = self._packed_reader.getf('<f')[0]

    def _read_geometry(self):
        self.mesh = DetailModelMesh()
        self._read_geometry_info()
        self._read_geometry_vertices()
        self._read_geometry_triangles()

    def _read_geometry_info(self):
        self.mesh.vertices_count = self._packed_reader.getf('<I')[0]
        self.mesh.triangles_count = self._packed_reader.getf('<I')[0] // 3

    def _read_geometry_vertices(self):
        for vertex_index in range(self.mesh.vertices_count):
            position_x, position_y, position_z = self._packed_reader.getf('<3f')
            tex_coord_u, tex_coord_v = self._packed_reader.getf('<2f')
            self.mesh.vertices.append((position_x, position_y, position_z))
            self.mesh.uvs.append((tex_coord_u, tex_coord_v))

    def _read_geometry_triangles(self):
        for tris_index in range(self.mesh.triangles_count):
            vert_index_1, vert_index_2, vert_index_3 = self._packed_reader.getf('<3H')
            self.mesh.triangles.append((vert_index_1, vert_index_2, vert_index_3))


dm = DetailModel('rain.dm')
input('OK')

```

Если так переписать все импортёры и написать импорт level, то сильно ли это скажется на производительности? Просто хотелось бы иметь библиотеку для работы с форматами (например, как библиотека xray_re в конвертере от Бардака) и иметь отдельно библиотеки для импорта/экспорта. То есть разделить код чтения/записи форматов от кода импорта/экспорта.

И есть предложение все эти возможности делать для блендера 2.80/2.81, так как трудно будет поддерживать одновременно и 2.79. Плюс в 2.8 есть инструменты для работы в вершинными нормалями, которых нет в 2.79.

И может перед внедрением нового формата, стоит сделать масштабный рефактор уже существующих форматов? Чтобы все импортёры/экспортёры использовали единую библиотеку xray_re. Плюс добавления такой библиотеки в том, что можно будет её использовать вне блендера.

#### Примеры использования:
Если сделать полноценный импорт/экспорт уровней из всех известных билдов сталкера, то можно будет конвертировать уровни между разными билдами без необходимости длительной компиляции. И можно будет вносить косметические изменения в уже скомпилированные уровни.

**Comment by Artem-Zaxler** [comment]
Доброго времени суток. Я понимаю, что пишу не совсем по теме, но текущий импортер .level формата почему-то не может загрузить ни одного уровня, ссылаясь то на version, то на objects chunk.

**Comment by PavelBlend** [comment]
Привет.

Аддон не поддерживает импорт уровней. Он поддерживает `Scene Selection`, который имеет такое же расширение как и у уровней. Более подробно описано здесь:
https://ap-pro.ru/forum/106-89353-1263126-16-1569078660

И перед импортом, нужно в настройках аддона указать путь к rawdata\objects папке.

**Comment by igelbox** [comment]
Про целесообразность и плюсы/минусы - навряд ли подскажу, а вот про рефакторинг и классы - есть мнение (мнение хейтера ООП и абстракций).

> Если так переписать все импортёры и написать импорт level, то сильно ли это скажется на производительности? Просто хотелось бы иметь библиотеку для работы с форматами (например, как библиотека xray_re в конвертере от Бардака) и иметь отдельно библиотеки для импорта/экспорта. То есть разделить код чтения/записи форматов от кода импорта/экспорта.

Думаю, что скажется, т.к. иногда в форматах встречаются большущие коллекции мелких объектов (например [VMREF-ы](https://github.com/PavelBlend/blender-xray/blob/2e930708e5b0d520a555a39f556d2ff12b192147/io_scene_xray/obj/imp/mesh.py#L96)) и хранение их, как объектов повлечёт большой оверхед. Ну и этот новый промежуточный слой - будет слоем абстрации и тут тоже желательно не увлечься преобразованиями в структуры, чуждые и Блендеру и СДК. Хз, какой пример тут привести, но думается, что при текущем прямом (м.б. даже костыльном подходе) есть возможность писать максимально эффективные импортёры/экспортёры, т.к. в функциях сразу видно, какой формат данных ожидается и сколько параметров нужно считать, чтоб начать процесс импорта.
Я, кстати, изначально тоже думал сделать так, как ты говоришь, но что-то побоялся)

--

> И есть предложение все эти возможности делать для блендера 2.80/2.81, так как трудно будет поддерживать одновременно и 2.79. Плюс в 2.8 есть инструменты для работы в вершинными нормалями, которых нет в 2.79.

Хз, 2.79 - жалко бросать. Я вот на прошлой неделе общался с людьми, которые вынуждено ставили 2.79, т.к. нужный им аддон не работает в 2.80. Жалко будет, если новые версии bledner-xray будут поддерживать только 2.80+.
Или, может я не правильно тебя понял. Если ты про какие-то встроенные алгоритмы - то тут да, можно нарулить абстракцию/полиморфизм и вынести кусок логики сделав его 2-мя разными алгоритмами - один для 2.80 (с intrinsic-ами), другой для 2.79 (с fallback-ами).
Или если ты про добавление нового формата только для 2.80+, то, наверное, норм.

--

> И может перед внедрением нового формата, стоит сделать масштабный рефактор уже существующих форматов? Чтобы все импортёры/экспортёры использовали единую библиотеку xray_re. Плюс добавления такой библиотеки в том, что можно будет её использовать вне блендера.

Ой, рефакторинг - холиварная для меня тема. Недавно ж масштабный рефакторинг был уже))
Я обычно за то, чтоб сперва начать писать новый код по новому, а затем уже (если получится/понравится) то и старый переписывать. Т.е. если хочется ООП, то пожалуйста используй, а как опробуешь/обкатаешь объектную модель, так можно и на другие части приложения её распространять.

**Comment by PavelBlend** [comment]
> Думаю, что скажется, т.к. иногда в форматах встречаются большущие коллекции мелких объектов (например VMREF-ы) и хранение их, как объектов повлечёт большой оверхед.

вот это меня разочаровывает. В си++ можно спокойно писать классы (как и сделал Бардак при написании конвертера), а в питоне нужно все данные использовать сразу после прочтения. Код получается как каша. Меня ещё напрягают длинные функции в сотни строк кода, которые есть сейчас в stalker_tools и в blender-xray.

> Ну и этот новый промежуточный слой - будет слоем абстрации и тут тоже желательно не увлечься преобразованиями в структуры, чуждые и Блендеру и СДК.

А если сделать класс, который будет принимать параметр bytes (или bytearray), и не будет читать все данные, а по мере обращения к ним. Например, при вызове метода read_header будет происходить чтение заголовка у level файлов, при вызове read_visual - чтение одного иерархического ogf визуала (который находится внутри level). То есть классы при этом подходе не будут содержать параметры, а будут их читать только в момент обращения к методам и выдавать их. Правда я ещё не до конца придумал, как это сделать. Попробую написать пример и выложу, если получится.


> при текущем прямом (м.б. даже костыльном подходе) есть возможность писать максимально эффективные импортёры/экспортёры

а если при текущем подходе большие функции разбить на много мелких или даже написать класс, который будет хранить методы, аналогичные уже имеющимся функциям, но не будет хранить данные?

> Хз, 2.79 - жалко бросать.

на первых порах можно его не бросить, а просто добавлять новые изменения только в 2.80. То есть импорта level не будет в 2.79, а будет в 2.8. А остальные старые импортёры останутся на месте в 2.79.

**Comment by igelbox** [comment]
> Код получается как каша.

А мне норм, т.к. я на python обычно с отвращением пишу) Я поклонник TS/JS.

--
> Меня ещё напрягают длинные функции в сотни строк кода, которые есть сейчас в stalker_tools и в blender-xray.

Ну так их можно разбивать на более мелкие функции, которые всё-также будут сразу blender-объекты создавать.

--
> А если сделать класс, который будет принимать параметр bytes

Думаю, хороший компромисс.

--
> а если при текущем подходе большие функции разбить на много мелких или даже написать класс, который будет хранить методы, аналогичные уже имеющимся функциям, но не будет хранить данные?

Думаю, норм будет. Может даже и класс норм подойдёт. Просто, больше половины примеров использования ООП в продакшене, что я видел, в одних случаях приводили к какому-то неповоротливому/неэффективному коду, который "прибит гвоздями" к экземплярам объектов. В других случаях - были просто лишней прослойкой или даже использованием классов не по назначению, а как неймспейсов (привет из Java-мира).
Так что, где не нужен развитой полиморфизм или где нужна пакетная обработка данных - я предпочитаю обычные функции. Их и переиспользовать проще, чем городить наследников какого-то класса ради пары методов.

--
> То есть импорта level не будет в 2.79, а будет в 2.8. А остальные старые импортёры останутся на месте в 2.79.

:+1:

**Comment by PavelBlend** [comment]
Ладно, делать импорт/экспорт в стиле ООП я не буду. Так как не сильно в голове представляю, как будет выглядеть структура кода и как его вообще грамотнее написать.

Может написать level плагин с помощью маленьких функций в 5-10 строк? Чтобы каждая функция делала свою узкоспециализированную задачу. А то сейчас в stalker_tools есть функции в 500-700 строк кода, которые трудно поддерживать/добавлять новые возможности. Я хочу level плагин переписать с нуля в внедрить его в blender-xray. Так как на данный момент меня лично интересует только импорт/экспорт уровней. Чтобы можно было бы конверитровать их между разными билдами и между финалкой. Идея level плагина у меня появилась давно, но вот реализовать её нормально пока не получилось.

Кстати, о функциональном подходе, когда используются маленькие функции в 5-10 строк: минус в этом подходе заключается в том, что иногда приходиться делать функции, которые принимают кучу параметров. А если писать одну длинную функцию, то переменные не нужно передавать. Они все храняться в области видимости функции. Но при таком подходе приходиться читать и изучать функцию заново, чтобы понять, что она делает. И их труднее поддерживать.

**Comment by igelbox** [comment]
> Ладно, делать импорт/экспорт в стиле ООП я не буду. Так как не сильно в голове представляю, как будет выглядеть структура кода и как его вообще грамотнее написать.

Хз, если есть желание, то почему бы и не поиграться. Для меня опенсорс проекты - не только польза для окружающих, но и возможность качать свои скиллы.

> иногда приходиться делать функции, которые принимают кучу параметров

Сделай объект с параметрами, типа как ImportContext был. И каждая функция будет требовать объект с парой тройкой нужных ей свойств, а ты ей будешь полную версию контекста передавать. Ну, или можно сделать ещё круче, с использованием dict и именованных аргументов (kwargs) будет и понятно и гибко.

**Comment by PavelBlend** [comment]
Буду писать о прогрессе разработки и о возникших проблемах здесь. Сделал импорт геометрии уровня с текстурами, юви, лайтмапами. Пока поддерживается формат финалки. Постепенно начинаю делать экспорт. И тут я понял, что очень мало писал экспортёров. В основном делал импортёры. Из проблем я пока вижу следующее:

- нужно при импорте сделать преобразование нормалей вершин в сглаживание
- при экспорте сгенерировать тангенсы и бинормали
- сделать генерацию swi data при экспорте

Некоторые проблемы обсуждались здесь:
https://github.com/PavelBlend/blender-xray/issues/180
https://github.com/PavelBlend/blender-xray/issues/226

**Comment by PavelBlend** [comment]
Пишу о прогрессе. Сделал экспорт. Пока не всё корректно экспортируется, но игру уже можно запускать на этих уровнях. Плюс сектора глючат, всё мерцает и исчезает:
https://youtu.be/5Qvd9I20_4A

**Comment by PavelBlend** [comment]
Доработал немного экспорт. Теперь экспортированные уровни в игре выглядят так:
![ss_pavel_10-11-19_18-28-25_(l01_escape)](https://user-images.githubusercontent.com/7983249/66665108-85582600-ec56-11e9-8140-237d7bf46b3a.jpg)

Правда всё экспортировалось долговато. 4 минуты. А если учесть, что в будущем будет экспорт fastpath геометрии и level.cform, то эту цифру можно умножать на два.

И вот добавил Сюзанну:
![ss_pavel_10-11-19_18-49-53_(l01_escape)](https://user-images.githubusercontent.com/7983249/66665865-14b20900-ec58-11e9-835a-3019162c62da.jpg)
