### ISSUE TITLE
Сделать модуль xray_io самодостаточным

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#282]
#### Описание идеи:
Я внёс изменения в xray_io, которые негативно сказались на нём. Сейчас этот модуль импортирует lzhuf.py модуль и utils.py. Модуль utils используется для вызова ошибки AppError, когда строка содержит недопустимые символы:

https://github.com/PavelBlend/blender-xray/blob/ab60b428e1283ce0fc32ca132fc9afebf289b8ab/io_scene_xray/xray_io.py#L165

Но проблема в том, что после таких изменений модуль xray_io нельзя будет использовать вне blender-xray. Например, я когда-то писал парсер thm, который использовал xray_io и lzhuf, но сейчас xray_io требует наличие utils.py. И, если скопировать utils модуль и запустить скрипт, то будет ошибка, так как не будет найден модуль bpy. В общем xray_io нельзя использовать вне блендера из-за модуля utils. Нужно переделать xray_io, чтобы он не требовал utils.py и был самодостаточным.

#### Примеры использования:
Если переделать xray_io, то его можно будет использовать вне блендера. Это часто пригождается при написании dump'еров форматов.

**Comment by igelbox** [comment]
Могу предложить сделать `xray_io.py` настраиваемым, т.е. завести у него глобальную переменную, в которую закидывать функцию обработки ошибок unicode-строк. Тогда bledner-xray сможет закинуть туда `lambda string: raise AppError('Not valid string: {}'.format(string))`, а другой аддон - закинет что-то своё.

**Comment by PavelBlend** [comment]
Это получается, что нужно делать настройку xray_io при каждом импорте в каждом модуле? Например, так:

```python
import xray_io

xray_io.cause_error = lambda string: raise AppError('Not valid string: {}'.format(string))
```

И этот код нужно будет добавлять во все py файлы, в которых есть использование xray_io? Ну или вынести этот код в функцию и поместить её в модуль utils. Но всё равно нужно будет в каждом модуле вызывать эту функцию.

Я подумал, может сделать по другому. Например, так:
xray_io.py:
```python
...
try:
    from .utils import AppError
    has_app_error = True
except:
    has_app_error = False
...
class PackedWriter():
    ...
            except UnicodeEncodeError:
                 if has_app_error:
                     error = AppError
                 else:
                     error = BaseException
                 raise error('Not valid string: {}'.format(string))
...

```

**Comment by igelbox** [comment]
> при каждом импорте в каждом модуле?

Думаю, не придётся, т.к. модули - это типа синглтоны, т.е. во всём python-приложении во время работы может быть только 0 или 1 экземпляр каждого модуля (во время тестов, там наверное можно и по нескольку раз модели загружать).
Т.е. будет достаточно только 1 раз инициализировать.

Пример написал в коммент к пулл-реквесту.
