### ISSUE TITLE
export object motions

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#29]
which imported in #27

**Comment by igelbox** [comment]
Проблема, с текущим скелетом возможна только выгрузка STEP-ед ключей, иначе получаем интерполяцию углов поворота в другой системе координат и, как следствие, разные нехорошие подёргивания анимации и прочие баги.
Вот теперь и не знаю, вносить эти правки в основную ветку или нет? Если внесу, то после перехода на новый скелет (а его ещё придумать/отладить нужно) придётся реимпортировать существующие blend-файлы (чтоб скелет и анимации автоматом сконвертировать).

**Comment by ghost** [comment]
Думаю оставить в текущей ветке и не вносить изменения в основную. Можно подсмотреть скелет в аддоне Source Engine (smd/dmx) - вроде как более предрасположен к функционалу хреевских объектов.

**Comment by igelbox** [comment]
А как мне сконвертировать скелет из object в smd? Я попробовал ogf2smd, но он выдал мне тонну ключевых кадров (по 6 на blender-овский кадр). Так-то я тоже умею. А хочется увидеть плавные анимации с небольшим количеством ключевых кадров (чтоб убедиться, что скелет подходит).

**Comment by ghost** [comment]
Через MilkShape. Дома буду и скину файл модели и файлы анимаций.

**Comment by PavelBlend** [comment]
"разные нехорошие подёргивания анимации и прочие баги"
А можно пример модели с багом, ради интереса. Я просто пробовал экспортировать, багов не было.

**Comment by ghost** [comment]
Модель (wpn_ak74_hud) и пара анимаций (idle и reload) в формате SMD. - Импорт и экспорт производился в программе MilkShape.
[smd.zip](https://github.com/igelbox/blender-xray/files/237108/smd.zip)

**Comment by igelbox** [comment]
"багов не было" - это потому, что сейчас нет интерполяции (плагин выгружает много-много STEP-ключей).
[примеры файлов и патч линейной интерполяции и разреженных ключей](https://github.com/igelbox/blender-xray/files/237146/bad-cube-animation.zip)
