### ISSUE TITLE
Проблема с hud-анимацией

### ISSUE THREAD

**Issue by molodoy-chelovek** [PavelBlend/blender-xray#291]
Здравствуйте. Давным-давно уже бьюсь с проблемой следующего характера: Экспортированная hud-анимация ведет себя некорректно в actor editor'e. Масштабирование костей и самого объекта применено, но вот что происходит с костями в Blender (2.81): 
![Без названия (1)](https://user-images.githubusercontent.com/33177434/72533093-3b966180-387d-11ea-9ed8-5195520ec91b.png)
А вот что в Actor Editor для CoP: 
![Screenshot_4](https://user-images.githubusercontent.com/33177434/72533159-5bc62080-387d-11ea-83d0-5cea8d8e3926.png)
Что ещё нужно сделать для правильного экспорта?

**Comment by molodoy-chelovek** [comment]
Кость топора прикреплена Child Of констреинтом к кости lead_gun, удалив скелет рук со сцены картина стала примерно такой же как в Actor Editor. Эту проблему я уже исправил с запечкой анимации, теперь в Blender (при удалении скелета рук) кости топора ведут себя так, как нужно... Но в Actor Editor картина не поменялась. Естественно я не забыл сделать ре-экспорт анимации и объекта. Вообще эта проблема у меня только с HUD анимациями, каждый раз я пытался их делать с помощью рига от Pavel Blend, и каждый раз руки ведут себя как надо, а анимируемый предмет подобным образом.
![Screenshot_6](https://user-images.githubusercontent.com/33177434/72644845-bdb88000-397a-11ea-9141-209027feb396.png)
![Screenshot_5](https://user-images.githubusercontent.com/33177434/72644685-484caf80-397a-11ea-90be-e6b4604a2569.png)
Ума не приложу что я делаю не так

**Comment by s30-zip** [comment]
Выложите модель.

**Comment by molodoy-chelovek** [comment]
[blend.zip](https://github.com/PavelBlend/blender-xray/files/4080180/blend.zip)
Прикрепляю .blend файл с аналогичной проблемой.
![Screenshot_7](https://user-images.githubusercontent.com/33177434/72661523-cc874d00-39e3-11ea-8117-76073d26049c.png)
![Screenshot_8](https://user-images.githubusercontent.com/33177434/72661524-cf823d80-39e3-11ea-8476-bc6d9d3ff33c.png)
Кстати, при импорте .skl в блендер картина идентична Actor Editor'y.

**Comment by PavelBlend** [comment]
Я пока не смотрел, файл. Так как в свободное время занимаюсь другим проектом. И, честно говоря, я пока забросил разработку и поддержку данного аддона.  Последние изменения были внесены два месяца назад. Как будет время, я изучу данную проблему и попробую её исправить. Скорее всего этим займусь на следующей неделе или немного позже.

**Comment by molodoy-chelovek** [comment]
Павел, перед тем как вы займетесь этой проблемой, хочу ещё раз уточнить: эта проблема у меня только тогда, когда я делаю HUD анимации с вашим ригом рук, и ни с чем более.

**Comment by PavelBlend** [comment]
Посмотрел я файл. Да, масштаб мешей равен 1, но масштаб арматуры не 1, а равен 0.026. Нужно применить масштаб для объекта Armature, но после этого анимации испортятся. Чтобы они не испортились, нужно изначально делать анимацию с масштабом арматуры равным 1.

**Comment by molodoy-chelovek** [comment]
Да, проблема была в этом. Спасибо большое!
