### ISSUE TITLE
Default Bone Group

### ISSUE THREAD

**Issue by Petethegoat** [PavelBlend/blender-xray#292]
Hi, thanks for a really robust addon.

I had a minor problem trying to export ogf/omf from the CoP SDK, which turned out to be because I didn't have a "default" bone group:
![image](https://user-images.githubusercontent.com/734762/72661040-87d7c380-399b-11ea-8567-67171be34084.png)
The SDK side error is not at all descriptive, so perhaps this is something the blender skl/object exporter could enforce?

**Comment by PavelBlend** [comment]
In order for the export from the SDK to the ogf / omf format to be error-free, you need to create a bone group in the blender named "default" and assign all exported bones to this group.
![02](https://user-images.githubusercontent.com/7983249/72809755-5138cc00-3c6d-11ea-8908-6c356c40de43.jpg)
