### ISSUE TITLE
Actor Editor .ogf export 

### ISSUE THREAD

**Issue by molodoy-chelovek** [PavelBlend/blender-xray#293]
Здравствуйте. Извините за столь частые обращения. 
Вообщем, на примере куба повторяю все действия с видео igelbox: https://www.youtube.com/watch?v=dXaG51wC9Ts дойдя до экспорта с Actor Editor он крашится с таким логом: 

> FATAL ERROR
[error]Expression    : assertion failed
[error]Function      : X:\stalker_addon\sources\trunk\editors\ECore\Editor\ExportSkeleton.cpp
[error]File          : X:\stalker_addon\sources\trunk\editors\ECore\Editor\ExportSkeleton.cpp
[error]Line          : 566
[error]Description   : m_Source->IsDynamic()&&m_Source->IsSkeleton()

прикрепляю .blend файл: 
[zip.zip](https://github.com/PavelBlend/blender-xray/files/4097408/zip.zip)

Скажите, пожалуйста, что я сделал не так

**Comment by PavelBlend** [comment]
Если экспортировать скелетные модели в ogf, то нужно, чтобы тип object модели был Dynamic, вместо Static. Измени в блендере xray-тип у куба, во вкладке Object, как на скриншоте:
![02](https://user-images.githubusercontent.com/7983249/72905084-ff617600-3d40-11ea-95e0-07492ddf84a5.jpg)

Вообще, надо бы сделать в плагине предупреждение, если пользователь пытается экспортировать из блендера подобные модели. Я с этой ошибкой никогда не сталкивался (или сталкивался, но не помню), так как всегда на автомате ставил тип Dynamic для скелетных моделей. Если бы знал об этой ошибке раньше, то наверное сделал бы предупреждение. А пока я не занимаюсь данным аддоном, поэтому оставлю данную issue открытой, чтобы в будущем не забыть добавить предупреждение.
