### ISSUE TITLE
Не работает экспорт .object

### ISSUE THREAD

**Issue by sheffchinski** [PavelBlend/blender-xray#295]
Даже не знаю как описать проблему, но во всех версиях блендера (2.79, 2.8, 2.82), другие версии аддона не тестил. (стоит 1.0.0)
Что делаю:
1. Импортирую объект и ничего не меняю.
2. Экспортирую объект.
3. Вуаля. Ошибка.
![6234562](https://user-images.githubusercontent.com/35099695/78089728-e9bb9d00-73d0-11ea-870a-568a87f23803.png)

**Comment by sheffchinski** [comment]
![изображение](https://user-images.githubusercontent.com/35099695/78090641-5a63b900-73d3-11ea-9127-f30900272bff.png)
в 0.9.0 тоже самое

Digest:
 Maya-SG incompatible: sharp edge adjacents has same smoothing group

Full log:
+-export-mesh(mesh='skin')
|  Maya-SG incompatible: sharp edge adjacents has same smoothing group

**Comment by PavelBlend** [comment]
У меня не получается воспроизвести ошибку. Можешь скинуть blend файл, на котором эта ошибка воспроизводится?
Экспорт должен работать на всех перечисленных тобой версиях (начиная с 2.77 и заканчивая дневной сборкой 2.83).

**Comment by PavelBlend** [comment]
Пока закрываю эту issue. Если всё таки кто-то столкнётся с этой ошибкой ещё раз и предоставит пример blend сцены, на которой воспроизводится эта ошибка, то я заново открою этот вопрос.
