### ISSUE TITLE
Не работает Target в Child Of

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#296]
#### Краткое описание проблемы:
Не возможно выбрать Target в Child Of, дабы объединить кости.

#### Описание
Выбираю wpn_hand_05.object.
![q](https://user-images.githubusercontent.com/62593770/78326845-77fd7200-75cf-11ea-813e-5182db7b8ef2.png)
![q2](https://user-images.githubusercontent.com/62593770/78326851-792e9f00-75cf-11ea-88ad-e739c8e15f35.png)
Но wpn_hand_05.object не выбирается и поле остаётся пустым.

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 2.82
 - Blender X-Ray: 1.0.0

#### Дополнительная полезная информация:
Все остальные Object'ы и Sharp'ы могут быть выбраны.
Blender файл: [untitled.zip](https://github.com/PavelBlend/blender-xray/files/4425188/untitled.zip)
Извиняюсь, если что-то было настроено неправильно.

**Comment by PavelBlend** [comment]
Нужно в режиме Pose добавить констрейнты, а не в режиме Edit. Плюс, нужно в другой вкладке указывать констрейнты (а именно вкладка Bone Constraints). На скриншотах у тебя выбрана вкладка констрейнтов для объекта и ты пытаешься указать в качестве цели этот же объект (владельца констрейнта). Вот скрин:
![01](https://user-images.githubusercontent.com/7983249/78344783-8767c580-75a5-11ea-806a-e9020efebf88.jpg)

**Comment by TheParaziT** [comment]
Благодарю!
Извините, а нормально ли то, что при переключении режимов из Edit в Pose или Object меш, который привязан к костям, начинает "прыгать" ближе к ним (костям)?

**Comment by PavelBlend** [comment]
Всё зависит от констрейнтов. Если есть IK, то да, кости могут в режиме Pose отличаться от режима Edit, даже если все транформации на нуле. Нужно в констрейнте IK менять параметр Pole Angle.

**Comment by TheParaziT** [comment]
Ещё раз благодарю.
Но теперь появилась очередная проблема. На сей раз связанная с оружием. 
Неизвестно почему, но при увеличении influence у wpn_body, оружие начинает увеличиваться.
Прошу прощения за столь долгий открытый issu'й
![r3](https://user-images.githubusercontent.com/62593770/79035538-b4565100-7c13-11ea-86f5-dc95687d328c.png)
Возможно, что это что-то связанное с неправильным размещением Origin'а костей?

**Comment by PavelBlend** [comment]
А масштаб всех костей (костей оружия и костей рук) равен 1.0, 1.0, 1.0? Если нет, то нужно сбросить масштаб. И масштаб всех объектов тоже должен быть равен 1.0. Движок сталкера не поддерживает масштаб, поэтому нет смысла его изменять. А констрейнт Copy Transforms копирует масштаб, поворот и позицию цели. Чтобы применить масштаб объектов нужно нажать Ctrl+A > Scale. А чтобы сбросить масштаб костей, нужно нажать Alt+S.

**Comment by TheParaziT** [comment]
В очередной раз благодарен вам.
Дело было действительно в этом.
