### ISSUE TITLE
Editing LEVEL file

### ISSUE THREAD

**Issue by Szabi123** [PavelBlend/blender-xray#297]
Dear Pavel!

Some time ago you showed in a video how to add an object into a map by importing and editing game level file in Blender.

Would you please tell me, for this editing process can I use the "level" file that is located in the installed game: gamedata\levels\mapname\ level ?

Or did you use a specific "level" file, that first has to be created somehow, perhaps using the SDK?

Thank you!

**Comment by PavelBlend** [comment]
Yes, you can edit levels from the `gamedata\levels` folder

**Comment by Szabi123** [comment]
Thank you!

Could I please have some more additional questions:

1. If I want to add a new object editing the level file, do I have to import it in *ogf, *obj or *object file format?
2. If I add a new object, will it have an impact on the graphics quality in the game?
3. Can I erase a tree from the level simply by selecting it and hit delete button? Or do I have to do other settings as well?

Thank you!

**Comment by PavelBlend** [comment]
1) To add a new object to a level, you can create this new object yourself or import from any format. You only need to specify the parameters and shaders correctly. From the parameters, if I'm not mistaken, I need to specify the type of object (Object Panel in Properties Window).

2) Yes, but not much. Smoothing will be lost in some areas. Geometry simplification data will also be lost (this will affect performance for the worse).

3) Yes, you can simply delete the tree (if I’m not mistaken, I haven’t used the plugin for a long time).

I think an easier way to change the level is to edit object files and then compile using xrLC. Since editing a level in a blender is not so easy. You need to know what you are doing, as the level format is a game format that has many additional settings (vertex colors, lightmaps, object type, you need to properly structure the object in a hierarchy, etc.). And if you use xrLC, then the difficulties will be less.

The level plugin was intended for converting level files from different builds of the game. But this plugin is not fully completed (there is no way to work with old builds).

**Comment by Szabi123** [comment]
Dear Pavel!

I have tried your method in the video, and it seems to work.

Please let me ask the following.

Vanilla file sizes for la24_Antennas are:
level - 1 350 KB
level.geom - 32 546 KB
level.geomx - 11 241 KB

After adding an ivy model in Blender the exported file sizes are:

level - 914 KB
level.geom - 27 637 KB
level.geomx - 7 078 KB

As you can see, after exporting the file sizes become much smaller. But what is the reason? What datas are not included in the exported level files compared to the vanilla files? 

Does this result in a graphics quality loss, and if yes, does graphics quality loss affect only the new objects, or all objects of the level entirely?

Thank you so much!

**Comment by PavelBlend** [comment]
Yes, some data is lost, namely the geometry simplification data. This does not affect the appearance, but it affects performance. Geometry simplification data is lost for all objects, and not just for those that you edited.

**Comment by Szabi123** [comment]
Dear Pavel!

Thank you very much for your help!

Please let me ask another thing.

In your previous comment you wrote, that it would be better to use xrLC. Unfortunately I don't know anything about this. Do you maybe have a video, where you show how to use the xrLC method?

Thanks again, greetings!

**Comment by PavelBlend** [comment]
You need to install the XRay SDK. I think you need the Lost Alpha SDK. But I do not know where the current version of the SDK LA is. I have never used the LA SDK.

After installation, you need to create a level in LevelEditor.

Next, make a Build level in the LevelEditor menu.

After building, you need to run xrLC using the command:

`xrLC.exe -f level_name`

**Comment by Szabi123** [comment]
Please let me ask something I don't yet clearly understand.

So there are the game "level" files in the installed map folders. This game level file can be opened in Blender, or also in SDK Level Editor, and this is the one you used in your video.

But in the installed SDK in "maps" folder there are some "*level" files, f.e. "la01_escape.level". These types of level files can also be opened in Level Editor.

My question is: what is the difference between the two "level" and "*level" file types, and which one should be used to edit and compile a level?

**Comment by PavelBlend** [comment]
level is a compressed binary file that the game reads.
*.level is the source level file, which is easy to edit using SDK.
To create a level in the SDK and compile in xrLC, you need to edit *.level files.

**Comment by Szabi123** [comment]
Thanks!

Please let me ask two more questions:

1. How are the "*level" files created? Do you have any video that shows this process?

2. In your Blender plugin I deleted some trees from a level. Using the exported level file in the game I noticed, that however the tress disappeared, but on the places where the trees originaly were there is still an invisible "wall" that I clip into and can not walk through. As if the tree trunks were invisibly still there. What causes this, and can I get rid of this somehow?

**Comment by PavelBlend** [comment]
1) *.Level files are created in the SDK. It is enough to save the scene using Ctrl + S.

2) You need to remove the geometry for collision. Visible geometry and collision geometry are two independent sets of geometry.

**Comment by Szabi123** [comment]
Can you tell me, after importing the level into Blender, where do I find the collision geometry datas that have to be removed when I want to delete a specific tree completely?

**Comment by PavelBlend** [comment]
In the outliner window, find the CForm collection. It will have geometry for the collision.

**Comment by Szabi123** [comment]
Thank you!

I will give a response if I succeed.

By the way, is there perhaps any e-mail address I could contact you directly?

**Comment by PavelBlend** [comment]
stalkermodkytia@yandex.ru

**Comment by Szabi123** [comment]
Thank you!

**Comment by Szabi123** [comment]
Dear Pavel!

Is it maybe possible, that you can show me in a short video, how do you erase a tree entirely from the level, including visible geometry and collison geometry of a tree?

**Comment by PavelBlend** [comment]
@Szabi123 I recorded a short video:
https://youtu.be/bjoDhSlA1Kk

**Comment by Szabi123** [comment]
Thank you!

I watched it several times, still a bit unclear, but I will test it and learn what is happening.

**Comment by Szabi123** [comment]
Dear Pavel!

Some time ago you created a short video about how to erase trees from a stalker level in Blender. This was the link: https://youtu.be/bjoDhSlA1Kk

I would like to watch this video again to follow instructions, but the link is no more available.

Could you please take the video back so I can watch it?

Thank you so much!
