### ISSUE TITLE
Назначение горячих клавиш на импорт

### ISSUE THREAD

**Issue by Usr-name** [PavelBlend/blender-xray#304]
Можно ли как-то назначить горячую клавишу на пункты из меню импорта? В контекстном меню нет такой возможности почему-то.

**Comment by PavelBlend** [comment]
Можно в настройках вручную назначить. В 2.8x это делается так:
- открыть меню Edit > Preferences
- перейти в категорию Keymap
- открыть свиток Window к примеру (можно и другой, но я не проверял на других)
- пролистать вниз и найти кнопу Add New, нажать на неё
- изменить значение оператора с none на любой (к примеру на xray_import.object)
- если нужен другой импорт, то нужно включить питоновские подсказки в настройках (Python Tooltips) и навести на нужный импортёр/экспортёр (в подсказке будет написан идентификатор оператора, bpy.ops писать не нужно, только то что идёт после)
- потом назначить клавишу (например, F8, другие могут не работать, если они заняты)
- сохранить настройки

**Comment by PavelBlend** [comment]
Можно попробовать сделать в настройках аддона значения горячих клавиш, чтобы вручную долго не настраивать. Оставлю этот вопрос открытым, чтобы потом не забыть реализовать это.

**Comment by PavelBlend** [comment]
Сделал горячие клавиши только для импорта/экспорта object. Для других плагинов делать не стал, так как они редко используются. Теперь можно назначать клавиши F5, F6, F7, F8 плюс можно включать Shift. Другие клавиши назначать нельзя, так как они могут вызвать конфликт с уже существующими.
![keymaps](https://user-images.githubusercontent.com/7983249/86291182-4b212100-bbf7-11ea-9ec5-05641efe8992.jpg)
