### ISSUE TITLE
Поддержка более свежей версии 2.83

### ISSUE THREAD

**Issue by Rikoshet-234** [PavelBlend/blender-xray#307]
Здраствуйте
Хотелось бы видеть поддержку свежего LTS релиза 2.83. Ещё в 2.82 было много улучшений в плане скульптинга, что хорошо помогло бы начинающим модмейкерам при создании террейна скажем, да и окружения в целом. Судя из чейнджлогов там работы вроде бы не много в сравнении с переносом на 2.80. Был бы крайне признателен если бы вы занялись поддержкой данной версии. А на счёт 2.81-2  - не вижу в них смысла так как это не LST релизы. Заранее спасибо :)

**Comment by PavelBlend** [comment]
@Rikoshet-234 привет.
Я тщательно не тестировал и пока тесты не запускал на 2.83, но вроде бы аддон должен работать в 2.83. Так как ничего вроде бы не было сломано по сравнению с 2.82. Разработчики обратную совместимость сохранили. Я даже делал тестовые уровни в 2.83, никаких ошибок не заметил.

Я думаю сейчас нужно настроить тесты на 2.83 и посмотреть, есть ли ошибки. Поэтому оставляю этот запрос открытым, чтобы не забыть это сделать.

**Comment by Rikoshet-234** [comment]
Не знаю. У меня там один крашстек за другим. С вами можно в том же дискорде сконтактироватся ? помню видел вас на одном сервере. Там и могу скинуть свои логи и показать что работает, а что нет

**Comment by PavelBlend** [comment]
@Rikoshet-234 Pavel_Blend#9966

**Comment by PavelBlend** [comment]
Сделал тесты 2.83 и 2.90 (дневная сборка). Ничего не завалилось. Так что всё должно работать и аддон поддерживается в 2.83.

@Rikoshet-234 наверное те ошибки, которые у тебя возникают, есть и в версиях раньше 2.83. Так что жду баг-репортов здесь в issues или в дискорде.

Поэтому закрываю эту issue. Для каждого бага лучше создать отделтную issue, чтобы легче было следить за ними.
