### ISSUE TITLE
Создавать группы нодов у материалов из game level

### ISSUE THREAD

**Issue by Rikoshet-234** [PavelBlend/blender-xray#310]
Смотрите в чем загвоздка: многие материалы и их структура очень часто повторяются, как здесь
![image](https://user-images.githubusercontent.com/34555340/84426296-446c4300-ac23-11ea-848b-ff22a4fc4f21.png)
так вот, вот такие пачки нодов можно объединить в группы с инпутами и аутпутами как тут к примеру
![image](https://user-images.githubusercontent.com/34555340/84426476-9a40eb00-ac23-11ea-8f00-9d9d715e72cc.png)
![image](https://user-images.githubusercontent.com/34555340/84426503-a3ca5300-ac23-11ea-8bb0-5a6fb2522952.png)
Что это дает ? Это нам позволяет модифицировать принцып работы с картами сталкера в одной нодгруппе, которая используется инстансом во всех материалах данного типа скажем (стекло, земля, вода, декали итд), не трогая каждый по отдельности что очень удобно и быстро.
Ко всему такой подход еще и сильно снижает нагрузку на блендер в больших сценах. тк функция как бы одна, но используется парралельно много где, что ускоряет и облегчает процесс рендеринга больших и сложных левелов. Следственно - работу с ними.
еще заметил что нигде не используется альфа канал третьего лайтмапа, А там - GI своего рода,запеченная АО карта
![image](https://user-images.githubusercontent.com/34555340/84427064-96619880-ac24-11ea-91d3-3d55b18021d7.png)
Вот где проблема собственно, а вот более верный вариант (ао карту перед этим прогоняю через гамму 0,4545 ибо в домах уж как то слишком темно)
![image](https://user-images.githubusercontent.com/34555340/84427333-0c65ff80-ac25-11ea-8f45-c08bc53ddd2c.png)
Вот такой сет получается, но и конечно же лучше всего это в нодгруппу запихать и раскинуть по остальным материалам 
![image](https://user-images.githubusercontent.com/34555340/84427460-39b2ad80-ac25-11ea-97c3-734fca203999.png)

**Comment by PavelBlend** [comment]
> так вот, вот такие пачки нодов можно объединить в группы с инпутами и аутпутами как тут к примеру

да, думаю это стоит реализовать. Как-то сразу, кода писал код, не пришло в голову использовать группы. Я python api групп ещё не использовал, но думаю там ничего сложного.

> еще заметил что нигде не используется альфа канал третьего лайтмапа, А там - GI своего рода,запеченная АО карта

а вот это уже недоработка импортёра. Так как карты освещения ТЧ отличаются от ЗП. На месте AO в ТЧ хранятся тени и являются дубликатом (эти тени есть как в lmap#_1 так и в lmap#_2). А в ЗП поменяли местами hemi и тени. В итоге аддон не правильно соединяет ноды для карт ЗП.

Вообще эти ноды и реализация освещения в блендере - это моя головная боль. Хотел переписать код, который создаёт эти ноды, но пока не знаю как сделать максимально компактный и эффективный код. Я сейчас подумал, и решил, что может лучше эти ноды создавать уже после импорта? Сделать кнопки в интерфейсе, которые бы создавали и удаляли эти ноды освещения. И сделать возможность менять параметры у principled шейдера (убрать блеск, добавить emission и т. д.)

Я делал импорт из билдов и в билдах нужно делать кучу вариантов освещения. В разных билдах лайтмапы влияют по разному.

**Comment by Rikoshet-234** [comment]
Вот это кстати то что хотел написать в первую очередь, но с головы вылетело. Было бы круто в эту группу еще и Principle BSDF засунуть. Что бы можно было такие вещи как глосс итд для всех материалов настраивать за раз. Ну и на худой конец сделать поддержку бампа и глосса из сталкера. Могу даже показать пример как это подрубить. В теории там еще и эррормапу можно применить и карту парралакса для дисплейсмента. Но вот на счет последнего - не уверен

**Comment by PavelBlend** [comment]
Для этой проблемы была создана отдельная issue: #345 
Поэтому я закрываю эту проблему. В новой issue собраны запросы из разных issue и относятся к одной функции.
