### ISSUE TITLE
Поддержка OMF

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#311]
#### Описание идеи:
В ветке support-omf делаю импорт/экспорт анимаций из omf файлов.

Здесь буду писать микро-задачи. На данный момент нужно сделать следующее:
- [x] импорт только boneparts из omf
- [x] экспорт только boneparts в существующий omf
- [x] добавление анимаций в существующих omf
- [x] замена анимаций в существующих omf
- [ ] ~~удаление анимаций из существующих omf~~
- [ ] ~~изменение параметров в существующих omf (в том числе изменение имени)~~
- [ ] ~~объединение существующих omf~~
- [x] параметр импорта, который отключает добавление анимаций в список
- [x] фильтр анимаций при импорте
- [x] написать тесты
- [x] добавить возможность привязать арматуру к другой арматуре (каждая кость с одинаковым именем повторяет все трансформации). Это нужно для того, чтобы не испортить порядок костей.
- [ ] ~~внедрить omf в просмотрщик в N панели~~
- [ ] ~~проигрывать omf из motion refs~~
- [x] использовать custom names при экспорте

И вот список проблем/ошибок на данный момент:
 - [x] не правильно указывается анимация в списке, если имя этой анимации уже существует в сцене
- [x] создать класс ImportContext вместо передачи большого количества параметров в функции
- [x] возвращать арматуру и анимацию после всех манипуляций в исходное состояние
- [x] исправить экспорт boneparts only в режиме replace

#### Примеры использования:
Иногда не желательно конвертировать omf в skls. Нужно редактировать omf, так как некоторые skls имеют тысячи анимаций (stalker_animations). Ещё при конвертации в skls теряется информация о bone parts. Эти bone parts нужно импортировать из omf.

#### Update:
Зачёркнутые пункты реализовать позже и создать для них отдельные issue. Всё это касается OMF редактора в блендере.

**Comment by s30-zip** [comment]
А такая штука, мне нужно было уменьшить длину одной анимации, я импортировал модель ogf, импортировал stalker_animation.omf, у нужной мне анимации уменьшил длительность (смаштабировал ключи) и экспортировал в omf - в игре жесть, все сталкеры используют неожиданные анимации, то есть как-будто порядок анимаций в массиве поменялся ( подхожу к Волку, а он облокотился об воздух и стоит как пъяный, новички вместо сидения просто падаю на землю лёжа и др.) Надеюсь это не очередной сбой блендера у меня.
