### ISSUE TITLE
OMF редактор

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#315]
#### Описание идеи:
Плагин omf почти готов. В этом вопросе обсуждение возможностей импорта/экспорта: #311 
В том же вопросе описаны возможности по редактированию omf. Вот список:

- [ ] удаление анимаций из существующих omf
- [ ] изменение параметров в существующих omf (в том числе изменение имени)
- [x] объединение существующих omf
- [ ] разделить omf на несколько файлов

#### Примеры использования:
Пригодиться для быстрого редактирования omf (параметры поправить, удалить анимацию и т. д.)

**Comment by s30-zip** [comment]
Сейчас изменение  анимаций массива omf и экспорт в omf не должен работать корректно? Просто я поменял длину одной и экспортировал , и в игре все сталкеры используют неожиданные анимации, то есть как-будто порядок анимаций в массиве поменялся.

**Comment by PavelBlend** [comment]
@s30-zip да, должен работать. Но я пока не могу воспроизвести такое поведение. Можешь дать файлы, на котором воспроизводится ошибка? И какие параметры при экспорте использовались? И какая версия игры, блендера, аддона?

**Comment by s30-zip** [comment]
[stalker_animation.zip](https://github.com/PavelBlend/blender-xray/files/7636026/stalker_animation.zip)   
Тут я ничего даже не менял. При экспорте "перезапись" и галка на "bone_parts", сталкер - тень, 6 патч, блендер - 2.79, аддон - 2.5

**Comment by s30-zip** [comment]
А вот если экспортировать в ogf, то модель работает с правильными анимациями.

**Comment by PavelBlend** [comment]
@s30-zip ошибку получилось воспроизвести. Для этого нужно было использовать 2.79, а не 2.93, как я до этого делал. Но код в 2.93 идентичен 2.79. Без понятия, почему в 2.7 не работает экспорт. Буду выяснять.

Создал отдельную issue: #444

**Comment by PavelBlend** [comment]
В окно `3d viewport` в `N` панель во вкладку `OMF Editor` добавлен оператор `Merge OMF`.
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/c3bbe4a5-bff7-4c3e-a395-6c483bc05de2)

После вызова этого оператора появится файловый браузер, в котором нужно выделить несколько `omf` файлов (поддерживается объединение более 2 файлов за раз).
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/3654614e-5172-43ea-b9f0-1d5b6eecf356)

После нажатия кнопки `Merge OMF` в файловом браузере, аддон объединит файлы и откроется второй файловый браузер, который позволит указать путь к `omf` файлу, в который запишется результат объединения `omf`.
![03](https://github.com/PavelBlend/blender-xray/assets/7983249/68ba0651-1b10-414d-9659-a1046f1671ad)

**Comment by PavelBlend** [comment]
Лучше реализовать в отдельной программе, как #553
