### ISSUE TITLE
Уменьшить количество версий blender для тестирования

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#321]
#### Описание идеи:
Удалить поддержку тестов для blender 2.77, 2.78, 2.80, 2.81, 2.82. Так как в плане python api у них нет различий от 2.79/2.83. Нужно оставить поддержку тестов для 2.79, 2.83.

#### Примеры использования:
Будет расходоваться меньше времени на тесты. Если тесты не завалятся на 2.83, то они будут работать и на 2.80-2.82. И сейчас мало кто использует все эти версии блендера.

**Comment by Rikoshet-234** [comment]
Здраствуйте, для 2.80 тоже желательно я считаю, ибо некоторые аддоны только для нее есть. на новые версии не переносятся и можно весь воркфлоу запороть конкретно. Что создаст неудобства при создании локаций к примеру

**Comment by PavelBlend** [comment]
Привет. А какие именно аддоны? По-моему api в 2.81, 2.82, 2.83 не на столько сильно изменён, что аддоны перестанут работать.

**Comment by Rikoshet-234** [comment]
у меня к примеру TexTools, UVpackmaster, EasyHDRI и еще несколько отваливалсь часто на 2.83. думаю для 2.80 можно хотя бы какое то время позаорачиватся. ну а на счет остальных тут я полностью согласен

**Comment by PavelBlend** [comment]
ну тогда пусть будут эти тесты пока. Раз 2.80 используется. Они только время выполнения добавляют, а так никому не мешают. В общем если версий станет больше (2.90, 2.91, ...), тогда стоит возобновить эту issue.
