### ISSUE TITLE
Дублирование пункта компактного меню импорта\экспорта при выборе\создании нового пресета настроек путей аддона

### ISSUE THREAD

**Issue by Rikoshet-234** [PavelBlend/blender-xray#335]
Здравствуйте. Используя последний релиз аддона (1.2.0) на версии 2.83.3, я столкнулся с вот такой проблемой при манипуляциях с пресетом настроек самого аддона:
![image](https://user-images.githubusercontent.com/34555340/88482374-2e131000-cf61-11ea-922d-24ff979799aa.png)
В общем как видно пункт компактного меню сдублировался при создании нового пресета под сдк:
![image](https://user-images.githubusercontent.com/34555340/88482400-5ac72780-cf61-11ea-93f7-3a82c5b6cc4d.png)
При создании нового пресета пункта уже три 
![image](https://user-images.githubusercontent.com/34555340/88482429-77635f80-cf61-11ea-8648-696745bf24d2.png)
![image](https://user-images.githubusercontent.com/34555340/88482440-84804e80-cf61-11ea-83de-b948d80244f9.png)
Когда сменил пресет и закрыл окно настроек блендера сохранив параметры их стало уже 4
![image](https://user-images.githubusercontent.com/34555340/88482504-de811400-cf61-11ea-8070-140c07f71a4b.png)
в общем весело :) 
В 2.80 точно такие же проблемы

**Comment by Rikoshet-234** [comment]
НО, если закрыть и открыть блендер после манипуляций то все на местах, при том что твои настройки аддона такие же как до закрытия блендера. UI bug одним словом

**Comment by Rikoshet-234** [comment]
После открытия блендера наново с пресетом настройки не сохраняются. все полностью слетает

**Comment by Rikoshet-234** [comment]
Правда в 2.83.3 все остается на своих местах, за исключением того что используется дефолтный пресет с настройками предыдуще выбранного (по видимому)
![image](https://user-images.githubusercontent.com/34555340/88482935-c2cb3d00-cf64-11ea-9d95-14c73c2c823f.png)

**Comment by PavelBlend** [comment]
@Rikoshet-234 исправил. Можешь качать последний коммит из ветки develop.
