### ISSUE TITLE
Невозможно импортировать HUD модель.

### ISSUE THREAD

**Issue by Lambda-logo** [PavelBlend/blender-xray#336]
#### Краткое описание проблемы:
Не могу импортировать HUD модель оружия из мода MISERY 2.1 (https://www.moddb.com/mods/stalker-misery/downloads/misery-2-1)

#### Как воспроизвести ошибку:
Вот скриншот: https://i.imgur.com/gpWv6Vy.png

#### Ожидаемое поведение:
Импортирование HUD модели как на этом видео: https://www.youtube.com/watch?v=xZ12xVqXZzE

#### Версии ПО:
 - OS: Win10 x64
 - Blender:  2.83.3

#### Дополнительная полезная информация:
Я не создавал раньше ничего для Сталкера, так что скажу так: модель, отображаемая от  третьего лица загружается без проблем (за исключением отсутствия сглаживания) а HUD модель (как я понял, это модель оружия от первого лица) загружается как обыкновенная (естественно с ошибками). Модель была взята из модификации "MISERY 2.1", мод для "
S.T.A.L.K.E.R.: Зов Припяти" но при выборе соответствующего параметра (для импорта модели) всё ровно нет сглаживания.

**Comment by PavelBlend** [comment]
@Lambda-logo можешь скинуть отдельно модель? Мне долго скачивать более 1 ГБ.

**Comment by s30-zip** [comment]
проверил в 2.81 не работает пример:
https://drive.google.com/file/d/14EQ9yNLmfZ-KiBlzfqw3vxI9MjKt8yld/view?usp=sharing

**Comment by PavelBlend** [comment]
Перезалил модель сюда, чтобы не потерять:
[wpn_stg44_hud.zip](https://github.com/PavelBlend/blender-xray/files/5760080/wpn_stg44_hud.zip)

Только сегодня начал смотреть и изучать эту ошибку, так как до этого сталкером/моддингом не занимался.

У меня при импорте нет ошибок. Модель импортируется. Да, сглаживания у модели нет. Но, возможно авторы модели сглаживание не добавляли, поэтому в блендере не откуда сглаживанию появиться. Хотя я лучше позже проверю это точно.

![01](https://user-images.githubusercontent.com/7983249/103455137-54e92580-4cfb-11eb-8318-45a883f776f4.jpg)

@Lambda-logo что ты имеешь в виду под?:

> Не могу импортировать HUD модель

Модель всё таки импортируется, но высвечивается окно ошибкой? Или в 3д окне вообще нет модели?

Если при импорте появляется такое окно:
![02](https://user-images.githubusercontent.com/7983249/103455157-8c57d200-4cfb-11eb-9ceb-2dd9daa234dc.jpg)
то это ещё не значит, что модель не импортировалась. Это не ошибка, а предупреждение.
`Duplicate faces found` означает, что в модели есть недопустимые полигоны. Дубликаты полигонов. Которые опираются на одни и те же вершины.

**Comment by PavelBlend** [comment]
Проверил сглаживание. В модели всего 4194 треугольников. А групп сглаживания 806. Можно сказать в среднем в одной группе сглаживания 5 треугольников. Так и получается, что модель практически не сглажена.

**Comment by PavelBlend** [comment]
Закрываю этот вопрос. Если проблема не в предупреждении `Duplicate faces found`, то откройте заново эту проблему.

**Comment by s30-zip** [comment]
открылась в 2.90.1, но что-то хочу сделать clear sharp помеченным острым граням и вылазят артефакты, может и не связано с плагином

**Comment by PavelBlend** [comment]
@s30-zip можешь скриншот показать? У меня артефактов нет.

**Comment by s30-zip** [comment]
https://yadi.sk/i/SY7X9KfcE0j7Gg

**Comment by s30-zip** [comment]
блин, тут чего то в 2.79 ещё не экспортирует, пути слетели https://yadi.sk/i/LbeDKWOg1liSKw

**Comment by PavelBlend** [comment]
Нужно в объектном режиме нажать ПКМ и выбрать Shade Smooth. Это просто полигоны не сглажены. При импорте импортёр делает треугольники не сглаженными, если все три его ребра помечены как sharp. Хотя смысла в этом я особо не вижу. Сейчас проверил, можно сделать все полигоны сглаженными. Чтобы при удалении sharp edges весь меш был сглаженным.

**Comment by s30-zip** [comment]
я имел ввиду тот чёрный полигон что ли, который появляется после очистки острорёбер

**Comment by PavelBlend** [comment]
@s30-zip а, я чёт быстро посмотрел, думал это чёрный треугольник от камеры. А это так модель отображается. А какая у тебя видеокарта? Старая? У меня на моей старой видеокарте тоже были глюки, но не у полигонов, а у частиц. Но их уже нет, исправили. Может у тебя устаревшая видеокарта? Или драйвера может поновее скачать с официального сайта?

У меня такого нет.

**Comment by s30-zip** [comment]
[wpn_usp45.zip](https://github.com/PavelBlend/blender-xray/files/5762113/wpn_usp45.zip)
попробуй этот пистоль в 2.9 импортировать, у меня, там каша получается, хотя в 2.79 норма

**Comment by s30-zip** [comment]
ну карта старовата nv gt240

**Comment by PavelBlend** [comment]
> попробуй этот пистоль в 2.9 импортировать, у меня, там каша получается, хотя в 2.79 норма

у меня всё без глюков в 2.90. Никаких чёрных треугольников. Хоть с sharp рёбрами, хоть без. Наверное это блендер не поддерживается на этой карте.

> ну карта старовата nv gt240

сейчас нагуглил. Это карта 2009 года получается? Я думаю, что даже если написать разработчикам блендера багрепорт, то они его не исправят, так как у них нет такой конфигурации, чтобы воспроизвести ошибку.

**Comment by PavelBlend** [comment]
> блин, тут чего то в 2.79 ещё не экспортирует, пути слетели

посмотрел. Пути не отображаются в настройках, потому что я в интерфейсе начал использовать недопустимую иконку, которой нет в 2.79. Сейчас исправлю.

**Comment by s30-zip** [comment]
ясно, спасибо, а насчёт не возможности указать settings presets в 2.79 нет мыслей, немного выше об этом писал?

**Comment by s30-zip** [comment]
ясно, спасибо!
