### ISSUE TITLE
Не корректный экспорт моделей из game level в формат fbx

### ISSUE THREAD

**Issue by duppehnsk** [PavelBlend/blender-xray#337]
#### Краткое описание проблемы:
При экспорте level в fbx теряются материалы

#### Как воспроизвести ошибку:
1. Импортировать любой level
2. Проверить в шейде их наличие
3. Экспортировать в .fbx
4. Импортировать созданную fbx модель

#### Версии ПО:
 - OS: Win10 Pro 64bit 1909
 - Blender: 2.82

#### Дополнительная полезная информация:
Изначальный материал prop_sigarets становится - prop_prop_sigarets в  fbx модели

**Comment by PavelBlend** [comment]
@duppehnsk я думаю это недостаток fbx плагина. Это поведение не зависит от blender-xray аддона. Я не знаю, каким способом fbx аддон указывает текстуры. Видимо аддон не сохраняет их, если в материале их больше одной. Чтобы это исправить, нужно подстраивать blender-xray аддон под fbx аддон. Создавать инструменты для удаления лишних текстур и прочих шейдерных нодов. И напрямую подсоединять текстуры к сокету Principled шейдера.

**Comment by PavelBlend** [comment]
Я хочу сделать импорт level так, чтобы он не создавал кучу нодов для карт освещения. Нужно создать один нод для основной текстуры. Если так сделать, то level можно будет экспортировать в другой формат без ошибок и потери текстур. Создавать ноды для карт освещения нужно не во время импорта, а с помощью оператора в любое время. И нужно добавить оператор для удаления всех этих нодов. Эта проблема частично описывалась здесь: #310

Так что я закрываю эту проблему, так как для данной проблемы была создана отдельная issue: #345
