### ISSUE TITLE
Сломанное сглаживание(смузгруппы) при импорте .object файла созданного в 3ds max скриптами от Den Stash

### ISSUE THREAD

**Issue by Rikoshet-234** [PavelBlend/blender-xray#338]
Здраствуйте. 

У меня возникла проблема с импортом .object-ов созданных через скрипты для макса. при импорте сглаживание ломается а весь мэш в хардэджах:
![image](https://user-images.githubusercontent.com/34555340/89009790-a553f580-d30d-11ea-8147-011ef1a0bf74.png)
![image](https://user-images.githubusercontent.com/34555340/89009808-af75f400-d30d-11ea-89b6-12b91f4f67ac.png)

Здесь у меня блндер 2.80. но и в более новом 2.83 наблюдается точно такая же ситуация.
Просто интерено, это проблема скриптов 3д макса или все же с аддоном что то не так.

Так же прикрепляю архивом те 2 .object-а для тестов. Здесь тч и зп форматы:
[soc_and_cop_formats_from_3dsmax.zip](https://github.com/PavelBlend/blender-xray/files/5005617/soc_and_cop_formats_from_3dsmax.zip)

Кроме того оригинальный мэш в .fbx:
[FNX_full_2.zip](https://github.com/PavelBlend/blender-xray/files/5005620/FNX_full_2.zip)

**Comment by PavelBlend** [comment]
@Rikoshet-234 привет. Я проверил на последнем коммите аддона эти модели. В итоге получил такой же результат, как в сдк. Вот скрины твоих моделей в сдк 0.4 и сдк 0.7:
![soc](https://user-images.githubusercontent.com/7983249/94335215-b144f680-ffe2-11ea-86a2-3833445383ec.jpg)
![cop](https://user-images.githubusercontent.com/7983249/94335220-b4d87d80-ffe2-11ea-85d1-3644120125f5.jpg)
В блендере у меня модели выглядят так же.

Возможно скрипты от Дена не правильно сглаживание сохраняют. И какой версией пользуешься? И попробуй импортировать эти модели обратно в макс. Какое будет сглаживание?

Результат в блендере выглядит глючно, но и в сдк тоже глючно.

**Comment by Rikoshet-234** [comment]
Скорее всего так и есть, но тут я еще одну проблему заметил - нет возможности экспортировать модель с кастомным сглаживанием. то есть аддон его всегда по шарпам пересоздает и не сохраняет кастомные вектора нормалей что крайне плохо тк не позволяет взять любую модель с любым сглаживанием и запихнуть без изменений в сдк и следственно в игру. 

Посмотри как будет время последние 2 коммита в данном репо ( ___ ), тут думаю то что нам нужно. 
Ибо генерировать каждый раз сглаживание одним и тем самым алгоритмом по шарпэджах или еще чему то это ровно тому что просто убить оригинальное, к которому были запечены карты нормалей которые теперь ему не соответствуют и в игре из за этого оно битое. 

Я к примеру специально на пыс модели вертел отдельные вектора нормалей через ALT+N\\Rotate что бы потом экспортировать такое сглаживание в игру. после экспорта сглаживание пересоздалось по новой а мои правки не дали никакого результата, что плохо. ибо к примеру если мы берем откуда то модель с инным сглаживанием, сделанным вручную, но не на шарпэджах то аддон его при экспорте просто поломает. в общем нам нужно именно сохранение векторов которые идут изначально, если есть такая возможность

**Comment by PavelBlend** [comment]
@Rikoshet-234 аддон из репо StalkMen сохраняет нормали вершин. Но ни один сдк (кроме ихнего) эти нормали не сможет прочитать. Для начала нужно научить сдк чтение нормалей. Изначально формат object вообще не может хранить информацию о нормалях вершин.

На данный момент аддон может сохранять сглаживание двумя способами: на основе Sharp Edges и на основе сглаживания с помощью Auto Smooth Angle или на основе кастомных нормалях. При экспорте нужно указывать этот параметр:
![01](https://user-images.githubusercontent.com/7983249/94677767-220f4a00-0326-11eb-9a10-15d53155779c.jpg)
