### ISSUE TITLE
Does this plugin import normal (bump) maps?

### ISSUE THREAD

**Issue by mdkdy** [PavelBlend/blender-xray#339]
I imported X-Ray game level, for example `l07_military` from SoC gamedata. Then i exported it to `obj `  with material writing to use in my homemade engine. In `mtl ` file there are albedo textures, but there are no normal maps.
 - OS: Win7 x64
 - Blender: 2.83

**Comment by Rikoshet-234** [comment]
No, you need to import it to blender manualy if you want. And one moment, thats not an Albedo, its diffuse because xray uses legacy blinn-phong lighting model and so on... So, you need to apply normalmap's manualy to your scene if you need them

**Comment by mdkdy** [comment]
Ok, I see, I can edit mtl file myself, a little repetitive work. Thanks.
