### ISSUE TITLE
No normal maps in materials

### ISSUE THREAD

**Issue by ZaDarkSide** [PavelBlend/blender-xray#341]
I know STALKER uses `texture_name_bump.dds` and `texture_name_#bump.dds`

For normal maps uses `texture_name_bump.dds`, to convert this to a normal map you need to swap the color channels:

- Red channel is a specularity map and can be ignored
- Green channel becomes Blue channel
- Blue channel becomes Green channel (you must invert the colors)
- Alpha channel becomes Red channel

If you swap out the channels you will get a normal map that you can use in Blender

**Comment by PavelBlend** [comment]
Why load normal maps into blender? To render and make a video? If so, this request will have low priority.

**Comment by ZaDarkSide** [comment]
Actually I use Blender to export via GLTF 2.0 to Unity and Godot game engines so I can move around the levels and play around with the models. So the level looks like crap because it's missing the normal maps.

**Comment by PavelBlend** [comment]
The blender-xray addon is primarily intended for modders using the xray engine. Therefore, this problem will be of low priority. There is no need to load normal maps to create models for the xray engine.

**Comment by ZaDarkSide** [comment]
Okay, I understand make it low priority.

**Comment by PavelBlend** [comment]
Этот запрос функции теперь описан здесь: #345 
Так что я закрываю эту issue.
