### ISSUE TITLE
Добавить Forest Generator из 3Ds Max.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#343]
#### Описание идеи:
Добавить Forest Generator из X-Ray Tools для 3Ds Max за авторством Dan Stash.

#### Примеры использования:
В зазеленении больших локаций. Вот, например, Агропром [расширяю](https://drive.google.com/file/d/1CH7W8IqcMRzT4PkFf_hF1c-g8MOpqT1S/view?usp=sharing), и хотелось бы всё это зазеленить в пару кликов %).

**Comment by SamArtGit** [comment]
Ну и как нибудь за это вспомнить если будет скучно, одиноко и нечем заняться.

**Comment by TheParaziT** [comment]
@SamArtGit по-моему легче поискать другие аддоны, которые это делаю. Как по мне, в аддоне это как-то не особо нужно (можно было бы конечно извертеться и сделать загрузку моделей деревьев из указанной в Preference папке или типо того)

**Comment by PavelBlend** [comment]
Я думаю, что такую возможность лучше не добавлять в аддон. Есть геоноды, у них больше возможностей. Есть другие инструменты. Аддон выполняет функцию импорта/экспорта и предоставляет инструменты для изменения параметров (что облегчает работу при редактировании моделей из сталкера). А остальные возможности по созданию моделей не относятся к задачам аддона.

Я хочу добавлять в аддон только те возможности, без которых трудно обойтись, которые решают проблемы, возникшие из-за импорта/экспорта и которые не являются общими проблемами, а касаются только сталкера. Например, кнопки для редактирования лимитов костей, кнопки для быстрого редактирования сталкеровских свойств и т. д. И не хочется добавлять ещё большое количество кода, так как аддон будет трудно поддерживать.

Поэтому я не буду делать эти возможности и закрою issue.
