### ISSUE TITLE
Доделать импорт/экспорт OGF

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#344]
#### Описание идеи:
Импорт/экспорт OGF напрямую.

#### Примеры использования:
Не использовать конвертер Бардака для импорта и SDK для экспорта.

**Comment by s30-zip** [comment]
При импорте ogf объекта в версии блендер 2.79 ошибка :
  armature.display_type = 'STICK'
AttributeError: 'Armature' object has no attribute 'display_type'

**Comment by PavelBlend** [comment]
@s30-zip исправил. Добавил релиз 2.0.1.

**Comment by s30-zip** [comment]
При импорте ogf не импортируются bone parts в виде групп костей. Только из ТЧ  худ "дэфолт" создаётся.

**Comment by PavelBlend** [comment]
@s30-zip у персонажей нет в ogf файле bone parts. Они есть у оружия и монстров. Так как оружие и монстры анимации хранят в ogf файле. А персонажи - в omf файле. Все bone parts записаны там же, где хранятся анимации. Если в файле анимаций нет, а есть только motion references, то bone parts движок считывает из omf файла, а не ogf. Анимации и bone part - это неразрывные вещи. Скорее всего отдельный omf файл может иметь свои bone parts, которые отличаются от тех, что в других omf.

**Comment by PavelBlend** [comment]
@s30-zip чтобы импортировать bone parts для персонажей, нужно воспользоваться импортом omf с включённой галочкой `Import Bone Parts` и с выключенной `Import Motions`.

**Comment by s30-zip** [comment]
Меня сбило с толку, то что я сначала импортировал персонажа и сдк (X-Ray CoP SDK\editors\rawdata\objects\dynamics\actors\stalker_neutral\stalker_neutral_1.object)  и там почему-то были группы хотя анимаций не было, а потом я взял ogf и там этих групп не было и я подумал что это баг.

**Comment by FeelFried** [comment]
При экспорте ogf экспортируется только первый материал модели ( если их несколько )

**Comment by PavelBlend** [comment]
@FeelFried я это знаю. Писал об этом баге здесь: #257
Но ogf экспортёр - экспериментальная возможность. Его никто пока не дорабатывает. Он появился на ранней стадии разработки аддона и давно глобально не обновлялся.

Чтобы при экспорте было более одного материала, нужно разделить объект на части так, чтобы каждый объект имел только один материал. Много-материальные меши не правильно экспортируются. Поэтому нужно разделить меш с помощью P > Separate by Materials в режиме редактирования. И возможно нужно будет удалить неиспользуемые материалы после разделения меша.

**Comment by FeelFried** [comment]
@PavelBlend понял, принял, и спасибо за шикарный плагин! \\(^o^)/

**Comment by s30-zip** [comment]
не знаю на что влияет этот параметр, но не выставляется длина у всех костей при импорте ogf и разный параметр Y относительно object , но при импорте ogf это правильные данные я так помню, поскольку  иначе колени выворачивались в другую сторону при рэгдоле
![primer](https://user-images.githubusercontent.com/30635540/138223353-d9e9a807-4b2b-4a1f-a9f4-1e52ca89b081.jpg)
![primer2](https://user-images.githubusercontent.com/30635540/138223363-440abd02-2a0b-4e8b-8cf6-baa94ab77347.jpg)

**Comment by PavelBlend** [comment]
@s30-zip я сам не знаю, на что влияет длина. В ogf файлах этого параметра нет.

По поводу лимитов:
какой конвертер ты используешь? Нужно использовать с этим фиксом:
https://github.com/abramcumner/xray_re-tools/commit/3604e6b2cfdc3df1370e3215acbe5e2659696ddf

Скачай последнюю версию конвертера из этого репозитория:
https://github.com/abramcumner/xray_re-tools/releases/tag/0.2.1

И лимиты будут одинаковыми как для ogf так для object.

В движке лимиты используются в физическом движке ODE. И этот движок имеет другую систему координат. Поэтому при конвертации ogf в object конвертер должен менять местами значения лимитов. Но в старых версия конвертер этого не делал.

**Comment by s30-zip** [comment]
Хорошо.

**Comment by s30-zip** [comment]
Такая штука при импорте .ogf и сразу экспорте в .object
![primer](https://user-images.githubusercontent.com/30635540/138895936-47587328-0b0b-40a5-8f89-6e15aebae94b.jpg)

**Comment by PavelBlend** [comment]
@s30-zip а на какой версии аддона эта ошибка?

**Comment by s30-zip** [comment]
2.3, поставил 2.5 также

**Comment by PavelBlend** [comment]
@s30-zip тогда файл ogf можешь скинуть? Я сейчас импортировал с помощью 2.5.0 из тч`gamedata\meshes\actors\novice\green_stalker_5.ogf` потом сделал экспорт в `object` и ошибки не было.

**Comment by s30-zip** [comment]
Ерунда какая-то, сейчас пробую - нормально и на 2.3 и 2.5  ( аномалия )

**Comment by s30-zip** [comment]
Блендер 2.79, аддон 2.6. Не экспортирует в OGF динамический объект, меш которого имеет более одного материала, это какая-то заглушка?
![untitled2](https://user-images.githubusercontent.com/30635540/144790108-8bf25edc-b167-4d2e-9e5f-ebaa2dc5290f.jpg)
[TEST_CUBIKI.zip](https://github.com/PavelBlend/blender-xray/files/7658116/TEST_CUBIKI.zip)

**Comment by PavelBlend** [comment]
@s30-zip да. Это известное ограничение. Формат ogf не поддерживает меши с более чем 1 материалом. Во время экспорта  много-материальные меши нужно разделять на отдельные одно-материальные объекты. Но этот код для разделения никто не писал. Поэтому пока только так.

Я хочу в будущем исправить это ограничение, чтобы аддон автоматически разделял меши.

Если нужно сделать экспорт объекта у которого много материалов, нужно разделить его вручную так, чтобы каждый объект имел только один материал. А потом все полученные объекты привязать родительской связью к одной root-арматуре. У самих мешей параметр object нужно отключить.

Можешь импортировать существующие ogf и посмотреть как они устроены. Например, файл `gamedata\meshes\actors\bandit\stalker_bandit_1.ogf`. Этот файл можно обратно экспортировать в ogf без каких либо изменений. Он уже корректен для экспортёра ogf.
