### ISSUE TITLE
Как избавится от второй UV развёртки, чтоб иметь возможность экспорта

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#366]
Ошибка : "Object "l06_generators_terrain.object" has more than one UV-map" , я так понял какой-то материал имеет текстуру с другой развёрткой , как можно узнать какой это из кучи материалов?Можно ли сделать поиск этих материалов по UV  или назначать всем текстурам одну из развёрток?  Возможно я что-то не так понял?

**Comment by PavelBlend** [comment]
@s30-zip объект `l06_generators_terrain.object` имеет меш, который хранит более одной юви карты. Аддон не знает, какую именно юви карту экспортировать. Нужно удалить лишние юви. Для этого нужно выбрать объект `l06_generators_terrain.object`, перейти во вкладку с настройками меша и удалить юви из списка:
![multiple_uvs_warrning](https://user-images.githubusercontent.com/7983249/106394309-0bc8e600-640d-11eb-8931-bc7110dca1e6.jpg)


Юви к материалу не привязана. И к текстуре тоже. В нодах может вообще отсутствовать нод `UV Map`.

**Comment by s30-zip** [comment]
Ясно, чего-то я не допетрил, просто несколько пар часов правил потяжки локации и на экспорте такой облом у меня паника случилась. Вопрос закрыт. Спасибо!
