### ISSUE TITLE
Не правильно записываются размеры шейпов для костей.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#370]
#### Краткое описание проблемы:
Записываются размеры с минусами перед каждым из показателей размеров шейпа.

#### Как воспроизвести ошибку:
[Объекты и blend. файлы](https://drive.google.com/drive/folders/1NnoaY2RQvExyupMlCwYfw04_IiXTm6l-?usp=sharing)

1. Импортируем "любой статический.object" (я брал из исходников) с параметрами: CoP или SoC (в зависимости от объекта).
2. Создаем Single Bone.
3. Делаем её родителем для ранее импортированного объекта With Automatic Weights.
4. Можно проверить правильно ли сгенерировались веса.
5. Включаем Display Bones Shapes во вкладке со скелетом.
6. В режиме позирования/редактирования скелета выделяем кость и в соответствующем разделе где X-Ray Engine: Bone, Shape Type меняем None на то что вам надо (я выбирал Sphere и Box).
7. Потом нажимаем Edit Shape, Fit Shape, Apply Shape.
8. И перед экспортом выходим из режима позирования/редактирования для скелета, переключаемся на вкладку Object Properties для него, в X-Ray Engine: Object выбираем Object, и в Type Static меняем на Dynamic.
9. Экспортируем с теми же параметрами что и импортировали.

#### Ожидаемое поведение:
Записывать размеры без минусов.

#### Версии ПО:
 - OS: Win10 x64.
 - Blender: 2.91.2, blender-xray-1.5.0 (Level Normals).

#### Дополнительная полезная информация:
Замечено пока только при создании костей с нуля. Есть ли такое при добавлении уже существующему скелету не проверял.

**Comment by PavelBlend** [comment]
@SamArtGit да, есть такое. Буду выяснять в чём причина.

Вот залил маленький пример:
[bone_shapes_scale_test.zip](https://github.com/PavelBlend/blender-xray/files/5971030/bone_shapes_scale_test.zip)

Нужно экспортировать в *.object объект `bone_shapes_scale_test`.

**Comment by PavelBlend** [comment]
@SamArtGit исправил. Только уже сохранённые файлы всё равно будут неправильно экспортироваться. Так как эта ошибка исправлена для новых шейпов. Те шейпы, которые уже сохранены в сценах, имеют неправильный масштаб.

Можно сделать костыль, чтобы аддон инвертировал масштаб, если он отрицательный. Позже сделаю.

**Comment by PavelBlend** [comment]
Что-то не пофиксилось. Через раз значения положительные. Сейчас буду заново искать причину.

**Comment by PavelBlend** [comment]
@SamArtGit всё, должно работать правильно. Если что-то ещё всплывёт, пиши. Я пока ошибок не вижу.
