### ISSUE TITLE
Изменять положение оружия ТЧ и CS/CoP в конфиге через Blender

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#371]
#### Описание идеи:
Загружать/изменять/сохранять положение оружия в конфиге, через этот плагин в Blender, как для ТЧ с его сшитыми руками/оружием, так и для CS/CoP с отдельными мешами и анимациями для оружия/рук.

#### Примеры использования:
В некоторых модах с правлеными движками есть такая опция в игре через консоль. Но хотелось бы напрямую: как настроил всё в Блендер, чтобы сразу так было и в игре.

Хотелки пользователей растут с каждым разом. Не успеваешь доделать одно, просят сделать другое :)

**Comment by PavelBlend** [comment]
@SamArtGit да, было удобно. Но есть проблема:
формат object позволяет хранить трансформации объекта (позиция и вращение). Вот в AE эти параметры:
![ae_transforms_properties](https://user-images.githubusercontent.com/7983249/107760161-6251f080-6d3a-11eb-8fed-e4cbf50eba2b.jpg)

Но формат ogf не поддерживает этих трансформаций. Получается при экспорте в ogf эти трансформации применяются. Но они применяются не к полигонам, не к костям, а к ключам анимаций.

Все object файлы, которые получены путём конвертации конвертером бардака имеют нули в этих трансформациях. Но объекты из слива исходников от gsc (которые являются результатом экспорта из max, maya, lightwave, и редактированы в AE) или при экспорте из blender'а могут иметь отличные от нуля трансформации.

Из-за этого есть конфликт. Вот на скриншоте зелёная модель - это исходник object до конвертации в ogf, а жёлтая модель - результат конвертации ogf в object конвертером бардака. Это одна и та же модель. ogf получена из зелёной модели, а потом этот ogf был сконвертирован в object (жёлтая модель):
![transforms_abakan](https://user-images.githubusercontent.com/7983249/107760930-9b3e9500-6d3b-11eb-9e88-9694b65c0403.jpg)

У этих моделей разные анимации. Вот одна и та же анимация:
![abakan_test_anim](https://user-images.githubusercontent.com/7983249/107761249-1acc6400-6d3c-11eb-8a26-34a510e436d3.jpg)
Видно, что глобальные трансформации костей совпадают, но локальные трансформации не совпадают. Стоит обнулить все трансформации у скелетов и будет это:
![abakan_test_anim_2](https://user-images.githubusercontent.com/7983249/107761365-4b140280-6d3c-11eb-9871-e242b6f05836.jpg)

Вот что нужно вписать в конфиг оружия? И откуда брать эти значения? Из Location и Rotation объекта блендера? Но эти параметры уже используются для экспорта в object (см. первый скриншот, AE Transform Position и Rotation).

Правильно настроить конфиги оружия получится только в том случае, если перед экспортом в object обнулить все трансформации объектов (т.е. в AE параметры в Transforms будут нулями). А если вдруг пользователь забудет это сделать, то в игре будет неправильный результат.

Вот к примеру в блендере объект имеет такие трансформации:
![blender_transforms_abakan](https://user-images.githubusercontent.com/7983249/107762014-62072480-6d3d-11eb-859f-08f8ec0d3b22.jpg)

При экспорте в object сохранится это:
![ae_transforms_abakan](https://user-images.githubusercontent.com/7983249/107762059-74815e00-6d3d-11eb-91a5-540c7d2501a4.jpg)

А при экспорте в ogf эти трансформации применятся к ключам анимаций, и вдобавок я в конфиги оружия впишу значения из блендера. Получается оружие будет иметь двойное смещение. Чтобы этого не было, нужно перед экспортом в object в блендере обнулить все трансформации (перед этим не забыв их записать в конфиги оружия).

Но это заставляет пользователей отказаться от использования Tranforms параметров в AE.

Нужно что-то придумать. Просто записать Loacation и Rotation в конфиг не получится.

**Comment by PavelBlend** [comment]
@SamArtGit у меня есть идея, как это сделать:
Добавить вспомогательный объект-пустышку в нулевые координаты с нулевым вращением и единичным масштабом. Потом привязать скелет оружия к этой пустышке. Будет что-то вроде этого:
![01](https://user-images.githubusercontent.com/7983249/107827314-94de0680-6d97-11eb-96ba-22e81e435aea.jpg)

Потом можно перемещать эту пустышку и считывать значения для position и rotation именно из этой пустышки.

Считывать нужно так (для ТЧ):
позиция блендера +X+Y+Z записывается как +X+Z+Y
углы измеряются в градусах и записываются из +X+Y+Z в -X-Z-Y

Нужно просто добавить параметры в панель, которые будут результатом преобразования блендеровских трансформаций в сталкеровские (с возможностью копирования).

**Comment by SamArtGit** [comment]
Вау, вы серьезно за это взялись? Я думал что это будет как с генератором леса из плагина для 3D Максима и импортом OGF - после того как закончите делать поддержку .level и когда нибудь в будущем. Оперативно.

**Comment by PavelBlend** [comment]
Я проверял в игре и у меня вышло так:
![test_hud_1](https://user-images.githubusercontent.com/7983249/107827635-3e24fc80-6d98-11eb-9d84-172eee4afc89.jpg)
![test_hud_2](https://user-images.githubusercontent.com/7983249/107827643-411fed00-6d98-11eb-8571-2321e0b6dfcd.jpg)

Но нужно в конфиге оружия временно отключить параметр allow_inertion, чтобы оружие было всегда на одной высоте, независимо от направления взгляда. И разрешение в игре должно быть 1280x720. Сделал скриншот и добавил на фон камере (которая тоже имеет разрешение 1280x720) эти скриншоты. Если разрешение в игре и в блендере будут разными, то картинка не совпадёт с моделью. Угол обзора у камеры в блендере нужно установить в режим Field of View (градусы) и установить значение в 51.5 градуса. 51.5 - это только для 1280x720. В остальных разрешениях углы другие

**Comment by PavelBlend** [comment]
> Я думал что это будет как с генератором леса из плагина для 3D Максима и импортом OGF

ну эти возможности могут занять намного больше времени, чем настройка конфигов оружия. Я хочу доделать level плагин, а только потом браться за такие фичи. И параллельно делаю мелкие улучшения, которые не затягиваются на долго.

**Comment by PavelBlend** [comment]
@SamArtGit я сделал инструменты для настройки конфигов hud моделей.
Вот параметры:
![transforms_utils](https://user-images.githubusercontent.com/7983249/107888377-ee237280-6f1c-11eb-9490-8537041edbb0.jpg)

Кнопка `Update X-Ray Transforms` преобразует блендеровские трансформации объекта и устанавливает полученные значения в xray трансформации в этой панели (параметры X, Y, Z для Position и Orientation).

Кнопка `Update Blender Transforms` преобразует xray трансформации в блендеровские и устанавливает их текущему объекту. Это нужно для того, чтобы установить трансформации объекта такими же, как в конфиге оружия. Но перед этим значения из конфига нужно скопировать в параметры Position и Orientation.

Кнопка `Copy X-Ray Transforms` копирует трансформации в xray формате (то есть параметры Position и Orientation из этой `X-Ray Engine: Object` панели) в буфер обмена. Можно в текстовом редакторе нажимать Ctrl+V и добавится такой текст:
```
[xray_transforms]
position = -0.11128265410661697, -0.12397761642932892, 0.28260284662246704
orientation = -7.788086488840251, 8.403417377393053, 3.8802360170129444
```

Значения поворота будут в градусах, если в настройках сцены параметр Units > Rotation равен Degrees. Иначе будут радианы. В конфигах сталкера в разных параметрах могут быть как градусы так и радианы.

И вращение нужно инвертировать, если они будут использоваться для смещения при прицеливании (параметры zoom_rotate_x и zoom_rotate_y в ltx конфиге оружия). Я не стал добавлять в интерфейс блендера параметр инверсии вращения. Итак параметров много.

И если оружие уже имеет смещение, к которому нужно добавить смещение конфига, то это нужно учитывать самому. Например, так:
![transforms_utils_info](https://user-images.githubusercontent.com/7983249/107888758-7276f500-6f1f-11eb-804f-c92e9f514abd.jpg)


Если есть замечания, предложения, то пиши, буду дорабатывать.

**Comment by PavelBlend** [comment]
Пытался переделать hud абакана и не получилось. Переписал аддон немного. Теперь значения не зависят от единиц вращения. И результат будет таким:
```
; hud transforms
position = -0.134240, 0.090355, -0.000000
orientation = 0.212113, -2.911084, 0.000000

; hud offset
zoom_offset = -0.134240, 0.090355, -0.000000
zoom_rotate_x = 0.050808
zoom_rotate_y = -0.003702
```
Инвертировать zoom_rotate_x и zoom_rotate_y теперь не нужно. Вот результат:
![ss_pavel_blend_02-15-21_00-44-03_(l01_escape)](https://user-images.githubusercontent.com/7983249/107890032-976f6600-6f27-11eb-893e-24990b35b9af.jpg)
![ss_pavel_blend_02-15-21_00-44-12_(l01_escape)](https://user-images.githubusercontent.com/7983249/107890033-98a09300-6f27-11eb-8433-9767d9e1f1cf.jpg)
