### ISSUE TITLE
Не работает экспорт нескольких арматур на горячие клавиши.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#373]
В настройках ничего не менял. Нажимаю Shift + F8, выдаёт ошибку. Через контекстное меню работает. Проверял на последней develop версии с фиксом  прошлого бага - #370.
![123426t5](https://user-images.githubusercontent.com/56885075/107852037-e4afe280-6e16-11eb-8dbe-e30fc3f6cd72.jpg)

**Comment by PavelBlend** [comment]
Я походу не тот оператор назначил на клавишу. Сегодня исправлю. Там одну строку поменять нужно.
