### ISSUE TITLE
Возможность хранения специфичных xray свойств в FBX формате.

### ISSUE THREAD

**Issue by StalkMen** [PavelBlend/blender-xray#374]
Неплохо бы сделать общий формат свойств с Max\Maya. Тогда можно будет перегонять через Fbx сразу со свойствами.

**Comment by PavelBlend** [comment]
@StalkMen можно по подробнее? Я этим форматом можно сказать не пользуюсь. Сейчас начал смотреть. Вот эти свойства?:
![01](https://user-images.githubusercontent.com/7983249/108820923-eecba100-75cd-11eb-80ad-4153e22709e3.jpg)
И при экспорте ставить галочку:
![02](https://user-images.githubusercontent.com/7983249/108820997-0c006f80-75ce-11eb-8765-f0b6e108c0c0.jpg)

И какие имена свойств должны быть? И как лучше сделать эту возможность?

**Comment by StalkMen** [comment]
@PavelBlend Речь про свойства из плагина - game mtl, shader, shader xrlc, double sided и прочие.
Сейчас если выставить эти свойства, сохранить в fbx, а затем открыть (в блендере), то все данные из плагина теряются.

Мы сейчас делаем импортер fbx и хотелось бы сделать совместимость со всеми плагинами.
На сколько я понимаю, формат fbx позволяет хранить в себе "Custom Properties", надо только хранить все переменные из плагина в них. Причем эти пропы можно цеплять к разным типам объектов (FbxNode, FbxMesh, FbxSurfacePhong и тп)

**Comment by StalkMen** [comment]
Желательно добавить переменные как у DenStash'а в скрипте макса,

**Comment by PavelBlend** [comment]
@StalkMen а что, если сделать такой вариант?:

добавить кнопку, которая делает экспорт в fbx, вызывая оператор bpy.ops.export_scene.fbx() из FBX аддона, но перед экспортом создаёт Custom Properties у тех объектов и материалов (может и у костей), которые нужно экспортировать. И эти Custom Properties будут заполнены значениями, которые указаны в панели XRay Engine: Material (EShader, CShader...) и других панелях.

И добавить тоже для импорта (заполнять xray параметры на основе Custom Properties, которые загрузились из fbx).

**Comment by StalkMen** [comment]
@PavelBlend 
Может и так, но как по мне, логичней не дублировать кнопку, а использовать стандартную Export - Fbx. Ну и для импорта аналогично.

**Comment by PavelBlend** [comment]
@StalkMen ну тогда придётся менять код fbx аддона. Или в blender-xray делать удаление старых операторов и добавлять в меню новые. А вдруг пользователь захочет экспортировать в fbx стандартным способом (без xray свойств), а там xray-fbx оператор в меню будет.

**Comment by StalkMen** [comment]
@PavelBlend Что такое "оператор"? Типо доп. менюшка в менюшке импорта-экспорта fbx? Если так, то зачем она..
Xray свойства должны записываться, только если они отличны от дефолтных, тогда плагин не будет мешать при работе с прочей геометрией. Те поменяли game mtl - добавился Custom prop - и он же попадет в fbx.

**Comment by PavelBlend** [comment]
Хотя у меня другая идея повилась.

При экспорте в fbx, экспортер извлекает кастомные свойства из панели Custom Properties и сохраняет в fbx файл.

Нужно будет сделать кнопку, которая будет заполнять эти свойства теми значениями, которые указаны в xray панелях. А вызывать экспорт в fbx нужно будет вручную.

И еще нужно добавить кнопку для обратного действия. Чтобы заполнить xray свойства значениями из Custom Properties.

И так же можно добавить в настройки параметры, которые указывают имена для Custom Properties. Вдруг кто то захочет их переименовать под себя. Может при экспорте в юнити нужно будет другие имена указать.

**Comment by StalkMen** [comment]
Если хранить данные сразу в виде Custom Properties, то и доп кнопки не нужны.

Идея с настройками норм.

**Comment by PavelBlend** [comment]
Делать хранение данных в custom properties я точно не буду. Это получается все мои и пользователей аддона сохраненные бленд сцены станут не актуальными? Нужно тогда делать кнопки, которые сделают старые сцены актуальными. Я стараюсь не менять свойства аддона, чтобы не потерять совместимость между версиями. И кастомные свойства ограничены. И вообще предназначены не для программистов, а для аниматоров, которые создают переключатели для ик и фк и т. д. Для полноценных аддонов их не используют.

**Comment by PavelBlend** [comment]
И ещё эти свойства добавляются только одному блоку данных. Если у меня десять материалов, то мне придётся вручную создавать эти свойства для каждого. Или писать костыли для автоматизации. А когда свойства добавляются полноценно, то они добавляются абсолютно всем материалам. Их нельзя будет удалить. А кастомные удалять можно.

**Comment by PavelBlend** [comment]
@StalkMen я пока вручную создал эти свойства для материала. Потом экспортировал в fbx. Вот файл:
[fbx_test.zip](https://github.com/PavelBlend/blender-xray/files/6030598/fbx_test.zip)
При импорте обратно в блендер этого файла свойства сохраняются:
![01](https://user-images.githubusercontent.com/7983249/108879650-86eb7980-7612-11eb-9979-35f60b4a6231.jpg)
Но можешь проверить, в макс/майю будут эти свойства импортироваться? Если да, то какие ещё свойства добавлять? Все, которые есть в аддоне? И как их назвать? У меня нет скриптов для макса и если я их скачаю, то буду долго искать, где определяются имена свойств. А запускать макс и смотреть в интерфейсе не могу, так как не знаю где что смотреть и нет у меня макса.

**Comment by StalkMen** [comment]
В максе не пашет.
Я думаю, чем больше свойств, тем лучше.
Вот как макс сохраняет свойства.
EShader, CShader, GameMaterial
![изображение](https://user-images.githubusercontent.com/13629855/109001621-34fc2f80-76b6-11eb-9594-0d7042372d4c.png)

**Comment by StalkMen** [comment]
Фиксирую проперти
![изображение](https://user-images.githubusercontent.com/13629855/109002176-e9965100-76b6-11eb-928f-ccff86cda438.png)

**Comment by PavelBlend** [comment]
А вот так правильно импортируется?:
[fbx_test_2.zip](https://github.com/PavelBlend/blender-xray/files/6036720/fbx_test_2.zip)

Получается, можно делать экспорт в fbx из блендера и импортировать в макс и сразу же, без настройки, экспортировать в object скриптами и все свойства будут сохранены? Или в максе нужно проделать манипуляции?

> Нужно будет сделать кнопку, которая будет заполнять эти свойства теми значениями, которые указаны в xray панелях. А вызывать экспорт в fbx нужно будет вручную.

всё таки нужно по другому делать. А то перед экспортом в fbx каждый раз придётся смотреть, не устарели ли Custom свойства или жать кнопку для обновления этих свойств.

Короче я буду сегодня или завтра пробовать делать эту функцию и по ходу буду смотреть, как лучше будет получаться. Чтобы нужно было делать минимум манипуляций перед экспортом/импортом fbx.

**Comment by StalkMen** [comment]
![изображение](https://user-images.githubusercontent.com/13629855/109020607-29673380-76cb-11eb-9d1f-5c1d6e6f19dc.png)
Ну импорер видит пропы, но макс нет.

**Comment by PavelBlend** [comment]
А если из макса экспортировать модель в fbx и потом опять импортировать, xray параметры сохраняются?

**Comment by StalkMen** [comment]
Хм, оказывается что нет, хотя при экспорте они есть.

**Comment by SkyLoaderr** [comment]
Максовский скрипт надо дорабатывать по этой теме. Макс подгружает параметры материалов, но хранит их в списке обычных кастомных параметров, так как импортер fbx не знает, что делать с ними.

**Comment by PavelBlend** [comment]
@StalkMen дописал эту возможность. Код находится в этой ветке:
https://github.com/PavelBlend/blender-xray/tree/issue/374/fbx-utils

Я добавил 4 кнопки и две настройки:
![01](https://user-images.githubusercontent.com/7983249/113512113-db680a00-956b-11eb-895e-9a8db8bdee73.jpg)

И не стал делать запуск fbx плагина. Его нужно будет делать вручную. Так как много костылей писать нужно было.

На данный момент аддон только создаёт/удаляет кастомные свойства.

`Edit Data` - этот параметры указывает, какие данные редактировать. Объекты, мешы, материалы, кости, анимации или все данные.

`Edit Mode` - режим редактирования. Возможные такие варианты: редактировать только активный блок данных (активный объект, меш активного объекта, активный материал активного объекта, кости активной арматуры, активная анимация активного объекта). Второй вариант: выделенные данные (выделенные объекты, меши выделенных объектов, все материалы выделенных объектов, все кости выделенных арматур, все анимации, которые указаны в motions выделенных объектов). И третий вариант: редактировать все данные blend файла.

Кнопка `X-Ray to Custom` создаёт кастомные свойства и заполняет их значениями из xray параметров.
Кнопка `Custom to X-Ray` заполняет xray свойства теми значениями, которые указаны в custom свойствах.
Кнопка `X-Ray` удаляет все кастомные свойства, имена которых совпадают с именами свойств в настройках (см. скриншот ниже).
Кнопка `All` удаляет все кастомные свойства (пригодится в том случае, если объекты хранят устаревшие свойства, имена которых не совпадают с именами свойств в настройках).

В настройках добавлен раздел для указания имён кастомных свойств:
![02](https://user-images.githubusercontent.com/7983249/113514578-2a1ba100-9578-11eb-8f06-087973e42011.jpg)

Можешь проверить эти возможности? Может у тебя будут замечания и идеи, как улучшить?

Если всё устраивает, то буду делать merge в основную ветку. И может сделаю релиз, так как исправил пару ошибок.

**Comment by PavelBlend** [comment]
@StalkMen я сделал мерж в develop ветку, так как не хочу затягивать, чтобы потом не разрешать сложные конфликты. И плюс тесты были исправлены в ветке issue/374/fbx-utils. Если будут замечания, то заново открой эту issue.

**Comment by PavelBlend** [comment]
Мерж этих возможностей: 01f5c3a845c976d439aea19e0a9676ee8bc790e8

**Comment by StalkMen** [comment]
Кайф, проверим.

**Comment by SkyLoaderr** [comment]
В итоге, нет совместимости со сталкерскими параметрами в fbx, экспортированном из 3ds max?

**Comment by PavelBlend** [comment]
@SkyLoaderr я не знаю, будет ли совместимость, так как у меня нет 3д макса. Но если экспортировать модели из блендера в fbx, а потом обратно импортировать этот fbx, то свойства сохраняются. Нужно только при экспорте галочку поставить:
![01](https://user-images.githubusercontent.com/7983249/114356824-b3833280-9b79-11eb-8548-a1d3dcfde9ec.jpg)

И при импорте, убедиться, что аналогичная галочка включена.

В результате, после импорта fbx, у объектов, материалов и других данных будут кастомные свойства, которые можно будет установить в xray свойства (как это сделать, я писал выше):
![02](https://user-images.githubusercontent.com/7983249/114357531-82efc880-9b7a-11eb-8aa4-13a03cc25ff7.jpg)

Если имена свойств не совпадают, то в настройках аддона их можно изменить.

И я не хотел бы устанавливать имена свойств как в максе. Так как скрипты для макса не официальные и имена свойств могут не соответствовать правильным именам, которые были даны параметрам в официальном сдк. Когда я писал имена свойств, то пытался сделать их такими же, как в сдк. Только вместо пробелов установил нижнее подчёркивание и все буквы сделал строчными.

**Comment by SkyLoaderr** [comment]
Сейчас получается, что нет совместимости х-рей параметров с fbx из 3дс макса, так как в скриптах кастомные параметры именуются как: EShader, CShader, GameMaterial, в то время как в блендере они: shader, compile, game_mtl. Сохранив модель в одном редакторе, не получится по дефолту использовать настроенные х-рей параметры в другом редакторе. Придется каждый раз переименовывать.

**Comment by StalkMen** [comment]
@SkyLoaderr 
Дык можно сделать пресет настроек под совместимость с максом.

**Comment by PavelBlend** [comment]
> EShader, CShader, GameMaterial

я думаю, что эти свойства не правильно названы. Я больше ориентировался на официальные названия из сдк.

> Дык можно сделать пресет настроек под совместимость с максом.

можно ещё этот пресет скопировать и распространять. Пресеты - это обычные питоновские скрипты. Если команда работает над модом, то можно один раз настроить и скопировать пресет другим. Они сохраняются в папку:
`C:\Users\<USER_NAME>\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\presets\io_scene_xray\preferences`
