### ISSUE TITLE
import ,export .level

### ISSUE THREAD

**Issue by ssijonson** [PavelBlend/blender-xray#375]
import game level работает 

import scene selection  level вообще никак
![Screenshot_3](https://user-images.githubusercontent.com/55274317/109378297-f52a8780-7903-11eb-8d4b-d47d958c115e.png)

export game level не работает
![Screenshot_2](https://user-images.githubusercontent.com/55274317/109378258-bac0ea80-7903-11eb-8449-39670378c787.png)

export scene selection когда как ,ну очень  редко 
![Screenshot_1](https://user-images.githubusercontent.com/55274317/109378239-8a794c00-7903-11eb-83ea-43bd51fd944a.png)

#### Версии ПО:
  Windows 10 Pro x64 (1909 build 18363)
 - Blender: 2.80

**Comment by PavelBlend** [comment]
> import scene selection level вообще никак

в сдк два формата *.level. Какой именно формат ты импортировал? Я описывал какой именно нужно импортировать здесь:
Сам вопрос: https://ap-pro.ru/forums/topic/87-blender/page/5/?tab=comments#comment-62358
Мой ответ: https://ap-pro.ru/forums/topic/87-blender/page/5/?tab=comments#comment-62380



> export game level не работает

перед экспортом нужно выделить главную пустышку уровня. Другие объекты выделять не нужно. И сделать экспорт в game level можно только из импортированного game level. Экспортировать любые объекты нельзя.



> export scene selection когда как ,ну очень редко

мне нужен пример blend файла, на котором можно воспроизвести ошибку. Или описание, как поэтапно воспроизвести её. Какие объекты экспортируются и т. д.

**Comment by ssijonson** [comment]
Какой именно формат ты импортировал?ну тот который со списком object'ов.
насчет этого уже вроде разобрался ,но после импорта lod'ы скомкались в центре.

export game level не работает

перед экспортом нужно выделить главную пустышку уровня. Другие объекты выделять не нужно. И сделать экспорт в game level можно только из импортированного game level. Экспортировать любые объекты нельзя.
про это не знал.

мне нужен пример blend файла,https://drive.google.com/file/d/1UoaiRpWcpy2pQAHTm6A847uw0p2PuTfM/view?usp=sharing

**Comment by PavelBlend** [comment]
> * Blender: 2.80

кстати, а почему такая устаревшая версия блендера? 2.9 давно вышла. Я помню в 2.80 было куча ошибок (оно и не удивительно, так как разработчики перелопатили весь код). Эти ошибки не влияют на импорт level. Но 2.9 стабильнее. Ну или хотя бы 2.83 LTS.

> про это не знал.

то есть вопрос по поводу экспорта в game level закрыт? Получилось экспортировать?


> но после импорта lod'ы скомкались в центре.

у меня нормально импортируется:
![01](https://user-images.githubusercontent.com/7983249/109389916-a68ae680-791f-11eb-94f1-f358ff75e71d.jpg)
не получается ошибку воспроизвести. А какой у тебя СДК? И какая версия аддона blender-xray? И какие шаги выполняешь? Включая настройку аддона.

Посмотрел blend файл. Это затон из ЗП, который был в виде level, level.geom, level.cfrom. И такие локации экспортировать нельзя. Модели, которые получены путём импорта game level предназначены только для экспорта в game level. Если делать экспорт в game level не планируется, то нужно пользоваться конвертером бардака и импортировать object'ы. Весь смысл game level плагина в том, чтобы редактировать готовые игровые уровни без многочасовой компиляции. И этот плагин никак не предназначен для перегонки в другие форматы (scene selection, object, ogf...). 

И при экспорте в scene selection у объекта обязательно должен быть корректно установлен этот параметр:
![02](https://user-images.githubusercontent.com/7983249/109390176-13eb4700-7921-11eb-9a4f-d7e89adb60ba.jpg)
Так как плагин не будет знать полный путь к объекту в rawdata\objects папке. Сам scene selection файл (*.level) не хранит геометрии. Он является списком object файлов и хранит только пути к object файлам.

Чтобы Export Path был правильным, нужно в настройках указать Objects Folder и импортировать существующие object файлы из rawdata\objects. Либо создать свой объект и вручную указать этот параметр и сделать экспорт этого объекта в object.

**Comment by ssijonson** [comment]
в в общем и целом с этим все понятно.
но тот файл что выдает конвертер(.level) после декомпиляции  открываться не хочет.
![Screenshot_1](https://user-images.githubusercontent.com/55274317/109391142-380e4e80-7948-11eb-9146-c0cf7e1a5457.png)
import'нул  левел посредством импорта object'ов вот  lod'ы и съехались(наверное).
![Screenshot_2](https://user-images.githubusercontent.com/55274317/109391310-faf68c00-7948-11eb-9a20-474e32abab88.png)

**Comment by ssijonson** [comment]
вопрос закрыт.
