### ISSUE TITLE
Не экспортируется информация из чанка 0x0921

### ISSUE THREAD

**Issue by mortany** [PavelBlend/blender-xray#381]
#### Краткое описание проблемы:

Не экспортируется информация из чанка 0x0921 ( BONES1 )
#### Как воспроизвести ошибку:

1. Импортировать любую модель с костями
2. Открыть модель в SDK
3. Открыть Bone Parts - список костей будет пустым
#### Версии ПО:
 - OS: Win10 x64
 - Blender: 2.92.0

**Comment by PavelBlend** [comment]
@mortany не могу воспроизвести ошибку.
1. Импортирую в blender любую *.object модель с костями, у которой есть bone parts.
2. Экспортирую обратно в *.object.
3. Открываю в SDK полученный *.object после экспорта из блендера.
4. Список BoneParts заполнен.

Я правильно повторил шаги? Или может не на любом object файле воспроизводится ошибка?

**Comment by mortany** [comment]
Да, не на всех моделях, не знаю почему, возможно модель привязанная в блендере изначально была. Сейчас на других проверил то всё тоже не получилось повторить.

**Comment by PavelBlend** [comment]
@mortany может модель изначально не имела boneparts? Ну если тоже не получилось воспроизвести, то вопрос закрыт?

**Comment by PavelBlend** [comment]
@mortany всё таки получилось воспроизвести ошибку. Проблема скорее касается СДК, а не блендера. СДК имена костей всегда хранит в виде строчных букв. Если сделать экспорт скелетной модели из блендера, у которой есть кость с заглавными буквами, то в сдк в bonepart она не попадёт. Хотя если эту же модель обратно в блендер импортировать, все boneparts на месте.

Вот пример:
[bonepart_bug.zip](https://github.com/PavelBlend/blender-xray/files/6670697/bonepart_bug.zip)

Скелет имеет кость Bone. Имя кости в object файле сохранится как Bone. Имя кости в bonepart сохранится тоже как Bone. Но в сдк имя кости будет bone, а в bonepart останется Bone. А это уже две разные кости. Поэтому в bonepart будет пусто.
![01](https://user-images.githubusercontent.com/7983249/122410510-a70dc280-cf8c-11eb-8e9f-3e3e7b8770b0.jpg)

Но после того, как я в блендере переименовал кость с Bone на bone, ошибка исчезла:
![02](https://user-images.githubusercontent.com/7983249/122410757-e0463280-cf8c-11eb-8ab7-23625a3aab17.jpg)

СДК не правильно обрабатывает имена с заглавными буквами.

Я сделаю фикс, чтобы аддон всегда сохранял имена костей строчными буквами.

**Comment by mortany** [comment]
@PavelBlend интересно получается. Я вообще столкнулся с этой траблой когда пытался прочитать object при помощи https://github.com/abramcumner/xray_re-tools
Я пытаюсь сделать плагин для 3д макса при помощи библиотек данного конвертора.

**Comment by PavelBlend** [comment]
@mortany исправил ошибку. Теперь аддон всегда будет сохранять имена костей и групп вершин в нижнем регистре.
