### ISSUE TITLE
Массовое изменение параметров анимаций

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#393]
Добавить инструменты для массового изменения параметров Action с помощью одного действия.
![011](https://user-images.githubusercontent.com/7983249/125676277-e095a39f-19da-4e0a-97b9-48bb4279bb73.jpg)
Сейчас долго настраивать параметры авто запекания для каждой анимации.

**Comment by s30-zip** [comment]
То есть можно будет перезапечь всю библиотеку с новыми настройками?

**Comment by s30-zip** [comment]
А смогу я на созданный свой скелет сделать ретаргетинг (другой аддон) и перезапечь на него все анимации?

**Comment by PavelBlend** [comment]
> То есть можно будет перезапечь всю библиотеку с новыми настройками?

можно будет менять xray-параметры у всех анимаций в blend-сцене. Либо у всех анимаций из списка motions в xray панеле.

> А смогу я на созданный свой скелет сделать ретаргетинг (другой аддон) и перезапечь на него все анимации?

это запекание происходит только во время экспорта анимаций в skls. Аддон просто устанавливает нужный кадр в таймлайне, а потом считывает мировые матрицы костей. Эти матрицы учитывают все констрейнты и драйверы. Вот и всё запекание. Я не знаю, как это можно использовать в связке с другими аддонами.

**Comment by PavelBlend** [comment]
В N-панель окна 3д вида добавлен оператор для изменения настроек авто-запекания анимаций:
![01](https://user-images.githubusercontent.com/7983249/126894298-30f8cd31-50c2-4ecc-b9f9-a834bb4c6004.jpg)

Первый параметр - `Mode`. Указывает на то, какие анимации нужно изменить.
`Active` - активная анимация активного объекта
`Selected` - анимации из списка `Motions` (в `X-Ray Engine` панеле, вкладка `Object` в окне `Properties`) для всех выбранных объектов:
![02](https://user-images.githubusercontent.com/7983249/126894540-4445063e-6898-46c6-8d81-f5609a2a690f.jpg)

`All` - тоже самое, что и `Selected`, но только для всех анимаций blend файла.

`Change Auto Bake Mode` - изменять ли параметр `Auto-Bake` (On/Off/Auto) или нет
Ниже список самих значений `On`, `Off`, `Auto`.

`Change Use Custom Thresholds` - изменять ли параметр `Custom Thresholds` у анимаций или нет
Ниже кнопка `Use Custom Thresholds` самого значения `Custom Thresholds`, которое нужно установить для анимаций

`Change Location Threshold` - изменять ли параметр `L` у анимаций
`Location Threshold` - значение для параметра `L`

`Change Rotation Threshold` - изменять ли параметр `R` у анимаций
`Rotation Threshold` - значение для параметра `R`
