### ISSUE TITLE
Возможен ли импорт  лодов по установленным местам

### ISSUE THREAD

**Issue by s30-zip** [PavelBlend/blender-xray#402]
Можно ли импортировать лоды по своим местам, к примеру мне нужно видеть деревья с локации или камни, например для рендера видео вставки или скрина для карты?

**Comment by PavelBlend** [comment]
@s30-zip можно импортировать игровую локацию из gamedata\levels (файлы level, level.geom, level.geomx, level.cform). Либо можно сохранить список выделенных объектов в LevelEditor и потом импортировать этот список object файлов в блендер. Для этого нужно в LevelEditor выделить меш объекты в режиме Object, потом нажать меню File>Save Selection As. В итоге будет сохранён *.level файл, который можно импортировать в блендер, через меню File>Import>X-Ray Engine>Scene Selection (.level).

**Comment by s30-zip** [comment]
@PavelBlend  спасибо, второй способ работает, а вот первый... почему-то не видит файлы level и др.

**Comment by PavelBlend** [comment]
@s30-zip это баг самого блендера, а не аддона. Вот здесь я описывал:
https://github.com/PavelBlend/blender-xray/issues/340

Нужно выключить фильтрацию по расширению в проводнике блендера с помощью этой кнопки:
![01](https://user-images.githubusercontent.com/7983249/127400311-dff3ef58-9710-4080-98fd-3cc48e77a076.jpg)

Если эту лейку выключить, то все файлы будут видны. Я не знаю, когда разработчики блендера исправят фильтрацию, поэтому это пока единственное решение. Либо можно вручную написать имя файла в поле внизу.

**Comment by s30-zip** [comment]
извиняюсь, не просмотрел активные проблемы...
Если мне скидывают файлы level, level.geom, level.geomx, level.cform, то для импорта мне нужны и лоды которые там задействуются? Просто эти 4 файла не хочет импортировать.

**Comment by PavelBlend** [comment]
@s30-zip какую ошибку пишет? Нужно выделить один файл level. Другие файлы выделять не нужно. Лод текстура и карты освещения должны быть в папке с уровнем.

**Comment by s30-zip** [comment]
Bad scene selection file. Cannot find "version" chunk.

**Comment by PavelBlend** [comment]
@s30-zip эта ошибка может возникнуть только в плагине `scene selection` (ниже на скриншоте красным обвёл).

У тебя какая версия блендера? 2.79? В 2.79 нет поддержки импорта `game level`. Этот плагин доступен только в версии 2.80 и выше:
![01](https://user-images.githubusercontent.com/7983249/127508747-7ded5050-cdd7-4471-9d8b-80bbc14cd3a3.jpg)

Я не стал добавлять `game level` в блендер 2.79 и старее, так как много нужно было учитывать различий между 2.80. В 2.80 были удалены группы и добавлены коллекции. Но я могу позже добавить поддержку в 2.7. И ещё не добавлял в 2.7, так как у него меньше инструментов для редактирования нормалей. В 2.8 их больше. Нормали повсюду используются в формате level.geom. В 2.79 просто не удобно будет редактировать кастомные нормали из-за скудных инструментов.

**Comment by s30-zip** [comment]
Да 2.79, у меня видеокарта старая, артифакты лезут.

**Comment by PavelBlend** [comment]
Я позже буду добавлять в 2.79. Создал issue: #403

**Comment by s30-zip** [comment]
Благодарю!
