### ISSUE TITLE
Game Level плагин в Blender 2.7

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#403]
Добавить поддержку `game level` плагина в 2.7.

**Comment by PavelBlend** [comment]
Теперь импорт игровых уровней поддерживается в блендере 2.7. Чтобы быстро выделить объекты одного типа можно использовать клавиши Shift + G для выделения объектов из одной группы. Аддон помещает объекты в группы, как на скриншоте:
![01](https://user-images.githubusercontent.com/7983249/128639251-bed64f84-3e00-4e1f-83b4-396891e72910.jpg)

**Comment by s30-zip** [comment]
А импорт из билдов в 2.7 не поддерживается? При импорте из 1935 : "Unsupported level version: 12". Я хотел "warlab" декомпилировать , вылетает конвертер на "merging submesh" кажется, думал левел загрузить - не идёт, как и из 1865 любой.
В 2.90.1 импортирует, но артефакты из-за старой видеокарты

**Comment by PavelBlend** [comment]
@s30-zip он поддерживался, но я его отключил, так как тестировал на ранних билдах и там столько ошибок посыпалось.
Если хочешь импортировать уровни из билдов, то измени эту переменную:
https://github.com/PavelBlend/blender-xray/blob/0451c0190cf62ab900e2ee41fba03c123d169bb3/io_scene_xray/level/fmt.py#L1

Она находится в файле io_scene_xray\level\fmt.py первая строка, называется EXPERIMENTAL_MODE. Нужно установить True вместо False.
Правда я не уверен в стабильности. Нужно код пересматривать. Я включу поддержку билдов позже, когда плагин level будет более стабильным.
