### ISSUE TITLE
Не правильно отрисовываются лимиты в режиме IK

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#412]
Если включить режим лимитов на `X-Ray Limits`, то в 3д окне лимиты будут отображаться правильно. Но если включить `IK Limits`, то в 3д окне продолжат отрисовываться `X-Ray` лимиты. Нужно отрисовывать IK вместо X-Ray лимитов:
![01](https://user-images.githubusercontent.com/7983249/128663806-e5eab25a-1ca7-43ea-af37-d3f059b0c7ca.jpg)

**Comment by PavelBlend** [comment]
Исправил:
![01](https://user-images.githubusercontent.com/7983249/128664140-dade7fed-a478-4f19-8f46-1b5cf9089bc9.jpg)

**Comment by s30-zip** [comment]
Я немного запутался, то ли подзабыл, x-ray limits это ограничения для не анимированных  костей, а IK для анимированных? В каких случаях какой используется?

**Comment by PavelBlend** [comment]
@s30-zip IK лимиты - это стандартные параметры блендера, которые в нём есть без аддонов. Находятся в окне Properties. В 2.79 находится здесь:
![01](https://user-images.githubusercontent.com/7983249/128778317-f2d8040c-9368-4ac5-a0d7-ff05d7a14609.jpg)

В старой версии аддона всегда использовались они, когда делался экспорт скелета в object. Но я пришёл к выводу, что с ними трудно работать. Когда IK включён, скелет невозможно анимировать. Он не гнётся. А если и гнётся, то с рывками. Это потому, что значения IK лимитов заполнялись значениями Joint лимитов, которые хранятся в object файлах и которые можно редактировать в ActorEditor. Эти Joint лимиты не подходят для анимирования.

В новой версии аддона я сделал новые параметры, которые назвал XRay лимиты. А старые лимиты назвал IK лимиты. Вот Xray лимиты хранятся здесь:
![02](https://user-images.githubusercontent.com/7983249/128778694-371bc03a-8607-43dc-b742-8a1ca3235e1f.jpg)

Эти XRay лимиты вообще не влияют на анимирование скелета (в отличие от IK лимитов). Можно хоть нули ставить и анимация не изменится. Для IK нужно отдельно лимиты настраивать.

Чтобы не потерять обратную совместимость со старыми файлами, был создан параметр для указания типа лимитов (откуда их брать):
![03](https://user-images.githubusercontent.com/7983249/128779097-5d0aa9bd-5ce6-4343-aedf-eec9a14a338d.jpg)

**Comment by PavelBlend** [comment]
Здесь описывалась проблема изначально: #74
