### ISSUE TITLE
Возможность изменить цвет шейпов в 3d окне

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#414]
Добавить в настройки параметры для указания цвета шейпов костей в 3д окне.

**Comment by PavelBlend** [comment]
Параметры добавлены в категорию Others:
![01](https://user-images.githubusercontent.com/7983249/128688850-6fe3adca-f977-4c0a-851d-73143c92bdee.jpg)

**Comment by s30-zip** [comment]
У меня кружок радуги не отображается 2.79  в шейп колор
![пример](https://user-images.githubusercontent.com/30635540/129922001-0a11a870-154e-4807-a99f-c90c8a7d4304.jpg)

**Comment by PavelBlend** [comment]
@s30-zip он в окне не помещается, поэтому не отображается. Сделай окно больше, чтобы этот круг влез в него. Или проскролить вверх окно.

**Comment by s30-zip** [comment]
Точно, не думал что так бывает
