### ISSUE TITLE
Не работает Change Shader Parameters в Material Tools

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#421]
Заметил в прошлых версиях, проверил на новой, крутил параметры, менял All на Active, всё равно баг остался.

![image](https://user-images.githubusercontent.com/56885075/130055021-8bc3a7ee-c275-4a2e-80ed-7008dba2adf1.png)

**Comment by PavelBlend** [comment]
@SamArtGit какой баг? В чём именно он заключается? И какая у тебя версия блендера и аддона? И этот баг на любых входных данных воспроизводится или только на определённых? Если на определённых, то мне нужен blend файл, в котором ошибка воспроизводится.

Этот параметр должен изменять параметры Principled шейдера. Если материал не имеет этого шейдера, а использует diffuse к примеру, то аддон выдаст просто предупреждение, что определённый материал не имеет principled шейдера. Остальные материалы, которые имеют principled, будут обработаны. А не подходящие материалы пропущены.

**Comment by SamArtGit** [comment]
Эх. Думал так можно будет, без подробных объяснений.

https://youtu.be/rbDcc_ScMXc

Использую последнюю версию Blender и плагина. Diffuse шейдеры не использую.

**Comment by PavelBlend** [comment]
@SamArtGit теперь я понял в чём проблема. Эта кнопка не работает в EEVEE. Я по-умолчанию использую Cycles, поэтому не знал об этой ошибке. И даже не проверял в EEVEE. Позже исправлю.
