### ISSUE TITLE
Внезапное снижение производительности

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#422]
Я использовал PavelBlend в течение довольно долгого времени и никогда не имел проблем с ним в отношении производительности.

Но после обновления 1.10 и выше производительность стала очень низкой.
Я проверил, что это было, и это действительно PavelBlend, потому что когда я отключаю его, все в порядке.

Эта проблема возникает, когда у меня много моделей в моем .blend-файле, а именно около 50 и выше.

Что может быть причиной этой проблемы?

**Comment by PavelBlend** [comment]
@Blackgrowl возможно в консоль пишутся ошибки и из-за этого будет снижена производительность.

Какая у тебя версия блендера? И какая версия аддона? И можешь скинуть проблемный blend файл? Какие модели он содержит? Скелетные или статичные?

Я помню снижение производительности было в blender 2.83. Описывал здесь: #309 

Если у тебя blender 2.83, то обнови его до самой последней версии.

**Comment by Blackgrowl** [comment]
Под консолью вы подразумеваете Window>Toggle System Console? Ну, у него есть ошибки, но он также статичен, когда я двигаюсь или делаю что-либо.

Я использую 2.93.3, версия аддона раньше была последней 1.12, пока я не перешел на 1.10, в которой меньше проблем с производительностью, но все же они есть.
Это модели персонажей, как игрока, так и NPC, также есть скелетные данные.

Я не уверен, как я могу отправить вам .blend файл, так как он имеет размер 200мб, должен ли я использовать Mediafire или что-то подобное?

**Comment by PavelBlend** [comment]
@Blackgrowl у меня получилось воспроизвести ошибку. Производительность в версии аддона 1.8.4 выше чем в последней 1.12.0. Я пока не знаю, из-за чего. Буду выяснять. Файл можно не присылать.

**Comment by PavelBlend** [comment]
@Blackgrowl исправил эту ошибку. Сегодня создам новую версию аддона и добавлю в релизы.

UPDATE
новый релиз: https://github.com/PavelBlend/blender-xray/releases/tag/v1.13.0
