### ISSUE TITLE
При попытке экспортировать skls открывается окно импорта skls

### ISSUE THREAD

**Issue by VaIeroK** [PavelBlend/blender-xray#425]
Блендер 2.8 \ 2.79b

Скриншоты:
http://prntscr.com/1r1oc3t
http://prntscr.com/1r1ohm1

**Comment by SamArtGit** [comment]
О, здарова Валера. 😅

**Comment by PavelBlend** [comment]
@VaIeroK исправил:
b2d947bac2a9c0b3bb7445949a741c4c47110fa6

Фикс будет в версии 1.14.1. Сейчас сделаю релиз.
