### ISSUE TITLE
Не экспортируются скелетные меши в object формат

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#427]
Когда я пытаюсь экспортировать файл .object, я получаю этот журнал.
```
Python: Traceback (most recent call last):
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\utils.py", line 429, in wrapper
    return method(self, context)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\utils.py", line 450, in wrapper
    return method(self, context)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\ops.py", line 225, in execute
    exp.export_file(bpy_obj, self.filepath, export_context)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\__init__.py", line 17, in export_file
    _export(bpy_obj, writer, context)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\__init__.py", line 11, in _export
    main.export_main(bpy_obj, writer, context)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\main.py", line 557, in export_main
    materials, bone_writers, some_arm, bpy_root, uv_map_names = export_meshes(
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\main.py", line 270, in export_meshes
    skeletal_obj = merge_meshes(armature_meshes)
  File "C:\Users\Blackgrowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_xray\obj\exp\main.py", line 205, in merge_meshes
    group = merged_object.vertex_groups[group_index]
IndexError: bpy_prop_collection[index]: index 43 out of range, size 42

location: <unknown location>:-1
```

И у меня никогда не было этого до версии 2.1.2. Кроме того, это кажется случайным, потому что я могу экспортировать другие файлы в .object просто отлично, за исключением этого одного файла.

**Comment by PavelBlend** [comment]
@Blackgrowl эта ошибка возникает в коде, который объединяет скелетные меши (меши, имеющие модификатор Armature) в один объект.

Только по коду я пока понять не могу, почему эта ошибка возникает. Должно всё работать. Я сейчас проверил у себя экспорт в object, который использует этот код и у меня ошибок нет. Может какие-то данные не корректные. Что-то с группами вершин. Пробовал создать пустые группы, повторяющиеся группы, группы, которые не привязаны к костям. Но всё равно ошибки у меня нет.

Можешь скинуть мне blend файл, в котором воспроизводится эта ошибка? Я без файла сказать ничего не смогу.

**Comment by Blackgrowl** [comment]
Извините, посмотрев получше, я обнаружил, что у меня были другие модели в самом скелете, хотя и скрытые.
Удаление их исправило ситуацию.

Однако это заставляет меня задаться вопросом... Почему PavelBlend нельзя сделать так, чтобы, например, когда объект скрыт, он не принимался при экспорте в .object?
То же самое касается текстур; PavelBlend должен считать первую "Image Texture" текстурой, или, по крайней мере, когда она привязана к "Base Color".

**Comment by PavelBlend** [comment]
> я обнаружил, что у меня были другие модели в самом скелете, хотя и скрытые.
> Удаление их исправило ситуацию

@Blackgrowl  у меня даже скрытые меши экспортируются. Я в окне Outliner выключил все кнопки видимости для меш-объекта лица:
![01](https://user-images.githubusercontent.com/7983249/133439497-15e9e565-3631-4b4f-ad98-ad105ebf3e45.jpg)
Сделал экспорт в object, а потом обратно импортировал object в blender и лицо сохранилось:
![02](https://user-images.githubusercontent.com/7983249/133439608-f7a4ecf6-4e45-48c0-a729-8ae3ff7325f3.jpg)

У меня ошибка не возникает, даже если объекты скрыты. Возможно причина в другом. Можешь скинуть blend сцену, я её изучу, чтобы понять причину ошибки. Если не хочешь в открытый доступ сцену заливать, то отправь мне на почту:
blendermediastudio _at_ gmail _dot_ com

**Comment by Blackgrowl** [comment]
Я отправил электронное письмо, как просили.

**Comment by PavelBlend** [comment]
@Blackgrowl я исправил ошибку, которая связана с группами вершин. Оказалось индексы групп вершин сбивались. Но эту ошибку было трудно воспроизвести, так как нужно было учесть сразу 3 условия. В остальных случаях код с ошибкой работал по случайности правильно.

И я заметил вторую проблему, которую тоже исправил. Во время экспорта скелетных мешей, аддон их объединял в один объект, если мешей было больше одного. Но во время объединения аддон не учитывал трансформации объектов. Я исправил это. Теперь аддон перед объединением будет применять трансформации.

Можешь проверить на работоспособность последний коммит?:
https://github.com/PavelBlend/blender-xray/tree/bfe5275a9cb17d602770b27606d1d8f31ac54d34

Нажми зелёную кнопку `Code` > `Download ZIP`. Распакуй архив и скопируй папку io_scene_xray в аддоны блендера.

Я после всех правок смог твой объект экспортировать. Правда я удалил лишние текстуры в нодах материала. Пока аддон требует наличие не более одной текстуры. Я пока не хочу это изменять, так как анализ дерева нодов у материалов может занимать больше времени. Так как изображение можно подключить не напрямую к сокету `Base Color`, а с помощью посредников в виде нод из группы `Color` и т. д. Все эти ноды нужно будет пропускать и анализировать всю ветку нодов, которая идёт от сокета `Base Color`.

Если всё работает правильно, то я создам новый релиз.

**Comment by PavelBlend** [comment]
@Blackgrowl я создал релиз:
https://github.com/PavelBlend/blender-xray/releases/tag/v2.1.3
Чтобы легче было устанавливать. Пока закрываю эту проблему.
