### ISSUE TITLE
Не работает импорт Bone Parts из OGF.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#432]
#### Описание проблемы:
Не работает импорт Bone Parts aka Bone Groups из .ogf-файла.

#### Как воспроизвести ошибку:
Открыть любую .ogf-модель из папки actors любой части игры.

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 2.93.5
 - Addon: 2.2.0

**Comment by PavelBlend** [comment]
@SamArtGit они и не должны импортироваться. Вот здесь я подробно объяснял:
https://github.com/PavelBlend/blender-xray/issues/344#issuecomment-917670976

У персонажей bone part хранятся в omf. В ogf файлах персонажей их нет.
