### ISSUE TITLE
Импорт модели из Viewer окна

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#433]
#### Описание идеи:
Возможность обычного и массового импорта моделей из Viewer окна.

#### Примеры использования:
Из оного выше окна гораздо быстрее импортировать модели, ибо можно осмотреть модель и не нужно каждый раз лезть в оператор импорта и выбирать модели, по сути, вслепую.

**Comment by PavelBlend** [comment]
@TheParaziT хорошо, позже сделаю. Такой вариант подойдёт?:
 - добавить кнопку `Import Active File` для импорта активного выделенного файла
 - добавить вторую кнопку `Import All Files` для импорта всех файлов из активной папки

**Comment by TheParaziT** [comment]
Вполне подойдёт. 
Неплохо бы сделать ещё Viewer окно со способностью выделения нескольких файлов одновременно.

**Comment by PavelBlend** [comment]
@TheParaziT я не знаю, как сделать выделение нескольких. Возможно никак. Скорее всего это ограничение блендера. Этот список файлов аналогичен списку групп вершин, shape keys, цветов вершин.

**Comment by PavelBlend** [comment]
@TheParaziT хотя нет, можно сделать. Вспомнил. Есть же список при импорте:
![01](https://user-images.githubusercontent.com/7983249/137633722-77734c6c-9887-4d59-a926-99ad6f36d58c.jpg)

Можно по аналогии сделать.

**Comment by TheParaziT** [comment]
Да, кстати, чуть не забыл.
Хорошо было бы ещё добавить подобный функционал и для skls browser. Опять же, для удобства.

**Comment by PavelBlend** [comment]
Добавил эту возможность:
![01](https://user-images.githubusercontent.com/7983249/144895423-60d8cf66-e624-488b-a726-85339b6f81a6.jpg)

Для skls браузера создам отдельную issue.
