### ISSUE TITLE
Возможность импорта модели вместе с текстурой, к которой она привязана

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#446]
#### Описание идеи:
Возможность импорта модели вместе с текстурой, к которой она привязана.
К примеру, можно добавить кнопку, как и "Import Motions".
![уа](https://user-images.githubusercontent.com/62593770/145703638-4716a4b9-4c41-4a8d-93b5-68aa61598617.png)

А так же найти место для такой же кнопки и в Viewer окне.

#### Примеры использования:
Аддон будет удобнее. Не нужно будет лезть в Preference каждый раз и выбирать профиль, либо же прописывать путь к папке с текстурами. Очень пригодится, когда работаешь над многими проектами, а зачастую текстуры лежат в разных папках.

**Comment by SamArtGit** [comment]
https://youtube.com/shorts/_r9_JxMdxHY?feature=share

**Comment by TheParaziT** [comment]
Да, я знаю, что так можно.
Но ведь дело как раз и в том, что я более-менее опытный, а новички, к примеру, могут об этом вообще не знать.

**Comment by SamArtGit** [comment]
А смысл тогда это добавлять? В .object не хранится конкретный путь к текстуре на диске. А если Blender будет сам искать по диску/дискам textures/act к примеру, то это будет очень долго. А может это дело будет быстрее, так что ждём слово Павла.

**Comment by PavelBlend** [comment]
> Возможность импорта модели вместе с текстурой

а сейчас разве не импортируется? Если в 3д окне её не видно, то нужно настроить режим отображения:
https://github.com/PavelBlend/blender-xray/discussions/382#discussioncomment-855420


> Не нужно будет лезть в Preference каждый раз и выбирать профиль, либо же прописывать путь к папке с текстурами

если ты импортируешь модели из одного мода или игры, то настроить пути нужно один раз и забыть.
Но если модели из разных модов, то можно в настройках создать пресеты настроек для каждого мода:
![01](https://user-images.githubusercontent.com/7983249/145711587-8a1d0f18-c684-497c-8c88-bb9c734946be.jpg)

И так то да, придётся лезть в настройки перед импортом.

Я хотел сделать импорт текстур из двух папок: из gamedata\textures из игры и из мода: #300

Но можно делать импорт не только из двух папок, но из целого списка папок.

> В .object не хранится конкретный путь к текстуре на диске.

да, там относительный путь и не понятно, где искать текстуру act\act_stalker. Автоматически делать поиск текстур невозможно.
