### ISSUE TITLE
Кости сломаны, по крайней мере, у мертвых

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#450]
Используя последнюю версию 2.9.2, когда я экспортирую свой .object, я использую Stalker SDK, чтобы разобраться с остальным, но я сомневаюсь, что это делает именно Stalker SDK.

Я не знаю, как я могу проверить "мертвую физику" в Blender, так что мне придется делать это в игре, ну...
Я сделал это, и я очень уверен, что я правильно экспортировал новый .объект, поскольку я целился в скелет с помощью ОДНОГО объекта, все работает нормально, но как только я стреляю в него, скелет исчезает, ни физики, ни ограничений костей, ничего.

Как я могу это исправить? Стоит ли мне на всякий случай отправить сам файл по электронной почте?

**Comment by Blackgrowl** [comment]
Моя ошибка, проблема была в том, что у меня не было "Bonegroups" в моей модели, я понятия не имею, как это произошло.

**Comment by PavelBlend** [comment]
@Blackgrowl можешь прислать мне blend файл на почту?

Возможно стоит сделать предупреждение в аддоне при экспорте таких объектов. Но пока я не до конца понял суть проблемы. Мне нужны исходные файлы blend. Ну и object, ogf тоже можешь скинуть. И папку gamedata в которой ты тестируешь эту модель (если эта папка не много весит). Если папка gamedata большая, то скажи как ты добавляешь на карту модель, чтобы я сам смог создать тестовый уровень и в игре увидеть такое поведение?

**Comment by Blackgrowl** [comment]
Не беспокойтесь об этом, проблема была в том, что мне не хватало "Bonegroups", так что, по сути, мне не хватало информации о скелете, чтобы все это работало должным образом.

Я не думаю, что есть что исправлять, это была ошибка пользователя, ничего общего с SDK или плагином.

**Comment by Blackgrowl** [comment]
Ну, я попробовал снова, у этого есть "Bonegroups", о которых я постоянно упоминаю, но он все еще распадается, когда умирает.

Возможно, это эффект обновления Blender или PavelBlend?

Я слишком много говорю, вот файлы. https://transfer.sh/g0u93f/Beril%20Zombie%20with%20Broken%20Glass.blend
Что я сделал, так это экспортировал это как .object (нацелившись на скелет), с опциями Format "CS/COP", Smoothing "Normals" и остальными не отмеченными.

Затем я открываю CoP SDK, Actor Editor, снимаю галочку "Make Progressive", но ставлю галочку "HQ Geometry" и просто экспортирую его как .ogf.

Я думаю, что проблема может заключаться в "Папке объектов"?
Тогда у нас этого не было, и я не использовал ее до сих пор, но папка в основном пуста.
Нашла ли модель .bones внутри моего .blend файла?

Я знаю, что если я извлеку оригинальный .ogf's .object и .bones, а затем импортирую этот новый извлеченный .object в мой текущий .blend файл, он работает нормально.

**Comment by PavelBlend** [comment]
@Blackgrowl я посмотрел файл. У костей неправильные типы. Нужно использовать Rigid или Joint, вместо Cloth и None.
![011](https://user-images.githubusercontent.com/7983249/147259683-6ac26c44-f01d-4f9c-a990-51c0d31dad2c.jpg)

В игре был такой результат:
![11212](https://user-images.githubusercontent.com/7983249/147259780-a8ce1a12-fb80-4196-a9e0-2c074beaecdb.jpg)

**Comment by Blackgrowl** [comment]
Большое спасибо, я ценю помощь, которую вы оказываете.
