### ISSUE TITLE
Сломался импортёр .object за 2001-2004

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#451]
![image](https://user-images.githubusercontent.com/56885075/148204727-9d826c69-43ac-4a4d-ac3e-49a6a55c6f0f.png)

Какую модель из слива не возьми, не переваривает.

Самая последняя версия аддона 2.9.2.

Модельки для примера + 1 одна из 2005 проверочная.

[actors.zip](https://github.com/PavelBlend/blender-xray/files/7814345/actors.zip)

**Comment by PavelBlend** [comment]
@SamArtGit починил. Фикс в последнем коммите. Релиз позже сделаю.
При импорте таких костей будет предупреждение:
`Не найдена родительская кость: {'parent': 'bip01', 'child': 'bip01_pelvis'}`
Кость таза `bip01_pelvis` имеет родителя с именем `bip01`, но самой кости `bip01` нет в файле, поэтому таких родителей аддон игнорирует и выдаёт предупреждение.
