### ISSUE TITLE
Добавить предмет в руку персонажа

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#453]
Здравствуйте.

Я пытаюсь найти способ заставить это работать, но, похоже, не могу, поэтому я подумал, что мой единственный шанс сейчас - это спросить.

Во-первых, что я хочу сделать...
У меня есть модель оружия, это "модель мира", я хочу сделать так, чтобы она держалась на руке NPC персонажа, а также чтобы она двигалась, когда персонаж двигается.

Однако есть разные проблемы:
Например, я не могу найти ни одного хорошего метода. Я пробовал "Child of", но это относится к третьей проблеме.
Во-вторых, даже если у меня все получится, он не очень хорошо "двигается", может быть, это ошибка, связанная с анимацией?
И третья проблема - это неточность, а я бы хотел, чтобы она была точной (насколько это возможно, если идеальная невозможна), чтобы я мог исправить положение в игре без необходимости начинать игру бесчисленное количество раз.

Вот в чем мой вопрос. Есть ли у PavelBlend способ заставить это работать или хотя бы облегчить процесс? Я был бы рад получить руководство, если это возможно.

Если нужно, вот .blend файл моей попытки:
https://transfer.sh/T6Elih/KnifeAttempt.blend

И фотография того, как это выглядит в игре:
![image](https://user-images.githubusercontent.com/60915973/149482745-7af9360c-0b45-4dfd-8fda-b600cb70c460.png)

**Comment by PavelBlend** [comment]
@Blackgrowl а какая часть игры? ТЧ, ЧН или ЗП? И какие параметры конфигов ты редактируешь?
Я в таких ситуациях обычно использую констрейнт Copy Transforms.

**Comment by Blackgrowl** [comment]
WP - это оружие? Для данного примера - да.

Я могу без проблем предоставить вам файл конфигурации, возможно, это поможет.

Также я забыл сказат
[m_knife.zip](https://github.com/PavelBlend/blender-xray/files/7870283/m_knife.zip)
ь, что это для "Anomaly", которая основана на X-Ray 1.6, Call of Pripyat, хотя они внесли некоторые изменения и называют ее "Monolith X-Ray".
В любом случае, считайте это CoP.

Я попробовал "Copy Transforms", но это не кажется надежным, возможно, я должен поставить "позицию" из конфигурации оружия? Но с этим модификатором она не меняется.

**Comment by PavelBlend** [comment]
@Blackgrowl я пока не до конца решил эту проблему, но я кое-что выяснил:
привязывать оружие нужно не к руке (кость `bip01_r_hand`), а к указательному пальцу (кость `bip01_r_finger1`). Это указано в конфиге `gamedata\configs\actor.ltx`, параметр `weapon_bone0`.

**Comment by shadept-GitHub** [comment]
Эту проблему ещё не исправили в новых релизах, да?

**Comment by PavelBlend** [comment]
@shadept-GitHub я пока не разобрался. Обнулил вращение и позицию ножа и нож всё равно повёрнут. Я не выяснил почему так происходит.

**Comment by Blackgrowl** [comment]
У меня есть хорошие новости, я нашел способ сделать это правильно, или, по крайней мере, я надеюсь, что это так. Это не совсем "чисто", но это самое точное, что я получил.
Вот видеогид: https://www.youtube.com/watch?v=CHk9Jslqxec
