### ISSUE TITLE
После экспорта слегка измененных .object файлов и их преобразование в .ogf файлы через СДК игра вылетает.

### ISSUE THREAD

**Issue by shadept-GitHub** [PavelBlend/blender-xray#461]
**Описание проблемы:** 

Экспорт слегка измененного .object файла и преобразование его в самом обычном пропатченном СДК 0.4 ТЧ в формат .ogf приводит к вылету игры при загрузке локации, где данная модель используется. **_КРАШ ЛОГА НЕТ, ИГРА ПРОСТО ЗАКРЫВАЕТЬСЯ И В ПАПКЕ _appdata_/logs/xray_user.log ФАЙЛ ПУСТ._**

**Как воспроизвести ошибку:**

1. Запустить blender c адонном
2. Установить путь в gamedata в папку ТЧ
3. Загрузить любой файл .ogf с тень чернобыля, 
4. Слегка изменить его вертексными манипуляциями и экспортировать в .object файл. 
5. После этого загрузить файл в СДК 0.4 тень чернобыля (к примеру репак от Yurshat (https://yadi.sk/d/_gAdYFEMtrQkUw) и экспортировать файл как .ogf в папку совпадающею с оригинальной моделью самой игры. 
6. Запустить игру и загрузить сохранение или же начать новую игру, где будет использоваться модель. Игра вылетает при загрузке локации.

**Ожидаемое поведение:** 
Игра запускается нормально и модель видно в игре без вылетов.

**Версии ПО:** 
- OS: Win10 x64 (Windows 10 Version 21H2)
- Blender: 2.92.0

**Дополнительная полезная информация:** До этого я мог спокойно экспортировать модели и делать абсолютно любые изменения и все это работало в игре. Теперь же ХЗ почему такого больше нету. Не уверен, но раньше у меня возможно был включен DEP как на картинке, а может и не был. Сейчас он точно выключен. Вот картинка как оно могло выглядеть. ![image](https://user-images.githubusercontent.com/65095770/151898521-5c8d5bc6-b758-4a34-aebe-89e731583ce2.png)
Кроме этого я не понимая использовал функцию File > Import... в СДК вместо File > Load... Теперь не имеет разницы как я импортирую .object файлы в СДК - игра все равно вылетает.

_П.С: Извиняйте за чуть запоротый русский. Я большую часть времени говорю по-английски в инете. И вообще русский для меня не родной язык._

**Comment by PavelBlend** [comment]
@shadept-GitHub у меня ошибка не появляется. Возможно следующее:
 - ошибка воспроизводится всё таки не на любом файле. Я импортировал `equipments\novice_suit.ogf`, сделал экспорт в object и потом в сдк в ogf и ошибки нет. Потом проверил на скелетной модели, которая использует анимации: `actors\bandit\stalker_bandit_3.ogf`. Я ещё поменял текстуры местами, чтобы модель было легче опознать:
![01](https://user-images.githubusercontent.com/7983249/151962081-934ed6a5-54e5-424c-b8ca-04b5162d388b.jpg)
![02](https://user-images.githubusercontent.com/7983249/151962091-127bfdba-0c44-4b0e-9cf2-702aeecf71d5.jpg)
 - Ошибка не в аддоне, а в сдк, который неправильно сохраняет ogf. Сейчас самый актуальный сдк находится здесь:
https://www.gameru.net/forum/index.php?s=&showtopic=59990&view=findpost&p=1699318
СДК от YURSHAT устарел и его никто не поддерживает.

**Comment by PavelBlend** [comment]
@shadept-GitHub можешь дать мне gamedata папку, в которой появляется эта ошибка? У меня есть движок 1.0007, который всегда вылетает с логом. Я посмотрю текст ошибки. Сам движок находится здесь:
https://github.com/PavelBlend/xp-dev_xray/releases/tag/build-5578-demo-record

**Comment by PavelBlend** [comment]
@shadept-GitHub есть ещё такое предположение: объект не имеет bone parts. Хотя если делать импорт ogf, они должны импортироваться, если в файле есть анимации. А если в файле их нет, то проверь корректность bone parts в omf файле, который использует данный ogf. Нужно, чтобы имена костей совпадали.

И я ещё проверил сдк по твоей ссылке, у меня всё работает. Так что проблема не в сдк. Может какие-то параметры модели неправильные.

**Comment by shadept-GitHub** [comment]
Все-таки решилось всё тем, что я поставил сбору СДК поновее.
