### ISSUE TITLE
An improvement for exporting with various Image Texture nodes.

### ISSUE THREAD

**Issue by Blackgrowl** [PavelBlend/blender-xray#469]
Hey there, I have been using this tool for so long that at first I was sceptical about it, but the author himself has proven that he knows his scripts and will answer to any issue, so not helping in this aspect would be an insult not just to him, but to all of us.

Anyway, excuse the theatrics, let's get to action...
**Make it possible to PICK an "image texture"**
One of the things I find frustrating with Pavelblend is that, I am using two image textures because the 2nd one is a bump-map.
But then Pavelblend will give me an error about "too many image textures".
I believe a solution to this is very simple: Let the "selected" Image Texture in the Node Editor be the one and only to be taken in mind.

Here is an image example, notice how the one on the top is highlighted in white borders, unlike the one at the bottom:
![image](https://user-images.githubusercontent.com/60915973/155094050-d2390746-06ac-4a63-a301-ab0f58191c35.png)

One problem I see with this is that, you have to make sure you pick that one, not the other, else it will be using "Image Texture" as the texture pathway. But this solution is also easy for the user; just have the other Image Texture node (which is the bumpmap for me) have the same node Name & Label.
Also, I believe that you should be using "NodeWrangler" for this to work more efficiently, which is no problem since it's an already-available plugin after Blender 2.7+.

Also I think I should call this a bonus:
I have noticed you were having issues with finding out how to make STALKER Normal Maps work in Blender.
I believe I did find a way, so I will give you a .blend file, in there you should see how I set the scene in my node editor and this Nodegroup called "STALKER Converted Normal Map", hopefully it will help you in some way.
[Beretta 92FS.zip](https://github.com/PavelBlend/blender-xray/files/8115026/Beretta.92FS.zip)

I hope this helps in the improvement of PavelBlend.

**Comment by PavelBlend** [comment]
@Blackgrowl Hi.



> Let the "selected" Image Texture in the Node Editor be the one and only to be taken in mind.

this can cause problems. The user will always have to check active nodes. The exporter requires a single texture to avoid ambiguity and to make the image selection logic easy to understand.

Here is an ambiguous and indefinite case:
![02](https://user-images.githubusercontent.com/7983249/155130637-9acad3b4-c4aa-4cf9-9b44-dc62731e7601.jpg)

This may confuse the user. In solid mode, one image, and in material preview mode, another.
The exporter logic becomes more complex, can introduce ambiguities, and requires the user to do extra work to check for active nodes.

**Comment by Blackgrowl** [comment]
Hey Pavel, from what I understand, you have the method set that way to keep it "user-safe", but I would rather prefer it "user-friendly" myself.

Is there any way you can make it an option, then? Something like, "Ignore more than one material error" and put it in Others?

I know that there would be an issue like this, but honestly, I consider it more work to remove an image, especially my method of using a bumpmap, when I can just select which texture it is to export.
And as I have written in the main post, I can just set the Name & Label to be the same as the other Image Texture.

**Comment by PavelBlend** [comment]
> my method of using a bumpmap

exporters do not require bump maps. Are you only using them for rendering?

I can do like this:

if the material has 1 image node, then the image search algorithm will be the same as it is currently used.
But if the material has more than one image node, then the exporters will use the active node.
In such a case, the export will print warnings to the log file to inform the user that the material has many image nodes.
But a situation may arise when the material has more than one image node, and not a single image node is active. In this case, the export will stop, since the exporter does not know which node from the set to use.

**Comment by Blackgrowl** [comment]
Alright, I like your suggestion, please do it like so.

As for the bump map, yes, I am only using it for rendering, but I also have to constantly check it again, because the normal map or specular might need fixing, as well as to check if any "smoothing errors" are handled by the normal map, which means I require to re-add the normal map and node setup, when simply making an image texture will do.

**Comment by PavelBlend** [comment]
@Blackgrowl I did. The changes are in the develop branch, latest commit.
If the material has one image node, then it will be used when exporting, regardless of whether it is active or not.

If the number of nodes is more than one, then the texture search will be like this:

- First, the active Material Output is searched, then the shader bound, then the texture bound to the Base Color or Color socket:
![01](https://user-images.githubusercontent.com/7983249/155381435-5f0309fb-cad9-4157-99a2-2626f6f1c960.jpg)

- If the first check fails, then the active image node is used, if it exists:
![02](https://user-images.githubusercontent.com/7983249/155381623-6f264917-3ef8-4fb9-a700-50168148d3be.jpg)

- If there is no active node, then the selected node is exported if it is the only one selected:
![03](https://user-images.githubusercontent.com/7983249/155381700-eaea3bf8-9173-47d4-9a49-6cde4951be72.jpg)

- If more than one node is selected, the export stops.
![04](https://user-images.githubusercontent.com/7983249/155381804-9f25b295-7e73-4058-9edf-2925d179f814.jpg)
