### ISSUE TITLE
Проблема с моделькой худа оружия после экспорта в OGF.

### ISSUE THREAD

**Issue by VovaMiller** [PavelBlend/blender-xray#474]
#### Краткое описание проблемы:
Экспортирую в формат OGF модельку худа оружия, буквально без изменений, после чего рука почему-то смещается в сторону.

#### Как воспроизвести ошибку:
1. Импортируем OGF-модельку худа оружия.
2. Сразу же без каких-либо изменений экспортируем как OGF.
3. Видим смещение руки (непосредственно в игре или при повторном импорте).

Пробовал на этой модельке: https://disk.yandex.ru/d/1Lresd9Uryl29A
Там смещение правой руки хорошо видно по анимации reload.
До экспорта: https://ibb.co/LrYBW8d
После экспорта: https://ibb.co/QDjvdPx

#### Версии ПО:
 - OS: Win10 x64,
 - Blender: version: 2.82 (sub 7), branch: master, commit date: 2020-03-12 05:06, hash: 375c7dc4caf4, type: Release
 - blender-xray 2.13.1

#### Дополнительная полезная информация:
Пробовал сделать то же самое на модельках из оригинального ТЧ - там проблемы не обнаружил.
Эту модельку АКС-74у взял из мода на движке OGSR Engine x64 (build: SEP. 30 2020), может там какая-то своя специфика? Хотя на оригинальном движке модельки оттуда отображаются как надо.
Если экспортировать в формат object, то бага нет. Однако мне как-то в итоге приходится конвертировать в OGF. Единственный известный мне способ - через X-Ray SDK Actor Editor, но тот не очень дружит с некоторыми модельками (ругается на Invalid Smooth Group; у этой АКС-74у такого нет).
Так что пока приходится через X-Ray SDK Actor Editor сначала извлекать анимации в формате OMF, а в Blender уже все анимации внутри убирать и оставлять только ссылку на внешний файл - тогда можно будет конвертировать сразу в OGF и проблем не будет, но получается мудрённо. Было бы круто, если можно было обойтись без этих танцев с бубном.

**Comment by PavelBlend** [comment]
@VovaMiller ошибку воспроизвёл на блендере 2,82. Но в новой версии 3,2 её нет. Хотя код одинаков для обоих.
Пока обнови блендер, так как я не знаю как быстро решить эту ошибку. Возможно это баг самого блендера 2,82, а не аддона. Нужно выяснять. И 2,82 довольно устарел.

**Comment by PavelBlend** [comment]
@VovaMiller исправил. Фикс в последнем коммите в ветке develop.
