### ISSUE TITLE
Не работает переключение анимаций в списке анимаций объекта.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#475]
Приходится переключать через Action Editor. Самый последний релиз (ого, уже 2 месяца прошло после последнего обновления аддона).

Скриншоты приложиться не могу ибо ужасная скорость интернета.

**Comment by PavelBlend** [comment]
@SamArtGit твои issue прочитал, но я пока не занимаюсь аддоном. Issue будут открыты и я к ним вернусь, когда будет желание дорабатывать аддон.
