### ISSUE TITLE
Изменять размер .bones

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#476]
Не помню, обсуждалось ли это, но когда импортируешь объект с анимациями, изменяешь размер (к примеру 1.2 или .09), применяешь (Ctrl + A, Scale) и экспортируешь в .object, или .skls, или .omf, размер анимаций изменяется в соответствии с размером объекта. Но параметры .bones остаются прежними!

**Comment by PavelBlend** [comment]
@SamArtGit я ещё не добавил эту возможность в текущую версию аддона. Та версия, которая у тебя содержит ошибки при экспорте в ogf. Я хочу переписать нормально, но позже. Так что я открою эту issue.
