### ISSUE TITLE
Force 16bit MotionT [export omf]

### ISSUE THREAD

**Issue by LittleBabyGABE** [PavelBlend/blender-xray#478]
### Discussed in https://github.com/PavelBlend/blender-xray/discussions/457
После продолжительной работы с фичей заметил баг. Как и ожидалось 16-битный экспорт убрал тряску в транслейте, но оказывается он не совсем корректно экспортирует положения (и кажется! вращение) костей. При этом 16-битный весит чуть меньше чем 8-битный, что странно.

Прогнал через сдк, сдк справился как надо, положения и вращения корректные, тряски нету, вес больше чем при экспорте в 8-бит. Т.е всё логично и корректно. При этом вес 16-битного из сдк с тем-же самым набором анимаций становится примерно 180кб.

На картинках видно разницу особенно сильно на мизинце, его положение и вращение такое как мне надо в 8-бит, а 16-бит даёт нежелаемый результат.
![8_bit](https://user-images.githubusercontent.com/98260026/164514185-aec18c20-a78e-4542-85e4-66bb801d692f.png) - 8 бит, вес 162кб - такой результат GOOD!
![16_bit](https://user-images.githubusercontent.com/98260026/164514176-bc1eb00b-cb7c-4ad2-897e-1adb1385dff0.png) - 16 бит, вес 158 кб - вес меньше, результат meh...

Гарантирую что позы идентичны на первой и второй картинке.

**Comment by LittleBabyGABE** [comment]
Решение проблемы - 

файл - io_scene_xray\omf\exp.py

Строка:
eps = 0.0000001 заменил на eps = 0.00000000001. 

вес с 9 нулями после точки - 196кб
вес с 10 нулями после точки - 197кб

Позы корректные, дёргания транслейта нету, всё как надо в обоих случаях(9 и 10 нулей).

В теории можно обойтись и 9 нулями для релизной версии

**Comment by PavelBlend** [comment]
@LittleBabyGABE посмотрел код. Скорее всего в экспорте логическая ошибка. Eps значение нужно не в виде константы, а рассчитанное для каждой кости, в зависимости от амплитуды движения.

Файл для себя добавляю:
[hq_omf_export_bug.zip](https://github.com/PavelBlend/blender-xray/files/9063605/hq_omf_export_bug.zip)

Буду выяснять, как исправить. Возможно эта ошибка связана с  #474
