### ISSUE TITLE
Не экспортируется скелет в .object

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#480]
#### Краткое описание проблемы:
При экспорте в .object не сохраняется скелет

#### Как воспроизвести ошибку:
Импортировать в .object файл

#### Ожидаемое поведение:
Object, судя из формата файла, должен включать в себя и скелет для меша.

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 3.2.1 Из Steam

#### Дополнительная полезная информация:
Blend сцена - [Gunslinger_BACKPACK.zip](https://github.com/PavelBlend/blender-xray/files/9064908/Gunslinger_BACKPACK.zip)
Пытаюсь импортировать рюкзак вместе со скелетом

**Comment by PavelBlend** [comment]
@TheParaziT объекты не правильно настроены. Сейчас я ошибку не вижу, так как при таких объектах это ожидаемое поведение. Чтобы экспортировать скелет, нужно назначить меш рюкзака (объект `bag_r_low`)  в качестве потомка скелету (объект `backpack_armature`). Это делается с помощью `Ctrl + P` > `Object`. Потом нужно включить параметр `Object` у арматуры. У меша этот параметр автоматом выключится, если он будет является потомком арматуры.
![arm](https://user-images.githubusercontent.com/7983249/177812280-531b56dd-4d90-4dfd-b194-8066b5ac6415.jpg)
![mesh](https://user-images.githubusercontent.com/7983249/177812295-aff4abb2-c65a-46e1-8e92-9c3f1d6b30de.jpg)
Потом нужно выделить root-объект (в данном случае это арматура с включённым параметром `Object`) и делать экспорт.

**Comment by TheParaziT** [comment]
Крайне благодарен
