### ISSUE TITLE
Поддержка split нормалей для формата *.object

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#481]
Дать возможность сохранять нормали для сглаживания в формат `*.object`, чтобы была возможность использовать их в правленом сдк.

**Comment by PavelBlend** [comment]
В этом коммите текущая версия с поддержкой нормалей:
ee60183272ab71ff726da84538e9757795b7f91b

@StalkMen можешь проверить на правленом сдк эту возможность? В настройки аддона была добавлена галочка `Use *.object Split Normals` в категории `Others`, которую нужно включить.

Ты когда-то просил сделать их поддержку и я сделал её опциональной. Смотрел код из твоего репозитория:
https://github.com/StalkMen/blender-xray/tree/52dccad376ab19ad578275059162e5889715ec0d
Будет ли твоя версия аддона правильно работать, если модель не триангулирована?

**Comment by PavelBlend** [comment]
Сделал: e3d52297b5fbb2e9cc42534cda02aa972b8ef2e3

**Comment by StalkMen** [comment]
Надо пробовать, но думаю шо без триангуляции никуда.
А что там с порядком осей в векторах?

**Comment by PavelBlend** [comment]
В последнем коммите я всё исправил: e3d52297b5fbb2e9cc42534cda02aa972b8ef2e3
Порядок осей для нормалей XZY. Проверял на этой программе:
https://ap-pro.ru/forums/topic/3577-object-editor-v30/
Она поддерживает сохранение нормалей из object в ogf, без использования групп сглаживания.

Ещё в настройки аддона была добавлена галочка `Use *.object Split Normals`. Её нужно включить.

**Comment by StalkMen** [comment]
Будем посмотреть

**Comment by SamArtGit** [comment]
Не скромный вопрос(ы) - что такое:

1) Split Normals?
2) Через Object Editor от Валеры можно экспериментировать в .ogf? Прикол, завтра проверю. Тогда вместо этого другой вопрос: что такое группы сглаживания. Слышал что это 3Д Максимовская штука.
3) Помню давно была добавлена функция при экспорте записывать сглаживание для модели на основе нормалей, помимо помеченных острых рёбер. Это не тоже самое, что и Split Normals? На основе экспорта сглаживания при помощи нормалей генерируются помеченные острые грани?
4) Стал пользоваться ТЧ сглаживанием, ибо СДК 0.7 бьёт ЧН/ЗП сглаживание при экспорте в OGF (Actor Editor от SDK от DaaGuda, где входит в комплект фикс сглаживания), но при экспорте выдаёт предупреждение в Blender, что модель имеет одну и ту же группу сглаживания. Из-за чего на примере экспорта модели кабана из исходников ЗП, у которого помечены острые рёбра на основе шерсти, которая растёт от тела, но сами мешы разделены, из-за чего получается дубликат помеченных рёбер, то при экспорте в ТЧ сглаживание и повторном открытии дублирующаяся острота рёбра исчезает.

Самые последние версии Blender, Windows и аддона (как всегда).

**Comment by PavelBlend** [comment]
@SamArtGit
1 - Split Normals - это нормали для loop'ов или face corner (углы полигона), которые используются для затенения и сглаживания. Вот включаются нормали для вершин:
![01](https://user-images.githubusercontent.com/7983249/178246807-65a183ff-957b-4810-a487-09a786dd65f4.jpg)

А вот включаются Split Normals:
![02](https://user-images.githubusercontent.com/7983249/178246822-b7c7ac9d-889d-4efe-8a24-babf66d4c73b.jpg)

Одна вершина может иметь одну вершинную нормаль, но одна вершина может иметь много split normals. Эти направления split нормалей можно менять:
![03](https://user-images.githubusercontent.com/7983249/178247849-7d19672f-86b8-4572-860a-cc6ce4b5b061.jpg)

До этого нельзя было сохранить эти направления, а сейчас можно.

2 - Object Editor сохраняет split нормали из object файла в ogf. А обычный сдк генерирует направления нормалей на основе групп сглаживания.

3 - Эта функция учитывает split нормали только для того, чтобы определить какие рёбра помечать как edge sharp. Но сами нормали не сохраняются. Вектора, направления нормалей не сохраняются. Экспорт сохраняет обычные группы сглаживания. Изначально формат object не поддерживает нормали для сглаживания.
