### ISSUE TITLE
default values not saved

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#49]
При изменении default-значений в коде аддона, эти значения применяются к blend-файлам, сохранённым в предыдущей версии аддона.
Т.е. если мы когда-нибудь поменяем `gamemtl` у кости с `'default_object'` на новое значение, то это новое значение будет использовано при открытии существующих blend-файлов для всех костей, для которых пользователь явно или неявно выбрал `'default_object'`, т.е. поменяет поведение уже ранее созданных объектов.
Наличие этой ишью не позволяет нам менять default-значения у свойств в коде.

**Comment by igelbox** [comment]
my message in bf-commiters mailing list: http://lists.blender.org/pipermail/bf-committers/2015-February/045003.html

**Comment by PavelBlend** [comment]
Мне кажется нерационально сохранять в blend файле все свойства, даже те, которые не были изменены. И свойства будут меняться после каждого редактирования из питона. И от этого никуда не деться. Такое побочное действие данной оптимизации.

Может закрыть данную issue?

**Comment by igelbox** [comment]
Обновил описание. Я бы не стал закрывать эту ишью, т.к. я всё ещё вижу тут проблему. Хотя, это навреное и не баг совсем, т.к. баг - проблема, возникающая у пользователя, а тут проблема возникает у нас - разработчиков.

**Comment by PavelBlend** [comment]
Эта проблема была давно решена с помощью `handlers` при создании/загрузке блока данных. Вот пример кода для материала:
https://github.com/PavelBlend/blender-xray/blob/b8a3c3d8a1118ed940bea6c1b8c53b7503182e3d/io_scene_xray/props/material.py#L35

Значение `eshader` по-умолчанию (`models\model`) не было изменено, но в коде, при создании нового материала, значение `eshader` устанавливается на `default`.

Поэтому закрываю эту issue.
