### ISSUE TITLE
Заставить Load Active Motion Reference работать

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#505]
😀

**Comment by PavelBlend** [comment]
@SamArtGit а можно поподробнее? У меня всё работает. Нужно в настройках указать путь к rawdata\objects и копировать в него skls (именно skls, не omf). И в skls браузер должны добавиться анимации, если клацнуть по reference. В список Motions анимации добавляться не должны.

**Comment by SamArtGit** [comment]
Завтра проверю.

**Comment by SamArtGit** [comment]
Перегнал в .skls из stalker_animation.omf  через https://github.com/VaIeroK/Omf-Editor и поместил в rawdata\objects\actors. Не работает.

https://user-images.githubusercontent.com/56885075/180845853-6a64b32d-2d28-40db-8fe0-23471889c499.mp4

**Comment by PavelBlend** [comment]
@SamArtGit а папка rawdata\objects в настройках точно правильно указана? И что в консоли пишется (Window > Toggle System Console)?

**Comment by PavelBlend** [comment]
Вот видео:
https://user-images.githubusercontent.com/7983249/180853057-796c7272-ba1a-47d0-803f-4b4e916437e8.mp4

**Comment by SamArtGit** [comment]
Выяснилось, что проблема в том, что в ЗП СДК (лично у меня сборка от DaaGuda, но в оригинальном такая-же структура) динамические модели лежат по пути rawdata\objects\dynamics\actors, из-за чего блендер не находил файл. Переместил в rawdata\objects\actors, всё работает. Но всё равно надо что-то делать, ибо не удобно. Сделал бы чтобы оно подгружало именно .omf, ибо зачем нужен .skls если у аддона есть возможность сразу-же экспортировать в .omf? А если надо подправить какую-то анимацию, то проект в Блендере в помощь. Ну и как-то научить программу, чтобы если не нашёл соответствующую папку, то чтобы шёл дальше по папкам и нашёл подобную \actors с анимации.skls.

**Comment by PavelBlend** [comment]
@SamArtGit сделал предупреждение:
![01](https://user-images.githubusercontent.com/7983249/181098297-676867f2-41f6-4b60-b4ca-61bf984998d1.jpg)

Я думаю, что аддон не должен сам искать во всех вложенных папках нужный skls.
