### ISSUE TITLE
Не работает создание presets в настройках аддона

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#506]
Указываю пути к ЗП СДК, создаю предмет и называю CoP, меняю пути на ТЧ, создаю SoC. В итоге при переключении оно путается и всё через Жору. Надо сниму демонстрацию завтра.

**Comment by PavelBlend** [comment]
@SamArtGit сейчас проверил. У меня работает. Скажу сразу:
сначала нужно указать настройки и только потом нажать на плюсик. Не наоборот. При нажатии на плюс, в пресет добавится то, что настроено в данный момент.

**Comment by SamArtGit** [comment]
Работает! Не знаю допрёт ли среднестатистический пользователь, но я не допёр. Сделать бы подсказку при наведении мышки или на Wiki объяснение.

https://user-images.githubusercontent.com/56885075/180848111-ea9435f6-54c4-40f4-9356-2ae6da4c5cd3.mp4

**Comment by PavelBlend** [comment]
@SamArtGit таким образом работают все пресеты в блендере. Так что для блендера это стандартное поведение. Даже в Cycles Render есть такие же пресеты для Light Paths.
