### ISSUE TITLE
Возможность импортировать и экспортировать Light Elements

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#514]
#### Описание идеи:
Добавить возможность импорта и экспорта Light Elements. В качестве заменителя для Blender, можно было бы использовать Light Source в Blender

#### Примеры использования:
В создании уровней

**Comment by PavelBlend** [comment]
@TheParaziT а Light Elements - это источники света из LevelEditor, которые задаются в Edit Mode > Light?

**Comment by TheParaziT** [comment]
Да

**Comment by PavelBlend** [comment]
Подумав над эти запросом, всё таки решил не реализовывать его. Источники света не относятся к форматам 3д моделей. Не хочется в 3д редакторе редактировать объекты, которые косвенно относятся к 3д мешам. Да и придётся использовать костыли, чтобы свет в блендере был похожим на свет в СДК. Это может отнять немало времени. Лучше свет редактировать в level editor. Иначе это может потянуть за собой желание реализовать импорт glow, waypoints, spawn и т. д. А этого делать не хочется, так как сложно будет поддерживать аддон. Лучше потратить силы на форматы 3д мешей.
