### ISSUE TITLE
import: bones too large

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#53]
e.g. finger bones in weapons\ak74\wpn_ak74_hud
![large-bones](https://cloud.githubusercontent.com/assets/5264687/4783182/98f44eca-5d1b-11e4-9755-24588faffaed.png)

**Comment by PavelBlend** [comment]
Можно сделать по-умолчанию размер костей в 0.01 blender unit. И добавить возможность указать размер кости при импорте. И выставлять режим отображения костей в Stick, так как в Octahedral при размере костей в 0.01 их практически не видно.

**Comment by igelbox** [comment]
Уменьшил кости, кости используют кастомные шейпы хитро-рассчитанных размеров.
Как такой вариант?
