### ISSUE TITLE
export-object: add SoC/MAX smoothing groups support

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#57]
not all geometries can be represented in SoC/Maya format, e.g. objects/props/objects/dekor/vedro_01.object from SoC SDK 0.4
MAX
![sg-max](https://cloud.githubusercontent.com/assets/5264687/10147985/be69ed0e-6639-11e5-9395-b90a1d49fc0a.png)

Maya
![sg-maya](https://cloud.githubusercontent.com/assets/5264687/10148035/050df1ce-663a-11e5-88ea-e25b53c3d503.png)

**Comment by PavelBlend** [comment]
Может плагин на данный момент не правильно импортирует MAX группы?
Я загрузил objects/props/objects/dekor/vedro_01.object
Там внизу ручки есть треугольник, который не сглажен (Shade Flat), но его рёбра почему-то не помечены как Sharp. Вот скриншот.
![bug_sg_max_type](https://cloud.githubusercontent.com/assets/7983249/21076899/5f5c18d6-bf49-11e6-9234-b34ba9d8cdc8.png)
Если нажать Shade Smooth, то этот треугольник станет Smooth:
![test_sg_max_type](https://cloud.githubusercontent.com/assets/7983249/21076905/85415246-bf49-11e6-94ad-fe6413970185.png)
Помоему, плагин делает этот полигон не сглаженным, но почему-то забывает пометить Sharp Edges.

**Comment by igelbox** [comment]
Похоже на багу, т.к. в SDK эти рёбра выглядят острыми.
Заведи, пожалуйста, это отдельной issue (т.к. эта - про экспорт, а не про импорт).

**Comment by igelbox** [comment]
Blender вроде бы [поддерживает](https://docs.blender.org/api/blender_python_api_current/bpy.types.Mesh.html#bpy.types.Mesh.calc_smooth_groups) нужный алгоритм расчёта групп сглаживания. Но он, к сожалению, не работает со сложными случаями (например: гладкая icosphere с одним острым ребром).

**Comment by PavelBlend** [comment]
Может быть не стоит реализовывать MAX формат групп сглаживания? Он ничем не отличается от Maya формата, за исключением того, что имеет меньшее количество групп сглаживания (32 максимум). А в плане возможностей он такой же, как и Maya. То есть у него те же ограничения, как и у майского формата (нельзя сохранить сглаженную икосферу с одим острым ребром).

Я наверное закрою данную issue.
