### ISSUE TITLE
Возможность импорта анимационного канала для определённой кости

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#570]
#### Описание идеи:
Возможность импорта анимационного канала для определённой кости из .skl (и если возможно из .omf)

#### Примеры использования:
При импорте анимации все анимационные каналы импортируются в сцену из анимации, но бывает и такое, что нужен именно анимационный канал для определённой кости (к примеру, для lead_gun кости), т.к. нет надобности в редактировании ключей для других костей.

![aug_bas_test](https://user-images.githubusercontent.com/62593770/181462710-5f4b100d-ccd4-4605-8303-f527d9607961.png)

![aug_bas_test_1](https://user-images.githubusercontent.com/62593770/181462808-119a7306-e53d-46e7-991f-0749925e441b.png)

**Comment by PavelBlend** [comment]
@TheParaziT можно импортировать все каналы, а потом лишние удалить. Или скопировать нужные и вставить в свою анимацию.

И эта возможность похожа на излишество. Редко такое может пригодиться. Всё таки, чаще всего, нужно импортировать всю анимацию, и смотреть, какие каналы нужны, а какие нет. Придётся в интерфейс добавлять новый параметр импорта и усложнять логику импортёра.

И я не хотел бы добавлять новые параметры импорта без особой нужды.

**Comment by TheParaziT** [comment]
@PavelBlend да, понимаю, что запрос очень специфический, но в монотоной работе, где добавлять анимации только с определенными каналами пригодилось бы, но ладно.
