### ISSUE TITLE
Сделать проверщик обновлений дополнения.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#572]
По аналогии как у [ScreenCast Keys](https://github.com/nutti/Screencast-Keys). У nutti удобно, что можно даже выбрать ветку.

**Comment by PavelBlend** [comment]
@SamArtGit такой запрос уже есть: #92 
Я посмотрю код ScreenCast. Насчёт выбора веток, не знаю, так как в ветках может быть сырой код. Лучше только из релизов проверять, так как у пользователей могут быть ошибки и проблемы. А релизы более стабильные.
