### ISSUE TITLE
polygons with same vertices glued together

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#58]
e.g. SoC:/objects/trees/new_trees/trees_topol_1_01.object

bmesh.new(..) automatically glues similar polygons

**Comment by PavelBlend** [comment]
Есть предложение, как исправить этот баг. Можно сделать галочку при импорте "Импортировать файл отдельными мешами". Чтоб один объект имел только один материал. Разделить по материалам короче. Тогда конфликта с одинаковыми полигонами не будет, так как они будут находится в разных мешах.

**Comment by ghost** [comment]
Скорее всего это сама модель такая, так как плагин не делает проверку на дублированные вершины и инвалидные полигоны. Протестировал на модели бочки, импортировал, выделил вершины и разрезал клавишей V, после чего экспортировал и импортировал - вершины такие же, какие были до экспорта.
[bochka_01.object.zip](https://github.com/igelbox/blender-xray/files/233058/bochka_01.object.zip)

**Comment by PavelBlend** [comment]
Нет. Тут баг в другом. Просто есть некоторые модели (например SoC:/objects/trees/new_trees/trees_topol_1_01.object) у которых полигоны одинаковые встречаются. Не дублированные вершины и не инвалидные полигоны, а просто одинаковые. То есть один полигон может быть в виде (3, 2, 5), и второй тоже (3, 2, 5). Модуль bmesh (который используется в плагине) автоматически удаляет одинаковые полигоны, в результате чего из нескольких одинаковых полигонов загрузится только один. То есть часть геометрии на импортированном меше будет отсутствовать.

**Comment by ghost** [comment]
В таком случае это не из-за плагина, а из-за самого Blender'а. - Потестил экспортированную модель из SDK в формате LWO, импортировал в Blender и SDK, в Blender'е так же как и при импорте object'а, а в SDK так же как и дефолтная модель (импортер LWO не использует модуль bmesh). Тогда на самом деле (как ты писал выше), нужно разбивать объект по материалам при импорте.

**Comment by PavelBlend** [comment]
Описанный мной способ обойти баг лучше не использовать (т.е. не разделять меш по материалам). Нужно придумать другой способ. Так как одинаковые полигоны могут встретится в одном материале. Я проверил некоторые объекты из сдк и выяснил, что объектов с одинаковыми полигонами достаточно много (особенно в папке rawdata\objects\trees\new_trees).

**Comment by igelbox** [comment]
> выяснил, что объектов с одинаковыми полигонами достаточно много

какие именно? (я, на вскидку, не смог найти)

> одинаковые полигоны могут встретится в одном материале

а в этом есть какой-то великий смысл? может всё-таки ну их (и пусть останется только один)?

**Comment by PavelBlend** [comment]
> а в этом есть какой-то великий смысл? может всё-таки ну их (и пусть останется только один)?

а, ну да. Ну разве что у них будут разные текстурные координаты, и то вряд ли.

> какие именно? (я, на вскидку, не смог найти)

Из XRay SDK 0.4, в папке rawdata\objects\trees\new_trees:

``` trees_1_01.object
trees_1_02.object
trees_1_03.object
trees_1_04.object
trees_1_sux_01.object
trees_1_sux_02.object
trees_2_01.object
trees_2_02.object
trees_2_03.object
trees_2_04.object
trees_2_sux_01.object
trees_2_sux_04.object
trees_2_sux_05.object
trees_3_03.object
trees_4_04.object
trees_big_urod_1_01.object
trees_big_urod_1_sux_01.object
trees_branch_1_01.object
trees_branch_1_02.object
trees_branch_1_04.object
trees_branch_1_05.object
trees_drop_1_01.object
trees_elka_1_01.object
trees_elka_1_02.object
trees_elka_1_03.object
trees_elka_sux_1_03.object
trees_elka_sux_1_04.object
trees_elka_sux_1_05.object
trees_rostki_1_01.object
trees_rostki_1_04.object
trees_rostki_1_05.object
trees_rostki_1_sux_01.object
trees_rostki_1_sux_02.object
trees_rostki_1_sux_03.object
trees_rostki_1_sux_04.object
trees_rostki_1_sux_05.object
trees_rostki_2_01.object
trees_rostki_2_02.object
trees_rostki_2_03.object
trees_rostki_2_04.object
trees_rostki_2_05.object
trees_rostki_3_01.object
trees_rostki_3_02.object
trees_rostki_3_03.object
trees_rostki_3_04.object
trees_rostki_3_05.object
trees_sosna_1_01.object
trees_sosna_1_02.object
trees_sosna_1_sux_01.object
trees_sosna_1_sux_02.object
trees_topol_1_01.object
trees_topol_1_sux_01.object
trees_topol_1_sux_02.object
trees_urod_1_01.object
trees_urod_1_02.object
trees_urod_1_03.object
trees_urod_1_04.object
trees_urod_1_05.object
trees_urod_1_06.object
```

**Comment by igelbox** [comment]
Сделал возможность разделения mesh-а по материалам во время импорта. Должно помочь.
А модели, в которых одинаковые полигоны в одном материале, например: `trees_2_04.object` - эти полигоны будут создаваться, используя копию одного из vertex-ов, а vertex-ы помещаться в группу `.xr-bad!`.

**Comment by PavelBlend** [comment]
Помоему группы сглаживания слетели. Например, в `trees_2_04.object`. Меш с листьями стал по другому сглажен, чем в предыдущей версии плагина. И ствол тоже.
Кстати, а плагин медленнее стал работать?

**Comment by igelbox** [comment]
Группы сглаживания поправил, теперь дублирующиеся полигоны целиком выносятся в отдельную часть mesh-а (а не только 1-й vertex).
Да плагин стал медленнее, из-за a994956a95a712f588415b8cef2668ba64032267. Но давно уже есть заявка по его ускорению - #10.

**Comment by PavelBlend** [comment]
А почему количество полигонов в blender не совпадает с количеством полигонов в СДК у объекта `trees_2_04.object`? В blender 14234, а в СДК 15934.

**Comment by igelbox** [comment]
Не знаю, откуда в СДК берут лишние треугольники. Реально, в том object-файле 2761 vertex и 14234 face (это можно посмотреть с помощью `python utils/dump-object.py trees_2_04.object --diff`)

**Comment by PavelBlend** [comment]
Я понял в чём дело. У некоторых материалов стоит галочка `2 sided`, которая удваивает количество полигонов. Если её отключить, то количество полигонов будет 14234
