### ISSUE TITLE
Мост между Blender и SDK. Возможность "Открыть в SDK"

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#585]
#### Описание идеи:
Добавить в N-панель свиток "Открыть в SDK" с кнопками "Открыть в Actor Editor", "Открыть в Level Editor" и т.д.
Для этого в настройках программы надо было бы указать пути до соответствующих редакторов с возможностью создания пресетов путей.
При нажатии на одну из кнопок сцена (либо можно сделать фильтр того, что сохранять) сохранялась с применением констрейнтов и т.п. и открывалась в соответствующем редакторе

#### Примеры использования:
За счет этого разработка и проверка была бы чуть быстрее

**Comment by PavelBlend** [comment]
СДК не имеет такой возможности. Я пробовал так запустить, но ничего не вышло:
```
"E:\sdk\bins\ActorEditor.exe" -editor "E:\sdk\rawdata\objects\props\objects\balon\balon_01.object"
```

СДК не имеет такого консольного параметра, чтобы при запуске передать файл для открытия. Всегда запускается пустое окно.

**Comment by PavelBlend** [comment]
Если будут идеи, как открыть файл в сдк через консоль, то пиши. А пока я закрою этот запрос из-за того, что я не знаю как его реализовать и возможно ли это вообще сделать.
