### ISSUE TITLE
Неправильно отображаеться моделька в игре, но в СДК - правильно вроде бы.

### ISSUE THREAD

**Issue by shadept-GitHub** [PavelBlend/blender-xray#586]
Я перенёс модельку оружия из другой игры в Сталкер ТЧ. Заменил wpn_bm-16_hud на свою модельку. Создал Bone Group и включил все кости в неё. Вот моделька в СДК:

![image](https://user-images.githubusercontent.com/65095770/197845782-674d86d9-39f9-48c2-8c74-88e6991e506f.png)

А вот моделька в игре:
![ss_user_10-24-22_23-45-25_(l01_escape)](https://user-images.githubusercontent.com/65095770/197845936-1f2a2ed8-fe2d-493c-9c31-8f6e577ad90f.jpg)

[Вот моя моделька в OGF формате.](https://www.dropbox.com/s/z28k25qdfaiofvk/wpn_bm-16_hud.ogf?dl=0)

Как воссоздать проблему: перевести мою модельку из OGF - > object - > закинуть в СДК и экспортировать как OGF - > заменить в игре

В чём дело? Я не понимаю, мне сказал один знакомый что не обязательно использовать только тот скелет рук, который уже в игре а можно и свой добавить.

**Comment by shadept-GitHub** [comment]
Значит я переделал модель и проблема остаётся. Может я что-то забыл при создании модельки? Если что я все кости добавил в один BoneGroup. Если анимации нету - моделька в норме и на месте, конечно, если чуть-чуть подвинуть её на координате Z. А вот после римейка модельки при анимации она вообще не отображается. В блендере и СДК, конечно, показуеться в норме. [Вот новая моделька.](https://www.dropbox.com/s/z28k25qdfaiofvk/wpn_bm-16_hud.ogf?dl=0)

Скрин модельки с анимацией: 
![ss_user_10-26-22_19-05-13_(l01_escape)](https://user-images.githubusercontent.com/65095770/198077626-dd6b73c0-2381-48bd-8955-37b4a48ae323.jpg)



Вот скрин модельки без анимаций и со слегка изменённым значением position в конфиге (0, 0, 3): ![ss_user_10-26-22_18-36-41_(l01_escape)](https://user-images.githubusercontent.com/65095770/198076899-29cb89d6-4b5d-4f27-b923-d9e1343214d0.jpg)
А вот скрин в СДК уже с анимацией: 
![image](https://user-images.githubusercontent.com/65095770/198077415-1206dfb3-d463-4ab7-8e1d-440501593015.png)

**Comment by PavelBlend** [comment]
@shadept-GitHub посмотрел файл. У анимаций не включен флаг Stop At End. Посмотри как в оригинале настроено и настрой так же.
![1](https://user-images.githubusercontent.com/7983249/211202727-c14dedc5-f4bb-4fdb-a359-35d0c18b8b95.jpg)

И анимации имеют не правильные имена. Я менял конфиг:

```
anim_idle					= idle
anim_reload					= reload_loop
anim_draw					= draw
anim_holster				= idle
anim_shoot					= fire
anim_shoot_both 			= fire
anim_idle_aim				= idle
anim_idle_sprint			= idle

anim_reload_1				= reload_loop
anim_shoot_1				= fire

anim_idle_1					= idle
anim_idle_2					= idle

anim_zoomed_idle_1			= idle
anim_zoomedidle_2			= idle
```

Другие параметры конфига не менял.

Вот результат:

![ss_pavel_blend_01-08-23_17-54-54_(l01_escape)](https://user-images.githubusercontent.com/7983249/211203155-d73022c6-e6a7-468c-9c80-467954187eb5.jpg)

СДК без ошибок открывает эти модели. Проблема в неправильной настройке параметров анимаций и возможно конфигов.

**Comment by PavelBlend** [comment]
@shadept-GitHub если изменение параметров анимации не помогло и проблема не решена, то заново открой issue.

Я пока проблему не воспроизвёл. Закрываю issue, чтобы очистить список задач.
