### ISSUE TITLE
Помогите при компиле в .mdl, модель ломается, скриншот, QC, и модель прилагается

### ISSUE THREAD

**Issue by MyakotinN** [PavelBlend/blender-xray#589]
#### Краткое описание проблемы:
При компиле в mdl модель не просто ломается, а как будто выворачивается и растягивается

#### Как воспроизвести ошибку:

![catcatactatc](https://user-images.githubusercontent.com/65569534/201788819-de85bf43-5fa9-49cb-9054-3e32842a67d6.png)
[cat.zip](https://github.com/PavelBlend/blender-xray/files/10007783/cat.zip)

#### Ожидаемое поведение:
Модель будет воспроизводить анимацию ходьбы

#### Версии ПО:
 - OS: <!-- Win10 x64, 
 - Blender: <!-- 3.3.1

#### Дополнительная полезная информация:
При разных костях (самодельный, аддон rigidi, генерированный риг, или при импорте в smd файле модель которая была экспортирована) получаются разные поломки

P.S. 
Люди помогите пожалуйста, в source плохо разбираюсь как и в блендер, весь интернет облазил но статьи именно по этой проблеме не нашёл

**Comment by TheParaziT** [comment]
Зачём ты здесь об этом пишешь? Аддон никак не связан с расширением .mdl и т.д.
