### ISSUE TITLE
Создание метрик 

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#591]
#### Описание идеи:
Добавить кнопку для создания метрик (например, при нажатии будет добавляться сталкер, либо иной объект с его высотой и шириной (можно сделать через Measurements Tool))

#### Примеры использования:
При создании или скачивания модели часто ее нужно увеличивать или уменьшать и чтобы модель четко вписалась в окружение (не была слишком большой или маленькой) можно будет использовать метрики из ориг объектов

**Comment by PavelBlend** [comment]
@TheParaziT а если импортировать модель сталкера? Я в таких случаях импортирую новый объект, который можно легко перемещать в любое место. А если это делать с помощью рисования во вьюпорте, то нужно будет писать код для перемещения этих нарисованных метрик. Я не до конца понимаю, как это реализовать лучше, чем обычный импортированный объект.

**Comment by TheParaziT** [comment]
А что если тогда добавить галочку при импортировании например "Показать высоту модели" и рисовать линейку от самой нижней до самой верхней точки?

**Comment by PavelBlend** [comment]
@TheParaziT  Высоту модели можно в любой момент узнать в n-панеле:
![0](https://user-images.githubusercontent.com/7983249/213009486-a81776c4-f08e-41e7-9f09-337fe8f84a81.jpg)

А если рисовать линейку, то это не облегчит ситуацию. Ведь на фоне есть координатная сетка.

Легче создать кубик нужного размера или импортировать сталкера, и перемещать его свободно.

**Comment by TheParaziT** [comment]
Ну да, получается, что легче просто импортировать объект и с ним сверяться
