### ISSUE TITLE
Не работает импорт моделей

### ISSUE THREAD

**Issue by Zfoksi** [PavelBlend/blender-xray#592]
![image](https://user-images.githubusercontent.com/122187444/211176423-12253943-1cdd-4acf-8c5a-3f4900f87ea9.png)

Раньше импорт моделей работал, но перед новым годом перестал. Верси Блендера 3.4.1. Но опять же, раньше всё великолепно работало. А без данного адонна я как без рук.

При том сам скелет модели импортируется

**Comment by SamArtGit** [comment]
Выдели любой не спрятанный объект перед импортом.

**Comment by PavelBlend** [comment]
@Zfoksi а если в настройках блендера отключить галочку, которая включает перевод новых блоков данных, то ошибка пропадёт?:
![555](https://user-images.githubusercontent.com/7983249/211192119-c0672cd4-f096-429b-ae3f-53eddb783852.jpg)

Скорее всего аддон не может найти ноду `Principled BSDF`, так как вместо неё создаётся `Принципиальный BSDF`.
