### ISSUE TITLE
Не работает на версии блендера 3.4

### ISSUE THREAD

**Issue by SadBoyOff** [PavelBlend/blender-xray#593]
Не работает на версии блендера 3.4
даже последний (2.19.0) релиз
![image](https://user-images.githubusercontent.com/48679903/212463502-d9685a97-b758-44bd-a9be-ddca5c878c0f.png)

**Comment by PavelBlend** [comment]
@SadBoyOff я эту ошибку исправлял #592
И лог какой-то непонятный. При такой ошибке он должен быть таким (как здесь #592):
![img](https://user-images.githubusercontent.com/122187444/211176423-12253943-1cdd-4acf-8c5a-3f4900f87ea9.png)

А у тебя в самом низу пишет, что не найдена нода `Principled BSDF`, но на строчку выше ноде устанавливается позиция по оси `y`. То ли аддон криво установился. В версии `2.19.0` в коде даже нет такой строки `Principled BSDF`, а у тебя она в логе пишется. Удали аддон и установи его заново.

Если не поможет, то скинь мне файл, на котором данная ошибка воспроизводится.

**Comment by SadBoyOff** [comment]
блендер автоматом подтянул старый плагин с 3.3 блендера
щас переустановил плагин с удалением, заработало
