### ISSUE TITLE
Автоматизированное изменение свойств объекта.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#595]
#### Описание идеи:
По аналогии с изменением свойств параметров шейдеров менять User Data, Motions Refs, Revision для выделенных или всех объектов в сцене.

#### Примеры использования:
В моём случае это прогрессивные динамические модели не игровых персонажей. Так-как делаю их поочерёдно, то перед экспортом приходится менять выше указанные параметры для больше сотни моделей (и это только для одной группировки с одним рангом) вручную (и то немного лукавлю, потому-что благодаря реимпорту уже ранее созданных моделей ещё в процессе "одевания" персонажей, отпадает надобность менять каждой модели Motion Refs, но всё так-же нужно менять вручную для каждой модели User Data. Да и Revision немного мусолит глаза, ибо если его не менять, то сложится впечатление, что все модели были сделаны в один год.месяц.день.час.минуту, хоть это и мелочь которую почти никто не заметит.

**Comment by PavelBlend** [comment]
revision я пока делать не буду. Сделаю потом. Эта issue похожа на #550, поэтому добавлю пометку туда, чтобы не забыть.
