### ISSUE TITLE
Проблемы с Viewer

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#599]
#### Краткое описание проблемы:
При выборе обьекта в Viewer (например модели) и если эта же модель уже была в сцене, то изначальная модель в сцене заменяется из Viewer окна

#### Как воспроизвести ошибку
- Импортируем модель
- Открываем Viewer
- Выделяем модель в Viewer, которая ранее была импортирована самостоятельно

#### Ожидаемое поведение:
Лучше чтобы в таких случаях модель из Viewer временно называлась по другому (дабы модели не заменялись)

#### Версии ПО:
 - OS: Win10 Pro x64
 - Blender: 3.4.1 stable.55485cb379f7

#### Дополнительная полезная информация:
Называю проблемой, т.к. при создании Asset Browser с моделями и [действий вышеописанных](#Как-воспроизвести-ошибку) модель не отмечается как ассет и приходится помечать его заново и настраивать

**Comment by PavelBlend** [comment]
@TheParaziT у меня изначальная модель не заменяется:

https://user-images.githubusercontent.com/7983249/213421962-31f8e9f3-e8ce-4d07-b909-34bbdd143ffd.mp4

Перед импортом моделей из вьювера, аддон собирает существующие объекты в список и не меняет их. Вьювер меняет только те объекты, которые сам импортировал. Импортированные объекты у меня имеют суффикс '.001'. А исходные объекты как были до импорта, такими же и остались после закрытия вьювера.

**Comment by PavelBlend** [comment]
@TheParaziT я эту ошибку воспроизвести не могу, поэтому закрывают issue. Если эта ошибка всё таки есть, то заново открой issue. И мне нужно будет более подробное описание последовательности действий. Может видео. Я помечал объект как Asset и аддон его не удалял.
