### ISSUE TITLE
plugin preferences: automatically deduce file paths to other shaders

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#60]
e.g. if we setup path for `gamemtl.xr` file, then plugin automatically deduce path to `shaders.xr` file

**Comment by PavelBlend** [comment]
А как в таком случае указать путь к shaders.xr, если он лежит в другой папке, отличной от папки где лежит gamemtl.xr? Такое часто бывает при импорте файлов из модов. Мне кажется, лучше оставить всё, как есть. Чуть дольше будет происходить настройка плагина, но зато будет гибкой она.

**Comment by igelbox** [comment]
Я хотел, чтобы и новый вариант позволял так сделать такую гибкую настройку.
А если пользователь явно не задал какие-то пути, то пусть они вычисляются автоматом.
(но это так, мысли на будущее, а пока есть более приоритетные задачи)

**Comment by ghost** [comment]
Как по мне, так лучше выставлять один путь, путь до gamedata, а все остальное подключать автоматом или сделать еще чекбокс (расширенного режима) для выбора всего по отдельности. - Нужно как можно больше всего упростить, чтобы народ уже начал использовать данный плагин (=
