### ISSUE TITLE
Не работает подгонка начала и конца анимации при её выборе в списке анимаций скелета.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#603]
Давно появилась ошибка, только сейчас вспомнил чтобы сказать про неё.

**Comment by PavelBlend** [comment]
@SamArtGit у меня работает:

https://user-images.githubusercontent.com/7983249/214145855-ae299a1a-8c97-4c54-ae75-c46d0f22ec60.mp4

А в консоли `Window > Toggle System Console` что-то пишется?

**Comment by SamArtGit** [comment]
Ля, работает. Может после обновления стало работать? Вчера буквально тестировал и не работало. Может обновил дополнение и всё починилось, хотя обновлял позавчера... Ну ладно, если снова проблема всплывёт то пере открою, ибо 2 раза уже чинили. Вдруг третий раз сломается. %)

**Comment by SamArtGit** [comment]
https://user-images.githubusercontent.com/56885075/217580796-6534028c-281f-4c4b-a1d9-59335eaa6277.mp4

**Comment by PavelBlend** [comment]
@SamArtGit выяснил причину. Аддон устанавливает диапазон, но блендер его не использует, так как используется альтернативный диапазон. Нужно отключить альтернативный диапазон кадров у timeline:
![000000](https://user-images.githubusercontent.com/7983249/217614294-e6797e0a-651f-4538-b327-d0e5f266105c.jpg)

После этого пропадёт светло-коричневый фон и будет использоваться диапазон сцены.
Я не знаю, зачем нужен альтернативный диапазон, и только сейчас узнал о его существовании:
https://docs.blender.org/manual/en/latest/editors/timeline.html#frame-controls

Можно сделать так, чтобы аддон автоматически выключал альтернативный диапазон во время переключения анимации.
