### ISSUE TITLE
Не работает очистка motion references у нескольких объектов.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#604]
Самая новая версия дополнения. Выделил 93 объекта, у них как были 7 refов, так и остались.

**Comment by SamArtGit** [comment]
Ошибка не актуальна. Работает, но не сразу. Спустя пару минут стирается у всех объектов (как в случае добавлением motion reference через файловый проводник в Blender).

**Comment by PavelBlend** [comment]
Нужно навести курсор мыши на окно properties, чтобы оно обновилось. Я сейчас написал код для автоматического обновления окна. Будет работать для всех операторов, в том числе skls браузера и viewer.
