### ISSUE TITLE
Support for Gunslinger *_hud.ogf

### ISSUE THREAD

**Issue by SvetkaDystopia** [PavelBlend/blender-xray#607]
Hello, I'm not sure how hard it would be to implement but I've found that trying to import any hud ogf from the gunslinger mods I've been working with hard locks blender.. can import any other mesh I've tried but if I do a weapon hud or arms, it locks up. 

Figured I'd bring it up as gunslinger+mods are seeming to be everywhere more and more so it should be a rather useful addition for the community if possible...  

Thank you for all you've put into this, it's an invaluable tool for our modding community and a big reason I learned to model and animate.

**Comment by igelbox** [comment]
BTW, it's always good to attach some sample files to reproduce the bug =)

Just managed to unpack `gunslinger_installer_160922.zip` into some exe then unpack it using wine into a buch of db-files then unpack them the unpack DB using AXRToolset 😮‍💨 
And now I have [dev_bolt_hud.zip](https://github.com/PavelBlend/blender-xray/files/12267621/dev_bolt_hud.zip) which imports pretty well, but [dev_detector_1_hud.zip](https://github.com/PavelBlend/blender-xray/files/12267625/dev_detector_1_hud.zip) yeah hangs:
<img width="818" alt="image" src="https://github.com/PavelBlend/blender-xray/assets/5264687/36ac7200-b78f-43ff-b38b-e26d0c198aad">

Addon: 428a95b748f809aabe0fab906cbd2596b9c4c279 (HEAD, upstream/develop)
Blender: 3.1.2

**Comment by igelbox** [comment]
Interrupting the stuck import gives some insights:
```python
^CPython: Traceback (most recent call last):
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/log.py", line 279, in wrapper
    return method(self, context)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/stats.py", line 266, in wrapper
    result = method(self, context)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/ie.py", line 70, in wrapper
    result = method(self, context, *args)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/formats/ogf/imp/ops.py", line 91, in execute
    utils.ie.import_files(
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/ie.py", line 124, in import_files
    report_errors(context)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/ie.py", line 139, in report_errors
    raise first_error
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/ie.py", line 115, in import_files
    result = imp_fun(file_path, context)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/log.py", line 265, in wrap
    return func(*args, **kwargs)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/utils/stats.py", line 227, in wrapper
    result = method(*args, **kwargs)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/formats/ogf/imp/main.py", line 117, in import_file
    import_ogf_visual(context, data, visual)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/formats/ogf/imp/main.py", line 22, in import_ogf_visual
    chunks = utility.get_ogf_chunks(data)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/formats/ogf/imp/utility.py", line 53, in get_ogf_chunks
    for chunk_id, chunkd_data in chunked_reader:
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/rw/read.py", line 207, in __next__
    return cid, memoryview(lzhuf.decompress_buffer(buffer, textsize))
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/rw/lzhuf.py", line 196, in decompress_buffer
    c = DecodeChar()
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/rw/lzhuf.py", line 172, in DecodeChar
    update(c)
  File "/Users/igelbox/Library/Application Support/Blender/3.1/scripts/addons/io_scene_xray/rw/lzhuf.py", line 138, in update
    if k > freq[l]:
KeyboardInterrupt
```
so probably I [messed](https://github.com/PavelBlend/blender-xray/pull/199) something with the lzhuf decompressor 💩

**Comment by PavelBlend** [comment]
@igelbox в гансе идентификаторы чанков имеют флаг сжатия, но само сжатие не используется. Ещё тип моделей непонятный. Или тип костей, уже не помню. Там какие-то рандомные числа, вместо знакомых значений. И чанк revision то ли новый, то ли в нём рандом из байтов или зашифровано что-то. Я писал, но не выложил код, который всё импортирует без ошибок, но он не сохраняет особенности формата ogf из ганса. Может там есть важная информация для мода.

**Comment by igelbox** [comment]
Вот же ж негодяи)
@PavelBlend, спасибо, что написал, а то я бы совсем пропал в этом мире без границ из нулей и единиц)

**Comment by PavelBlend** [comment]
@igelbox а ты хотел писать поддержку импорта моделей ганса?

**Comment by igelbox** [comment]
Да хз, я просто, когда скучно/грустно, захожу посмотреть как тут дела) Вот увидел эту ишью, на английском, да с благодарностями, ну и про то что что-то зависает - меня это всё подкупило - решил починить.
Я посмотрю их [исходники](https://github.com/gunslingermod/GunsXRay) (или это не оно?), может что накопаю, но мне тестировать особо не на чем (что оно сохраняет все важные чанки) ибо запускать Сталкера под Wine на Linux на Маке - ну это too much).
Если есть ещё какая-нить ишью больше техническая, модет что падает/зависает/тормозит - я б глянул.

**Comment by igelbox** [comment]
@PavelBlend, ну или если надо что-то странное обсудить, чтоб тут простыни текста не писать - можешь найти меня в Телеге по нику (опознать можно по шлему). Хз как ещё контакт оставить. Пусть тут часик повисит)

**Comment by PavelBlend** [comment]
@igelbox про исходники - не знаю. Скорее всего это они, судя по названию репозитория.

> мне тестировать особо не на чем

Я могу попозже примеры файлов из мода скинуть.

**Comment by igelbox** [comment]
> Я могу попозже примеры файлов из мода скинуть.

Так я уже [научился](https://github.com/PavelBlend/blender-xray/issues/607#issuecomment-1666540851) и распаковал. Я именно про:
> но он не сохраняет особенности формата ogf из ганса. Может там есть важная информация для мода.

т.е. я не могу после ре-экспорта его запустить/проверить.

Ладно, пока есть мотивация - посмотрю их исходники. Но ничего не обещаю ¯\\\_(ツ)\_/¯

**Comment by igelbox** [comment]
[dump_ogf.py](https://github.com/PavelBlend/blender-xray/blob/develop/utils/dump_ogf.py) (после отключения компрессии) прожевал проблемный файл, но нашлось 2 аномалии:
- в заголовке в `S_DESC` приходит что-то вызывающе непонятное `101 b"I'll make you cry. Sin!\x00X,\x8c]dX\xe1\xf7pZ \x0e\x94\x87\x1bW\x11\xb9\xe7\xdd\xeem\xf7\xfci\x984J\x86\xc9!\xd9\xb9#\x80\xbev$\xf9\xbb\xeep\xa6\x88\x8d\xfd\xa8&\xcbX\x1d\x12z\xd8\x0fs\xa3\x1fAo\x92\x06\xe9Q\xab\xef\xc1=&A\xfa\x80\xcd&\x07\xce_"`. Странно, что там только 1 окончание строки `\x00`, а [должно](https://github.com/gunslingermod/GunsXRay/blob/4fd762f6f95c75aba1e4dbb84282e0112fcc819c/src/xrCore/FMesh.cpp#L6) быть ровно 4.
- у первой `S_IKDATA_2` странная версия:
```yaml
s ikdata 2: [{
  version: 47
  gamemtl: default_object
```

Закомментировал пока чтение строк/дат в заголовке - и импорт заработал:
<img width="383" alt="image" src="https://github.com/PavelBlend/blender-xray/assets/5264687/d2957072-2ec4-4535-88bd-e9549da0accc">

**Comment by PavelBlend** [comment]
@igelbox может попробовать сделать декомпрессию с помощью lzhuf тех байтов, которые идут после `101 b"I'll make you cry. Sin!\x00`. Этот чанк видимо полностью переписан и не имеет ничего общего с оригинальным форматом.

> * у первой `S_IKDATA_2` странная версия:

а в исходниках движка непонятно, почему версия такая? Когда я тестировал, у меня вроде бы у каждого файла были уникальные версии.

**Comment by igelbox** [comment]
Я уже попробовал) - деаомпрессия не помогает, ни целиком, ни только хвоста. Там странно, последние 4 байта - это нормальный таймштамп:
```python
>>> struct.unpack_from('<I', d, len(d)-4)
(1607337766,)
>>> from datetime import datetime
>>> datetime.fromtimestamp(1607337766)
datetime.datetime(2020, 12, 7, 16, 42, 46)
```
т.е. перед ним должно бы быть завершение предыдущей строки, т.е. `\x00`, но там `\xcd`.
Если бы это был какой-нить обычный XOR - тогда бы `\xcd` ещё раза 2 встретилось, но его нет.
Короч, это конечно занятно - разгадывать чужие шифры), но я бы им ишью написал :shit:
Можно ещё попробовать посравнивать эту строку у разных файлов и в разных их билдах - вдруг можно просто константой обойтись.

Про IKDATA - пока непонятно, [читают](https://github.com/gunslingermod/GunsXRay/blob/4fd762f6f95c75aba1e4dbb84282e0112fcc819c/src/xrCore/Animation/Bone.cpp#L81) они её вроде обычно ¯\\\_(ツ)\_/¯
Как/если найду, откуда оно такое пишется - напишу.

Но так-то, думаю можно научить аддон импортировать эти файлы не идеально, а как получится. И решать проблемы с ре-экспортом по мере их возникновения (если они вообще будут).

**Comment by igelbox** [comment]
Я уже попробовал) - деаомпрессия не помогает, ни целиком, ни только хвоста. Там странно, последние 4 байта - это нормальный таймштамп:
```python
>>> struct.unpack_from('<I', d, len(d)-4)
(1607337766,)
>>> from datetime import datetime
>>> datetime.fromtimestamp(1607337766)
datetime.datetime(2020, 12, 7, 16, 42, 46)
```
т.е. перед ним должно бы быть завершение предыдущей строки, т.е. `\x00`, но там `\xcd`.
Если бы это был какой-нить обычный XOR - тогда бы `\xcd` ещё раза 2 встретилось, но его нет.
Короч, это конечно занятно - разгадывать чужие шифры), но я бы им ишью написал :shit:
Можно ещё попробовать посравнивать эту строку у разных файлов и в разных их билдах - вдруг можно просто константой обойтись.

Про IKDATA - пока непонятно, [читают](https://github.com/gunslingermod/GunsXRay/blob/4fd762f6f95c75aba1e4dbb84282e0112fcc819c/src/xrCore/Animation/Bone.cpp#L81) они её вроде обычно ¯\\\_(ツ)\_/¯
Как/если найду, откуда оно такое пишется - напишу.

Но так-то, думаю можно научить аддон импортировать эти файлы не идеально, а как получится. И решать проблемы с ре-экспортом по мере их возникновения (если они вообще будут).

**Comment by igelbox** [comment]
Короч, на S_DESC надо просто забить, т.к. он в [рантайме](https://github.com/gunslingermod/GunsXRay/blob/4fd762f6f95c75aba1e4dbb84282e0112fcc819c/src/Layers/xrRender/FBasicVisual.cpp#L67) не читается, только каким-то редактором.
Т.е. AFAIK это такая silly-попытка защититься от копирования/редактирования моделей всеми желающими.

И похоже никакого смысла в том шуме - нет, ну по крайней мере последние 4 байта - тоже не всегда нормальная дата:
```python
datas = [
  b"I'll make you cry. Sin!\x00X,\x8c]dX\xe1\xf7pZ \x0e\x94\x87\x1bW\x11\xb9\xe7\xdd\xeem\xf7\xfci\x984J\x86\xc9!\xd9\xb9#\x80\xbev$\xf9\xbb\xeep\xa6\x88\x8d\xfd\xa8&\xcbX\x1d\x12z\xd8\x0fs\xa3\x1fAo\x92\x06\xe9Q\xab\xef\xc1=&A\xfa\x80\xcd&\x07\xce_",
  b"I'll make you cry. Sin!\x00\xcc\xc2\xb0|\xfb\x93)\xb1\xd6\xc5\x8a:\x1e\xe9K\x84\x9f\xd3F\x1f:\x149\x10P\xb2\x9c\xf0\x0e\xfa\xcb\xc3\x1bg\xc7\x8f\x95\xea\x02[rG\xee\x08\x95\to\x1aRb#\x81\x1f J\xe1\x955\xe2\xf85\xc6\xf2\x16]\xadF\xc7~\xc3!B\x89\x85\x97\xfb\xfe\xd2\x8f\xa8A\xe1\x9b\x85\xec\xa9D\x8d\x85",
  b"I'll make you cry. Sin!\x00\xa8$\x1d\x06\x92\xfa\x06\xc0\\st\xabV\xbeh\x9e\xf8G\xb6e\xfa\xd4\x7fM:Jr\x16\x9c\xd3\x9cK\x11\xd8\x88X$\xe8\xd1\xe9\xf7\x81\x8dT\x97x\x1b\x1e\xcaF:\xf0\x0b\x91\x92\x872\xb8\xe7P\x02/\xbd\xe4\x9b\xe8$\x9c\x82G\xdf\xbe\xcd\x17I(\x9f\xadep\xfb>8\xd6\x9f\xc9T",
  b"I'll make you cry. Sin!\x00\x12\xbb\xe58Q\x9d\xfd\xd5o*Z\x05\xe2\xea\x89\xafs`\xdebU\xcdm\xfd-_\xa6w3\x17\xfd\xb9\x0fK@\t3\xa8\x87\x7f\xca\xf1\xff\x87|\x03\xdee\x90\xcd=3MM\xc2\xe5\x8c\xa5QG\xde\xfd\r\xd8\xc0\xb6~<\xad\x12\xb4t)r\x8e\x17\xf9\xc7\xa0g0\xc4U",
  b"I'll make you cry. Sin!\x00\xb1\xf9G\x06u\xf6\xef\x93\x96\x02!y\xe5\x15\xe9\xa4\xbd%\xe8\x0c\x1d\xe8\x1c\x86^\xa0\xae\x7f\x19\x8el\xd0\xe98\xb9tF\x84V\xd3\x84Z7\xe2\xd0\\BX\xb4\xd4\xbd\xa0M\xf8\xb2n}\x18\xa0\xf6\xa6U:L\xb0\x08\rPm\xdfEB\xa7c\xfc\xe5g",
  b"I'll make you cry. Sin!\x00\x1b\xd1n\xcf\x83\xd1\x0c\xf3\xb8U\xa3\xf5\xf0e?\xc2Xq\x92k\xb2\x1c\x8b\x0e\xc3\xf2M\x02+eu",
  b"I'll make you cry. Sin!\x00%\xd6\xf8\x12\x7f\xee\xa9w\xc1O\x0c\xc3,\xdd\xc9\x9cH\xb4\xfe\x8d\x85F\t\xb4\x03\x80\x19{\x91%\xd05M\xc5C\xc49;\xfb\x9f\xcd",
]

from datetime import datetime
import struct

for d in datas:
    t = struct.unpack_from('<I', d, len(d)-4)[0]
    print(t, datetime.fromtimestamp(t))

# 1607337766 2020-12-07 16:42:46
# 2240627881 2041-01-01 10:38:01
# 1422499798 2015-01-29 08:49:58
# 1438920807 2015-08-07 10:13:27
# 1743125603 2025-03-28 07:33:23
# 1969564418 2032-05-31 03:13:38
```

**Comment by SamArtGit** [comment]
> т.е. я не могу после ре-экспорта его запустить/проверить.

Если Вы за проверку работоспособности в игре, то модель починенная и сохранённая в . object, а потом перегнанная в .ogf нормально работает на оригинальном "Стрелке". %)
Может Вам спросить ВалерКа? У него как-раз есть починка .ogf и .omf в одноимённых редакторах и для этого дополнения сделал экспорт Split Normals без перегонки его в группы сглаживаний.

**Comment by SamArtGit** [comment]
> т.е. я не могу после ре-экспорта его запустить/проверить.

Если Вы за проверку работоспособности в игре, то модель починенная и сохранённая в . object, а потом перегнанная в .ogf нормально работает на оригинальном "Стрелке". %)
Может Вам спросить ВалерКа? У него как-раз есть починка .ogf и .omf в одноимённых редакторах и для этого дополнения сделал экспорт Split Normals без перегонки его в группы сглаживаний.

**Comment by PavelBlend** [comment]
Сделано: #671

**Comment by igelbox** [comment]
> нормально работает на оригинальном "Стрелке". %) Может Вам спросить ВалерКа?

Ой, я продолбал коммент. Я не понял ничто такое оригинальный Стрелок, ни кто такой ВалерКа =)
Нужно бы проверить, будет ли GUNSLINGER mod читать ogf-ки ре-экспортированные данным адоном.
Ну или можно просто заявить, что у тут всё работает, и ждать когда/если ишью/баги принесут)

**Comment by PavelBlend** [comment]
> Может Вам спросить ВалерКа? У него как-раз есть починка .ogf и .omf

я уже сделал. В моде в чанке с анимациями имена анимаций испорчены, но я взял имена из другого omf чанка, который хранит параметры анимаций.

> для этого дополнения сделал экспорт Split Normals без перегонки его в группы сглаживаний.

для этого аддона blender-xray? Он прислал мне Pull Request с кодом, который экспортировал нормали, но не работал их импорт. Я добавил этот код в историю репозитория из-за того, что он старался, хоть код был не рабочим. Но потом, как оказалось (я это не сразу понял), рабочий код экспорта был взят из репозитория https://github.com/StalkMen/blender-xray/commit/52dccad376ab19ad578275059162e5889715ec0d

А код импорта он вроде бы сам пытался писать. Говорил, что у него не получается. Я его нерабочий код переписывал и добавлял поддержку триангуляции во время экспорта и т. д.:
https://github.com/PavelBlend/blender-xray/commit/e3d52297b5fbb2e9cc42534cda02aa972b8ef2e3

**Comment by PavelBlend** [comment]
> Нужно бы проверить, будет ли GUNSLINGER mod читать ogf-ки ре-экспортированные данным адоном.

проверил. OGF работают. Вот грозе кубик слева добавил, чтобы точно было видно, что модель из блендера:

![ss_pavel_08-10-23_11-15-27_(zaton)](https://github.com/PavelBlend/blender-xray/assets/7983249/621e3bb9-4346-4eac-a7f7-2b355036c131)

**Comment by SamArtGit** [comment]
> Стрелок, ни кто такой ВалерКа

Gunslinger и ValeroK. Люблю коверкать в шутку, но тут впервые это сыграло против меня. %)

https://github.com/VaIeroK/OGF-tool

https://github.com/VaIeroK/Omf-Editor

Хотя, оно уже вам ни к чему видимо, бо судя по статусам, вопрос уже закрыт.
