### ISSUE TITLE
Удалять при экспорте ненужные развёртки.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#608]
Оставлять ту которая активна для рендера (вообще слышал что .object умеет/умел хранить несколько развёрток, но нужна ли эта функция в дополнении если в игре дополнительная развёртка из файла не используется?).

**Comment by PavelBlend** [comment]
@SamArtGit можно не удалять, а использовать активную uv, не трогая другие. Потому что можно иметь важные и нужные uv, но забыть о них и сделать экспорт и потерять их.

**Comment by TheParaziT** [comment]
@SamArtGit это что-то типо зародыша UDIM'ов?
