### ISSUE TITLE
Экспорт чанка 0x0922

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#61]
Чанк содержит имя автора, дату создания, имя модификатора, дата модификации.
В качестве имени автора можно использовать следующее:
import os
authorName = '\\{0}\{1}'.format(os.environ['COMPUTERNAME'], os.environ['USERNAME'])

В качестве moder использовать пустую строку.

Время создания можно записать так:
import time
createTime = int(time.time())

Время модификации выставлять в 0x0.

**Comment by igelbox** [comment]
`os.environ['COMPUTERNAME']` и `os.environ['USERNAME']` - не кроссплатформено (на linux работать не будет)
лучше использовать `platform.node()` и `getpass.getuser()`

**Comment by igelbox** [comment]
Можно проверять. Но смущает один момент: теперь невозможно экспортировать файл с именем оригинального модера. Хотя, ActorEditor из SDK тоже заменяет оригинальное имя при сохранении object-файла.

**Comment by PavelBlend** [comment]
Проверил. Мне кажется немного не правильно сделано. "Owner Name" - это имя компьютера и имя пользователя, на котором произошёл экспорт из 3д редактора (3ds Max, Maya или Blender в нашем случае). А поле "Moder Name" нужно оставлять пустым, так как это имя компьютера и имя пользователя на котором была отредактирована модель через X-Ray SDK. И зря в интерфейс вывел эти значения. Так как они заграмождают интерфейс. Нет необходимости редактировать эти параметры через интерфейс. Плагин должен сам автоматически выставлять значения без участия  пользователя. Значение "Moder" выставлять в пустую строку (так как этот параметр можно изменить только через SDK), "Mod. Time" выставлять в 0x0, а вот Owner Name и Owner Time нужно выставлять с помощью плагина.

**Comment by igelbox** [comment]
А как в этом случае работают официальные 3D-редакторы для XRay-SDK (в чём там авторы рисовали, 3dsMax/Maya/LightWave?)?
В ActorEditor ведь изначально, наверное, не object-файл загружали (ибо откуда ему взяться-то было), а lwo-какой-нибудь. Но тогда как прописывался "Owner Name", если SDK пишет только "Moder Name"?

**Comment by ghost** [comment]
Изначально загружался LWO формат - но там были только зачатки редактора. Первый редактор был LightWave, потом стал юзаться Maya и в редких случаях 3Ds Max. Под все эти редакторы были плагины экспорта в object, а под Maya даже и anm.

Функция данного чанка нужна для большой, нет, просто огромной команды моделлеров - дабы отслеживать, кто работал, а кто нет. И в пределах моддинга эта функция лишняя.

**Comment by PavelBlend** [comment]
Я знаю как работает 3ds MAX с официальным плагином. Он заполняет Owner и Create Time. А Moder выставляет в пустую строку и moder time заполняет какими-то левыми значениями (2018 год).
Только что проверил на lwo формате. СДК выставляет Owner в unknown и create time в 0x0.

**Comment by igelbox** [comment]
Получается, что если затянуть чужую модельку, немного её поправить и сохранить, то становишься её Owner-ом. Я считаю, что это не справедливо. Думаю, лучше сделать так:
- если был импортирован Owner, то его и писать (но дать возможность изменить его в интерфейсе), а себя писать как Moder-a
- если модель не импортировалась (Owner пустой или равен текущему пользователю), то писать себя как Owner-а, а в Moder-а писать пустую строку

**Comment by PavelBlend** [comment]
Проверил. Есть один нюанс. Если в новосозданном объекте вручную заполнить пустое поле Owner, а Created не заполнять, то экспортируется время создания как 0x0. А должно быть время экспорта вместо 0x0.
И ещё. Мне кажется нет смысла редактировать Created через интерфейс. Этот параметр можно спрятать.

**Comment by igelbox** [comment]
"а Created не заполнять, то экспортируется время создания как 0x0" - странно, я вчера проверял, работало. Проверю ещё раз.
"нет смысла редактировать Created через интерфейс" - а если я создал модельку вчера и отдал её тебе, а ты её последний раз экспортнул, например, в конце этого года, то Created будет не тот, когда я её создал. Как автоматом запоминать время создания в blend-файле я не знаю, пусть хоть руками задать возможность будет.

**Comment by igelbox** [comment]
Проверил. Так получается потому, что заданное имя Owner-а не похоже на твоё текущее (\\comp\user). Странно было бы, если мы проставляли свою дату создания вместо той, что задал (или не задал) автор.
