### ISSUE TITLE
Подгонять количество кадров в секунду в соответствии с анимацией.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#610]
По аналогии с подгонкой начала и конца анимации в зависимости от позиции ключевых кадров анимации. Сэкономит время на переключение количества кадров в секунду в Параметрах вывода каждый раз при создании нового проекта (понимаю, что можно его задать в новом проекте и сохранить его как новый проект при запуске Блендера, но раз уж у Вас такое многофункциональное дополнение то почему-бы и не добавить такую мелочь? Тем-более что кто-то может делать анимации в 60 КВС, хоть движок и 30 воспроизводит, если не изменяет память).
<details>
  <summary></summary>

![image](https://user-images.githubusercontent.com/56885075/226861173-03ee0c50-f231-4124-917e-df20746b2afc.png)
</details>

**Comment by PavelBlend** [comment]
> можно его задать в новом проекте и сохранить его как новый проект при запуске Блендера

наверное лучше так и сделать. Мне лично эта автоматизация будет мешать. В сталкере все анимации имеют 30 фпс. Так что  это значение можно поменять один раз и сохранить настройки.

А то потом нужно будет каждый раз менять фпс после экспорта, если он не равен 30. Или проверять, не изменилось ли оно.

Может я захочу переделать все анимации на 60 фпс, и работать с 60 фпс-ными версиями (может для рендеринга видео или в других ситуациях). Но аддон мои 60 фпс будет менять на 30.

**Comment by PavelBlend** [comment]
Эту возможность добавлять не буду, так как она лишняя и будет мешать. Поэтому  закрою issue.
