### ISSUE TITLE
у меня не экспортируются ogf файлы, СРОЧНО ПОМОГИТЕ!!!

### ISSUE THREAD

**Issue by sasha244** [PavelBlend/blender-xray#613]
я отвязал кости от (очистил родителя) монолитовца и пришил к метрокопу которуму я применил его модель и удалил арматуру для того чтобы он стоял как монолитовец, пришил с автоматическими весами, может двигать телом,начал портировать в ogf файл и появляется ошибка (меш-объект имеет вершины, которые не привязаны к экспортируемым костям)

**Comment by SamArtGit** [comment]
СРОЧНО НЕ ПОМОЖЕМ!!! но установи себе этот файлик и в режиме редактирования в панели групп вершин нажми эту кнопку чтобы выделить не привязанные к группам вершин костей вершины.

https://github.com/Psycrow101/blender3d_smd_utils/blob/master/select_unassigned_vertices.py

<details>
  <summary></summary>

![image](https://user-images.githubusercontent.com/56885075/229275110-59cd1239-dbaa-432d-b3e8-f723dcfd0abc.png)
</details>

**Comment by sasha244** [comment]
я скачал этот мод и у меня ничего не произошло
версия блендера 2.92.0

**Comment by PavelBlend** [comment]
> меш-объект имеет вершины, которые не привязаны к экспортируемым костям

нужно чтобы все вершины имели веса. И чтобы эти веса были назначены на экспортируемые кости.
Экспортируемая кость - это кость, у которой включен параметр `Exportable` и эта кость будет сохранена в файл `*.object`. Если этот параметр деактивирован, то кость в файл не попадёт.
![000000](https://user-images.githubusercontent.com/7983249/229297726-fb1d7608-6ef7-4583-af23-31bf28addc4c.jpg)

И второй случай возникновения этой ошибки:
есть вершины, которые вообще не привязаны ни к одной кости. Такие вершины можно найти с помощью этого оператора:
![22222](https://user-images.githubusercontent.com/7983249/229297863-f1c56964-c06e-4047-ad67-a968a5baa3be.jpg)
