### ISSUE TITLE
Вписывать лимиты костей в зависимости от их позы.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#618]
Не знаю сложно ли сделать такое или нет но в N панели во вкладке Transform указывается-же вращение по осям для конкретной кости, то можно оттуда брать для Minimum и Maximum, только сделать 2 разные кнопки чтобы с конкретной позы кости захватывать для Minimun либо Maximum соответственно.

**Comment by PavelBlend** [comment]
@SamArtGit сделал эту возможность. Можешь проверить, всё ли удобно? Код с этой возможностью в последнем коммите ветки develop.

Как пользоваться:

Минимальные лимиты в 3д окне рисуются более тёмным цветом, чем максимальные. Красный цвет - максимум, тёмно-красный - минимум.

![01](https://user-images.githubusercontent.com/7983249/233436917-db317772-5caa-42e2-b8f6-8676fada8114.jpg)

В N-панель добавлены кнопки во вкладку `Armature tools`:

`Min X`, `Min Y`, `Min Z` - эти кнопки устанавливают минимальный лимит для осей x, y, z соответвенно
`Max X`, `Max Y`, `Max Z` - тоже самое, но для максимальных лимитов
`Min XYZ`, `Max XYZ` - тоже самое, что и верхние кнопки, но позволяют за один раз указать лимиты сразу для всех осей x, y, z, а не по отдельной
`Min/Max X`, `Min/Max Y`, `Min/Max Z` - указывает минимальный и максимальный лимиты для осей x, y, z соответственно. Если вращение по оси x равно -20, то после нажатия `Min/Max X` минимум будет -20, а максимум 20. Значения одинаковые, но разные знаки. Диапазон лимитов будет симметричным.

Кнопки будут изменять лимиты только для активной кости в режиме `Pose Mode`.

При изменении лимитов цифры могут не совпадать с вращением кости. Это нормально, так как режим вращения может быть `Quaternion`, `Euler XYZ`, `Euler ZYX` и т. д. Цифры лимитов будут совпадать только если у кости режим вращения `Euler ZXY`.

**Comment by SamArtGit** [comment]
Извиняюсь за позднюю обратную связь, "заработался", не думал что вы возьметесь за это, сделано всё удобно и так как представлял это в голове (и даже больше)! Спасибо!
