### ISSUE TITLE
Не работает экспорт в .object с изменённым размером модели.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#619]
Павел, помните в Discord спрашивал вас как экспортировать увеличенный объект, чтобы вместе с ним увеличивались и размеры форм костей с анимациями? Вы тогда сказали, что нужно экспортировать объект без применения Scale, но тогда выдаёт эту ошибку:
`Armature-object has incorrect scale: "название_модели"`
А если применить, то тогда остаются старыми размеры форм костей.

**Comment by s30-zip** [comment]
Возможно можно увеличить масштаб в режиме редактирования; скелет и потом меш на то же значение. Если б можно было масштабировать все скопом...

**Comment by PavelBlend** [comment]
@SamArtGit в текущей версии нельзя масштаб менять. Я ещё не внедрял эту возможность в основную ветку, так как там были баги экспорта ogf. Вот здесь писал: #476

Тот код скорее всего поломал всё, кроме object экспорта.
