### ISSUE TITLE
Некорректно работает импорт level в Blender 3.5

### ISSUE THREAD

**Issue by SadBoyOff** [PavelBlend/blender-xray#622]
![image](https://user-images.githubusercontent.com/48679903/232652679-4f42cc74-0a66-4f96-8e85-54cc077be08e.png)
что с UV происходит?(тут лишь плитку отмасштабировал чуть)
в конфигах все папки указаны корректно, форматы указаны CS/CoP
уровень mp_bath

**Comment by SamArtGit** [comment]
Кстати да, наблюдается такая проблема. Думал это только у меня на уровнях из модификаций такое.

**Comment by PavelBlend** [comment]
@SadBoyOff проверил. Этот баг есть только в 3.5.0. Я импортировал mp_bath из Зова Припяти и он импортируется через раз. Иногда блендер просто закрывается, а этого не должно быть ни при каких случаях, какие бы скрипты не выполнялись. Зато в 3.4.1 всё без ошибок:
![02](https://user-images.githubusercontent.com/7983249/232716790-375bf9d4-c197-406d-9595-2b7d62f5fc94.jpg)
И Затон:
![00](https://user-images.githubusercontent.com/7983249/232716963-1b550843-5b50-4199-8f7f-27c94a310fbf.jpg)
В 3.5.0 Затон вообще не импортируется, блендер закрывается.

Здесь написано, что был изменён внутренний формат мешей:
https://wiki.blender.org/wiki/Reference/Release_Notes/3.5/Python_API

Но я не использую внутренний меш. Все объекты создаются с помощью bmesh. Такое ощущение, что есть баг блендера при конвертации bmesh во внутренний меш.

Решение пока такое: используй 3.4.1 для импорта уровней.

**Comment by SadBoyOff** [comment]
в 3.4.1 редактор UV вовсе сломан, но ладно буду через него только импортировать, работать в 3.5
спасибо за ответ

**Comment by PavelBlend** [comment]
В 3.5.1 Release Candidate ошибки UV были исправлены, но импортёр level в 3.5.1 всё равно нестабилен. Вторая ошибка заключается в том, что блендер просто закрывается, как писал здесь:

> Иногда блендер просто закрывается, а этого не должно быть ни при каких случаях, какие бы скрипты не выполнялись.

Ошибка возникает при импорте большого уровня с деревьями.
Я создал баг репорт разработчикам блендера, так как проблема в коде блендера:
https://projects.blender.org/blender/blender/issues/107168

И открою эту issue, чтобы следить за багом.

**Comment by SadBoyOff** [comment]
Blender 3.5.1
последняя версия плагина
плагин переустанавливал с нуля
![image](https://github.com/PavelBlend/blender-xray/assets/48679903/4e113421-eeea-4920-bc0f-abaf2dff7a9e)

**Comment by PavelBlend** [comment]
@SadBoyOff версия плагина сегодняшняя v2.29.0? Если нет, то обнови, так как я вроде бы что-то такое исправлял.

**Comment by PavelBlend** [comment]
Удалось найти обходной путь, чтобы работал импорт:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/1e2094dd-d358-42ca-b79a-41b49f3cfdb6)

**Comment by PavelBlend** [comment]
Решение проблемы подсказал [Martijn Versteegh](https://projects.blender.org/Baardaap) здесь:
https://projects.blender.org/blender/blender/pulls/113525#issuecomment-1086214

Ошибка связана с тем, что удаляются питоновские ссылки на данные меша (uv слои, цвета вершин и т. д.) после освобождения и перераспределения памяти.
