### ISSUE TITLE
Добавить на панели Import/Export горячие клавиши для операторов импорта/экспорта

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#623]
Чтобы не открывать настройки и не искать в них сочетания клавиш, нужно добавить сочетания клавиш на видное место в панель окна `Viewport 3D`.
![01](https://user-images.githubusercontent.com/7983249/233836877-eec46b33-a047-49a8-9e80-84b62e445517.jpg)

**Comment by PavelBlend** [comment]
![01](https://user-images.githubusercontent.com/7983249/233837373-bca8a938-2328-46ff-aa3b-46243ec3344f.jpg)

**Comment by PavelBlend** [comment]
![01](https://user-images.githubusercontent.com/7983249/233837965-eebefe88-65c4-4539-8426-0c825cf60fd6.jpg)

**Comment by SamArtGit** [comment]
> Чтобы не открывать настройки и не искать в них сочетания клавиш

Или просто не наводить курсор на кнопку и не ждать сколько-то там секунд.
