### ISSUE TITLE
Оператор для поиска Invalid face/Area is too small

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#625]
#### Описание идеи:
Сделать оператор подобный оператору для поиска ошибок групп сглаживания, но уже только для слишком маленьких полигонов

#### Примеры использования:
Быстрая проверка, например, скачанных моделей

#### От себя
Я делал библиотеку моделей. Потратил кучу времени на адаптацию моделей под X-Ray и уже во время создания и компилирования тестовой локации происходила проблема с Invalid face/Area is too small (компилировал на компиляторе от Sky-Loader, возможно и в этом конечно проблема), но думаю такой оператор помог бы мне и возможно другим избежать проблемы еще на этапе адаптации/создания

[На всякий скучай прикреплю модель в которой точно будет ошибка (при импорте в Blender через GLTF)](https://sketchfab.com/3d-models/ussr-soda-machine-first-low-76677d5ac8af46a78f4db494a84ba280)

**Comment by PavelBlend** [comment]
Связанный запрос #305

**Comment by TheParaziT** [comment]
@PavelBlend закрыть тогда issue, чтобы не дублировать проблему?

**Comment by PavelBlend** [comment]
@TheParaziT пусть будет. Та issue больше про баг, а это новый функционал. Я просто пометил, что они связаны, чтобы в истории коммитов легче поиск был.

**Comment by PavelBlend** [comment]
Добавил оператор `Check Invalid Faces`:

![01](https://github.com/PavelBlend/blender-xray/assets/7983249/41d70927-f092-4e65-8f7d-9ad2cffe3c1d)

Параметры:

`Mode` - режим, который указывает, какие объекты проверять:
 - `Active Object` - активный объект
 - `Selected Objects` - выделенные объекты
 - `All Objects` - все объекты

`Check Face Area` - проверить наличие полигонов, которые имеют близкую к нулю (меньше `0.00001`) площадь. Для `xrLC` такие полигоны некорректные.

`Check UV Area` - проверить наличие полигонов, которые имеют близкий к нулю (меньше `0.000122`) периметр `UV`. Такие полигоны тоже некорректные для `xrLC`.

Для `UV` минимальный периметр вычисляется так: `0.5 / 4096`, что равняется половине пикселя при разрешении текстуры `4096`.
