### ISSUE TITLE
Не работает загрузка локации.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#626]
Попробовал загрузить локацию вокзал Лиманска на самой последней версии дополнения и Blender.
<details>
  <summary></summary>

[blender.crash.txt](https://github.com/PavelBlend/blender-xray/files/11434493/blender.crash.txt)
</details>

**Comment by PavelBlend** [comment]
@SamArtGit блендер 3.5 имеет ошибки из-за которых аддон не работает нормально. Я об этом знаю, здесь писали #622 
Я жду, когда разработчики блендер исправят:
https://projects.blender.org/blender/blender/issues/107168

Пока используй 3.4.1.
