### ISSUE TITLE
Пожелания улучшений в будущих версиях

### ISSUE THREAD

**Issue by SadBoyOff** [PavelBlend/blender-xray#627]
![image](https://github.com/PavelBlend/blender-xray/assets/48679903/d323edbf-8c4f-4aa2-945d-21b52c85fdc2)
1
зачем вообще нужна эта часть в шейдере?(к тому же ломает Node Preview)
![image](https://github.com/PavelBlend/blender-xray/assets/48679903/4ed6d59b-4bc9-47df-a2de-53b20de0dc40)
2
автоматическое указание упакованного альфа канала вместо прямого
![image](https://github.com/PavelBlend/blender-xray/assets/48679903/21264be3-defe-4d30-8fe9-8d95136568a3)
3
как то надо решить постоянное дублирование материалов, постоянно приходится прогонять M-Cleaner ом
![image](https://github.com/PavelBlend/blender-xray/assets/48679903/a522f121-d978-4b16-901f-e5f6d4204791)
4
самое важное - при импорте уровня подключается только диффуз, не удобно

**Comment by PavelBlend** [comment]
@SadBoyOff 
1 - указывает, какую юви карту использовать для данного материала. У некоторых объектов, кроме юви текстуры, есть юви для карт освещения. И чтобы на рендере была правильная текстура, нужно указывать эту юви карту. Если её не указать, то будет использоваться карта с иконкой фотоаппарата:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/805497b4-e56a-4d1b-a789-6e7c3742d8a3)

Если редактировать объекты, добавлять новые, создавать им развёртки с разными именами, объединять объекты, то в какой-то момент юви карта может потеряться, если не указать ноду UV Map. Эта нода гарантирует, что юви у материала как минимум на рендере будет правильная. Во вьюпорте отображается активная юви.

И что такое Node Preview? Стандартная возможность или инструмент аддона Node Wrangler? И как запустить эту preview?

2 - для чего это может быть использовано? В блендере 2.77-2.79 нет такого режима, я выбрал тот, который есть во всех версиях блендера.

3 - эти материалы имеют одну текстуру, но скорее всего, разные игровые шейдеры. Проверь эти параметры, они должны быть разными:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/33eef40c-8e5c-4723-809c-460ff5820db6)
Если они разные, то это не дубликат.

4 - это я специально сделал для материала террейна. У других объектов альфа канал подключен:
![04](https://github.com/PavelBlend/blender-xray/assets/7983249/a0107257-00ee-4637-a726-7d5afedd6864)

Если террейну подключить альфу, то он будет в дырках. Так как у тестуры террейна нет альфа канала. Вместо альфы там установлена карта hemi, а её нельзя использовать в качестве альфа канала.
![03](https://github.com/PavelBlend/blender-xray/assets/7983249/59c9084d-f2fc-4e61-89f5-eab6470ef66a)

**Comment by SadBoyOff** [comment]
ну хоть галочки дай перед импортом)
повыключать чё не нужно
я локу просто для рендеров загружаю

**Comment by PavelBlend** [comment]
> ну хоть галочки дай перед импортом)

@SadBoyOff для чего именно галочки? Для всех 4 пунктов?

> я локу просто для рендеров загружаю

а что для рендера мешает? Из всех 4 пунктов вроде бы ничего не должно мешать.

1 - указывает юви, а для рендера наоборот это более стабильно
2 - результат тот же, что и для Strainght. Насчёт потребления памяти, то не думаю что будет намного выше
3 - дубликаты на рендер не влияют. Результат тот же
4 - тоже не портит рендер

**Comment by SadBoyOff** [comment]
issues можешь удалять
ты меня не понял
