### ISSUE TITLE
Выбор анимаций для экспорта

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#64]
Предложение: сделать возможность выбрать анимации, которые будут экспортироваться в object файл. Сейчас экспортируются все анимации, что есть в blend файле.

**Comment by igelbox** [comment]
Либо хранить у анимации флаг-признак того, что она экспортируемая +возможность задания флага через интерфейс Graph Editor-а.
Либо, например, использовать NLA -треки для группировки экспортируемых анимаций +возможность выбрать нужный nla-трек при экспорте.

**Comment by PavelBlend** [comment]
Мне кажется, что первый вариант не подойдёт. Например, в тех случаях, когда в сцене два скелета. Получается, что для двух скелетов будут экспортироваться одни и те же анимации. А чтоб сделать экспорт разных анимаций для каждого из них, нужно будет перенастраивать все флаги.
Логичнее добавить список root объекту или NLA использовать.

**Comment by igelbox** [comment]
Согласен, 1-й вариант - не гуд.
Через NLA задаётся в [valve-вском Blender Source Tools](https://developer.valvesoftware.com/wiki/Blender_Source_Tools_Help).
Ну ещё и список у root-а надо попробовать сделать.
