### ISSUE TITLE
Добавление камеры для уровня

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#641]
Добавить возможность создавать камеру с параметрами, которые совпадают с параметрами глобальной игровой камеры уровня. Сейчас есть возможность создавать камеру только для HUD-моделей оружия.

**Comment by PavelBlend** [comment]
Добавлен параметр `Camera Type` для оператора `Add X-Ray Camera` в `N`-панеле, вкладка `Add`:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/8e157e07-2aad-42ce-b1d5-99d1068e264d)

`HUD` и `Level` камеры отличаются значением `FOV`:
- `HUD` - 30.5 градусов
- `Level` - 67.5 градусов

Эти значения взяты из ТЧ.

**Comment by TheParaziT** [comment]
А что эта за камера и для чего нужна? Что-то для облетов по локациям?

**Comment by PavelBlend** [comment]
@TheParaziT level камера - это глаза ГГ в игре. Дома, деревья, кусты, транспорт и т. д. рисуются на экране с помощью этой камеры. У этой камеры fov равен 67.5

Но HUD модели оружия рисуются со своим независимым FOV. В ЗП этот FOV можно изменить с помощью консольной команды `hud_fov`. В ТЧ этой команды нет, угол обзора для оружия всегда равен 30.5.

Если ты создаёшь анимации оружия для тч, то добавь камеру, указав `Camera Type` в `HUD`.
Но если ты хочешь создать анимацию `*.anm` для катсцены, то добавь камеру, указав `Camera Type` в `Level`.
