### ISSUE TITLE
Ошибка импорта файла .level

### ISSUE THREAD

**Issue by RedErr404** [PavelBlend/blender-xray#647]
При открытии файла вываливается сообщение - Недопустимый scene selection файл. Не найден "version" блок. Версия аддона 2.31.0, версия SDK 0.7.

**Comment by PavelBlend** [comment]
@RedErr404 для импорта объектов локации из СДК нужно использовать `.part` импортёр и импортировать `scene_objects.part` файл.

Импортёр `.level` импортирует выделение из СДК.

В сталкере два формата `.level`:
- основной файл локации (хранится в `rawdata\levels` или в `rawdata\maps`)
- список выделенных объектов `Scene Selection`

Аддон поддерживает импорт второго. Файлы формата `Scene Selection` создаются в LevelEditor:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/fff21ffc-6248-4d69-8d09-d04da5aa12bd)
После сохранения будет создан файл с расширением `.level`, который можно будет импортировать.

`Scene Selection` - это не геометрия. Это список `.object` файлов. Весит несколько килобайт, даже если хранит сотни объектов. Перед импортом нужно указать параметр `Objects Folder` в настройках аддона, чтобы аддон знал, где искать модели для импорта.

**Comment by RedErr404** [comment]
Спасибо за разъяснение!
