### ISSUE TITLE
Когда уже будет Discord

### ISSUE THREAD

**Issue by SadBoyOff** [PavelBlend/blender-xray#648]
Когда уже будет Discord сервер

задавать вопросы через эту форму на гитхаб не удобно, да и спрашивать постоянно у разработчика необходимости нет
сделать бы нормальный сервер чтобы старожилы и новички могли поделится мелочами не только в плане функционала плагина, но и в принципе блендера

**Comment by PavelBlend** [comment]
Есть же форумы amk и ap-pro с темами по блендеру. Есть много серверов по блендеру, которые не связаны с моддингом сталкера. Если создавать дискорд, то за ним нужно следить, модерировать, тратить на него время. Поэтому я его создавать не буду. Если у кого есть желание, то пусть создаёт свои сервера.
