### ISSUE TITLE
Ошибка экспорта ключей форм.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#650]
При выключенном одном из ключей во время экспорта будет учитывается его значение.
![image](https://github.com/PavelBlend/blender-xray/assets/56885075/4bce74cd-d88a-4623-95b7-93f610191f7b)

**Comment by PavelBlend** [comment]
@SamArtGit у меня не учитывается. Вот пример:
[shape_key_test.zip](https://github.com/PavelBlend/blender-xray/files/11779659/shape_key_test.zip)
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/e84515c3-002d-4800-9ca7-d7482d2fa0e0)

**Comment by SamArtGit** [comment]
А, ой... Действительно работает. Вчера 2 раза экспортировал для перепроверки и показалось что не работает. Извиняюсь за мусорный пункт.

**Comment by SamArtGit** [comment]
Нет, всё таки не показалось! Не работает когда в скелете есть несколько не объединённых моделей, в итоге при экспорте и объединении моделей учитывается значение отключённых ключей форм. Вот .blend файл с переименованным расширением в обход ограничений по типу загружаемых файлов на GitHub.

[Shape_keys_bug_test.blend.zip](https://github.com/PavelBlend/blender-xray/files/11830187/Shape_keys_bug_test.blend.zip)
