### ISSUE TITLE
Ошибка/вылет при экспорте в ogf

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#658]
#### Как воспроизвести ошибку:
1. Открыть файл crash.blend.
2. Экспортировать в ogf с любым названием.

#### Версии ПО:
 - OS: Win10 x64 22H2
 - Blender: 3.5.1
 - Версия аддона: 2.31.0

#### Дополнительная полезная информация:
Прикладываю blend файл, в котором вылетает, а также лог блендера: https://disk.yandex.ru/d/cfiH7ujnrI4OlQ
При экспорте blender либо зависает намертво, либо закрывается, либо вылезает портянка в логе, по-разному.

**Comment by PavelBlend** [comment]
Файл перезалил сюда, чтобы не утерять:
[crash.zip](https://github.com/PavelBlend/blender-xray/files/12016641/crash.zip)
Ошибка скорее всего связана не с аддоном, а с самим блендером.

**Comment by PRXPHET** [comment]
Я откатил аддон до версии 2.28.0 и ошибки там такой нет, потому не знаю.
