### ISSUE TITLE
Отсутствующие кости в файле

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#66]
На данный момент есть модели, которые плагин не может загрузить.
Например: [hpsa_new_bone.zip](https://github.com/igelbox/blender-xray/files/237228/hpsa_new_bone.zip)

В этом файле кость bip01_neck ссылается на parent-кость bip01_spine, а этой кости нет в файле.
Хотя Actor Editor их читает.

**Comment by igelbox** [comment]
Нужно попытаться игнорировать эту ошибку, выдавая просто warning.
