### ISSUE TITLE
Непонятки с импортом scene selection

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#667]
При попытке импорта любой сцены вылетает ошибка: Bad scene selection file: cannot find "objects" chunk.
Пути в paths указаны все, в том числе rawdata\objects, который упоминался в схожих issues.

В чём может быть проблема?

**Comment by PavelBlend** [comment]
@PRXPHET прочитай здесь решение вопроса #647
Тебе нужно импортировать `scene_objects.part` файл. Файлы .level из rawdata\maps не импортируются
