### ISSUE TITLE
Выбирать предустановку путей к текстурам при импорте моделей в N панели.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#669]
Не удобно перед импортом каждый раз лезть в настройки и менять предустановку путей с ТЧ на ЗП и прочее.

**Comment by PavelBlend** [comment]
@SamArtGit в какой N-панели? В той, которая в 3д окне? Или так, которая в файловом браузере?

**Comment by SamArtGit** [comment]
Да, в файловом проводнике. По сути это окно свойств но когда прочитал, что Вы называете её N панелью, то так для себя и запомнил на будущее.

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/452701a1-1cbe-4fd6-b211-59aee945ee84)

**Comment by PavelBlend** [comment]
@SamArtGit да, она называется N панелью. так как вызывается клавишей N. Но у каждого окна своя N панель. Я уточнил, в каком именно окне.

Я не хотел бы добавлять новые параметры в панель в файловом браузере. Не хочу плодить много параметров. Хотелось бы даже удалить галочку `Split Mesh by Materials`. Сделать так, чтобы был один режим импорта, без этой галочки. Но код будет медленнее работать, поэтому галочка ещё есть.

Можно было бы добавить выбор пресета не в браузер, а в 3д окно в N панель, в панели Import/Export. Так как если добавлять в браузер, то придётся добавлять для всех форматов, которые используют текстуры. И не хочется добавлять только для object формата.

Вторая проблема в том, что пресеты настроек изменяют все параметры аддона. Даже цвета шейпов во вьюпорте, значения по-умолчанию для импортёров/экспортёров и т. д. Для путей нужно создать свои пресеты. Даже не пресеты, а список, как список с анимациями у объекта. Я здесь это описывал: #300 #95

@SamArtGit а тебе часто приходится переключаться между разными папками с текстурами?

**Comment by SamArtGit** [comment]
> Хотелось бы даже удалить галочку `Split Mesh by Materials`. Сделать так, чтобы был один режим импорта, без этой галочки.

К слову да, по сути она не нужна. ведь если нужно разделить модель по материалам, то есть P > By Material, а кому нужен разделённый меш по материалам внутри модели? Но если и так нормально работает, то лучше не трогать. %)

> часто приходится переключаться между разными папками с текстурами?

Честно говоря, часто, но обхожусь поиском недостающих материалов в нужной папке через File > External Data > Find Missing Files. Если это действительно много муторной работы нужно чтобы сделать эту возможность, то обойдусь

**Comment by PavelBlend** [comment]
> К слову да, по сути она не нужна. ведь если нужно разделить модель по материалам

она нужна всё таки. Так как некоторые модели имеют неправильные данные. Импортируй файл `rawdata\objects\trees\new_trees\trees_topol_1_01.object` из СДК 0.4. Там будет месиво из полигонов, если эту галочку не включать. Ствол тополя имеет полигоны с текстурой коры и полигоны с текстурой fake collision. Но они склеятся. Их нужно разделять. Вот подробнее описано:
https://github.com/PavelBlend/blender-xray/wiki/Plugin-.object
Внизу есть описание `Параметры оператора импорта .object` > `Split Mesh By Materials`

> Если это действительно много муторной работы

я уже начал писать. Вроде бы получается без большого переписывания кода.

**Comment by PavelBlend** [comment]
@SamArtGit добавил в N-панель 3д окна параметр для выбора пресета путей:
![06](https://github.com/PavelBlend/blender-xray/assets/7983249/6966e119-1194-4e74-8caf-d0d944a80df8)

Сами пресеты описал здесь: [#300 ](https://github.com/PavelBlend/blender-xray/issues/300#issuecomment-1666500219)

Эта возможность пока есть в ветке [issue/300/alternative-paths](https://github.com/PavelBlend/blender-xray/tree/issue/300/alternative-paths)
