### ISSUE TITLE
unsupported shape: 0

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#67]
Нашёл файл, который не поддерживает плагин. Не импортируется анимация, пишет ошибку "unsupported shape: 0". Вот ссылка на файл: [wpn_binoculars_hud.zip](https://github.com/igelbox/blender-xray/files/237346/wpn_binoculars_hud.zip)

**Comment by ghost** [comment]
Используй обновленный конвертер Бардака https://bitbucket.org/stalker/xray_re-tools/downloads/converter_2015-06-24.7z сконвертировал и импортнул без проблем и ошибок.
[wpn_binoculars_hud.object.zip](https://github.com/igelbox/blender-xray/files/237233/wpn_binoculars_hud.object.zip)

**Comment by igelbox** [comment]
В оригинальном файле в ключах анимации используется TCB интерполяция (shape:0), а плагин сейчас поддерживает только STEP (shape:4).
В файле, сконвертированном обновлённым конвертером Бардака, (внезапно!) все ключи с интерполяцией STEP.
Blender не поддерживает TCB, когда-нибудь плагин будет импортировать эти кривые аппроксимируя их (например через множество точек с линейной интерполяцией).
А пока можно, опять-же, перевести эту ошибку в warning, что анимация импортировалась с погрешностями (а импортировать, как сейчас, f-curve-ами).
Голосуем ))

**Comment by ghost** [comment]
Мне кажется, что TCB интерполяция - это тоже самое, что и Bezier с определенными свойствами хенделов (к примеру интерполяция безье, а своство третьего из десяти хенделов вектор или фри), вот и вся TCB интерполяция. Так что заменять ее не вижу смысла, пусть будет STEP, а данную ошибку перевести в ворнинг с пометкой (используй последнею версию конвертера).

**Comment by PavelBlend** [comment]
Этот object файл получен не путём конвертации конвертером бардака. Я взял его из слива исходников от GSC.

**Comment by igelbox** [comment]
"TCB интерполяция - это тоже самое, что и Bezier" - ну почти, смысл тот же. Только вот с blender-овскими f-curve-ами она не всегда и не совсем совместима.
Можно, конечно, импортировать её как Bezier, а не Linear, но всё-равно будут погрешности (и, наверное, менее предсказуемые, чем в Linear). Но STEP - это хуже, т.к. это означает, что нет никакой плавной интерполяции, а значения изменяются скачкообразно.
Я думаю, надо подправить плагин, чтобы он импортировал STEP, как настоящий STEP, а все остальные виды, как Linear (а не Bezier, как сейчас). Тогда все станет очевиднее.

**Comment by ghost** [comment]
> Этот object файл получен не путём конвертации конвертером бардака. Я взял его из слива исходников от GSC.

А максовские скрипты от Дэна грузят данные модели?

**Comment by PavelBlend** [comment]
Нет, не грузят.

**Comment by igelbox** [comment]
> > А максовские скрипты от Дэна грузят данные модели?
> 
> Нет, не грузят.

А мы будем, когда-нибудь. Нам же не нужна совместимость по багам.
Я считаю, что это косяк/недоработка плагина, и её надо будет рано или поздно исправлять/реализовывать.

**Comment by igelbox** [comment]
Теперь будут импортироваться все виды ключевых кадров. Но так же как и раньше, как-будто бы это были BEZIER с хендлами по-умолчанию. Скелет сейчас всё-равно не очень-то правильный и погрешности при импорте (да и экспорте тоже) даёт.
