### ISSUE TITLE
Ошибка импорта/экспорта, когда удалена горячая клавиша оператора

### ISSUE THREAD

**Issue by L4U6H1N6-LUN4T1C** [PavelBlend/blender-xray#674]
With the release  v2.32.0 I cannot export omf any longer. Any other format works fine
Using blender 3.5.
The error shown is always the same: 
![image](https://github.com/PavelBlend/blender-xray/assets/112844517/49ad6aa4-405c-4757-a190-ef8dc4d1bf6c)

**Comment by PavelBlend** [comment]
Эта ошибка возникает, есть удалить хоткей:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/1013f450-35b4-4056-86f8-abab79abb93b)

**Comment by L4U6H1N6-LUN4T1C** [comment]
thanks!
