### ISSUE TITLE
Bug: Errors/failings to parse and handle fsgame.ltx or sth. similar, the same affects the manually set paths.

### ISSUE THREAD

**Issue by SevenChalices** [PavelBlend/blender-xray#675]
Does the Plug-In adjusts it's behavior when you run it on Linux platforms (is it actually Linux-compatible)?

#### Краткое описание проблемы:
When adjusting the Plug-In's settings (file paths, etc.), no matter if I choose fsgame.ltx or some "for Blender specially modified fsgame.ltx-version (all comments removed, etc.)", I get each time the same tooltip warning...which has more effect during work than just a tooltip showing just symbolically some warning...

"Ltx File Syntax Error: /path/to/call-of-chernobyl/fsgame.ltx"

See the uploaded screenshot: https://imgbb.su/image/0MtjOb

#### Как воспроизвести ошибку:
Whether fresh installation (of Blender and/or the Plugin) or not, just set the LTX-file first, then you get the error message the first time. Then, each time after setting some file-path in the same Plug-in-settings-window, the tooltip with the error appears.

#### Ожидаемое поведение:
No error messages (even if displayed as tooltips), automatic detecting the file paths for meshes, textures, etc. after fsgame.ltx was parsed. It also sucks to browse from your home directory for textures, meshes, EVERYTHING - despite you have set already everything correctly.

#### Версии ПО:
 - OS: Linux 6.4.0-3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.11-1 (2023-08-17) x86_64 GNU/Linux (Debian Testing/Trixie) - but I had the same problems on other computers with Debian 12 (Stable/"Bookworm"), it's barely few months ago.
 - Blender: Bforartists 3.6.2 which is based on Blender 4.0.0 alpha (it's 1:1 compatible, Bforartists is rather a more intuitive interface, it's not really a hard fork. The problems occur in real Blender (in versions below 4.0.0) anyway.

#### Дополнительная полезная информация:

Is this plug-in actually Linux-compatible?..

Nevertheless, big thanks for your work, Pavel! Bolshoye spasibo! :)

**Comment by PavelBlend** [comment]
The addon should work on linux. But I can't check since I only have windows. Can you give me your fsgame.ltx file? There are no errors on my files. I want to know the reason for the error. Does it depend on the OS.
