### ISSUE TITLE
Ввести версию .level из платформы Call of Chernobyl

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#676]
#### Описание идеи:
Ввести версию .level из платформы Call of Chernobyl

#### Примеры использования:
Полезно для людей, создающих уровни на базе CoC

**Comment by TheParaziT** [comment]
Возможно я ошибся и поддержка есть, но например при импорте слитых уровней из ЧН тоже выдается ошибка
- Версия Blender 3.4.1 Stable
- Win 10x64
```
Full log:
+-import-scene-selection(file='F:\\Need\\StalkerEditorsObjectsMap\\StalkerEditorsObjectsMap\\карты чн\\levels_cs\\levels_cs\\!FinalSP\\agroprom.level')
|  Bad scene selection file. Cannot find "version" chunk
```

**Comment by PavelBlend** [comment]
Аддон не поддерживает эти .level файлы. Он поддерживает другие .level файлы (у них просто расширение одинаковое). И поддерживает .part. Вот описывал: #647
.level нужно вручную создавать. В интернете их не скачать. Как минимум я их ни разу не встречал.

**Comment by TheParaziT** [comment]
> .level нужно вручную создавать. В интернете их не скачать. Как минимум я их ни разу не встречал.

Хм, ну вот например .level ЧН Кордона из пака сливов [StalkerEditorsObjectsMap](https://www.gameru.net/forum/index.php?showtopic=45394)
[escape.zip](https://github.com/PavelBlend/blender-xray/files/12665343/escape.zip)

Вот .level Кордона из CoC SDK
[l01_escape.zip](https://github.com/PavelBlend/blender-xray/files/12665366/l01_escape.zip)

**Comment by PavelBlend** [comment]
ну я же написал:

> у них просто расширение одинаковое

Открой свои .level файлы в текстовом редакторе. У них внутри ничего нет практически. Нет списка объектов. Это как бы главный файл проекта локации. Тебе нужен `scene_objects.part` файл, если хочешь импортировать объекты.

Импортёр `.level` - это импорт выделенных объектов из СДК.
Я дал ссылку выше (https://github.com/PavelBlend/blender-xray/issues/647#issuecomment-1587877179), как создать `.level` файл. Да, расширение то же, но это другой формат. Он как раз хранит в себе список объектов. И их я ни разу не видел в интернете.

**Comment by TheParaziT** [comment]
Окей, спасибо
