### ISSUE TITLE
Текстура земли при загрузке Level - низкого разрешения

### ISSUE THREAD

**Issue by Imartyanov** [PavelBlend/blender-xray#677]
#### Краткое описание проблемы:
При загрузке Level, текстура земли - низкого разрешения
![image](https://github.com/PavelBlend/blender-xray/assets/8487820/a0631220-2050-4c45-bc45-4738deb6a039)

#### Как воспроизвести ошибку:
Загрузить файл Level любого уровня

#### Ожидаемое поведение:
Текстура земли как в игре

#### Версии ПО:
версия аддона: 
v2.32.0
версия блендера: 
2.93/3.41/3.6
Игра: SoC 10006

**Comment by SamArtGit** [comment]
Она такой и будет, так-как это текстура террейна без наложения текстур деталей поверх, которые настраиваются при помощи редактора шейдеров в SDK и назначаются на определённый цветовой канал в текстуре маски терейна.
