### ISSUE TITLE
Экспорт анимации камеры (anm)

### ISSUE THREAD

**Issue by ghost** [PavelBlend/blender-xray#68]
Была создана кривая, пустышка1, пустышка2 и камера, камера присоединена к пустышке1 (Ctrl + P > Object) и повернута на 90 градусов по оси X, кривая в режиме редактирования была масштабирована в 10 раз. К пустышке1 применен ограничитель (Follow Path) и (Track To), для ограничителя (Follow Path) была выбрана кривая, для ограничителя (Track To) была выбрана пустышка2, после чего была нажата кнопка (Animate Path) на ограничителе (Follow Path).

После чего были запечены ключи для пустышки скриптом:
`import bpy

obj = bpy.context.object
sce = bpy.context.scene
set = 'BUILTIN_KSI_LocRot'
ani = []
c = 0

for fra in range(sce.frame_start,sce.frame_end):
    sce.frame_set(fra)
    mat = obj.matrix_world
    ani.append((mat.to_translation(), mat.to_euler()))

for fra in range(sce.frame_start,sce.frame_end):
    sce.frame_set(fra)
    obj.location = ani[c][0]
    obj.rotation_euler = ani[c][1]
    bpy.ops.anim.keyframe_insert(type=set)
    c += 1`
И экспорт с выделенной пустышкой.

Экспортированный файл (untitled.anm) занимает 244 байта и соответственно не несет в себе сто кадров анимации (для теста экспорта использовалось и большее количество кадров - но исход один и тот же, 244 байта).

**Comment by igelbox** [comment]
Не получается воспроизвести: "Animate Path" говорит "path already animated". Приложи, пожалуйста zip с blend-файлом (можно уже с запечёнными ключами).

**Comment by ghost** [comment]
Держи (=
[anmPath.blend.zip](https://github.com/igelbox/blender-xray/files/237525/anmPath.blend.zip)

**Comment by igelbox** [comment]
Да уж, в experimental/format-anm какая-то жесть и сыромятина.
Всё самое нужное перенёс в issues/68-format-anm
Проверь, пожалуйста (особенно анимацию вращения).

**Comment by ghost** [comment]
> (особенно анимацию вращения)

Значение вращения оси X инвертированные, так если было -20, то стало 20 (анимацию смотрел в LevelEditor'е).
[anmATPcircle.blend.zip](https://github.com/igelbox/blender-xray/files/239834/anmATPcircle.blend.zip)

**Comment by vladimirtd** [comment]
Импортируется правильно (только значение bpy_obj.rotation_mode заменил на XYZ, чтобы камера не шла боком - на дефолтных anm протестировано, положение такое, какое должно быть 'LevelEditor').

**Comment by vladimirtd** [comment]
Решил проблему:
(fmt_anm_exp.py)
```
23c23
<         kv = (1, 1, 1, -1, -1, 1)[i]
---
>         kv = (1, 1, 1, -1, 1, 1)[i]
```

**Comment by vladimirtd** [comment]
И импортер поправил:
(fmt_anm_imp.py)
```
28c28
<             bpy_obj.rotation_mode = 'XYZ'
---
>             bpy_obj.rotation_mode = 'ZXY'
50c50
<                 kv = (1, 1, 1, -1, -1, 1)[i]
---
>                 kv = (1, 1, 1, -1, 1, 1)[i]
```

**Comment by vladimirtd** [comment]
Удалил предыдущий комментарий, так как написал не то, что нужно (проблема импортера и экспортера решена - все так, как должно быть). Ключи стал запекать не скриптом, а дефолтными средствами Blender'а - там есть выбор шага, в зависимости от сложности кривой можно с легкостью изменить шаг (пока что оптимальный шаг 10 кадров). Видимых дефектов из-за интерполяции не заметил (тестировал на кривых разной сложности).

**Comment by vladimirtd** [comment]
Протестировал в игре и почему-то положение в нулевых координатах.

**Comment by vladimirtd** [comment]
Или не в нулевых, а просто координаты куда-то делись.

**Comment by igelbox** [comment]
Сейчас тоже проверил в LE из SDK-0.7, но у меня анимация получилась нормальная (никакой инверсии оси X нет).
[Empty.anm.zip](https://github.com/igelbox/blender-xray/files/243268/Empty.anm.zip)

**Comment by ghost** [comment]
> (никакой инверсии оси X нет)

У тебя вращение оси X не задействовано, только Z (Y).
Попробуй эту анимацию:
[2Empty.anm.zip](https://github.com/igelbox/blender-xray/files/243551/2Empty.anm.zip)
