### ISSUE TITLE
Не работает импорт .level

### ISSUE THREAD

**Issue by Piwondepola** [PavelBlend/blender-xray#682]
![Снимок](https://github.com/PavelBlend/blender-xray/assets/148664922/67daf19c-1a9a-43c9-a596-86f2fe3157f9)

Методом тыка перепробовал все, пробовал разные сцены, но никак не хочет импортировать

**Comment by PavelBlend** [comment]
@Piwondepola нужно другие файлы `*.level` импортировать. У тебя файл из `rawdata\levels`, но нужно другие. Вот подробнее:
#647
#676
#667

**Comment by Piwondepola** [comment]
Спасибо!)

**Comment by TheParaziT** [comment]
@PavelBlend может, при импорте этого вида .level выдавать более ясную ошибку или давать ссылку на эти ишшуи?
