### ISSUE TITLE
Я пытался экспортировать анимацию в формате ogf но в итоге выдало ошибку в скриншоте. Я сделал группы default и добавил каждую кость

### ISSUE THREAD

**Issue by Dmitry2005** [PavelBlend/blender-xray#684]
Версия ПО: Windows 10
Blender: Последняя версия с Стима
Плагин тоже качал недавно

![image](https://github.com/PavelBlend/blender-xray/assets/63141956/5c80a093-4d57-40d4-8c92-b557c290d63d)
![image](https://github.com/PavelBlend/blender-xray/assets/63141956/af96284b-7dc2-46df-8cf8-6a6c5a0b1c53)

**Comment by Dmitry2005** [comment]
@PavelBlend

**Comment by PavelBlend** [comment]
@Dmitry2005 скинь файл, я у себя проверю в чём причина.

**Comment by PavelBlend** [comment]
@Dmitry2005 посмотри, все ли кости ты выделял, когда назначал Bone Group? Может некоторые кости скрыты, или может они находятся на другом слое:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/5adc0d5d-5e17-43dc-92fc-fbb786acf719)

И для экспорта нужно выделять не Connected скелет, а исходный. Connected используется для создания анимаций.

**Comment by Dmitry2005** [comment]
[Stalker Rig ZIP.zip](https://github.com/PavelBlend/blender-xray/files/13164921/Stalker.Rig.ZIP.zip)
@PavelBlend вот файл ZIP, в нем .Blend файл с ригом

**Comment by Dmitry2005** [comment]
Как проверю слои скажу что выйдет, благодарю за то что ответили

**Comment by PavelBlend** [comment]
@Dmitry2005 посмотрел файл. Тебе нужно экспортировать объект `stalker_neutral_1.ogf`, а не `stalker_neutral_1.ogf connected`. Connected объект нужен для анимации и у него вся иерархия костей перестроена. Этот скелет вспомогательный и используется только в блендере.

Но перед экспортом нужно настроить объект `stalker_neutral_1.ogf`. Добавь ему анимации в список и укажи в параметр `Dependency` объект `stalker_neutral_1.ogf connected`, так как из него будут браться анимации. Исходный объект как бы зависит от `connected` объекта.

![01](https://github.com/PavelBlend/blender-xray/assets/7983249/eeff2cf4-5c57-4a70-9b50-daa750555e5d)

**Comment by Dmitry2005** [comment]
Благодарю за помощь! Как только экспортирую поделюсь анимацией
