### ISSUE TITLE
Отказ от фейковых костей

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#69]
Предложение: отказаться от фейковых костей (не создавать их), или сделать опцию при импорте для отключения их. Так как пользы от них я не заметил. Анимировать скелет с ними проблематично.

**Comment by igelbox** [comment]
Фейковые кости очень пригодятся, чтобы после каждого экспорта не приходилось настраивать Joint Limits (чтоб коленки у персонажей в обратную сторону не гнулись) в SDK.
Т.к. xray-евские анимации нормально не представимы в blender-е, то придётся для каждой xray-кости делать минимум 2 кости в blender-е: одну - для задания Limits-ов, другую - для привязки анимации. Конечно, можно попробовать создавать доп.кости только тогда, когда нужны Limits-ы, например, hud-модели оружия прекрасно обойдутся без них.

> Анимировать скелет с ними проблематично

В чём проблематичность? Может её получится как-то по-другому устранить.

**Comment by PavelBlend** [comment]
Что-то я не совсем понял то, как применяются фейковые кости. Я их удалял и экспортировал в игру и лимиты сохранялись.

**Comment by igelbox** [comment]
Пока, фейковые кости для limits-ов не используются (а только для connect-инга основных костей для работы IK). Но пока и не все xray-евские анимации нормально представимы в blender-е.
А когда анимации/скелет буду переделывать, то, думаю, фейковые кости очень пригодятся. Вот и хочется выяснить почему

> Анимировать скелет с ними проблематично

**Comment by PavelBlend** [comment]
> Но пока и не все xray-евские анимации нормально представимы в blender-е.

а какие например?

**Comment by igelbox** [comment]
Я уже выкладывал пример в #29.
[выкладываю ещё раз](https://github.com/igelbox/blender-xray/files/237146/bad-cube-animation.zip)
(в zip-е патч для плагина (чтоб он не выгружал тонну step-ключей))

**Comment by PavelBlend** [comment]
Я экспериментировал с импортированной моделью, и понял, что проблемы при анимировании были из-за IK Limits, а не fake костей. Но всё равно как-то не хотелось бы, чтоб плагин их создавал. Так как хочется, чтоб импортировалось всё как есть.
