### ISSUE TITLE
В "локальном виде" отрисовываются формы костей.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#691]
И центры массы костей тоже, хотя скелет в данный "локальный вид" не входил, только модель по и иерархии.
<details>
  <summary></summary>

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/b357aae6-f830-41b2-aeff-5de2816ab2b4)
</details>

**Comment by PavelBlend** [comment]
@SamArtGit сейчас протестировал и нашёл ещё баг: #692
Создал отдельную issue, так как она связана с коллекциями, а не с локальным видом.
