### ISSUE TITLE
Вернуть старый алгоритм Fit Shape.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#693]
Совместив с новым. Иногда не нужно чтобы примитив при припасовке изменялось вращение, а только положение и размеры. Может отдельной кнопочкой, чтобы 2 Fit Shape было? Или подменю, как с Place Selected Objects, но чтобы было 2 сценария припасовки?
<details>
  <summary></summary>

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/7eef87d9-f187-420d-b327-3de09fdea8ac)
</details>

**Comment by PavelBlend** [comment]
@SamArtGit да, я хотел такое сделать, но не создавал issue.

**Comment by PavelBlend** [comment]
Для шейпов `Box` и `Cylinder` добавлены три кнопки для генерации шейпа:

![ui](https://github.com/PavelBlend/blender-xray/assets/7983249/352f5f21-eae2-4442-b372-d1eee7506372)

Для `Sphere` кнопки остались прежними:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/04d37afd-d653-4098-8495-4676aa0e5cb7)

**Fit Shape** - меняет позицию и масштаб шейпа, но не меняет вращение:

![fit](https://github.com/PavelBlend/blender-xray/assets/7983249/2e66ef5a-92fb-4029-8a14-63a52ec7a22d)


**Axis Align Bounding Box** - генерирует шейп таким образом, чтобы он имел минимальные габариты и оси шейпа совпадали с глобальными осями X, Y, Z:

![aabb](https://github.com/PavelBlend/blender-xray/assets/7983249/b4d19d3c-f844-44ec-8d0a-ee5df4546e37)


**Orient Bounding Box** - меняет позицию, вращение и масштаб шейпа, чтобы он имел минимальные габариты и плотно прилегал к вершинам кости:

![obb](https://github.com/PavelBlend/blender-xray/assets/7983249/80f9f3f2-3ab6-4726-b159-cfbecbd167e6)
