### ISSUE TITLE
Генерировать статический канал для кости при экспорте анимации

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#701]
#### Описание идеи:
При экспорте анимации генерировать статический канал кости в скелете, где у этой кости нет анимационного канала

#### Примеры использования:
При создании скелета обьекта, оружия и т.д. может потребоваться доработка (в частности добавление костей), из-за этого анимации сделанные на старом скелете при загрузке в движок не смогут проигрываться и произойдет вылет (сейчас не могу проверить, точно ли так). Предлагаю при экспорте анимаций или в настройках аддона добавить кнопку для этого.

**Comment by PavelBlend** [comment]
@TheParaziT вылета не будет, так как аддон и так сохраняет ключи для всех костей. Нужно, чтобы кость была `Exportable`. Аддон не выясняет, есть ли у кости ключи или нет. Вместо этого аддон поочерёдно включает каждый кадр анимации и считывает матрицы трансформаций костей. А есть ли ключ у кости или нет, аддон не выясняет.

![01](https://github.com/PavelBlend/blender-xray/assets/7983249/18ae02e7-2ea5-4dcd-b79d-3df438d2e20b)

После экспорта:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/60dd813a-bcc0-4745-9a38-24bfff19b845)
