### ISSUE TITLE
При импорте билдовских уровней, у материалов указываются несуществующие слои цветов вершин

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#703]
В ранних билдах формат освещения был другим. Не было освещения hemi и sun. Вместо них был единый light. Но при импорте таких уровней, аддон всё равно указывает материалу слои hemi и sun, хотя их нет у меша. В итоге они подсвечены красным:

![01](https://github.com/PavelBlend/blender-xray/assets/7983249/c2f6347e-d4b2-4be6-8581-9a0e7cbe4a12)

Нужно оставлять параметры пустыми.

**Comment by PavelBlend** [comment]
Теперь аддон не будет создавать эти слои при импорте level из билдов ранее 1580. В 1580 билде появилась динамическая погода.

**Comment by SamArtGit** [comment]
А разве не раньше, в 1558?

**Comment by PavelBlend** [comment]
@SamArtGit сейчас проверил. Да, в 1558. Точнее в level версии 11. Версию 11 имеют два официальных билда: 1558 и 1569 и один неофициальный - 1537.
