### ISSUE TITLE
Выделять вершины при **Mesh-object has vertices that are not tied to any exportable bones**

### ISSUE THREAD

**Issue by TheParaziT** [PavelBlend/blender-xray#707]
#### Описание идеи:
Выделять вершины при **Mesh-object has vertices that are not tied to any exportable bones**. Можно было бы создавать отдельную группу вершин с этими вершинами или просто выделить их Edit режиме

#### Примеры использования:
При экспорте с данным предупреждением сложно найти, либо вовсе невозможно найти такие вершины. 

Пример сцены, где такое происходит
[USR_aek971.zip](https://github.com/PavelBlend/blender-xray/files/13359756/USR_aek971.zip)

**Comment by PavelBlend** [comment]
Аддон будет выделять проблемные вершины:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/44588616-86c0-4864-a5fa-fd2036a0c17d)

Имя проблемного меша пишется в лог файл:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/d409e90a-c204-495d-a94a-3a493ba14bdc)
