### ISSUE TITLE
экспорт anm: автогенерация ключевых кадров по констрейнтам

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#71]
Попытка самостоятельно нарисовать анимацию камеры для сложной сцены показала, что сделать это весьма не просто, т.к. анимированная камера:
- так и норовит протаранить какие-нибудь объекты
- постоянно то разгоняется, то замедляется
- в поворотах смотрит не туда, куда хотелось бы

Было бы удобно анимировать камеру с использованием путей и констрейнтов (типа FollowPath и TrackTo), а затем - просто экспортировать, анимированный таким образом, объект.

Нужно сделать у экспортируемого объекта свойство "Вычислять ключевые кадры при экспорте", а также свойства: frame_start, frame_end и fps.
Вычислять ключевые кадры, можно так:

``` python
for f in range(sce.frame_start,sce.frame_end, 5):
    sce.frame_set(f)
    m = objs.matrix_world
    ...
```

**Comment by ghost** [comment]
Может проще сделать в T панели вкладку X-Ray Tools и добавить кнопку Bake Action, чтобы было удобнее. Так на мой взгляд больше контроля будет.
