### ISSUE TITLE
Ошибка ogf экспорта, когда меш имеет слишком много вершин

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#712]
![blender_EXLBEn4eH7](https://github.com/PavelBlend/blender-xray/assets/75882664/8ebe2d9c-9171-4234-b5ec-6bd90e6a5cb5)

Лог на картинке. На этот раз я адаптирую под скелет СВД модель из Sketchfab. Если нужен blend файл, на котором есть ошибка, могу прикрепить.

**Comment by PRXPHET** [comment]
UPD: [Сразу прикрепляю blend файл.](https://drive.google.com/file/d/1ESllYgcmqSxcW7OYva5s1dd14IqZgl6x/view?usp=sharing)
Заметил, что если удалить основную часть СВД (которая называется svdm внутри ветки svd_hud), то ошибка пропадает.

**Comment by PavelBlend** [comment]
@PRXPHET при экспорте образуется слишком много вершин. Индексы вершин хранятся в 2 байтах. Это значения от 0 до 65 535. Максимальное количество вершин 65 536. У тебя в сцене свд имеет ~32 тыс вершин, но при экспорте они преобразовываются в большее количество, так как формат ogf хранит только одну юви координату для вершины.

Если в блендере вершина имеет 2 юви координаты, то при экспорте в ogf будет сохранено 2 вершины вместо 1.

То же самое касается split нормалей. Если у одной вершины несколько split нормалей, то она сохранится не одна, а будут созданы новые вершины.

СДВ после экспорта имеет более 100 тыс вершин.

Чтобы вершин было меньше, удали двойные вершины. Если не поможет, то сделай меньше юви островов или меньше split нормалей:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/4a17e6d4-fff1-43fe-b8b0-7739590af6aa)
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/3bf8421d-ffea-4d16-8b71-dc3aff9586ea)

Или раздели объект на несколько частей.

Я потом напишу код, который будет печатать читаемое предупреждение.

**Comment by PRXPHET** [comment]
Спасибо за наводку. Помогло уменьшение количества вершин с помощью модификатора Decimate.

**Comment by PavelBlend** [comment]
Теперь будет появляться читаемое предупреждение:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/54d01e3c-24de-46cd-8952-f829336ab212)
