### ISSUE TITLE
Экспорт OMF не дружит с Child Of

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#713]
Некорректно сохраняются позиции костей, которые создаются с помощью констрейна Child Of.
Более наглядно:
Анимация до экспорта (Зеленые кости с констрейном Child Of):
![blender_ahihQopVvT](https://github.com/PavelBlend/blender-xray/assets/75882664/9d04d5d7-b939-4f34-970f-2173f62e209e)
Анимация после экспорта, добавленная к этому же худу (Выделил мышкой, констрейна Child Of на них уже нет):
![blender_M63aJW4B0x](https://github.com/PavelBlend/blender-xray/assets/75882664/7702828a-157a-49dc-97e9-cd9f85fe325b)

При этом экспорт в skl работает корректно. Но если импортировать skl и экспортировать в omf, то будет всё абсолютно так же.

blend файл: https://drive.google.com/file/d/1ZnQA_TW0_8PEhPpa_DcCe8p_Qy3yd7Cr/view?usp=sharing

Действия:
1. Экспортировать в OMF.
2. Импортировать созданный OMF файл на тот же худ.
3. Включить анимацию на скелете, предварительно выключив констрейны Child Of на костях.

**Comment by PavelBlend** [comment]
@PRXPHET кости патронов слишком далеко расположены, когда констрейнт child of отключён. Координаты имеют значения больше тысячи метров.

В omf данные позиции хранятся в сжатом виде. Сначала записывается амплитуда движений, затем сами движения. Координаты костей записаны в 1 байте для ТЧ или в 2 байтах для ЗП для каждой оси. В итоге наименьший шаг равен амплитуде движений / на 256 (диапазон 1 байта 0-255). На таких огромных расстояниях слишком гигантская погрешность.

Расположи кости патронов гораздо ближе к оружию. Чтобы кости имели маленькую амплитуду движений за всю анимацию:
![002](https://github.com/PavelBlend/blender-xray/assets/7983249/8ae69c95-97f2-4979-9202-3d5cc71b5894)
