### ISSUE TITLE
Ошибка при экспорте *.object

### ISSUE THREAD

**Issue by Graff46** [PavelBlend/blender-xray#717]
#### Краткое описание проблемы:

Ошибка наличия более одного рут элемента при экспорте *.object

#### Как воспроизвести ошибку:

Создать модель с арматурой и ригом. Хотя бы одну вертекс группу оставить пустой. Попытаться экспортировать. 

#### Ожидаемое поведение:

Вывод ошибки о неиспользуемых вертексах в вертекс группе.

#### Версии ПО:
 - OS:  Win10 x64
 - Blender: 3.6.4 и 2.93.0

#### Дополнительная полезная информация:

Скачал VS Code и плагин для отладки аддонов блендера, настроил все и дебажил. В коде действительно получался массив нескольких рут объектов, хоть выделяй рут в блендере - хоть нет. Задал в коде жестко выбирать рутом выделенный в редакторе обект: ошибка рутов пропала, но появилась ошибка о пустой вертекс группе. В блендере оказалась одна из вертекс групп действительно пустой, я назначил ей вертексы и кость. Все ошибки пропали. Вернул код плагина в исходное состояние от моих правок - всё работало нормально. Видимо не правильные вертекс группы вызывают ошибки определения рут объектов. Возможно нужно проверять вертекс группы до определения рут элемента или если есть более 1го рут элемента проверять тут же вертекс группы, чтобы в лог писалась реальная проблема.

**Comment by PavelBlend** [comment]
@Graff46 я не понял сути проблемы.

> Ошибка наличия более одного рут элемента при экспорте *.object

по этому описанию не понятно, в чём проблема. Нужно читать, что ниже написано. При экспорте в object, наличие более одного root объекта - это норма.


> Создать модель с арматурой и ригом. Хотя бы одну вертекс группу оставить пустой. Попытаться экспортировать.

лучше предоставить пример в виде blend файла. Я создал арматуру с ригом, сделал пустую группу, экспортировал и получил ожидаемое правильное поведение. Имя пустой группы должна совпадать с именем существующей кости или нет?


> Вывод ошибки о неиспользуемых вертексах в вертекс группе.

у меня ошибка выводится. Пишет, что один объект экспортирован, а второй нет:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/ed10b8ee-c578-47fb-9729-97e5659688b7)

Если рядом с сообщением есть иконка с крестиком, то файл не экспортировался. А если восклицательный знак, то это не критическое предупреждение и файл сохранится.
