### ISSUE TITLE
Баг репорт для скриптов из 3ds max

### ISSUE THREAD

**Issue by Dmitry2005** [PavelBlend/blender-xray#718]
Краткое описание проблемы:
Пытался закинуть анимацию экспортированную используя ваш плагин в 3d Max используя скрипт x-ray-merge-anims.mseб выдало ошибку в скрине и игра не запускается когда пытался добавить анимацию. Неизвестно из за чего проблема происходит. 

Версии ПО:
 - OS: Win10 x64
 - Blender: 3.6

![Снимок экрана 2023-11-26 101621](https://github.com/PavelBlend/blender-xray/assets/63141956/9c16b4ca-702f-4e28-8f2a-9c26ab1c1b98)

**Comment by PavelBlend** [comment]
@Dmitry2005 у меня нет плагина для 3ds max. Здесь хранится аддон для blender.
