### ISSUE TITLE
не анимируются кости

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#72]
Есть object файлы, которые плагин не правильно загружает. В Actor Editor в этом файле анимация проигрывается нормально:
[wpn_g36_hud.zip](https://github.com/igelbox/blender-xray/files/247126/wpn_g36_hud.zip)

а в blender руки не двигаются. Я думаю, что это связано с тем, что имя канала ключей и имя кости не совпадают (например, bip01_r_hand и Bip01_R_Hand)

**Comment by igelbox** [comment]
Надо бы не сломать #3.

**Comment by igelbox** [comment]
Готово, проверяй и буду мерджить.

**Comment by PavelBlend** [comment]
Теперь анимируется как нужно. Всё работает правильно.
