### ISSUE TITLE
Lod_reference doesn't save properly in .ogf format.

### ISSUE THREAD

**Issue by monorio1** [PavelBlend/blender-xray#720]
Exporting and model with a Lod Reference doesn't save the value on export. 
![image](https://github.com/PavelBlend/blender-xray/assets/14852470/2f321973-ff8e-4205-8890-b8a498309a5c)
I have imported a WPN_AK74_world to see how Levels of Details are done, the world model needs to be filled with the _lod model path. 
On reimport of the model, the field is blank. Also opening the file with [AXRToolset](https://github.com/revolucas/AXRToolset) ODF editor doesn't display the Skeleton_lod path. The models from the 0.7 sdk can be opened the same way and display the path. 
![image](https://github.com/PavelBlend/blender-xray/assets/14852470/e131d013-0188-490a-8835-e54846ff7028)

You can change the path and save it. However for models exported using the blender addon, the path registered is empty. 
![image](https://github.com/PavelBlend/blender-xray/assets/14852470/f89c3a50-054b-4efb-b1a1-77fe9da6d502)

Entering a path and saving it, reload of the object in the OGF editor also leaves the path empty. This only happens with .ogf from the blender addon.

**Comment by PavelBlend** [comment]
@monorio1 I reproduced the error. I will fix this error soon.
