### ISSUE TITLE
Ошибка при импорте Gunslinger OMF файла

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#729]
#### Краткое описание проблемы:
При попытке импорта анимаций рук из Gunslinger (Конкретнее, под ПП-19 Бизон) происходит ошибка.
![blender_CGSGtCwxGz](https://github.com/PavelBlend/blender-xray/assets/75882664/4e1b4a66-6605-41ab-8920-7ed27f09e940)

#### Как воспроизвести ошибку:
Импортировать wpn_hand_bizon_hud_animation.omf

#### Версии ПО:

 - OS: Win10 x64
 - Blender: 3.5.1
 - Версия аддона: 2.36.0

#### Дополнительная полезная информация:
Возможно, проблема и не в аддоне вовсе, ибо тот же OMF Editor тоже отказывается открывать этот файл. При этом худ анимации открываются. Сам Gunslinger специально перекачал на всякий, может файлы побились, но нет, ошибка повторяется.
Ссылка на файл, чтобы самому не качать: https://drive.google.com/file/d/1Nob0F-eu417929kI8Gks9PAbd25tLTNQ/view?usp=sharing

**Comment by PavelBlend** [comment]
@PRXPHET посмотрел данный файл. Он битый. Может заглушка. Нашёл анимации бизона в файле `wpn_hand_ak74u_hud_animation.omf`. Файл `wpn_hand_bizon_hud_animation.omf` мод не использует. Я распаковал архивы и удалил этот файл и игра не вылетела.
