### ISSUE TITLE
FATAL ERROR: sp_it!=m_SurfFaces.end()

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#73]
Пытаюсь экспортировать модель из blender'а, но при открытии в Actor Editor появляется ошибка
FATAL ERROR

[error]Expression    : assertion failed
[error]Function      : I:\xray-svn\editors\ECore\Editor\EditMeshRender.cpp
[error]File          : I:\xray-svn\editors\ECore\Editor\EditMeshRender.cpp
[error]Line          : 292
[error]Description   : sp_it!=m_SurfFaces.end()

В чём может быть проблема? Вот blend файл [hand_01.blend.zip](https://github.com/igelbox/blender-xray/files/247323/hand_01.blend.zip)

**Comment by igelbox** [comment]
Похоже на багу в SDK:
- если в объекте есть кости, то`CEditableObject::Render` для каждой surface (по нашему - материала) вызывает `CEditableMesh::RenderSkeleton`, который требует, чтобы в этом mesh-е были полигоны, связанные с текущим рисуемым материалом
- если бы в объекте не было костей, то вызывался бы `CEditableMesh::Render`, который не так строг

Получается, что для в каждом mesh-е косистого объекта должен быть хотя бы один полигон использующий каждый материал (из всех материалов, которые экспортируются).
