### ISSUE TITLE
Problems when exporting OMF

### ISSUE THREAD

**Issue by MPB-TDOA** [PavelBlend/blender-xray#733]
![`A6}~X)ZIB5PJ$PUC6D~4 R](https://github.com/PavelBlend/blender-xray/assets/105104291/8c382c49-98f9-4e78-88c5-8c1b5907d862)
![FIT}Y_SR12Q81F9F4IM0(MU](https://github.com/PavelBlend/blender-xray/assets/105104291/fcdaee3d-7238-4d75-8267-247e88474464)

Some bones will move after the OMF exported, I tested other weapon hand animations and the results are same.But this won't happen when exporting to SKL.

I can't speak Russian. Sorry for that.

blender version:2.83
win10 x64

**Comment by PavelBlend** [comment]
@MPB-TDOA I can't reproduce the error. I need an example blend file that reproduces this error.

**Comment by MPB-TDOA** [comment]
> 我无法重现错误。我需要一个重现此错误的示例混合文件。

[bug.zip](https://github.com/PavelBlend/blender-xray/files/13920136/bug.zip)

Thanks in advance

**Comment by PavelBlend** [comment]
@MPB-TDOA This error is in the blender code, not the addon. When exporting, I use the matrix to_quaternion method, which does not work in version 2.83. Here is my question in the blender bug tracker:
https://projects.blender.org/blender/blender/issues/117400

Solution to the problem: Use a newer version of blender, for example 3.6.
