### ISSUE TITLE
Автосоздание bone group при импортировании корректного OMF

### ISSUE THREAD

**Issue by PRXPHET** [PavelBlend/blender-xray#736]
Заметил, что bone group автоматически создаётся, если OGF дополнительно хранит в себе и анимации, почему бы подобный автоматически не создавать для OGF, если к нему импортируется корректный OMF?

**Comment by PavelBlend** [comment]
@PRXPHET Это придётся во время импорта ogf читать omf файл, в котором хранятся анимации.

Можно в принципе и прочитать omf. Это нужно вычислить ~последний~ первый motion references у ogf, и найти по нему omf файл с помощью путей в настройках аддона (meshes folder).

Сейчас есть такой способ импортировать boneparts:
импортируешь omf с включённой галочкой `Import Bone Parts` и выключенной `Import Motions`.

<br></br>

Всё таки нужно первый motion references вычислить. Проверил в игре.

**Comment by PavelBlend** [comment]
@PRXPHET Это придётся во время импорта ogf читать omf файл, в котором хранятся анимации.

Можно в принципе и прочитать omf. Это нужно вычислить последний motion references у ogf, и найти по нему omf файл с помощью путей в настройках аддона (meshes folder).

Сейчас есть такой способ импортировать boneparts:
импортируешь omf с включённой галочкой `Import Bone Parts` и выключенной `Import Motions`.

**Comment by PavelBlend** [comment]
Теперь при импорте ogf, которые не содержат анимации, аддон будет импортировать bone parts из omf. Так как в самом ogf нет информации о bone parts, если анимации вынесены во внешний omf файл.

Чтобы аддон смог найти omf, в настройках аддона нужно указать Meshes Folder.
