### ISSUE TITLE
Не работает удаление мешей

### ISSUE THREAD

**Issue by damoldavskiy** [PavelBlend/blender-xray#738]
#### Краткое описание проблемы:
После удаление меша и экспорта файла в .ogf сохраняется удаленный меш

#### Как воспроизвести ошибку:
1. Импортировать wpn_fnx45.ogf
2. Выделить линзу прицела
3. Удалить
4. Выделить все
5. Экспортировать в .ogf (Format Version: CS/CoP)
6. Перезапустить Blender, открыть сохраненный файл
7. Линза не удалена

#### Ожидаемое поведение:
В сохраненном файле линзы не будет

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 3.6.5 cf1e1ed46b7e

#### Превью
Вложил видео с демонстрацией проблемы и проблемный файл
[Desktop.zip](https://github.com/PavelBlend/blender-xray/files/14171176/Desktop.zip)

**Comment by SamArtGit** [comment]
Тоже самое заметил в версии 3.не помню какая. Теперь перед нужно очищать неиспользуемые mesh'ы в Orphan Data в разделе Outliner'а.

**Comment by PavelBlend** [comment]
@damoldavskiy без понятия, почему так происходит. У меня ошибка не воспроизводится. После удаления объект удаляется из outliner:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/157674cc-ffe4-4f17-ad04-31e76ddb0e5b)

Импортирую обратно, линзы нет. Может блендер глючит.

Напиши версию аддона, на всякий случай. И посмотри в outliner, остался ли удалённый объект в нём? По идее объекта не должно быть в outliner в режиме blender file.

Видимо у тебя объект не удаляется, а просто отвязывается из текущей сцены.

**Comment by Nestandart5443** [comment]
Тоже встречался с такой проблемой.
Теперь приучился перед экспортом каждый раз нажимать
file - clean up - recursive unused data blocks

Версия Blender 3.2.2

**Comment by PavelBlend** [comment]
@Nestandart5443 эта ошибка стабильно появляется или через раз?

**Comment by Nestandart5443** [comment]
@PavelBlend стабильно. Сейчас на новой версии плагина перепроверил - удалил один объект (штаны), специально датаблоки не очищал - импортировал опять модель - штаны на месте.

**Comment by PavelBlend** [comment]
@Nestandart5443 не знаю, почему так. У меня работает. Проверял в блендере `3.2.2`, аддон последний `2.38.0`. Могу только гадать:

Может у тебя какие-то сторонние аддоны установлены, которые заменяют оператор удаления и меняют его поведение (чтобы объект не удалялся, а просто отвязывался)? Я правда таких аддонов не видел, но мало ли. У себя попробовал все стандартные аддоны включить и сделать экспорт. В итоге всё работает. Значит проблема не в стандартных аддонах. Напиши, какие сторонние аддоны у тебя установлены.

Либо настройки блендера у меня другие. Хотя я не помню такой настройки, которая влияет на удаление объектов. На всякий случай скинь свои файлы с настройками `startup.blend` и `userpref.blend`. Они находится здесь:

`C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\ВЕРСИЯ\config\`

**Comment by Nestandart5443** [comment]
Сторонний аддон один:
Blender Source Tools 3.2.5

И дело, как оказалось, в нëм! Отключил его, и всё заработало как надо! Буду, значит, теперь писать его разработчикам! 

Вам нижайший поклон за аддон и за отзывчивость. И всего хорошего!

**Comment by PavelBlend** [comment]
> Буду, значит, теперь писать его разработчикам!

я попробую у себя код изменить, чтобы он экспортировал только те объекты, которые находятся в сцене. Может не придётся править Source Tools.
