### ISSUE TITLE
Расширение обрезает пути текстур

### ISSUE THREAD

**Issue by damoldavskiy** [PavelBlend/blender-xray#739]
#### Краткое описание проблемы:
При экспорте объекта без опции "Texture Names from Image Paths" сохраняются только первые 63 символа названия текстуры

#### Как воспроизвести ошибку:
1. Импортировать объект (в примере у одного из мешей назначена текстура "wpn\wpn_addons\wpn_addon_scope_c-more_new\wpn_addon_scope_c-more_crosshair_dot")
2. Экспортировать этот объект обратно в .ogf, отключить опцию "Texture Names from Image Paths"
3. При открытии нового .ogf файла в ogf editor название текстуры обрезалось до 63 символов: "wpn\wpn_addons\wpn_addon_scope_c-more_new\wpn_addon_scope_c-mor". В игре теперь эта текстура, логично, не отображается

#### Ожидаемое поведение:
В сохраненном файле должна быть необрезанная строка

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 3.6.5 cf1e1ed46b7e

**Comment by PavelBlend** [comment]
@damoldavskiy это ограничение блендера. Имена блоков данных не могут быть длиннее 63. В данном случае имя ноды Image. В этом случае нужно делать экспорт только с включённой галочкой `Texture Names from Image Paths`.
