### ISSUE TITLE
Joint Limits в виде XRay свойств

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#74]
Создать отдельные "xray" свойства для Joint Limits, вместо использования блендеровских "IK limits". Так как сейчас с данными значениями невозможно анимировать арматуру. Насколько мне известно, Joint Limits используется в движке не для анимации, а когда тело персонажа мёртвое лежит на земле. А для анимации значения не подходят. Это я к тому, что бы использовать для анимирования одни значения limits (блендеровские во вкладке "Inverse Kinematics"), а для экспорта брать другие (из вкладки "XRay").

**Comment by igelbox** [comment]
> Joint Limits используется в движке не для анимации, а когда тело персонажа мёртвое лежит на земле

Странно будет, если мёртвый персонаж будет более или менее гибкий, чем анимированный (если уж коленки назад не гнутся, то это одинаково верно и для ragdoll и для анимации).

> Так как сейчас с данными значениями невозможно анимировать арматуру

Жду пример.

**Comment by PavelBlend** [comment]
Вот пример: [actor_ik.zip](https://github.com/igelbox/blender-xray/files/247339/actor_ik.zip)

Попробуй опустить вниз кость bip01_pelvis, и ноги станут дёргаться

**Comment by igelbox** [comment]
Если выключить опцию `View 3D > Tool Shelf > Options > Auto IK` (ну или `<armature>.use_auto_ik = False`), то скелет перестанет дёргаться.
Такое решение подходит?

**Comment by PavelBlend** [comment]
Всё равно дёргается. Вот видео:
[https://youtu.be/yCllvrANEII](https://youtu.be/yCllvrANEII)
Левая ступня не должна дёргаться и опускаться ниже. Она должна стоять на месте, при опускании таза вниз.

**Comment by igelbox** [comment]
@PavelBlend, спасибо, теперь вижу. Оно даже на `actor_ik.zip` воспроизводится.
А в чём состоит негатив от этого подёргивания: раздражает при анимировании, экспортируется с подёргиваниями, или что-то другое?
Мне бы не хотелось отключать IK Limit-ы, т.к. хочется чтобы их тоже нормально настраивали, а не забивали. А как настраивают (и настраивают ли) IK Limit-ы при производстве серьёзной анимации (фильмы или мульты там, какие-нибудь)?

**Comment by PavelBlend** [comment]
> А в чём состоит негатив от этого подёргивания

в том, что ступни сдвигаются с места при приседаниях (опускаются в низ под пол). Ступня должна быть неподвижной на полу.

> А как настраивают (и настраивают ли) IK Limit-ы при производстве серьёзной анимации (фильмы или мульты там, какие-нибудь)?

Я думаю настраивают. Но в сталкере значения для ragdoll не подходят для анимирования, всё дёргается.

**Comment by igelbox** [comment]
> Ступня должна быть неподвижной на полу.

Неа, так человеки не гнутся.
Ты попробуй, встань у стены (чтобы плечи, задница и пятки к сетене прилегали) и попробуй сесть (не отрывая эти 3 точки от стены, а пятки ещё и от пола). Я думаю, что не получится, так почему тогда у сталкера такое должно получаться (ты же `bip01_pelvis` у него вертикально вниз тянешь)? Или этот сталкер у тебя аномальный какой-то (пару дней в холодце пролежал)? =)

> Но в сталкере значения для ragdoll не подходят для анимирования

А какие значения бы подошли? Может если такие "подходящие" значения выставить, то и в игре физика ragdoll-а будет выглядеть нормально? Это я всё к тому веду, что может просто модели, которые импортируем, были "на скорую руку" (абы как) настроены.

**Comment by redpython** [comment]
>в сталкере значения для ragdoll не подходят для анимирования, всё дёргается.

Лимиты костей модели из Actor Editor никоим образом не пересекаются с лимитами костей, задаваемыми при анимировании в 3-д пакете. Это разные вещи. АЕшные лимиты используются только для реалтаймовой внутриигровой физики, которая настроена вовсе не так, как можно себе представить :)

**Comment by PavelBlend** [comment]
Сделал лимиты в виде XRay свойств 4a162ed56b49d505278c0b7f73966ad3d7d8bf7b
![01](https://user-images.githubusercontent.com/7983249/52857224-97211200-3137-11e9-8913-dd234184170c.png)

И добавил инструменты для редактирования этих свойств:
![02](https://user-images.githubusercontent.com/7983249/52857256-a86a1e80-3137-11e9-924a-2d99d1db1db8.png)

И лимиты могут отображаться в 3д окне:
![03](https://user-images.githubusercontent.com/7983249/52857269-b3bd4a00-3137-11e9-9b8b-9c61f30f4dd1.png)

Жёлтая точка указывает текущий поворот. А красные/зелёные/синие дуги указывают лимиты

**Display Bone Limits** - включает отображение лимитов у выделенных костей в 3д окне

**Gizmo Radius** - размер виджета лимитов в 3д окне

**Limit X / Limit Y / Limit Z** - включает/отключает видимость лимитов осей X / Y/ Z

**Convert Limits to Constraints** - создаёт констрейнты Limit Rotation для выделенных костей, с настройками XRay лимитов

**Remove Limits Constraints** - удаляет констрейнты Limit Rotation у всех выделенных костей

**Convert IK Limits to XRay Limits** - копирует значения из лимитов IK в лимиты XRay

**Convert XRay Limits to IK Limits** - копирует значения из лимитов XRay в лимиты IK

**Clear IK Limits** - отключает IK лимиты (устанавливает значения для минимума в -180, а для максимума 180).

**Comment by PavelBlend** [comment]
Есть одна проблема:
нельзя будет корректно экспортировать лимиты костей, которые уже сохранены в blend файле.
Так как раньше экспортёр в object использовал значения IK лимитов (PoseBone.ik_min_x), а теперь экспортёр использует XRay лимиты (Bone.xray.ikjoint.lim_x_min).

Решение:
нужно выделить все кости в сохранённом blend файле и нажать кнопку `Convert IK Limits to XRay Limits`

Но это решение не удобно тем, что перед экспортом нужно выяснять, какие лимиты были у костей во время импорта (то есть, нужно выяснить, с помощью старой или новой версией плагина был импортирован объект с костями).

Поэтому, нужно придумать другое решение. Например, создать Enum параметр, который будет иметь два пункта:
1 - `использовать IK лимиты при экспорте`
2 - `использовать XRay лимиты при экспорте`
И сделать значение по-умолчанию в первый пункт, а при импорте выставлять второй пункт.
То есть, если так сделать, то все объекты, которые сохранены в blend файлах, будут экспортироваться с использование IK лимитов.
А все импортированные (новые) объекты будут экспортироваться с использованием XRay лимитов.

**Comment by igelbox** [comment]
Enum-параметр - хорошее решение. Только вот значение по-умолчанию будет применяться и для вновь созданных объектов, т.е. будет сподвигать пользователей использовать устаревший формат лимитов (IK лимиты). Если я, конечно, правильно понял, что он теперь устаревший.
Для решения этой проблемы можно использовать [костыль](../blob/509dc495adea7dc9ce6473993d919507c863157b/io_scene_xray/xray_inject.py#L219) который будет выставлять использование XRay-лимитов для новых объектов.
