### ISSUE TITLE
Не работает удаление предыдущей модели при переключении во Viewer.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#747]
У ТЧ .ogf, с ЗП нормально. 

<details>
  <summary></summary>

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/fa1f61ec-8272-4ee3-b579-2a890dba3ca7)

https://github.com/PavelBlend/blender-xray/assets/56885075/640db1d6-e043-4d67-b7e0-8a1edf13e97e

</details>

**Comment by PavelBlend** [comment]
@SamArtGit у меня удаляются объекты. Посмотрел код и по коду я ошибки не вижу. Может у тебя во время импорта ошибка возникает и выполнение кода до удаления не доходит. Посмотри, что пишется в консоль `Top Bar` > `Window` > `Toggle System Console`. Если там ошибки, то скинь их сюда. И на всякий случай, напиши версию блендера и аддона. Я проверял на блендере `3.6.9` и аддоне `2.38.0`.

**Comment by PavelBlend** [comment]
@SamArtGit воспроизвёл ошибку. В консоли текст ошибки такой:

```python
Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\viewer.py", line 258, in update_file
    import_file(file)
  File "C:\Users\Pavel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_xray\ops\viewer.py", line 145, in import_file
    bpy.ops.xray_import.ogf(
  File "C:\progs\blender369\blender-3.6.9-windows-x64\3.6\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Ошибка: Арматура не имеет всех костей, которые есть в OMF файле: "stalker_neytral_hood_1.ogf"
```

Вроде бы эта ошибка появилась в недавней версии аддона. Скорее всего из-за этой возможности: #736

**Comment by PavelBlend** [comment]
Понял почему возникает ошибка. Нужно не просто открыть ogf из ТЧ, но и в настройках аддона указать папку meshes из ЗП. Во время импорта ogf, аддон считывает bone parts из omf, а в скелете ЗП костей больше. Поэтому omf из ЗП выдают ошибку.

**Comment by PavelBlend** [comment]
0f64e65b5b9b175bdf7a25ad78aab9a9e19017be
