### ISSUE TITLE
Пакетное изменение шейдеров и не только материалов X-Ray.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#756]
Аналогично Blender'овским.

<details>
  <summary></summary>

![image](https://github.com/PavelBlend/blender-xray/assets/56885075/e3ec4997-70f5-404a-916e-56b7819636c8)

</details>

**Comment by PavelBlend** [comment]
@SamArtGit какие параметры нужно изменять? Shader, Compile, Material, Two Sided? А что ещё? У костей и объектов то же дать возможность параметры изменять?

**Comment by SamArtGit** [comment]
Точно, за кости не подумал!
Ну и сделать это аналогично Prop Tools: перезаписать на основе параметров с выделенного объекта, применить на материалы выделенных объектов определенный набор преднастроек.
Если нужно на конкретные материалы одного объекта, то пользователю можно предварительно его P > by Material и обратно объединить. Поэтому не проблема.

**Comment by PavelBlend** [comment]
Кстати, такой запрос уже есть: #550 Так что этот является дубликатом. Закрою эту проблему, так как в 550-той больше описания.
