### ISSUE TITLE
При экспорте .part объединять данные уже с существующим .part

### ISSUE THREAD

**Issue by Seakad** [PavelBlend/blender-xray#758]
Что я имею ввиду, при сохранении объектов из сцены блендера в scene_object.part, блендер создает новый файл, игнорируя/стирая старые данные из уровня LE.
Самый простой вариант, добавить смещение, с какого числа начинать писать id.
К примеру смещение 475 - будет object_476, object_477, object_478 и т.д, потом останется только ручками objects_count поправить, и все.

**Comment by PavelBlend** [comment]
@Seakad для чего это может пригодится? Сейчас можно все необходимые объекты импортировать, а потом за раз их экспортировать. Чтобы два part файла объединить, нужно их импортировать в одну сцену и сделать экспорт опять в part. Это обходной путь. В принципе можно было бы добавить эту возможность, но я не хотел бы ещё больше кода добавлять, если нет других более важных причин.

**Comment by Seakad** [comment]
@PavelBlend ну импортировать из LE 2000-3000 объектов как-то тяжело/накладно, смотрите сами в общем.

**Comment by PavelBlend** [comment]
Пока закрою этот запрос. Может в будущем, когда будет желание и время, вернусь к нему. А пока я не буду его реализовывать.
