### ISSUE TITLE
Чтение/редактирование/сохранение аудиофайлов/X-Ray комментариев к ним в .ogg.

### ISSUE THREAD

**Issue by SamArtGit** [PavelBlend/blender-xray#759]
Добавить в N панель Video sequencer'а вкладку X-Ray где будут редактируемые параметры/комментарии аудиофайла как для анимаций + Viewer аналогичный для трёхмерных объектов из .object, .ogf и т.п.. 😀

**Comment by PavelBlend** [comment]
Для таких целей лучше создать отдельную программу, так как 3д редактор косвенно относится к звукам. Я хочу сконцентрировать все силы, внимание и время на 3д форматы. Редактирование звуков и комментариев к ним выходит за пределы предназначения аддона. Поэтому я не буду добавлять эту возможность.
