### ISSUE TITLE
Проблема с Invalid face

### ISSUE THREAD

**Issue by ghost** [PavelBlend/blender-xray#760]
Привет, при использования твоего плагина возникла проблема. Компилятор ругается на invalid face (В сдк), но вот сам плагин не может найти проблему в развертки модели.

**Comment by PavelBlend** [comment]
@Stalker-Vernite Привет. Нужен пример файла.

**Comment by ghost** [comment]
Хорошо, щас скину.

**Comment by ghost** [comment]
https://disk.yandex.ru/d/jyb8SrQBBQfUVQ

![2024-04-20_14-51-42](https://github.com/PavelBlend/blender-xray/assets/164559960/2ad5f309-1389-425e-910d-df35290b15cc)

**Comment by Seakad** [comment]
@Stalker-Vernite invalid face это не про развертку, а про множество вершин в одной точке, или полигоны с 2мя вершинами, это раз. А во вторых, в самой модели есть меш с текстурой prop_fake_kollision, которая тут нахрен не нужна, и лежит в той же плоскости, что и террайн. 
https://disk.yandex.ru/d/grx0UZgMMjkZAw

**Comment by ghost** [comment]
Ого, спасибо большое а объяснение, и фикс

**Comment by ghost** [comment]
Постой, а почему не нужна другая часть объекта prop_fake_kollision?

**Comment by Seakad** [comment]
@Stalker-Vernite вроде как совсем древние версии xrLC не могли коллизию из основного меша генерировать, поэтому пыс такой костыль применяли, но это точно. В любом случае во всех релизных играх коллизия строится по модели, и городить велосипед смысла нет.

**Comment by PavelBlend** [comment]
> Компилятор ругается на invalid face

@Stalker-Vernite скомпилировал твой объект и у меня нет invalid face. Может invalid face вызвал другой объект на карте? Или у тебя кроме террейна ничего нет?

Я компилировал с помощью xrLC от skyloader. СДК 0.4. Вот команда:

`Final core params: -geometry -f test_err -version shoc -static`

Ключей для обхода инвалидов нет.

Вот часть лога:
```python
Startup time: 18:21:34, date: 20.4.2024
 
* New phase started: Reading project [test_err]...
    |    | Input file version: 17
    |    | Output file version: 17
* Phase ended: Reading project [test_err]... - 00:00:00
 
* New phase started: Converting data structures...
    | Vertices...
    |    | *         vertices: 135159
    | Faces...
    |    | *            faces: 289869
    | Models and References
    | Other transfer...
    |    | *        materials: 8
    |    | *          shaders: 2
    |    | *     shaders_xrlc: 2
    |    | *            glows: 1
    |    | *          portals: 0
    |    | *             LODs: 0
    | Loading lights...
    |    | *lighting*: HEMI:   1 lights
    |    | *lighting*: SUN:    1 lights
    |    | *lighting*: STATIC: 1 lights
    |    | *   Dynamic lights: 1
    | Processing textures...
    |    | * Loading thm file: glow\glow_white.thm
    |    | * Loaded texture: 'glow\glow_white' 256x256 alpha[true]
    |    | * Surface sizes: thm[64x64] -> texture[256x256]
    |    | * Loading thm file: prop\prop_fake_kollision.thm
    |    | * Loading thm file: terrain\terrain_dom.thm
    |    | * Loaded texture: 'terrain\terrain_dom' 1024x1024 alpha[false]
    |    | * Loading thm file: veh\veh_raf1.thm
    |    | * Loading thm file: veh\veh_rafwheel1.thm
    |    | * Loading thm file: veh\veh_kamaz_u_01.thm
    |    | * Loading thm file: mtl\mtl_truba_pod_01.thm
    |    | * Loading thm file: ston\ston_rocks2.thm
    | Post-process materials...
    |    | * sizes: V(80),F(144)
    |    | Build parameters:
    |    | Quality: 0
    |    | Normal smooth angle: 75.000000
    |    | Weld distance (m): 0.005000
    |    | Pixel per meter: 0.100000
    |    | Error (lightmap collapsing): 4
    |    | Error (lightmap zero): 4
    |    | Jitter samples: 1
    |    | Options:
    |    | Lightmap resolution: 1024
    |    | Hemi bias: 0.100000
    |    | Subdivide maximum size (m): 32
* Phase ended: Converting data structures... - 00:00:00
 
* New phase started: Optimizing...
    | Processing...
    | Processing... (0 verts removed)
    | Processing... (0 verts removed)
    | Removing degenerated/duplicated faces...
    | Adjacency check...
    | Cleanup...
    |    | 11 vertices removed. (135148 left)
    |    | 18 faces removed. (289851 left)
    | Processing...
    |    | *** 173 junctions and 1 long edges found.
* Phase ended: Optimizing... - 00:00:02
```

У тебя карта не компилируется и появляется ошибка? Или в чём заключается "ругань" компилятора?

**Comment by PavelBlend** [comment]
Если проблема не решилась, то открой заново эту issue. Я пока её закрою, так как не вижу проблемы. У меня компилятор не выдаёт ошибок.

**Comment by ghost** [comment]
Закрывай или удаляй. Проблема решилась) Спасибо.
