### ISSUE TITLE
Проблема при экспорте камеры

### ISSUE THREAD

**Issue by ghost** [PavelBlend/blender-xray#761]
Привет. Столкнулся с проблемой. При экспорте камеры в расширение anm, камера меняет позицию.

В блендере просматривая анимацию все нормально, работает должным образом. Но вот посмотрев в игре результат, вижу что у камеры параметры rotation ломаются, она грубо говоря смещается вверх, хотя в блендере такой проблемы не было, все работало хорошо, а при экспорте, как ранее было сказано, параметры камеры rotation меняются и она смотрит вверх

https://disk.yandex.ru/d/ABoExtCwmctMUg

![2024-04-20_14-47-31](https://github.com/PavelBlend/blender-xray/assets/164559960/f7d47486-9a64-4b6e-a5ad-b36c77ba1c9d)

**Comment by PavelBlend** [comment]
@Stalker-Vernite привет. Лучше скинь blend файл, из которого можно сделать экспорт. Но я могу написать предположение:
скорее всего ты анимировал камеру так, что вверх указывала ось Y, а нужно чтобы она указывала туда, куда смотрит камера (то есть вперёд). Вот я записывал видео о работе с форматом anm:
https://youtu.be/Ta4WgPIIUpw

Про направление камеры я говорил на 8:45:
https://youtu.be/Ta4WgPIIUpw?t=525

**Comment by ghost** [comment]
@PavelBlend  Кхм... Нет, я анимировал камеру так, что она смотрела туда, куда надо. То есть как ранее ты сказал вперед

Вот сам файл blend
https://disk.yandex.ru/d/chOVrZDbMVqq5g

**Comment by PavelBlend** [comment]
@Stalker-Vernite анимацию нужно было создавать для пустышки, а не для камеры. Камера - это вспомогательный объект. Включи оси у камеры. Ось Y направлена вверх:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/6389bc88-7e54-4298-8063-4b5e5e7ee2ac)

Нужно, чтобы ось Y смотрела вперёд, поэтому нужно анимировать пустышку. Ось Y - направление взгляда. Камеру невозможно так установить, чтобы взгляд из неё в блендере совпадал со взглядом из неё в игре.
