### ISSUE TITLE
Как повернуть скелет

### ISSUE THREAD

**Issue by kusyukin** [PavelBlend/blender-xray#765]
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/3b3ac2a0-e700-4de3-90cc-3ac4b0c70e12)

Павел, здравствуйте. Подскажите пожалуйста, как можно развернуть скелет в сторону камеры для экспорта модели?
Я импортирую модели из модификации Anomaly. 90% моделей импортируются в нужном мне направлении, но существуют ещё 10%, которые импортируются спиной. Пробовал черед редактирование позы развернуть модель в сторону камеры, но в таком случае, позы накладываются неправильно.

![image](https://github.com/PavelBlend/blender-xray/assets/136234486/fab7167e-6d5c-4ee5-b47a-05eff1ba35dd)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/0b70f874-2b94-4c9f-881e-b94fe881727c)

Помогите пожалуйста. Разворот таких моделей мне необходим для скрипта, который я написал для автоматической установки позы и рендера моделек из папки.

![image](https://github.com/PavelBlend/blender-xray/assets/136234486/bb011c9b-72b9-420a-bad2-0c00127234cb)

**Comment by PavelBlend** [comment]
@arenacreatoru Привет. Нужно анимации переделывать. Либо можно повернуть скелет в объектном режиме на 180 градусов:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/52c6392c-1656-4707-ab1b-5b90a8c04384)

**Comment by kusyukin** [comment]
Я пробовал уже так. Вот такой результат обычно.
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/fa430156-471d-4119-8d04-f59592c4189f)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/e36aa8b0-8455-41f0-9586-9b6bb3a9bb15)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/b5ab858d-fb4c-4421-8634-32d0412fb0e6)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/117c0123-2138-4b71-bc1e-150e06cb0197)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/4436af51-b397-48b0-a0cf-414105f623a7)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/f11f2127-3884-4fcb-b80a-65e368e31c71)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/9b6b3400-5580-4f17-8f41-620259a44725)
![image](https://github.com/PavelBlend/blender-xray/assets/136234486/cfc19bd3-809f-4e32-9451-a2a876960cbd)

**Comment by PavelBlend** [comment]
@arenacreatoru я не знаю, почему в аномали некоторые модели не туда смотрят. В ТЧ все модели смотрят в одну сторону. В ЧН/ЗП тоже смотрят в одну сторону, которая противоположна стороне ТЧ. Но в аномали почему-то смешанные варианты. Может они не используются в моде? Или у них другой набор анимаций?

Поверни арматуру на 180 градусов по вертикальной оси и примени вращение арматуры с помощью Ctrl+A > Rotation.

**Comment by kusyukin** [comment]
Получилось! Спасибо огромное!
Большая часть моделей, которые стоят спиной, применяются в аномали
