### ISSUE TITLE
uv map 'Texture' != 'texture'

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#77]
Нашёл object файл, который импортируется не так как нужно. Проблема в том, что имя юви карты у меша импортируется как "texture", а текстура ссылается на юви карту с именем "Texture".
![texture_and_texture_uv_map_error](https://cloud.githubusercontent.com/assets/7983249/15112003/d63de25e-15f3-11e6-87e4-90ee9eff952c.png)

**Comment by PavelBlend** [comment]
Вот сам файл: [stalker.zip](https://github.com/igelbox/blender-xray/files/255308/stalker.zip)

**Comment by igelbox** [comment]
Так там в самом object-файле такие значения: в vmaps2 имя задано как "texture", а ссылки с surfaces2 как "Texture". А где в SDK посмотреть как это имя uv-карты отображается?

**Comment by PavelBlend** [comment]
В СДК нельзя посмотреть имя юви карты. Я так понял, что для СДК не важен регистр символа, поэтому он не выдаёт ошибки.
