### ISSUE TITLE
Xray sdk can not find texture in .object file

### ISSUE THREAD

**Issue by DimoNULL** [PavelBlend/blender-xray#778]
The problem is this: when trying to load a file.object in the sdk, for some reason there is no texture. There is a texture in the blender itself, but the sdk says that the texture was not found. In the addon settings, the paths to gamedata and the rest of the folders are specified

**Comment by PavelBlend** [comment]
Check all the image paths and textures folder, the path does not refer to another xray sdk version (you may have two sdk installed)?
If the textures folder is specified correctly, then tell me what export options were set.
What warnings were there during export?
What warnings does ActorEditor or LevelEditor give?
