### ISSUE TITLE
Странно работает сглаживание

### ISSUE THREAD

**Issue by Zfoksi** [PavelBlend/blender-xray#779]
Модель отображается в actor_editor без этих затенении.
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/1b89f99c-86b4-4fb5-a262-09eb9d8617f3)
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/c7c05975-8894-4842-9311-444a09e6275a)
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/20335184-484f-4c2d-b7c0-6da8b9778227)
В самой же игре эти затенения есть. При том они не часть текстуры. Я пытался баловатся со сглаживанием но не получилось. Как их убрать? И возможно ли убрать?

#### Версии ПО:
 - OS: Win10 x64
 - Blender: 3.6

**Comment by PavelBlend** [comment]
@Zfoksi как был создан этот ogf файл? У меня такое ощущение, что ты сделал экспорт сглаживания в ТЧ формате, а использовал ActorEditor с ЗП форматом сглаживания (или наоборот ЗП формат в ТЧ сдк).

Напиши точные шаги, как воспроизвести такое поведение. Опиши все параметры импорта/экспорта. Все программы, которые были использованы (ActorEditor ЗП или Actor Editor ТЧ или ObjectTool или что-то другое).

**Comment by Zfoksi** [comment]
Какой вид сглаживания без понятия, я просто не думал что есть виды. Использовал всё ЗПшное, т.е. и actor editor , и модель из ЗП . Параметры аддона (кроме указания какого-то файла где лежат пути к папкам с мешами и текустарами)  я не трогал

**Comment by PavelBlend** [comment]
При экспорте в object нужно установить формат ЗП, чтобы сглаживание было в формате ЗП СДК 0.7:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/9a2b5cb8-e3e8-4fd2-be1f-0b3b87d096b3)

И покажи, как выглядит сглаживание в самом блендере. Может ты импортировал модель из ЗП, указав ТЧ формат при импорте. Или модель получена путём конвертации ogf в object конвертером бардака. В этом случае нужно установить ТЧ формат при импорте, даже если модель взята из ЗП. Конвертер не поддерживает сохранение сглаживания в ЗП формате:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/5640ce2e-a3ca-4c42-83da-fa70c34757a4)

**Comment by Zfoksi** [comment]
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/2be36f63-c041-4219-b955-73d4cbeb7f24)
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/6a427a7f-c61c-45a8-a297-d8cb0e0ef129)
я импортирую ogf сразу 
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/4d9dca79-3e58-49c7-bcb2-581834d4e19a)
а так экспортирую

**Comment by PavelBlend** [comment]
@Zfoksi можешь дать мне ogf файл, который ты в начале импортируешь? По-моему эта проблема связана с этой: #775 
Но мне нужен файл, чтобы сказать точно.

И какая у тебя версия аддона? Судя по скриншотам, не последняя. Попробуй обновить аддон, на всякий случай. Хотя я не менял код импорта сглаживания, но мало ли.

**Comment by Zfoksi** [comment]
[stalker_neutral_2.zip](https://github.com/PavelBlend/blender-xray/files/15300795/stalker_neutral_2.zip)

Версия аддона : 2.24.0

**Comment by PavelBlend** [comment]
@Zfoksi проверил. Это не проблема аддона, а проблема ЗП СДК. Почему-то при экспорте object в ogf, он генерирует такие нормали:
![01](https://github.com/PavelBlend/blender-xray/assets/7983249/bbef9f46-f8dc-4916-9591-86a47d49a924)

Из-за которых в игре эти потемнения:
![02](https://github.com/PavelBlend/blender-xray/assets/7983249/a79ce285-6a24-4a19-93eb-2f3efa3d9d53)

Я удалил сглаживание рёбер на капюшоне:
![04](https://github.com/PavelBlend/blender-xray/assets/7983249/bb231907-f84f-448f-94b4-2c631dd8dfe6)

И в игре пропали эти пятна:
![03](https://github.com/PavelBlend/blender-xray/assets/7983249/a36d1898-c655-45f7-bbea-ff6f0a7d63f5)

**Comment by PavelBlend** [comment]
Если сделать экспорт модели из блендера сразу в ogf, без использования СДК, то сглаживание будет нормальным:
![05](https://github.com/PavelBlend/blender-xray/assets/7983249/7eee1b63-5c10-4aa7-8bab-0c80af05a5f7)

Что-то не то в самом алгоритме ЗП СДК, что нормали такие получаются.

**Comment by Zfoksi** [comment]
А как удалить сглаживания ребёр?

**Comment by Zfoksi** [comment]
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/bdc13297-8be5-4d5c-8348-c944bb2d2c44)

И можно ли будет в самом блендере настроить необходимые анимки ?(пример на скрине)

**Comment by PavelBlend** [comment]
> А как удалить сглаживания ребёр?

для это нужно сделать их "острыми" с помощью Ctrl+E > Mark Sharp

> И можно ли будет в самом блендере настроить необходимые анимки ?(пример на скрине)

Да, можно. Эти motion references находятся в параметрах объекта, панель X-Ray Engine: Object

**Comment by Zfoksi** [comment]
![image](https://github.com/PavelBlend/blender-xray/assets/122187444/d117ba13-90f7-4899-9912-23cc07f89e7e)
И ещё один вопрос : можно настроиь эти вот инклюды, которые отвечают за здоровье и другие вещи для нпс?

**Comment by PavelBlend** [comment]
@Zfoksi нет, нельзя.

**Comment by PavelBlend** [comment]
Вроде бы вопрос решился. Это поведение не является ошибкой аддона, а является ошибкой СДК. Закрывают багрепорт.
