### ISSUE TITLE
Хотелось бы инструкцию по переносу модели оружия из ЧН\ЗП в ТЧ (Другими словами можно ли соеденить модели и анимации рук и оружия в одну и экспортировать ее?

### ISSUE THREAD

**Issue by 4yvachok** [PavelBlend/blender-xray#780]
Из всех плагинов для 3д Редакторов эти самые лучшие, но есть один момент с которым я не совсем могу разобраться, а как можно соеденить худ модели рук и оружия в одну модель, и тоже самое проделать с анимациями? Сразу скажу, я в блендере не силен особо, я его в основном чисто как экспортер использовал до этого и модели рук и оружия соединял вообще в другом 3д редакторе, но там увы это сильно затратно по времени выходит, не говоря о том что тот 3д редактор рассчитан на лоу поли модели и от некоторых моделей "давится".

https://www.youtube.com/watch?v=KG5r0vRfUtk
Тут в 52:40 вроде есть что-то похожее, но видео не показывает а как собственно импортировать 2 модели чтобы так же 2 комплекта анимаций было - при попытке импорта omf файла он импортируется только на 1 скелет, и можно ли получить соедененный экшен чтобы его экспортировать как 1 анимацию и как "прицепить" само оружие к кости wpn_body?

**Comment by 4yvachok** [comment]
И еще один момент, интересно как правильно еще цеплять кость оружия когда в конфиге она сдвинута через item_position и orientation

**Comment by PavelBlend** [comment]
@4yvachok Нужно объединить два скелета, и потом скопировать анимационные ключи (Ctrl+C) и вставить их (Ctrl+V). Но в одном сообщении трудно объяснить все шаги. И я не знаю, какой именно у тебя уровень в блендере. Знаешь ли ты окно Dope Sheet, работал ли с арматурой и костями и т. д. Лучше изучи блендер по видео, статьям, документации. Тогда придёт понимание, и ты сам сможет додуматься, как объединять скелеты, разделять их, менять анимации и т. д.

Чтобы добавить смещение, можно использовать промежуточный объект (пустышку например). И потом использовать констрейнты. Как именно это сделать, я не смогу сказать, так как нужно экспериментировать с этим.
