### ISSUE TITLE
Экспорт уровня

### ISSUE THREAD

**Issue by ReindeerFloatilla** [PavelBlend/blender-xray#783]
Всем привет. Я пытаюсь написать урок о том, как создать собственный уровень для STALKER Shadow of Chernobyl с помощью этого плагина. У меня возникают некоторые трудности с этим. Когда я пытаюсь выбрать экспорт->Уровень игры Xray, он говорит: «Нет световых объектов».

![image](https://github.com/PavelBlend/blender-xray/assets/24368041/384463cd-e1d9-4e9a-b959-fd13eed479ae)

Что мне нужно сделать как минимум, чтобы экспортировать уровень в SDK? Если вы дадите мне знать, я смогу правильно написать учебник английского языка. 

Прошу прощения, если мой русский звучит криво, я использую переводчик.

**Comment by PavelBlend** [comment]
@ReindeerFloatilla Привет. Импортируй готовый уровень и посмотри, как они устроены. Нужно создавать сектора, порталы, glows, источники света и определённым образом их соединять родительскими связями. И у импортированного уровня посмотри настройки во вкладке `Object` в панели `X-Ray Engine: Object`. Там расположены параметры объектов уровня.
