### ISSUE TITLE
плагин работает абсолютно не правильно

### ISSUE THREAD

**Issue by DimoNULL0F** [PavelBlend/blender-xray#786]
Вот так выглядела модель при создании:
![blendwin](https://github.com/user-attachments/assets/93d0d2d6-a446-485e-bd58-edcfdba95059)

А вот так она выглядит после:
![blendwinaft](https://github.com/user-attachments/assets/09b01093-c0e0-4787-9c40-735382f20f1d)

Во первых - геометрия искажена полностью, и из за шейдеров в игре она выглядит еще хуже. Во вторых - машина в игре проваливается под землю на половину, какие то колеса торчат из земли, а потом она проваливается полностью. И вот проблема которая была во всех версиях плагина: размеры шейпов при создании модели никогда не соответствовали размерам при экспорте. При экспорте все шейпы были на порядок меньше, и так со всеми моделями. 

А так же вот скриншот после еще одного экспорта:
До экспорта:
![dim](https://github.com/user-attachments/assets/c1c5cd54-8f60-4a31-a70d-218f659978e9)
После экспорта в object:
![objim](https://github.com/user-attachments/assets/920eb16a-757e-40ba-910d-6855b6eaa9b8)

Программа абсолютно не стабильная, при каждом экспорте разные результаты, и никогда нет нужного. 
[wheeltest.zip](https://github.com/user-attachments/files/16228292/wheeltest.zip)
Это архив с blend и object файлом.

Использую версию блендера 3.6, а версию плагина 2.40.0

**Comment by PavelBlend** [comment]
> Во первых - геометрия искажена полностью

что значит "искажена"? Триангулирована?



> Во вторых - машина в игре проваливается под землю на половину, какие то колеса торчат из земли, а потом она проваливается полностью.

ну значит так настроено. Я сейчас сделал импорт/экспорт готовой машины из игры и она не проваливается. Посмотри настройки у готовых машин с делай так же.

> размеры шейпов при создании модели никогда не соответствовали размерам при экспорте

у меня всё корректно экспортируется. Мне нужен пример blend-файла, в котором можно воспроизвести данное поведение.
![01](https://github.com/user-attachments/assets/5f4aef4e-0f25-4021-a6cf-20687da4aae2)

**Comment by DimoNULL0F** [comment]
это не триангулировка, на поверхности цилиндра буквально артефакты с вертексами, когда они стоят как будто в случайных местах, это можно заметить на одном из колес, а насчет файлов - я их приложил

**Comment by DimoNULL0F** [comment]
вот скрин колеса:
![scr](https://github.com/user-attachments/assets/1f4d5d81-cfe3-4b08-a6ae-9ad23a14a59e)
Тут так же можно заметить что кости вообще перевернулись на бок

**Comment by PavelBlend** [comment]
> кости вообще перевернулись на бок

нужно сделать арматуру root-объектом. Вот описание root-объектов:
https://github.com/PavelBlend/blender-xray/wiki/Root-Object

Для этого нужно у арматуры включить параметр object, а у меша выключить:
![01](https://github.com/user-attachments/assets/8bfb9e4e-c6cc-435b-80ac-a351c1e165aa)

Можно сделать, чтобы и меш мог быть root-объектом, но для этого придётся переписывать код, чтобы он учитывал два случая.

Обычно я делаю root-объектом арматуру (хотя есть и другие варианты, на скриншоте по ссылке выше) и добавляю арматуре все анимации и настраиваю другие параметры.

**Comment by PavelBlend** [comment]
> на поверхности цилиндра буквально артефакты с вертексами, когда они стоят как будто в случайных местах

Вот эти вершины?:
![01](https://github.com/user-attachments/assets/b0af0054-1e9b-48e5-93fc-3262a1c88e7d)

Я сделал экспорт и у меня их нет. При экспорте аддон новые вершины не добавляет.

**Comment by DimoNULL0F** [comment]
Откуда эти вершины я не знаю. Сделал еще один экспорт и их больше нет, как я и говорил результаты вечно разные. Лучше расскажи почему на скриншотах кости просто взяли и на бок перевернулись? До экспорта все было нормально, а после такое вот. Я просто не могу с первого раза сделать модель, размеры коллизий костей вечно изменяются, а кости куда то сваливают или переворачиваются

**Comment by DimoNULL0F** [comment]
Кстати размер коллизий костей всегда изменялся в меньшую сторону, а в большую никода

**Comment by PavelBlend** [comment]
> Лучше расскажи почему на скриншотах кости просто взяли и на бок перевернулись?

я уже написал:


> нужно сделать арматуру root-объектом. Вот описание root-объектов: https://github.com/PavelBlend/blender-xray/wiki/Root-Object
> 
> Для этого нужно у арматуры включить параметр object, а у меша выключить: ![01](https://private-user-images.githubusercontent.com/7983249/348562568-8bfb9e4e-c6cc-435b-80ac-a351c1e165aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTYyMjgsIm5iZiI6MTcyMTE1NTkyOCwicGF0aCI6Ii83OTgzMjQ5LzM0ODU2MjU2OC04YmZiOWU0ZS1jNmNjLTQzNWItODBhYy1hMzUxYzFlMTY1YWEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMTg1MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVkOTM0M2NlMjc2Y2JmMDg4Njc2MzgzZDZmYmI2MTVjN2IzMzkzYzFiYzM1NGRlOWNkZGRhNTMwMTY4YjY0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7TkwXlzQA6mVvLL6A7y51c2ej4ZyKqHqYw8rfyckdsY)

Нельзя делать меш root-объектом. Root-объектом может быть либо пустышка, либо арматура. Ну или сам меш, если он не имеет скелета. Чтобы меш можно было бы сделать root-объектом, нужно кучу кода переписывать и делать кучу дополнительных вычислений матриц трансформаций. Аддон и так много чего учитывает (см. скриншот по ссылке выше). Тебе просто нужно включить параметр Object у арматуры, а у меша его выключить.

**Comment by PavelBlend** [comment]
> Во первых - геометрия искажена полностью, и из за шейдеров в игре она выглядит еще хуже.

по поводу шейдинга модели в игре: если сглаживание не корректно настроено, то меш будет плохо выглядеть. Нужно настроить сглаживание в блендере и указать правильные параметры экспорта.

**Comment by DimoNULL0F** [comment]
Хорошо, а тут что не так?
До экспорта:
![aaexp](https://github.com/user-attachments/assets/22787925-a238-406b-b3c6-a8835b7df45a)
После:
![aexp](https://github.com/user-attachments/assets/a0dba267-d1e3-4cb4-ab6d-44e4ddedbb57)
Тут я вообще ничего не делал с родительскими и дочерними объектами

**Comment by PavelBlend** [comment]
Скинь этот файл, я посмотрю.

**Comment by PavelBlend** [comment]
Воспроизвёл поведение. Нужно применить масштаб меша Ctrl+A>Scale. Это меш меньше стал.

**Comment by DimoNULL0F** [comment]
А, вот оно что. Тогда последний вопрос: почему машина под землю проваливается? Два колеса снаружи, а корпус и остальные два колеса просто улетают вниз. На каждой из костей машины есть коллизия, но такое чувство будто ее нет, только на двух колесах

**Comment by DimoNULL0F** [comment]
при экспорте все тоже в порядке, все размеры соответствуют, именно в игре такое

**Comment by PavelBlend** [comment]
Можешь скриншот скинуть?

Я посмотрел твой файл и увидел, что у твоей модели нет весов вершин для всех костей. У тебя только одна группа вершин:
![03](https://github.com/user-attachments/assets/db90fc73-7627-4211-a453-0592b386544e)

Нужно для каждого колеса создавать свои веса. И один вес для кузова.

И ещё для настройки костей колёс, нужно определённым способом повернуть кости. Чтобы вращение по оси X - это было вращение колёс рулём влево/вправо, а вращение по оси Z - это вращение колеса при езде. Вот нива настроена так:
![01](https://github.com/user-attachments/assets/1a282e63-6624-449c-baad-065042fd8591)

А вот твои колёса:
![02](https://github.com/user-attachments/assets/986bc46e-38ad-46b3-bdb9-cca63ecabc7c)

**Comment by DimoNULL0F** [comment]
Да я заметил что на каждом колесе у меня bone04, хотя должна быть соответствующая bone. И Z смотрит вперед, а должна внутрь машины что бы я мог нормально поворачивать. Вопросов не осталось больше, спасибо большое

**Comment by PavelBlend** [comment]
Я уже создал тестовый уровень и добавил физический объект. Изначально объект выглядел так:
![111](https://github.com/user-attachments/assets/4e7fcaaf-383e-4a0d-9287-8a16bf4b4e54)

Потом я изменил группы вершин, но колёса не настроил:
![222](https://github.com/user-attachments/assets/1f21cb60-6b29-4758-8a99-1c435d4319d1)

Потом настроил кости колёс, но шейпы остались старыми. Нужно старые шейпы адаптировать под новые трансформации костей:
![04](https://github.com/user-attachments/assets/ee395ee7-2635-4784-aaba-aca02db24b95)

Перед настройкой шейпов лучше применить масштаб, позицию, вращение меша, а то операторы для редактирования шейпов не правильно работают, если трансформации не применены (надо будет исправить эту ошибку).

В итоге я получил такой результат:
![333](https://github.com/user-attachments/assets/1aebde9d-3308-4624-9b5c-349242e690ad)

**Comment by DimoNULL0F** [comment]
Спасибо большое, не знал что тут столько разных тонкостей
