### ISSUE TITLE
Упростить добавление коллизии на объект

### ISSUE THREAD

**Issue by DimoNULL0F** [PavelBlend/blender-xray#787]
#### Описание идеи:
Предлагаю добавить систему, при помощи которой можно будет выделить в edit mode некоторые полигоны, и создатся арматура с такими параметрами, что бы ее область коллизии покрывала выделенные полигоны

#### Примеры использования:
Например можно сделать куб, выделить его стенки, и на каждую стенку создастся арматура покрывающая это выделение

**Comment by PavelBlend** [comment]
@DimoNULL0F я думаю это будет излишне. Не хочется без особой нужды добавлять и писать ещё кода в аддон. Эти вещи можно сделать существующими инструментами. То, что кость автоматически добавится, скорость работы не сильно увеличится. Я думаю, ты знаешь о текущих инструментах редактирования шейпов коллизии костей:

https://github.com/PavelBlend/blender-xray/wiki/Bone-Shapes

https://github.com/PavelBlend/blender-xray/wiki/Panel-Edit-Helper
