### ISSUE TITLE
Export bug for blender 4.2

### ISSUE THREAD

**Issue by L4U6H1N6-LUN4T1C** [PavelBlend/blender-xray#791]
in blender 4.0 up to 4.2 the bone groups are replaced by bone collections and so, omf cannot be exported any more
for the same or another reason, also the import of ogf does not work any longer

**Comment by SamArtGit** [comment]
Yo check pinned issue:

#715

**Comment by L4U6H1N6-LUN4T1C** [comment]
Aah thanks! I missed that. I'll close my issue then. And will eagerly await a patch.
