### ISSUE TITLE
Меняется масштаб объекта, если меш является root объектом

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#802]
Нужно сделать экспорт в ogf или object из этой сцены: [test_root_mesh.zip](https://github.com/user-attachments/files/16896017/test_root_mesh.zip)

В качестве root-объектов может выступать как арматура, так и пустышка. Вот все варианты (см. скриншот):
https://github.com/PavelBlend/blender-xray/wiki/Root-Object

Но если root-объект - это меш, то масштаб будет не корректным:
![001](https://github.com/user-attachments/assets/6f7a170b-50ec-4a7f-acb3-dc37c39d9db4)

Нужно дать возможность установить меш в качестве root-объекта и чтобы это не влияло на масштаб.

**Comment by igelbox** [comment]
А у меня оно в object **в любом случае** (даже если пустышки или арматуру выбирать) с неправильным масштабом выгружается. Ну, т.е. потом при импорте меш - помасштабирован в 1.5+раза, но арматура - нет.

**Comment by PavelBlend** [comment]
@igelbox  У меня такой результат:
![111](https://github.com/user-attachments/assets/a1bb8205-0fcc-41cc-9cc7-096a213c1178)

**Comment by igelbox** [comment]
А в каких-то случаях надо, чтоб объект экспортировался не в 0,0,0 координат и/или повёрнутый (если он повёрнут в блендер)?
У меня просто идея что удобно импортировать несколько объектов в сцену, расставить их чтобы они друг на друга не залезали, настраивать/редактировать, НО, чтоб при экспорте они были будто бы в нуле координат и с вращением по-умолчанию.

Это я всё к тому, что в коде меня пугают `get_obj_scale_matrix` и `get_object_world_matrix`, которые как-то хитро получают отдельные матрицы для смещения/вращения, а я бы просто брал world-матрицу у объекта т.к. в ней уже все родительские преобразования учтены и использовал только её.. ну разве что сделал бы так, что сам общий/корневой объект будто бы в нуле оказался и не повёрнут.

**Comment by PavelBlend** [comment]
@igelbox я думаю, что нужно сделать так: меш и скелет экспортируются так, как они выглядят во вьюпорте. Если объект перемещён и повёрнут, то он сохранится перемещённым и повёрнутым (во время экспорта сохранятся объекты с применёнными трансформациями).

Мне в принципе всё равно, как оно будет, так как у меня все объекты имеют позицию 0,0,0 вращение 0,0,0 и масштаб 1,1,1. Это я из-за пользователей хочу такое поведение. Потому что пользователи редко вообще следят за трансформациями. Может пользователь переместил и повернул объект не для того, чтобы он не мешал другим объектам, а потому что хотел, чтобы объект так и выглядел.

Аддон должен учитывать все случаи и варианты трансформаций у всех объектов: root-пустышки, арматуры, мешей с разными родительскими связями. Вот issue, где были проблемы с экспортом из-за трансформаций: #786

И мне ещё много раз попадали в руки примеры файлов, где пользователи не применяли масштабы, вращения, позиции.

Нужно, чтобы аддон применял трансформации, но не портил анимации. Ещё нужно учитывать, что для object экспорта есть позиция и вращение: #5 #62 и их применять не нужно. Их нужно записывать в Transforms чанк.

А у ogf позицию и вращение нужно применять.

В общем во время экспорта нужно применять все трансформации, но для object формата не применять позицию и вращение для root-объекта.

Ещё есть масштабирование меша, скелета и анимаций: https://github.com/PavelBlend/blender-xray/wiki/Scaling
Масштабирование нужно не сломать.

**Comment by PavelBlend** [comment]
Если объекты мешают друг другу, то их можно расставить с помощью оператора: https://github.com/PavelBlend/blender-xray/wiki/Panel-Batch-Tools#place-selected-objects

Но перед экспортом сделать Alt+G.
