### ISSUE TITLE
Отображать полигоны для шейпов костей

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#809]
А не только рёбра:
![002](https://github.com/user-attachments/assets/3f272dfb-a7dd-49b3-8e43-5a9114dcc870)

Нужно сделать как в сдк:
![001](https://github.com/user-attachments/assets/c7376f04-ce3d-4adc-b062-c3861b61e645)

**Comment by PavelBlend** [comment]
Теперь шейпы во вьюпорте выглядят так:
![01](https://github.com/user-attachments/assets/0917a6d5-5576-40b6-9f56-1e833232cddf)
![02](https://github.com/user-attachments/assets/69f2e617-28df-40ee-9e65-7aff58701160)
![03](https://github.com/user-attachments/assets/50b9af0d-dc48-4109-aaad-7d9dc3cecb90)

Шейпы имеют полупрозрачные полигоны. В предыдущих версиях аддона отображались лишь каркасы:
![04](https://github.com/user-attachments/assets/4f8220ce-eb8f-4e8a-87dc-b6e141ba0730)

В настройки аддона добавлен параметр `Alpha Coefficient`, который указывает долю прозрачности от основного цвета шейпа для отрисовки полигонов:

https://github.com/user-attachments/assets/69623a65-7002-4117-b89d-53c294ca289f

Альфа канал для каркасов задаётся как обычно, с помощью параметров цвета.

**Comment by igelbox** [comment]
В 3.1.2 - хреново работает:
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/8afccc34-2569-4731-bea8-760e95b11c4d">

а в 3.6 - уже норм:
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/ac9eaee8-25bd-44e7-bfe7-83b4bec5453c">

**Comment by PavelBlend** [comment]
@igelbox да, у меня тоже. Сейчас буду смотреть.

Что то не работает функция gpu.state.depth_test_set('LESS_EQUAL') в 3.1. Надо старую использовать из модуля bgl.

**Comment by PavelBlend** [comment]
В финальном варианте в настройках есть параметры цвета для полигонов шейпа:
![01](https://github.com/user-attachments/assets/65630ae5-dea8-4373-b536-52d29424993c)
