### ISSUE TITLE
двойные символы новой строки в user data

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#82]
Почему в user data импортируется по два символа новой строки, вместо одного (т.е. если в object файле будет записан один символ новой строки, то в блендере их будет два)?
![double_n_symbols](https://cloud.githubusercontent.com/assets/7983249/15205052/d8571666-181c-11e6-98a7-9473f7004509.png)

**Comment by igelbox** [comment]
Это символы перевода строки в стиле windows (https://ru.wikipedia.org/wiki/Перевод_строки).
Может быть, когда буду делать в плагине редактор многострочного текста, то придётся такие переносы нормализовать. А пока - вроде бы никому они не мешают?

**Comment by PavelBlend** [comment]
Да в принципе не мешают. Я просто user data скопировал в тексторый редактор и заметил двойные переносы строк. Думал это баг.

**Comment by igelbox** [comment]
А что за редактор? Я сейчас копировал и вставил в leafpad и в wine-вский notepad - вставилось нормально. А вот обратно в blender вставить не получилось (вставляется только 1-я строка).

**Comment by PavelBlend** [comment]
Только что проверил. В текстовый редактор блендера вставляется нормально, в блокнот вставляется нормально, а в notepad++ 6.0 вставляется с двойными переводами строк. Наверное это баг notepad++.
![notepad _cntl_v](https://cloud.githubusercontent.com/assets/7983249/15222981/c98cf87c-187a-11e6-80dc-0ed6b22a189d.png)

**Comment by igelbox** [comment]
Твоё копирование в блокнот натолкнуло меня на мысль: убрать поле ввода, а вместо него сделать кнопки копирования и вставки из буфера обмена.
Ну как, удобно?

**Comment by PavelBlend** [comment]
Да, удобно. А возможно ли сделать так, чтоб можно было просмотреть user data? Может добавить четвёртую кнопку 'view'. При нажатии на которую выводился бы текст из user data (в виде сообщения, как warning-окошко)

**Comment by igelbox** [comment]
Сделал такую кнопку. Проверяй.

**Comment by PavelBlend** [comment]
Кнопка правильно работает. Но почему то экспортируется user data без символов новой строки (всё в одну строку)

**Comment by igelbox** [comment]
> экспортируется user data без символов новой строки (всё в одну строку)

У меня не воспроизводится. Выложи пример исходного .blend и итогового .object файла.

**Comment by PavelBlend** [comment]
[user_data_test.zip](https://github.com/igelbox/blender-xray/files/264554/user_data_test.zip)

**Comment by igelbox** [comment]
Поправил. Теперь при экспорте плагин будет заменять все переводы строк (которые смог распознать python) на windows-переводы строк, т.е. на CRLF.
