### ISSUE TITLE
Экспорт с вложенными папками

### ISSUE THREAD

**Issue by PavelBlend** [PavelBlend/blender-xray#91]
Это легче объяснить на примере:
Допустим, есть blend сцена, в которой 6 root объектов:
`terrain, building, sector_1, sector_2, balon, tree`
Если их экспортировать с помощью batch-экспорта, то они сохранятся в одну папку.
Для того, чтобы их экспортнуть в разные папки, нужно будет по одному их экспортировать.
Предложение состоит в том, чтобы root объекту создать строковое свойство "Export Path", которое будет указывать куда его экспортировать.
Например, для этих шести root объектов свойства можно было бы сделать такими:
```
terrain -> levels\my_level
building -> levels\my_level
sector_1 -> levels\my_level\sectors_in_building
sector_2 -> levels\my_level\sectors_in_building
balon -> props\objects\balon\my_balones
tree -> trees\new_trees\my_trees
```
При batch экспорте, сделать так, чтобы плагин читал это свойство и плюсовал к пути.
Например, если при batch экспорте была указана папка C:\X-Ray SDK\level_editor\rawdata\objects, то шесть файлов сохранятся так:
```
C:\X-Ray SDK\level_editor\rawdata\objects\levels\my_level\terrain.object
C:\X-Ray SDK\level_editor\rawdata\objects\levels\my_level\building.object
C:\X-Ray SDK\level_editor\rawdata\objects\levels\my_level\sectors_in_building\sector_1.object
C:\X-Ray SDK\level_editor\rawdata\objects\levels\my_level\sectors_in_building\sector_2.object
C:\X-Ray SDK\level_editor\rawdata\objects\props\objects\balon\my_balones\balon.object
C:\X-Ray SDK\level_editor\rawdata\objects\props\objects\trees\new_trees\my_trees\tree.object
```
И при batch экспорте сделать возможность выбора типа сохранения (в виде галочки, например):
"Экспортировать в одну папку" или "Экспортировать с использованием свойства Export Path"

Для чего это может быть использовано? Пример:

1) Если мы сохранили файл tree в нужную папку. Потом через неделю решили изменить модель и сохранить object в туже папку с заменой. Но мы забыли, куда мы сохраняли в прошлый раз, а искать вручную в папке rawdata\objects очень долго, так как там файлов много. В таком случае свойство "Export Path" помогло бы сохранить модель tree в нужную папку.

2) Ускорить экспорт множества файлов с сохранением структуры папок (не нужно каждый раз указывать другую папку).

**Comment by igelbox** [comment]
По 2-му пункту - согласен, это должно помочь.
А по 1-му - не понятно, т.к. это не batch-экспорт и поведение, при включённой галке, будет странным.

У меня есть немного другая идея (см. #93): сделать примерно так, как сделано в плагине для Source Engine, а именно - добавить панельку "X-Ray Export" на вкладку Scene в панели Properties. В этой панельке можно будет задать, относительно какого каталога делать экспорт и т.п.
