### ISSUE TITLE
Автоматизированная проверка обновлений

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#92]
Например, кнопочка в интерфейсе.
Список релизов можно получить из: https://api.github.com/repos/igelbox/blender-xray/releases
Кнопку можно добавить в #93

**Comment by PavelBlend** [comment]
Может лучше добавить кнопку в настройки плагина, а не в свойства сцены? Так как обновление не относится к данным сцены.

**Comment by igelbox** [comment]
> в настройки плагина

Так, конечно, логичнее. Но, по моему, залезть в настройки плагина - не такое уж и простое и частое действие. Тогда уж можно смотреть обновления плагина на сайте (github-е) - что будет не многим сложнее.
Тут идея в том, чтобы сподвигнуть пользователя часто тыкать на эту кнопку. Да и в Source Engine Tools так же сделано.

**Comment by PavelBlend** [comment]
Тогда пусть будет в сцене.
