### ISSUE TITLE
Возможность настройки нескольких SDK

### ISSUE THREAD

**Issue by igelbox** [PavelBlend/blender-xray#95]
- Возможность задать в настройках плагина несколько SDK, например: "SoC-SDK", "CoP-SDK", "Каталог с распакованной игрой" и т.п.
- У каждого заданного SDK должны быть свои свойства:
  - каталог текстур, файл для gamemtl и т.п.
  - каталог объектов (полезен для экспорта) (пустой, для каталога с распакованной игрой)
  - версия SDK (SoC или CS/CoP)
- При импорте/экспорте объектов определять версию SDK на основе пути импортируемого файла (но и с возможностью ручного выбора версии)
- Добавить в свойства проекта (см. #93) возможность выбора, ранее настроенного, SDK (если задан, то можно использовать его "каталог объектов" и "версия SDK" для экспорта)

Плюсы такого подхода:
- не надо лишний раз выбирать версию формата импортируемых/экспортируемых объектов
- легче передавать blend-файл другому разработчику (ему достаточно будет настроить у себя такой же SDK и при экспорте будут использоваться пути от его SDK, а не зашитые в blend-файл)

**Comment by igelbox** [comment]
@PavelBlend и @vladimirtd, может что-то ещё интересного скажете по этой теме? Нужна ли настройки нескольких SDK одной версии? Кто-нибудь устанавливал одновременно несколько SDK одной и той же версии? Или, может быть "Каталог с распакованной игрой" - это не самостоятельный SDK, а лишь часть настройки? Нужно ли для моддинга устанавливать несколько копий одной игры?

**Comment by PavelBlend** [comment]
> Возможность задать в настройках плагина несколько SDK

Это будет нужно. Можно сделать настройки для трёх версий: СДК ТЧ, СДК ЧН, СДК ЗП. 
Так как у всех СДК свои текстуры, материалы и т.д., которых может и не быть в других СДК.

> Кто-нибудь устанавливал одновременно несколько SDK одной и той же версии?

Я устанавливал два СДК ТЧ 0.4. Но это из-за того, что переходил с оригинального СДК от GSC на тот, который скомпилировали мододелы. В СДК от GSC у меня были объекты и текстуры, а в новый СДК я их пока не перенёс. Вот и выходит, что у меня два СДК одной версии. Но вообще так никто не делает.

> Нужна ли настройки нескольких SDK одной версии? 

Я думаю, что не нужна.

> Нужно ли для моддинга устанавливать несколько копий одной игры?

Наверное не нужно.

> может что-то ещё интересного скажете по этой теме?

Можно ещё сделать (опционально) чтение путей к текстурам, шейдерам и т.д. из файла `fs.ltx` от СДК.

**Comment by PavelBlend** [comment]
> Возможность задать в настройках плагина ... "Каталог с распакованной игрой"

У меня есть идея. Сделать что-то вроде менеджера путей к каталогу с распакованной игрой.
Вот я нарисовал как это приблизительно должно выглядет:
![blender_xray_settings_concept](https://cloud.githubusercontent.com/assets/7983249/20657074/23e91eb6-b544-11e6-8ec7-3025e86dbac6.jpg)

Это пригодится для импорта моделей из модов. Например, есть модели, которые используют текстуры из папки gamedata от мода и так же эта же модель использует текстуры из db архивов оригинальной игры (например ТЧ). И чтобы импортировать такой объект, нужно указать `Основную Конфигурацию Путей`, которая будет ссылаться на папку с модом. Если текстуры в папке gamedata от мода не будут найдены, то плагин будет искать их в `Альтернативной Конфигурации Путей` (которая ссылается на папку gamedata от распакованных db архивов ТЧ).

И ещё можно добавить кнопку `Взять Пути из Файла fs.ltx`

**Comment by igelbox** [comment]
> Вот я нарисовал как это приблизительно должно выглядет:

Я думаю, что выбор конфигурации путей (верхние комбобоксы) - это настройка сцены (blend-файла), а не плагина.
А ещё мне не очень понятно, зачем нужны альтернативные материалы и шейдеры? Ведь, в отличие от текстур, шейдеры и материалы не объединяются с оригинальными, а заменяют их (т.е. если мы положим .xr-файл в котором один шейдер, то в игре будет доступен только один шейдер, а остальные пропадут).

И ещё вопрос: как может выглядеть структура каталогов при одновременной разработке нескольких модов на одну игру? Object-файлы обоих модов будут лежать в одном XRay SDK или в разных? Если в одном, то как их разделять?

**Comment by PavelBlend** [comment]
> зачем нужны альтернативные материалы и шейдеры?

Сделать так, чтобы плагин игнорировал шейдеры из основной конфигурации, а читал их из более приоритеной альтернативной конфигурации.

> Object-файлы обоих модов будут лежать в одном XRay SDK или в разных?

В одном наверное.

> Если в одном, то как их разделять?

Я думаю что можно вообще не разделять. И тогда папка rawdata\objects будет как бы общей для обоих модов. И 3д модели могу быть использованы как в одном так и в другом моде. А если и разделять, то сделать папки rawdata\objects\mod_1 и rawdata\objects\mod_2

**Comment by PavelBlend** [comment]
Частично решил эту issue. Сделал пресеты для настроек. Теперь можно указать много версий настроек, для каждого СДК (0.4, 0.5, 0.7) и переключаться между ними. Для остальных запросов создам отдельные issues.
